### ISSUE TITLE
Where is the daemon.json in Docker for mac 1.12

### ISSUE THREAD

**Issue by hector70** [docker/for-mac#1015]
### Expected behavior
I need to change the IP of the default bridge network
### Actual behavior
Cannot find where to set it. I found only documentation for windows and linux.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @hector70, it will be merged on stable next week or the week after with the 1.13 binaries.
If you want to use it for now, you will have to switch on beta.

**Comment by hector70** [comment]
Thanks a lot.

2016-12-06 10:47 GMT+01:00 Emmanuel Briney <notifications@github.com>:

**Comment by ebuildy** [comment]
Hello @ebriney , any release date about the 1.13? Or a web page where we can follow the road-map?

Cheers,

**Comment by ebriney** [comment]
Hi @ebuildy, the official date is january 18, so in less than 2 weeks!
Best regards.

**Comment by ebuildy** [comment]
ha super !

Many thanks, where did you find this info?

**Comment by ebriney** [comment]
I don't know if it has been already announced but as far as I'm working on d4m/d4w, I can tell you it will be released on 01/18 :)
Public rc are already available on linux in docker/docker and since beta33 we are embedding it, today we will release beta35 with 1.13.0-rc5 which should be the same as the next stable official 1.13 release in 2 weeks if nothing goes wrong
