### ISSUE TITLE
Docker hung after waking from sleep

### ISSUE THREAD

**Issue by bunchjesse** [docker/for-mac#1046]
This has been reproducing for me nearly 100% of the time my computer sleeps for anything more than 30 minutes. When it wakes up, docker is hung. None of my containers are responsive and `docker ps` hangs until cancelled with ctrl+c. The only remedy is to manually kick docker by restarting from the docker app.

### Information

[spindump.txt](https://github.com/docker/for-mac/files/654841/spindump.txt)

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.2 (build: 16C67)
logs: [/tmp/0877108C-FF1A-48CE-BAFE-3AFE4C521EA1/20161215-060031.tar.gz](https://github.com/docker/for-mac/files/654827/20161215-060031.tar.gz)
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by iBobik** [comment]
### Expected behavior

macOS with running Docker went to sleep for some hours, after wake up Docker containers should work like before.

### Actual behavior

After wake it seems like server does not respond to requests, does not matter if HTTP to localhost or MySQL to 127.0.0.1.

```
$ curl -v http://localhost
* Rebuilt URL to: http://localhost/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
Curl seems idle there. After a while (tens of minutes) I triggered VM restart.
```
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

### Information

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/35E688C8-9E19-4429-B87F-650A5628D92C/20161219-141448.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run containers
  2. Sleep Mac
  3. Wake Mac
  4. Try to connect to services running in containers

### Workaround

When it happens it does not help to restart VM by Docker menu. It helps to restart the app.

**Comment by djs55** [comment]
I think these 2 reports are different.

@iBobik your logs contain:
```
Dec 19 00:57:44 ... <Notice>: System wants to go to sleep
Dec 19 00:57:44 ... <Notice>: Asking com.docker.hyperkit to freeze vcpus
```
This is the old ACPI crash workaround which shouldn't be needed on macOS 10.12. Could you:
```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ git reset --hard
HEAD is now at 5ae6336 last-start-time changed at 1482228353
$ echo 'do not freeze' > com.docker.driver.amd64-linux/on-sleep 
$ git add com.docker.driver.amd64-linux/on-sleep 
$ git commit -s -m 'do not sleep'
[master 255587b] do not sleep
 1 file changed, 1 insertion(+), 1 deletion(-)
```

@bunchjesse your failure is more mysterious. You don't have the ACPI crash workaround and there's nothing obvious in the logs. I notice some (but not all) of the logs are missing from inside the VM. Could you try upgrading to the latest beta version (beta 34 is due to be released today) and see whether the problem reproduces? If it does, could you upload a new set of diagnostics? It would also be helpful if you could log into the VM `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` and see whether `docker ps` works, and whether `ls /var` and `ls /Users/` works. Thanks!

**Comment by iBobik** [comment]
Thanks, I will write later if it happened again. No Docker restart needed?



Jan Pobořil

2016-12-20 15:20 GMT+01:00 Dave Scott <notifications@github.com>:

**Comment by djs55** [comment]
@iBobik sorry I missed this -- I think the `on-sleep` setting should take effect immediately without a restart.

**Comment by iBobik** [comment]
Issue not happened again until then.



Jan Pobořil

2017-01-10 13:42 GMT+01:00 Dave Scott <notifications@github.com>:

**Comment by yallop** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by iBobik** [comment]
@yallop Issue is probably not fixed yet, only confirmed workaround works.

**Comment by yallop** [comment]
@iBobik: I'm closing this because there's no new information from @bunchjesse.  You're seeing similar symptoms, but the underlying cause seems to be different.  If your problem is not resolved, would you mind opening a new issue?

**Comment by iBobik** [comment]
For me it is solved, but by manual action (see discussion above). Clean
installation could be broken, but it also can be fixed, just nobody
mentioned this issue.

Maybe it is best to wait if somebody else will report it.



Jan Pobořil

2017-01-24 16:01 GMT+01:00 yallop <notifications@github.com>:

**Comment by stewburnell** [comment]
I believe I've had similar behaviour with an R container that needed to make HTTP requests.  The R script executed correctly on the day I wrote it, then the following days I was getting Bad Request 400 messages every time I ran it, even if I rebuilt the image, making various changes etc.  Only when I restarted my computer a week later and tried it on whim did it work.  So I think that was due to putting my MacBook to sleep.  I was able to replicate that behaviour this morning after my computer had been in sleep mode overnight.
