### ISSUE TITLE
Docker for Mac 1.13.0-rc3 not work under VPN (L2TP)

### ISSUE THREAD

**Issue by dmifedorenko** [docker/for-mac#1049]
### Expected behavior
"docker info" must show actual docker information.

### Actual behavior
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/info: EOF

### Information
In one of last Docker for Mac 1.13 betas VPN mode was broken. All works fine after downgrade to 1.12 stable version.

Docker for Mac: version: 1.13.0-rc3-beta32 (9cf974f9e)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/37148456-F68E-47DA-9AAE-C8B1D0BE32F3/20161216-225809.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/fedorenko/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior
1. Connect to L2TP VPN.
2. Execute in shell "docker info"
3. Check output.

**Comment by djs55** [comment]
I think the root cause is virtualisation-related rather than VPN-related (although perhaps enabling the VPN triggered it). Looking at the docker logs from a few days ago there was a problem accessing VMX:
```
2016-12-09 ... <Notice>: Unable to create VM (-85377018)
2016-12-09 ...  vmx_init: processor not supported by Hypervisor.framework
```
and now there's a hyperkit crash:
```
2016-12-16 22:36:38+10 mac Docker[com.docker.driver.amd64-linux][14689] <Notice>: vm exit[2]
2016-12-16 22:36:38+10 mac Docker[com.docker.driver.amd64-linux][14689] <Notice>: 	reason		VMX
2016-12-16 22:36:38+10 mac Docker[com.docker.driver.amd64-linux][14689] <Notice>: 	rip		0xffffffff8183ba7d
```
Another strange thing I see is too many `com.docker.hyperkit` processes:
```
$ grep com.docker.hyperkit ps-ax.log  | wc -l
       9
```
I see a pattern in the logs:
- launch new `com.docker.hyperkit`
- `vmx_init` failure, cannot create VM
- process supervisor tries again, but the child process is deadlocked and doesn't quit

Perhaps the VM failure is actually out-of-memory, or provoked by memory exhaustion? It's hard to tell whether this is cause or effect.

@dmifedorenko could you try the following:

- stop `Docker`
- manually terminate any leftover processes (`ps uax | grep docker')
- upgrade to beta 33.1 (which has some hypervisor-related deadlock fixes)

If it still reproduces, could you tell me if it only happens if `Docker` is running while the VPN starts? Does it work if you connect the VPN before starting `Docker`?

**Comment by dmifedorenko** [comment]
Upgrade to beta 33.1 fix the problem. Thank you a lot.

You can close this issue now.

**Comment by djs55** [comment]
Great, thanks for letting me know!
