### ISSUE TITLE
"chown" failure trying to use ExpanDrive (virtual drive) as a volume

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1051]
### Expected behavior

I use a virtual drive on OSX (v5.4.2.0  http://ExpanDrive.com) to create a file system /Volumes/archive.example.org/test backed by S3-compatible object storage. 

I expect to be able to use this directory as a docker volume, especially read-only. But I get a "chown" error:

```
$ ls -ld /Volumes/archive.example.org/test
drwxr-xr-x  10000 user1  staff  0 Dec 18 16:27 /Volumes/archive.example.org/test
$ docker run -ti -v /Volumes/archive.example.org/test:/var/input/:ro centos bash
docker: Error response from daemon: error while creating mount source path '/Volumes/archive.example.org/test': chown /Volumes/archive.example.org/test: no such file or directory.
```

### Actual behavior

I get above error because docker for mac apparently needs to "chown" the directory but this virtual file system does not allow it, even trying to assign it to the same user:

```
$ sudo chown root /Volumes/archive.example.org/test
chown: /Volumes/archive.example.org/test: Operation not permitted
$ chown user1 /Volumes/archive.example.org/test
chown: /Volumes/archive.example.org/test: No such file or directory
```

Don't know if all virtual filesystems, e.g. DropBox or iCloud, have this same problem.

### Information

Docker for Mac: version: 1.13.0-rc3-beta33.1 (e35ff41ca)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/9D052C1E-09A7-4126-BC50-6FC7D513ED7C/20161218-163612.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Create an ExpanDrive backed by S3-compatible object storage
  2. Try to use that drive as a Docker for Mac volume.

**Comment by djs55** [comment]
Could you try reporting this issue to ExpanDrive? I think in particular:

```
$ ls -ld /Volumes/archive.example.org/test
drwxr-xr-x  10000 user1  staff  0 Dec 18 16:27 /Volumes/archive.example.org/test
```
-- means the "file" exists

```
$ chown user1 /Volumes/archive.example.org/test
chown: /Volumes/archive.example.org/test: No such file or directory
```
-- means the "file" doesn't exist i.e. it's inconsistent.

On my mac `man 2 chown` describes the error meaning
```
[ENOENT]           A component of path does not exist.
```
which is inappropriate because the path clearly does exist.

Ideally ExpanDrive would agree and make `chown` of a "file" or "directory" to the same owner a no-op. It ought to be easy since it doesn't require any change of the mapping from S3.

For reference I think the error comes from [here](https://github.com/docker/docker/blob/0d93970c527b7bbe970655ada658f3c7466d015a/volume/volume.go#L150) and I suspect the [os.Chown is this one](https://github.com/docker/docker/blob/0d93970c527b7bbe970655ada658f3c7466d015a/pkg/idtools/idtools_unix.go#L63).

**Comment by dsheets** [comment]
This issue is due to ExpanDrive not supporting extended attributes and our not handling that correctly.
