### ISSUE TITLE
Docker can not start

### ISSUE THREAD

**Issue by kstaniek** [docker/for-mac#1052]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Not known
[20161219-003925.tar.gz](https://github.com/docker/for-mac/files/659765/20161219-003925.tar.gz)

  2. ...

**Comment by djs55** [comment]
The logs contain
```
com.docker.hyperkit: [ERROR] Mirage block device raised exception: "Assert_failure lib/qcow.ml:444:13"
```
This [assert](https://github.com/mirage/ocaml-qcow/blob/7399315e42b8762e8faac8b70ed8fcfee28308a1/lib/qcow.ml#L444) triggered because we only support .qcow2 files which have no shared clusters. This also means that refcounting was enabled somehow -- by default Docker for Mac uses the "lazy refcounts" option for efficiency.

The VM console has
```
Configuring host block device ...boot2docker-data: recovering journal
```
The mention of `boot2docker`  suggests that the qcow2 was imported from a previous toolbox / boot2docker -- this could explain where the shared clusters and the refcounting came from.

Do you remember whether the disk was originally imported from boot2docker? Do you remember whether you ever used the "snapshot" feature in Virtualbox?

Unfortunately the only workaround is to use the "Whale menu -> Preferences -> Reset -> Reset to factory defaults" and then say no to importing any toolbox VM. Unfortunately this means that images and containers will need to be rebuilt.

Sorry for the inconvenience, but thank you for reporting the bug.

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
