### ISSUE TITLE
cli issue on update to 1.12.5

### ISSUE THREAD

**Issue by jshartshorn** [docker/for-mac#1082]
### Information

Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/FCBB355B-3A69-4056-B861-B6BCF3F6800E/20161223-115625.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by pebreo** [comment]
I got the error.

**Comment by dsheets** [comment]
Unfortunately, the daemon cannot start because the disk image which holds the files in `/var/lib/docker` has been corrupted. This can happen if the filesystem is unmounted uncleanly during an unexpected system shutdown or an application crash. The workaround is to reset to factory defaults (:whale: ➡️ `Preferences...` :arrow_right: `Uninstall / Reset`) which will unfortunately delete `/var/lib/docker`: all containers and images will need to be rebuilt and Docker volumes will be deleted.

I'm sorry for the inconvenience. On the bright side, once you have reset, you should be automatically switched from the `aufs` graph driver to the `overlay2` graph driver which we have found to be significantly more robust to unexpected shutdowns.

If this doesn't fix the problem you are experiencing, feel free to re-open this issue with more information. Thanks for using Docker for Mac!
