### ISSUE TITLE
Docker for mac freezes

### ISSUE THREAD

**Issue by dazzla76** [docker/for-mac#1104]
### Expected behavior

Containers run and respond normally

### Actual behavior

Container does not respond to external http requests.  
restart container appears to hang.  
Attempt to attach to container bash prompt gives the following output
  docker exec -i -t couchpotato /bin/bash
    rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed:        container_linux.go:247: starting container process caused \"process_linux.go:83: executing setns process caused \\\"exit status 16\\\"\"\n"

Docker ps shows the container as still running

I have to restart docker completely for it to start responding normally again

### Information

Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/ECB1A74B-62E3-41E8-9080-F40F0D7C01D0/20170104-205558.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jmreicha** [comment]
Saw a similar oci runtime error earlier today.  I blew out all the related Docker images, rebuilt and everything started working again.

**Comment by canamo06** [comment]
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/D2F6109F-EDEF-4F4D-A95A-9FB489B53AE8/20170105-133203.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

It is happening to me when my computer is waking up from sleep. So I have to quit docker(restart doesn't work) and start it again.

**Comment by jsjohns** [comment]
I'm also observing identical behavior, e.g.:

```
docker@default:~$ docker exec -it ef2c297c9488 bash
 rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:83: executing setns process caused \\\"exit status 16\\\"\"\n"
```

Version information:

```
macbook$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C67)
      Kernel Version: Darwin 16.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: io
      User Name: Josh Johnson (josh.johnson)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 1:16
```

```
macbook$ docker-machine --version
docker-machine version 0.8.2, build e18a919
```

```
macbook$ docker-machine ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.5, build HEAD : fc49b1e - Fri Dec 16 12:44:49 UTC 2016
Docker version 1.12.5, build 7392c3b
```

```
docker@default:~$ uname -a
Linux default 4.4.39-boot2docker #1 SMP Thu Dec 15 17:43:51 UTC 2016 x86_64 GNU/Linux
```

```
docker@default:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-boot2docker
Operating System: Boot2Docker 1.12.5 (TCL 7.2); HEAD : fc49b1e - Fri Dec 16 12:44:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.821 GiB
Name: default
ID: WIYI:6XWC:T4XX:LUCM:UN47:CKB4:YJY5:WVE3:TXIM:NXIA:NNGQ:QSVX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 49
 System Time: 2017-01-05T20:18:04.108334082Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by thanasis00** [comment]
I am experiencing the exact same behavior, although I have an interesting theory. I was having the exact same problem a few days ago, and decided to uninstall Docker for Mac and install it again (downloaded the latest version). And the problem was fixed! Coming to today, I was prompted to update Docker for Mac, applied the update and the problem appeared once again. I can't be 100% sure that this created the problem, because I was experiencing some other issues as well with my containers, but it seemed to apply in that case.

`system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C67)
      Kernel Version: Darwin 16.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Thanasis MacBook Pro
      User Name: Thanasis Katsadas (thanasis)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3:56`

`docker --version
Docker version 1.13.0-rc5, build 43cc971`

`docker-machine --version
docker-machine version 0.9.0-rc2, build 7b19591`

`docker info
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 1.13.0-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.15-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934 GiB
Name: moby
ID: XC4Q:OGUB:XEYY:QLAR:YLDG:NIVZ:W5A7:C4LR:GLGZ:QSCW:SRVX:C5Y3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 76
 Goroutines: 79
 System Time: 2017-01-10T14:43:40.644765746Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by samoht** [comment]
@dazzla76 Are you still seeing these errors?

@jsjohns and @thanasis00 I am not sure to understand why you gave `docker-machine` versions. Are you reporting an issue with Docker for Mac or with `docker-machine`? In any case, please open a separate issue with a diagnostic ID as described in https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues. Thanks!

**Comment by jsjohns** [comment]
@samoht I provided `docker-machine` version information because I was using it. I understand that this is the Docker for Mac project -- I commented here because this was the only open issue across the Docker, Docker for Mac, and `docker-machine` projects that described the symptoms I observed.

I suspect that this is a bug in Docker itself and not Docker for Mac or `docker-machine`.

**Comment by samoht** [comment]
@jsjohns I see, thankst! Would you be able to also provide a diagnostic ID so I could try to see if I find something interesting in your logs?

**Comment by jsjohns** [comment]
Unfortunately, I can't. The system in question has since been re-imaged.

On Mon, Jan 30, 2017 at 3:44 PM, Thomas Gazagnaire <notifications@github.com

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
