### ISSUE TITLE
Docker not starting after upgrade to 1.13.0-rc5-beta35

### ISSUE THREAD

**Issue by shauvik** [docker/for-mac#1113]
### Expected behavior
Docker should start after update

### Actual behavior
complains about com.docker.osx.hyperkit.linux failing to start on a Mac!

![image](https://cloud.githubusercontent.com/assets/141353/21738085/e96c686e-d44d-11e6-8b53-0a712364e39e.png)

### Information

 - Full output of the diagnostics from "Diagnose & Feedback" in the menu
 
```
Docker for Mac: version: 1.13.0-rc5-beta35 (25211e84d)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/65CD2722-6442-41AE-8D84-507328048A4C/20170106-201457.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/shauvik/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/shauvik/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/shauvik/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/shauvik/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/shauvik/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/shauvik/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Update docker 
  2. Start after update

**Comment by djs55** [comment]
Thanks for the report.

Looking at the logs it looks like the qcow2 has become corrupt:
```
com.docker.hyperkit: [ERROR] Found two references to cluster 31293: 2204.11392 and 75.3976
```
This means that two "clusters" (64 KiB chunks) of the virtual disk have been set to point at the same portion of the physical file, which means a write to one would overwrite the other. Unfortunately it's not safe to continue when this happens, hence the application fails to start.

I notice you upgraded from beta 33.1 to beta 35:
```
2017-01-06 20:13:36-05 ... Docker[com.docker.docker][3743] <Notice>: AppDelegate: new version detected: 1.13.0-rc5-beta35 (previous: 1.13.0-rc3-beta33.1)
```
I think this is significant because in beta 34 there were 2 relevant changes

1. file locking bug fix. This bug would allow 2 processes to edit the qcow2 at once, both allocating the same cluster. Beta 33 was vulnerable to this problem.
2. a change to VM start to check the qcow2 integrity on VM start

I suspect you had some file corruption caused by bug (1) while running beta 33.1 and now this is being detected by change (2) in beta 34.

I think the only way forward is to reset to factory defaults (or alternatively `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`). Unfortunately this will require containers and images to be rebuilt  :(

Let me know if anything else goes wrong -- I'm sorry for the inconvenience this has caused.

**Comment by Lorel** [comment]
I didn't upgrade my beta for a long time, and I encountered the same issue
I confirm it is fixed by
```bash
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
@djs55 thx for the tip ;)

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
