### ISSUE TITLE
Download of 1.12.5

### ISSUE THREAD

**Issue by johnmcconnell** [docker/for-mac#1139]
Anyone know where I can download the dmg for 1.12.5?

1.12.6 breaks a container running: alexeiled/docker-oracle-xe-11g

**Comment by jeremiasalmeidadaitan** [comment]
Having problems with selenium/standalone-chrome. My solution was download docker-toolbox 1.12.5 and remove Docker For Mac.

**Comment by dsheets** [comment]
1.12.5 is available from <https://download.docker.com/mac/stable/1.12.5.14777/Docker.dmg> but **1.12.5 contains a critical security flaw that has been fixed in 1.12.6**. It is vital that you do not use 1.12.5 to run untrusted content.

@johnmcconnell could you be more specific about the issue you encounter with `alexeiled/docker-oracle-xe-11g`? It seems to start for me with 1.12.6. Could you provide step-by-step reproduction instructions? Also, if you're comfortable running the Beta channel (it's generally pretty reliable), could you see if the problem is fixed in those releases?

@jeremiasalmeidadaitan could you be more specific about the issue you encounter with `selenium/standalone-chrome`? It seems to start for me with 1.12.6. Could you provide step-by-step reproduction instructions? Also, if you're comfortable running the Beta channel (it's generally pretty reliable), could you see if the problem is fixed in those releases?

**Comment by dsheets** [comment]
The changelog for 1.12.6 from 1.12.5 is only:

* Upgrades
    - Docker 1.12.6
    - Linux Kernel 4.4.41

* Bug fixes
    - Fix CVE-2016-9962 which can lead to container escapes via a runc vulnerability

**Comment by andrewaustin** [comment]
I also had to roll back to 1.12.5 from 1.12.6. I would see a lot of ```ERROR: Bad response from Docker engine``` and then 1.12.6 seemed to crash. (State changed from ```Docker is running``` to ```Docker is starting```).

**Comment by johnmcconnell** [comment]
Hey @dsheets.

Actually, reinstalling the Docker for Mac (1.12.6) fixed it.

When connecting to the oracle database from the exposed container port: (`localhost:12345`)

The database was throwing a ORA-12505: https://chartio.com/resources/tutorials/how-to-fix-ora-12505-tns-listener-does-not-currently-know-of-sid-given-in-connect-descriptor/

That is the best I got.

**Comment by dsheets** [comment]
@andrewaustin could you please open a new issue with your uploaded diagnostic ID and macOS and Docker for Mac versions?

@johnmcconnell We'd be happy to try to reproduce the issue including the migration from 1.12.5 to 1.12.6. We're not familiar with Oracle, though, so you'd need to post step-by-step instructions.

**Comment by johnmcconnell** [comment]
Hey,

Okay steps.

1. download and install docker for mac 1.12.5
2. download and install docker for mac 1.12.6
3. start oracle container: `docker run -d -p 49160:22 -p 49161:1521 alexeiled/docker-oracle-xe-11g`
4. Try to connect (with SQL developer or JDBC) using the following credentials 
     (hostname: localhost, port: 49161, SID: xe, username: system, password: oracle)
5. The connection will be refused and give an ORA-12505

**Comment by dsheets** [comment]
@johnmcconnell I tried your reproduction steps with SQLDeveloper but could not reproduce. I'm glad it's working for you now, though. If you have further issues using Docker for Mac in the future, please file a new issue. Thanks!

**Comment by wied03** [comment]
Anyone have the link for 1.12.6? 1.13.0 broke a different Oracle DB setup for me and I haven't yet had time to figure out why.

**Comment by mrhanlon** [comment]
Link for 1.12.6 is https://download.docker.com/mac/stable/1.12.6.14937/Docker.dmg

**Comment by wied03** [comment]
Thks
