### ISSUE TITLE
E72DF63F-C6D9-40FD-B788-6AFAD49C1301

### ISSUE THREAD

**Issue by KrayTwins** [docker/for-mac#1141]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. upgade
  2. start docker from aaplications

Docker for Mac: version: 1.13.0-rc6-beta36 (a158c69c7)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/E72DF63F-C6D9-40FD-B788-6AFAD49C1301/20170115-052127.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/williammallett/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/williammallett/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/williammallett/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/williammallett/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/williammallett/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/williammallett/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

**Comment by dsheets** [comment]
It looks like this is related to #1062

Looking at the logs it looks like the qcow2 has become corrupt:
```
com.docker.hyperkit: [ERROR] Found two references to cluster 29567: 7.65400 and 7.65024
```
This means that two "clusters" (64 KiB chunks) of the virtual disk have been set to point at the same portion of the physical file, which means a write to one would overwrite the other. Unfortunately it's not safe to continue when this happens, hence the application fails to start.

I notice you upgraded from beta 27 to beta 36:
```
2017-01-15 01:13:22.698821+1000  ... Docker[3001]: [com.docker.docker.] AppDelegate: new version detected: 1.13.0-rc6-beta36 (previous: 1.12.2-rc1-beta27)
```
I think this is significant because in beta 34 there were 2 relevant changes:

1. file locking bug fix. This bug would allow 2 processes to edit the qcow2 at once, both allocating the same cluster. Beta 27 was vulnerable to this problem.
2. a change to VM start to check the qcow2 integrity on VM start

I suspect you had some file corruption caused by bug (1) while running beta 27 or earlier and now this is being detected by change (2) in beta 34.

I think the only way forward is to reset to factory defaults (or alternatively `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`). Unfortunately this will require containers and images to be rebuilt and will remove any Docker volumes. :(

Let me know if anything else goes wrong -- I'm sorry for the inconvenience this has caused.

**Comment by yallop** [comment]
I'm closing this as a duplicate of #1159; please subscribe to that issue if you'd like updates on the problem, and please feel free to open a new issue if the workarounds above (e.g. deleting `Docker.qcow2`) don't solve the problem for you.
