### ISSUE TITLE
Docker ps fails after running for 1 day

### ISSUE THREAD

**Issue by benjlai** [docker/for-mac#1143]
### Expected behavior
docker ps to work 
### Actual behavior
Error response from daemon: Bad response from Docker engine
### Information

Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/2C66082A-AFE2-4659-ADC9-2FDFDA4664FB/20170115-174538.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Run postgres docker image
  2. create 2 databases
  3. leave it run overnight

This happens 2 days in a row.

**Comment by dsheets** [comment]
I see several recent crashes due to a use-after-free bug in one of the supervisory processes. I'm escalating this issue to the relevant team. Thanks for your report!

**Comment by ijc25** [comment]
@benjlai @pfeilbr @Nithanaroy. Thanks for your various reports, I believe @dsheets has consolidated them all here so I'll just post this here.

Since the issue you are all seeing appears to be a use-after-free we only get a crash when the corruption eventually surfaces elsewhere in the code base, which makes it rather tricky to track down.

It would be useful if you could each run Docker for Mac with additional checks in the Macos memory allocator enabled. You can do this by:
* Exiting Docker for Mac (Chose `Quit` from the Whale menu)
* Open a terminal window
* Run `MallocLogFile=docker-malloc.log MallocScribble=1 MallocCheckHeapStart=1 MallocCheckHeapEach=1 MallocCheckHeapAbort=1 /Applications/Docker.app/Contents/MacOS/Docker` (if you have installed other than to `/Applications/Docker.app` then adjust as appropriate).
* Continue to use Docker as usual until you next observe the issue.
* Run `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u` (again adjust if not installing to `/Applications/Docker.app`) and post the output here attaching `$HOME/docker-malloc.log` at the same time.

In my experiments enabling these aggressive memory allocation checks makes the Docker UI rather sluggish (not completely unusable, but not great) however interactions with the docker daemon via the CLI (`docker run`, `docker build` etc) are not effected so things remain usable for doing actual work.

If you find it to be otherwise for you then please try with just `MallocLogFile=docker-malloc.log MallocScribble=1 /Applications/Docker.app/Contents/MacOS/Docker` (i.e. none of the `MallocCheckHeap*` options) which isn't as aggressive but may still produce useful information.

Thanks all for your help.

**Comment by samoht** [comment]
@benjlai @pfeilbr @Nithanaroy ping. It would be very helpful if you can try the steps described by @ijc25 just above. Thanks!

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
