### ISSUE TITLE
Docker for Mac OS Sierra Start Up Issues Diagnostic ID 96E5E549-C29C-4497-8C71-CA6B327F72F3

### ISSUE THREAD

**Issue by roacobb** [docker/for-mac#1147]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dsheets** [comment]
It looks like this is related to #1062

Looking at the logs it looks like the qcow2 has become corrupt:
```
com.docker.hyperkit: [ERROR] Found two references to cluster 23013: 5214.7040 and 5214.6784
```
This means that two "clusters" (64 KiB chunks) of the virtual disk have been set to point at the same portion of the physical file, which means a write to one would overwrite the other. Unfortunately it's not safe to continue when this happens, hence the application fails to start.

I notice you upgraded from beta 33.1 to beta 36:
```
2017-01-12 14:08:57-05 ... Docker[com.docker.docker][60380] <Notice>: AppDelegate: new version detected: 1.13.0-rc6-beta36 (previous: 1.13.0-rc3-beta33.1)
```
I think this is significant because in beta 34 there were 2 relevant changes

1. file locking bug fix. This bug would allow 2 processes to edit the qcow2 at once, both allocating the same cluster. Beta 33 was vulnerable to this problem.
2. a change to VM start to check the qcow2 integrity on VM start

I suspect you had some file corruption caused by bug (1) while running beta 33.1 and now this is being detected by change (2) in beta 34.

I think the only way forward is to reset to factory defaults (or alternatively `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`). Unfortunately this will require containers and images to be rebuilt and will remove any Docker volumes. :(

Let me know if anything else goes wrong -- I'm sorry for the inconvenience this has caused.

**Comment by yallop** [comment]
I'm closing this, as there's a workaround (deleting the `Docker.qcow2`) file, but please feel free to reopen if the workaround doesn't work for you, or if you experience further problems, @roacobb.
