### ISSUE TITLE
Unable to start docker daemon on mac

### ISSUE THREAD

**Issue by tdigangi5** [docker/for-mac#1148]
### Expected behavior
docker to start up on run daemon on mac OSx Yosimite 10.10.5
### Actual behavior
docker is stuck in endless starting cycle
diagnostic id: C6873C65-7421-4AF6-8BA5-8F2A9A60027F
### Information
docker 1.12.5 was working correctly as of Friday. When I started my Mac today Docker cannot seem to run. After facing this issue, I restarted the daemon multiple times through the UI. restarted the system and still nothing

### Steps to reproduce the behavior

  1. restart Mac 
  2. wait for docker daemon to start
  3. docker stuck in enless cycle

**Comment by dsheets** [comment]
It looks like your virtual block device has become corrupted, possibly due to a bug in OS X 10.10.5's Hypervisor.framework related to suspend/resume. If you `Reset to factory defaults` from :whale: ➡️ `Preferences...` ➡️ `Uninstall / Reset`, the virtual block device will be configured to use the overlay2 graph driver, which we have found more robust, rather than AUFS. Unfortunately, this will delete all of your containers, images, and Docker volumes. Finally, we recommend upgrading, if you can, to OS X 10.11 or 10.12 which have more stable Hypervisor.framework implementations.

Sorry about that. Thanks for using Docker for Mac!
