### ISSUE TITLE
Accessing private registry on Kubernetes through port forwarding

### ISSUE THREAD

**Issue by andrey-moor** [docker/for-mac#1160]
I'm trying to push image to the private registry deployed in Kubernetes cluster. I'm using port forwarding on the host (on my Mac) of port 5000 so repository looks like `localhost:5000`.

### Expected behavior

Image should be pushed successfully to the private registry within Kubernetes cluster and be available for pull within it.

### Actual behavior

Push doesn't work as it seems like forwarded port is not being used by docker for Mac.

**Comment by dsheets** [comment]
Could you please tell us which version of Docker for Mac you are using and exactly which `docker` commands you are executing to both start the server and connect to it?

**Comment by andrey-moor** [comment]
I'm using Version 1.12.6 (14937) of Docker for Mac. K8s deployment is not local and I'm using the following command to forward port 5000: 
`kubectl port-forward --namespace kube-system $POD 5000:5000 &`

I can confirm that docker registry is accessible by sending raw http requests. 
`$ curl -I localhost:5000/v2/`
`Handling connection for 5000
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Fri, 20 Jan 2017 17:58:51 GMT
`

But commands like 
`docker push localhost:5000/andrey/image` and `docker pull localhost:5000/andrey/image` return an error: 
`Pulling repository localhost:5000/andrey/hello
Error while pulling image: Get http://localhost:5000/v1/repositories/andrey/hello/images: dial tcp [::1]:5000: getsockopt: connection refused`

**Comment by sazbad** [comment]
I can reproduce the same issue.

**Comment by sirajmansour** [comment]
I am experiencing the same behaviour exactly.

**Comment by luciferous** [comment]
This is because Docker for Mac runs inside a VM, and localhost:5000 is resolved within the VM environment. What we'd need to do is forward the VM's localhost:5000 to the registry pod. I'm not sure how to do this, though.

**Comment by djs55** [comment]
If the `localhost` address is `127.0.0.1` on the Mac host, then the VM can connect to it by the internal IP address `192.168.65.1`. In version `17.06` this should be exposed by the DNS name `docker.for.mac.localhost`.

If you'd like to forward the VM's `localhost:5000` somewhere then you could `docker run --net=host <some proxy program>` (`--net=host` will run the container in the VM's network namespace)

**Comment by andrey-moor** [comment]
I guess `docker run --net=host ` will not help when I need registry access.

**Comment by luciferous** [comment]
What I ended up doing as a workaround:
1. Open a terminal into the VM session
a. `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`
b. `apk update`
c. `apk add socat`
d. `socat TCP-LISTEN:5000,reuseaddr,fork TCP:$HOST_IP_ADDR:5000`
2. On the host
a. `brew install socat`
b. `socat TCP-LISTEN:5000,bind=$HOST_IP_ADDR,reuseaddr,fork TCP:localhost:5000`

The `HOST_IP_ADDR` is the IP of the host on my LAN. This works by forwarding TCP traffic from VM-localhost:5000 to HOST-IP:5000, which forwards to HOST-localhost:5000, where `kubectl` is forwarding to the remote pod.

**Comment by tkgregory** [comment]
@luciferous I have tried your solution but I can't get it working. I have the following commands running:

On the host (mac)
`kubectl --namespace kube-system port-forward kube-registry-v0-1nbj5 5000:5000`
`socat TCP-LISTEN:5000,bind=$HOST_IP_ADDR,reuseaddr,fork TCP:localhost:5000`

On the docker for mac container
`socat TCP-LISTEN:5000,reuseaddr,fork TCP:$HOST_IP_ADDR:5000`

The `docker push` command no longer immediately fails, but times out after about a minute. I can hit the registry using `curl -I localhost:5000/v2/` so am fairly confident that it is running as expected. Any ideas?

**Comment by luciferous** [comment]
@tkgregory Where is your kubernetes cluster running? I'm using something I created with kops/AWS. I'm not sure if it matters (it shouldn't, but we are doing something weird here). Also, does the `curl` command work inside the docker for mac container?

Try change the ports so that you have:
- docker for mac: localhost:5000 => $HOST_IP_ADDR:5001
- on  the host (mac): $HOST_IP_ADDR:5001 => kubernetes:5000

**Comment by tkgregory** [comment]
@luciferous Thanks for your follow up. I'm actually running on Minikube, so essentially a container inside VirtualBox. Will try your suggestions when I get a bit of time.

**Comment by stevenaldinger** [comment]
Anyone have any luck? I'm gonna be working on it for a while tonight.

**Comment by rkuzsma** [comment]
Running Docker for Mac 17.06, I was able to push to a private registry running in a Kubernetes pod port-forwarded to localhost:5000. Add `docker.for.mac.localhost:5000` to your list of insecure registries. Then run:
`docker push docker.for.mac.localhost:5000/some-image`

**Comment by Amit-PivotalLabs** [comment]
@rkuzsma Thanks, after doing that I was able to push.  I'm running [this registry](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) in my K8s cluster.  After pushing like you did, how then are you referring to the images in your container specifications?  I've tried both `localhost:5000/some-image` and `docker.for.mac.localhost:5000/some-image` and I get either an `ImagePullBackOff` error or an `ErrImagePull` error, respectively.

**Comment by artemyarulin** [comment]
Not related to the original issue, but if you just want to build images and start using it inside your k8s cluster there is no need to have dedicated registry:

Just build image `docker build --tag foo:42 [your-app-folder]` and then in your pod ensure to have following 
```
...
  image: foo:42
  imagePullPolicy: Never
...
```
`kubectl apply --filename pod.yaml` and you'll get the new app version. Use `sed/grep` magic in order to automate it, but important thing is to use different tag number and to have `imagePullPolicy: Never`, in that case k8s will pull the image from your local docker cache

**Comment by monoj** [comment]
> I've tried both localhost:5000/some-image and docker.for.mac.localhost:5000/some-image and I get either an ImagePullBackOff error or an ErrImagePull error, respectively.

I am facing similar issue as @Amit-PivotalLabs. 

@artemyarulin, in my case i would like to build images in my mac, and start using inside the K8s cluster, so the above approach will be not sufficient for me.

**Comment by quantonganh** [comment]
@Amit-PivotalLabs @monoj You still have to add that hostname into `/etc/hosts` on the docker host:

```
❯❯❯❯ minikube ssh "cat /etc/hosts"
127.0.0.1	localhost docker.for.mac.localhost
127.0.1.1	minikube
```

then I can pull the images on my Mac:

```
❯❯❯❯ docker pull docker.for.mac.localhost:5000/grpc-k8s-api
Using default tag: latest
latest: Pulling from grpc-k8s-api
1160f4abea84: Already exists
4d49542c61a4: Already exists
3ee103c86f60: Already exists
9a56d2eb1eed: Already exists
67e0ebed9a3b: Already exists
194910951a14: Already exists
add9d3c0a673: Pull complete
Digest: sha256:84da046571366f28291834fa8921193b296907475ed7fc88dd4c82b14c16674f
Status: Downloaded newer image for docker.for.mac.localhost:5000/grpc-k8s-api:latest
```

**Comment by hypnoglow** [comment]
@monoj 
> in my case i would like to build images in my mac, and start using inside the K8s cluster, so the above approach will be not sufficient for me.

This can be done in another way without registry:
```
docker save some-image:latest | (eval $(minikube docker-env) && docker load)
```

**Comment by Amit-PivotalLabs** [comment]
In my case, I have Docker version 17.12.0-ce-mac46 on my Mac, and Kubernetes v1.8.2 running in the cloud.  I'm following the instructions [here](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) to run a registry as an addon in my K8s so that I don't need to deal with the overhead of pushing to DockerHub and want to exercise a self-contained workflow.

Because the URL that I use to push to the Docker registry from my local workstation is conflated with the URL the kubelet pulls from (because it's baked into the image tag), I need a hostname that both my local workstation and the kubelet can agree on pointing at the same thing.  Furthermore, the cluster registry addon linked above doesn't have basic security features so Docker running on the K8s worker would fail to pull unless it can see the registry as "localhost".  Therefore, I have to push from my workstation to "localhost".

This would seemingly be possible via a `kubectl port-forward` so that `localhost:5000` goes to the registry running in K8s, but **the problem seems to be that my local Docker resolves localhost to an IPv6 address, and that will fail because the `kubectl port-forward` is set up against `127.0.0.1` and the registry pod's `hostPort: 5000` configuration only applies to IPv4 as well**.

`localhost` is being resolved a such because that's how `/etc/hosts` looks on my Mac, and that's the default, so I don't intend to touch it.  I notice that when I run `curl` against `localhost` it also first tries `::1`, fails to establish a connection, and then falls back to `127.0.0.1` and works.

I suspect there are a few potential feature requests here:

* `docker` should follow `curl` and be able to try both IPv4 and IPv6 addresses if the first one it tries fails for certain types of failures.
* The registry addon (separate project) should support proper TLS and authentication so as to not need to use this "localhost" hack
* I should run a different registry that already has the required security features
* Specifying the URL of the registry to push to/pull from should be decoupled from the repo+image+tag in the Docker/K8s ecosystem so that I can push `some-image` to `127.0.0.1:5000` but in my K8s pod spec, specify the container to use `image: some-image` from `registry_url: localhost:5000`.

Just some ideas, thanks for reading!

**Comment by wittlesouth** [comment]
I have the same issue as @Amit-PivotalLabs, but I'm running my Kubernetes cluster on an internal network (not my mac). I'm not sure my solution works for everyone who is seeing this, but it might be worth sharing.

The local Kubernetes registry project referenced in @Amit-PivotalLabs post is configured to listen on port 5000 on all of its hosts if you follow its instructions. You can push an image to its repository by using port 5000 on an accessible domain name for one of the hosts in the cluster (I admit I've only tested this on the master host so far).

`docker tag <image> <kubernetes_host_name:5000>/<user>/<image_name>:<image_tag>`
 `docker push <kubernetes_host_name:50000>/<user>/<image_name>:<image_tag>`

Unfortunately, while this does show progress (the docker image starts uploading), I'm getting file integrity checksum failure errors for the larger layers. I'm not sure of the cause, but passing the general suggestion on anyway in case it it useful.

**Comment by meori** [comment]
Found a workaround for Mac:
Since the localhost is resolved in the internal docker VM, we need to set port forwarding there.
To do so, we need to run a container that has access to the base docker VM's network settings.
This can be done by running a container with nsenter.
The solution we ended up using is running another container that does that and then manages the port forwarding with socat (you'll need an image with socat installed for that).

 `docker run -it --privileged --pid=host IMAGE_WITH_SOCAT nsenter -t 1  -u -n -i socat TCP-LISTEN:5000,fork TCP:docker.for.mac.localhost:5000` 

leaving this image running in the background - you can now access localhost:5000 from docker.

**Comment by vsayer** [comment]
@rkuzsma

Oddly enough at `17.12.0`, I can no longer resolve `docker.for.mac.localhost` or `docker.for.mac.host.internal`. I can This flow was working before. Not sure what changed in xhyve.

With the kubectl port forwarder to registry, I can still curl to localhost:5000, but now can't `docker push` to `docker.for.mac.host.internal:5000`

**Comment by petermikitsh** [comment]
I'm running a private docker registry on a remote Kubernetes cluster, and here's what worked for me.

Using port forwarding, I've specified address `0.0.0.0`:

`kubectl port-forward service/docker-registry 8080:5000 --address 0.0.0.0`

Then I logged in and was able to pull images, e.g.,

```
docker login 0.0.0.0:8080
docker pull 0.0.0.0:8080/myimage:latest
```

**Comment by timbrandin** [comment]
I'm running a private docker registry (installed using this [helm](https://github.com/helm/charts/tree/master/stable/docker-registry)) on a remote Kubernetes cluster, and here's what worked for me.

This worked for me to expose the registry locally:
```console
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=docker-registry,release=register" -o jsonpath="{.items[0].metadata.name}")
$ kubectl port-forward $POD_NAME 5000:5000
```

I also specified `0.0.0.0:5000` as an insecure registry in the Docker for Mac preferences 'Daemon' tab.

![image](https://user-images.githubusercontent.com/1715834/52274619-84dff080-294d-11e9-8af8-65c8ab52b15e.png)

Then I was able to tag and push an image that I already had locally (node:8-alpine):
```console
$ docker tag node:8-alpine 0.0.0.0:5000/node
$ docker push 0.0.0.0:5000/node
The push refers to repository [0.0.0.0:5000/node]
8b59e4cead98: Pushed
7aa09d2ca0a3: Pushed
df64d3292fd6: Pushed
latest: digest: sha256:81abb8de1e5e8b6e55bca143b3c2ec1e2d167cb27fd2cd3191a0d222f7c5e710 size: 951
```

**Comment by JCzz** [comment]
Thank you @timbrandin
docker push 0.0.0.0:5000/<imageName> that really did work :-)

How do you reference the image in a deployment then?

**Comment by habbas99** [comment]
@JCzz I have the same issue. In my case, I can push to the private registry in the k8s cluster but when I reference in the image in my pod spec file I get a connection refused.
