### ISSUE TITLE
Unable to start Docker after updating to 1.13.0 

### ISSUE THREAD

**Issue by MarcoMontel** [docker/for-mac#1173]
### Expected behavior
Operational docker environment
### Actual behavior
Error during startup 
### Information

Diagnostic ID: 2E740794-8126-4A51-AD00-95E5DFFBE421

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.1 (build: 16B2555)
logs: /tmp/2E740794-8126-4A51-AD00-95E5DFFBE421/20170120-142458.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mmontel/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mmontel/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mmontel/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mmontel/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mmontel/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mmontel/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Update to 1.13.0

**Comment by MarcoMontel** [comment]
As explained in #1159 removing the Docker.qcow2 file I was able to start Docker

`rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`

**Comment by jdaehn** [comment]
This fix does get Docker running again, but beware: you'll lose all your local images and containers.

**Comment by yallop** [comment]
I'm glad to hear that you've found a workaround for the problem.  A little more detail, in case you're interested:

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

The issue docker/for-mac#1159 has more information.

**Comment by timiTao** [comment]
👍  fix working, thanks :)
