### ISSUE TITLE
docker won't start diagnostic id = 0B363704-B279-4996-9D5C-DCF3B806FA9F

### ISSUE THREAD

**Issue by gnbchwarz** [docker/for-mac#1177]
### Expected behavior
Docker starts
### Actual behavior
I see a sweating whale
### Information

  Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/0B363704-B279-4996-9D5C-DCF3B806FA9F/20170120-121043.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/bschwarz/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/bschwarz/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bschwarz/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/bschwarz/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/bschwarz/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/bschwarz/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. try to launch docker

**Comment by cneth** [comment]
Take a look at: https://github.com/docker/for-mac/issues/1173 and try the fix suggested there.

**Comment by yallop** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.
