### ISSUE TITLE
docker for mac won't start on OSX 10.10.5

### ISSUE THREAD

**Issue by nrser** [docker/for-mac#1180]
### Expected behavior

docker for mac starts when os starts and when app is started.

### Actual behavior

docker for mac fails to start with an error message:

```
Fatal Error

com.docker.osx.hyperkit.linux failed to start
Exit code 1
```

### Information

diagnostic output:

```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/37C652A3-8DA4-4BC8-891B-0FB1A3094649/20170121-120832.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/nrser/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/nrser/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/nrser/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/nrser/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/nrser/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/nrser/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. start docker for mac

**Comment by nrser** [comment]
i just turned this machine back on after being away from it for a few weeks. docker for mac was working fine before it was shut down. the OS is fully updated.

**Comment by viztastic** [comment]
I'm still getting this exact same error

**Comment by yallop** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

**Comment by nrser** [comment]
thanks, i had already gone for a re-install which cleared the issue up.
