### ISSUE TITLE
Docker run slow start

### ISSUE THREAD

**Issue by cangussu** [docker/for-mac#1183]
### Expected behavior

Run the command: `docker run -ti --rm ubuntu true` in less than a second.

### Actual behavior

Takes 5 seconds or more.

### Information

The diagnostic ID: 17884C2E-239C-4696-B162-25C0FE2CC717

As a comparison, it takes less than 1 second to run the same command inside a VirtualBox Ubuntu machine running on the same Mac Mini host.

### Steps to reproduce the behavior

  1. `docker run -ti --rm ubuntu true`
  2. wait for 5 or more long seconds :(

I have tested in both beta and stable - 1.13.0 (15072) - channels, same behaviour.

**Comment by samoht** [comment]
I cannot reproduce the timings that you see, but your logs indeed indicate that something wrong is going on:

```
Jan 21 14:03:42 moby root: time="2017-01-21T14:03:42.618220557Z" level=debug msg="sandbox set key processing took 589.471465ms for container 4b30d08b7f7ed70f13e5966a0b386a61cb26fd78d6447d07d9e1a8598a8ab372"
Jan 21 14:14:23 moby root: time="2017-01-21T14:14:23.171153388Z" level=debug msg="sandbox set key processing took 331.050517ms for container 32977ed8982ad309ec7d9f76e3ed6a2aeb20d869269c225832cd157d35c7ce01"
Jan 21 14:14:31 moby root: time="2017-01-21T14:14:31.851060341Z" level=debug msg="sandbox set key processing took 321.611812ms for container 5ac69ca2aee1796d301b2d2a5f61604b42fac3e8df8986222aa1a788f8db903f"
Jan 21 14:17:03 moby root: time="2017-01-21T14:17:03.139876408Z" level=debug msg="sandbox set key processing took 285.851761ms for container 6dcb25f55570f306658ed5322e8cea76190af10fa5816f6cae0fb0bd3ab76743"
Jan 21 14:30:55 moby root: time="2017-01-21T14:30:55.308641976Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jan 21 23:09:05 moby root: time="2017-01-21T23:09:05.026008094Z" level=debug msg="sandbox set key processing took 384.078518ms for container 2f4c8989b967272bf1a073450901aa78c24d16652508290f19589c041aec4747"
Jan 21 23:09:13 moby root: time="2017-01-21T23:09:13.267582221Z" level=debug msg="sandbox set key processing took 249.710535ms for container ce50c4b5f783b543c3da5c8070fe771f3e31b6fe9901f815d21b5e1a9adbfa50"
Jan 21 22:22:07 moby root: time="2017-01-21T22:22:07.824863913Z" level=debug msg="sandbox set key processing took 396.596883ms for container 025fc2f8b7d6d63d47fd19a113b6d806cf46d92a549ccd6b30e5a046a8205b5b"
Jan 21 22:22:16 moby root: time="2017-01-21T22:22:16.041392287Z" level=debug msg="sandbox set key processing took 234.751915ms for container 23ee010f72b802278d316940a48b595d45947992c715c6242a1d148f2b205124"
Jan 21 22:22:25 moby root: time="2017-01-21T22:22:25.623898113Z" level=debug msg="sandbox set key processing took 284.010786ms for container 9db7acafb210907326cdb2b09838523870dd9c17d46e390d5307621d7ef64c0a"
Jan 21 22:22:34 moby root: time="2017-01-21T22:22:34.825285271Z" level=debug msg="sandbox set key processing took 251.830246ms for container 9c6be65911672524d7b1fe475167b73ca090d84ddf7232746862638b400a644e"
Jan 21 22:22:39 moby root: time="2017-01-21T22:22:39.588084854Z" level=debug msg="sandbox set key processing took 242.927391ms for container fc6ecb815f1ed36f74a8f1f55c0b087f6d5cdc835a1d9f105a861c52a562fb21"
Jan 21 22:22:45 moby root: time="2017-01-21T22:22:45.922855125Z" level=debug msg="sandbox set key processing took 273.323432ms for container 1220e1d039b6294350a151a475f7851e915b1e593f8c6d5ad550bf8e28800767"
Jan 21 22:22:55 moby root: time="2017-01-21T22:22:55.969588509Z" level=debug msg="sandbox set key processing took 231.577411ms for container 5b5a253c55b7050aeb22331f740afd361807874786aa652bc2cf65df6a148e74"
```

(although only the first one took more than 5s apparently)

Which CPU do you have? Where do you store the `qcow2` image? Is is on a local disk or on a network drive?

**Comment by cangussu** [comment]
It is a Mac mini (late 2012) with a 2.3 GHz i7. Everything is on the local spinning (5400 rpm) disk.

**Comment by dave-tucker** [comment]
@cangussu what happens if you remove all of your containers and/or "Reset to Factory Default" within the "🐳 > Preferences > Reset" menu (Warning this will delete all containers/images).
I have a feeling something may be wrong with some (hopefully old) containers on your system that might be the result of the delays.

Alternatively the rather excellent `docker container prune` and `docker image prune` commands are a good way of removing any cruft left over from previous Dockering.

**Comment by cangussu** [comment]
Did the factory reset but the problem persists.

**Comment by ijc25** [comment]
@cangussu thanks for confirming. Are you performing any other actions between the factory reset and running `docker run -ti --rm ubuntu true`?

I ask because your logs contain:
```
Jan 21 22:23:29 moby root: time="2017-01-21T22:23:29.399044208Z" level=error msg="Error getting nodes: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."  
Jan 21 22:23:29 moby root: time="2017-01-21T22:23:29.399082147Z" level=error msg="Handler for GET /v1.25/nodes returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."  
```
and I wonder if perhaps attempting to communicate with a (non-existent) swarm is causing the delay.

Please could you update to the latest stable (currently 1.13.1), perform a factory reset, immediately run `time docker run -ti --rm ubuntu true` three times (since the first time will be slow due to the pull, then one which should be fast and another for good measure) and then immediately upload a new diagnostic along with the output of the three `time docker run -ti --rm ubuntu true` runs.

FWIW I see (with beta42 which is very similar to current stable):
```
$ time docker run -ti --rm ubuntu true
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
8aec416115fd: Pull complete 
695f074e24e3: Pull complete 
946d6c48c2a7: Pull complete 
bc7277e579f0: Pull complete 
2508cbcde94b: Pull complete 
Digest: sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950
Status: Downloaded newer image for ubuntu:latest

real	0m11.700s
user	0m0.020s
sys	0m0.013s
$ time docker run -ti --rm ubuntu true

real	0m1.198s
user	0m0.011s
sys	0m0.008s
$ time docker run -ti --rm ubuntu true

real	0m1.243s
user	0m0.012s
sys	0m0.008s
$ time docker run -ti --rm ubuntu true

real	0m1.233s
user	0m0.012s
sys	0m0.008s
```

**Comment by cangussu** [comment]
I upgraded and now I have the CE version and the same timings.

New diagnostic after upgrade/reset: 7184CF99-68ED-459B-A434-BF7173FA36AF

Where can I see those moby logs?

```
$ for t in $(seq 1 5); do time docker run --rm ubuntu true; done

real	0m5.186s
user	0m0.015s
sys	0m0.015s

real	0m4.614s
user	0m0.018s
sys	0m0.015s

real	0m5.783s
user	0m0.018s
sys	0m0.014s

real	0m4.728s
user	0m0.017s
sys	0m0.014s

real	0m5.417s
user	0m0.018s
sys	0m0.015s
```

**Comment by djs55** [comment]
It's possible to look at the logs in a live moby by running a privileged shell with a command like `docker run --rm --net=host --pid=host --privileged -it justincormack/debian nsenter -m -t 1 sh`

Comparing your `/var/log/docker.log` to mine, the timestamps shows yours going a bit more slowly but I don't see any particular step which is particularly slow. I notice you mentioned you have a local spinning disk -- this may be relevant because in v1.13 we switched to an extremely conservative implementation of block device `flush`. When something in the VM really wants to commit data to stable storage (which probably `docker` does while its adding network setup instructions to the local database) then it issues a `flush`. In v1.12.1 we took the conservative advice of the [fsync manpage](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/fsync.2.html) and used `fcntl(F_FULLFSYNC)`. It turns out that this is very slow even on a machine with a fast SSD. It may well be even slower on a system with a spinning disk.

In the `edge` channel (note: a new release is due to be released today) we switched the default to a plain `fsync` rather than `fcntl` which is much higher performance and only slightly less safe (in particular we're more vulnerable if macOS crashes). On my fast local SSD this decreases the `docker run` latency from ~1.3s to ~0.8s.

Could you try the following:
```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ cat com.docker.driver.amd64-linux/disk/on-flush 
drive
$ echo os > com.docker.driver.amd64-linux/disk/on-flush 
$ git add com.docker.driver.amd64-linux/disk/on-flush 
$ git commit -s -m 'use fsync'
[master 21022ad] use fsync
 2 files changed, 2 insertions(+), 2 deletions(-)
```
the VM will automatically reboot, but containers will be preserved.

Let me know if this makes a difference for you. For reference the `fsync` vs `fcntl` ticket is #668.

Thanks again for your report!

**Comment by jeanlaurent** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by lsh-0** [comment]
I'm not sure if this is the most appropriate place to report this, but I'm seeing similar timing. I've used docker once in the past but I remember it being much faster.

```
$ for t in $(seq 1 5); do time sudo docker run --rm ubuntu true; done

real	0m4.886s
user	0m0.029s
sys	0m0.007s

real	0m5.549s
user	0m0.003s
sys	0m0.022s

real	0m6.361s
user	0m0.023s
sys	0m0.000s

real	0m6.572s
user	0m0.016s
sys	0m0.010s

real	0m5.904s
user	0m0.025s
sys	0m0.000s
```

system information:
* arch
* Docker version 17.10.0-ce, build f4ffd2511c
* btrfs fs

is this 4-6 seconds normal? cheers

**Comment by cangussu** [comment]
I don't think it's normal for a Linux box.

- Ubuntu 16.04.3 LTS
- Docker version 17.05.0-ce, build 89658be
- ext4

```
real	0m0.467s
user	0m0.004s
sys	0m0.012s

real	0m0.529s
user	0m0.012s
sys	0m0.004s

real	0m0.510s
user	0m0.012s
sys	0m0.004s

real	0m0.484s
user	0m0.016s
sys	0m0.000s

real	0m0.480s
user	0m0.012s
sys	0m0.000s
```

**Comment by ryancastle** [comment]
I'm seeing over 1s latency on a top-end macOS machine. Compared to 200ms latency on our low-end Linux VPS. Switching to edge did not make a difference.

It's probably hard to avoid on mac, but it does make Docker less viable as a front-end development support tool.
