### ISSUE TITLE
Installation failing for Current stable Docker on mac

### ISSUE THREAD

**Issue by corniste01** [docker/for-mac#1192]
### Expected behavior
install docker and start right up with the current version
### Actual behavior
Docker won't start
### Information
8AF80276-3E29-4831-AE27-436B9CCE9F7D
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. uninstall docker toolbox as per the instructions
  2. download current version of docker and try to install.
3. Installation fails

**Comment by yallop** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.
