### ISSUE TITLE
Fresh install of Docker for Mac 1.13.0 stuck at "Docker is Loading"

### ISSUE THREAD

**Issue by edgrosvenor** [docker/for-mac#1194]
### Expected behavior
Docker Starts

### Actual behavior
Docker Does Not Start

### Information

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/9C511D3F-16DB-44E5-AE74-BBD5F1BA1A4C/20170123-135225.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install Docker
  2. Attempt to start Docker
  3. Run diagnostics after nothing happens for 30 minutes or so
  4. Repeat several times
  5. Open issue

**Comment by hatembr** [comment]
same here.

**Expected behavior**
Docker Starts

**Actual behavior**
Docker fails to start with the following error: 
```
com.docker.osx.hyperkit.linux failed to start
Exit code 1
```

**Diagnostic**


```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/AACC4361-0E87-4545-8EF7-A3B07E548542/20170123-171809.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/hatembenrais/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/hatembenrais/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/hatembenrais/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/hatembenrais/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/hatembenrais/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/hatembenrais/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

Diagnostic ID: AACC4361-0E87-4545-8EF7-A3B07E548542

Steps are simple, after installing the update, try to start docker and it will fail with error mentioned above.

**Comment by ddacunha** [comment]
+1

**Comment by ddacunha** [comment]
Removing `Library/Containers/com.docker.docker/Data` allows docker to start.

**Comment by hatembr** [comment]
Thanks, I will give it a try.

**Comment by ddacunha** [comment]
I think the proper way to do this is 
```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
docker volume rm $(docker volume ls |awk '{print $2}')
rm -rf ~/Library/Containers/com.docker.docker/Data/*
```
(from https://github.com/docker/for-mac/issues/371)

**Comment by ddacunha** [comment]
@hatembr this will reset your docker installation and you'll have to re-download all images and create built dockers again.

**Comment by hatembr** [comment]
@ddacunha that worked, and like you said I'll have to rebuild all my images but that's fine.
thanks

**Comment by yallop** [comment]
I'm glad to hear that you've found a workaround for the problem.  A little more detail, in case you're interested:

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

The issue docker/for-mac#1159 has more information.

**Comment by steve-federowicz** [comment]
Maybe a button in preferences to wipe the qcow2? Something like "Delete all current images and containers."?  

I actually did click the bomb logo reset for factory default but that did not delete the qcow2 and I still needed to remove it manually.
