### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 1(  docker failed on the Mac after upgrading )

### ISSUE THREAD

**Issue by JuanLUJoanne** [docker/for-mac#1198]
com.docker.osx.hyperkit.linux failed to start
Exit code 1

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C68)
logs: /tmp/6A7535AF-BB98-400D-80BF-7772418EDF26/20170124-142548.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/juanlu/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/juanlu/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/juanlu/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/juanlu/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/juanlu/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/juanlu/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by JuanLUJoanne** [comment]
version: Version 1.13.0 (15072)
Channel: Stable
0c6d765c54

**Comment by yallop** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

**Comment by JuanLUJoanne** [comment]
thank you. working for me now

**Comment by jakecollins** [comment]
This worked for me also.

**Comment by prasadmahendra** [comment]
Just ran in to this problem on my mac and your soln worked! Thanks @yallop

**Comment by muyiwaolu** [comment]
For those of you trying @yallop's recommendation — uninstalling and re-installing docker didn't work for me, but removing the file did. Most likely my method of uninstalling (`brew cask uninstall docker`) didn't remove the file, however removing the file manually did the trick.
