### ISSUE TITLE
Latest update broke Docker

### ISSUE THREAD

**Issue by mfeblowitz** [docker/for-mac#1205]
### Expected behavior
Startup without error
### Actual behavior
- [Fatal Error: com.docker.osx.hyperkit.linux failed to start ] 
- Diagnose and Report (did so)
- complaints on Diagnose showed error starting at DB.
### Information
reinstall did not work

had to ``rm -fr ~/Library/Containers/com.docker.docker/Data/* `` to get it to start

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. accept offer to install latest update
  2. see Docker crash and burn

**Comment by jaxley** [comment]
Ditto

**Comment by yallop** [comment]
Thanks for the report. 

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  In some cases the existing `Docker.qcow2` file may have some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

The issue docker/for-mac#1159 has more information.

I'm sorry for the inconvenience this has caused.

**Comment by jaxley** [comment]
Would be great if the code could recover on its own.  If the solution is to just delete that corrupted file, why wouldn't the app just do that itself so it can start up successfully?

BTW, I believe my Reset to Defaults ended up clearing this file, although I really couldn't easily get to that option because the dialog to diagnose the failure doesn't give you the option to leave the app open (forces you to exit).  I had to race that dialog when starting it to click on the Reset option.
