### ISSUE TITLE
Docker failed to restart after update

### ISSUE THREAD

**Issue by swthomas55** [docker/for-mac#1208]
### Expected behavior
Expected Docker to start.

### Actual behavior
Docker fails with an error

com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Diagnostic ID: DEEE0903-D430-491D-A494-8FF3C0F91118

### Steps to reproduce the behavior

  1. Try to run Docker.

**Comment by swthomas55** [comment]
After restarting Mac OS, same problem appears.

**Comment by swthomas55** [comment]
Reinstalled from stable download and it is ok now.

**Comment by alias1** [comment]
I'm also unable to start docker since getting the latest upgrade.

```
C39C90BD-7968-40A5-8697-61123CEDBE54
```
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.1 (build: 16B2659)
logs: /tmp/C39C90BD-7968-40A5-8697-61123CEDBE54/20170125-102522.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk
```

**Comment by yallop** [comment]
@swthomas55: recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file had some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

I'm glad to hear that reinstalling has fixed the problem for you, and apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

@alias1: the problem you're seeing appears to be unrelated.  Could you please open a new issue if the workarounds suggested in #1159 (reinstalling or deleting the qcow2 file and restarting) don't fix things for you?
