### ISSUE TITLE
Failure to start Docker on MAC

### ISSUE THREAD

**Issue by mcherfaoui** [docker/for-mac#1216]
### Expected behavior

Start Docker

### Actual behavior

Docker fails to start with following message box: 

Fatal Error

com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
Thanks for the report.  Without a diagnostic ID there's nothing we can do to investigate further.  But the problem you're seeing may be due to new integrity checks on a corrupt `Docker.qcow2` file.  If that's the case then the workaround suggested in #1159 may fix things: https://github.com/docker/for-mac/issues/1159#issuecomment-273899215

**Comment by mcherfaoui** [comment]
Thanks, the w/around helped!
Regards,
Mourad.
