### ISSUE TITLE
794B1815-9102-4764-AB0A-787586FCBBF6

### ISSUE THREAD

**Issue by saidatom** [docker/for-mac#1229]
[ERROR]  driver.amd64-linux
[ERROR]  moby
[ERROR]  db
[ERROR]  virtualization kern.hv_support
[ERROR]  slirp
[ERROR]  osxfs
[ERROR]  docker-cli
[ERROR]  disk

**Comment by yallop** [comment]
The problem appears to be due to corruption of the `qcow2` file.

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

Please reopen the issue if the above doesn't solve your problem.
