### ISSUE TITLE
Docker wont start

### ISSUE THREAD

**Issue by ifeatu** [docker/for-mac#1231]
### Expected behavior
Docker starts
### Actual behavior

Docker fails to start

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

73B23DDA-1F27-4826-B269-6C3B61ED3668
  - A reproducible case if this is a bug, Dockerfiles FTW

Updated to Sierra 10.12.3 and updated Docker client after which it will not start
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Updated to Sierra 10.12.3 
  2. updated Docker client

**Comment by yallop** [comment]
Thanks for the report, @ifeatu.

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.
