### ISSUE TITLE
Docker not running after I updated to new version

### ISSUE THREAD

**Issue by gdabli** [docker/for-mac#1235]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
Thanks for the report, @gdabli.  Without a diagnostic ID there's nothing we can do to investigate further.  But the problem you're seeing may be due to new integrity checks on a corrupt `Docker.qcow2` file.  If that's the case then the workaround suggested in #1159 may fix things: https://github.com/docker/for-mac/issues/1159#issuecomment-273899215
