### ISSUE TITLE
Failing to start after upgrade to 1.13

### ISSUE THREAD

**Issue by tedyoung** [docker/for-mac#1237]
### Expected behavior

It should start.

### Actual behavior

    com.docker.osx.hyperkit.linux failed to start
    Exit code 1

### Information

Diagnostic ID: CFA30D4B-01C3-4D1F-96FB-6BDA0A37F078

```
Docker for Mac: version: 1.13.0-beta39 (5e9e408b0)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/CFA30D4B-01C3-4D1F-96FB-6BDA0A37F078/20170127-161839.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/tedyoung/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/tedyoung/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/tedyoung/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/tedyoung/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/tedyoung/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/tedyoung/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by yallop** [comment]
Thanks for the report, @tedyoung.

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

**Comment by tedyoung** [comment]
Thanks for the quick response, @yallop -- it'd be great if the error message provided that information, or even somewhere in the diagnostic output. I can file an issue, if there isn't one already.

**Comment by yallop** [comment]
Yes, the error reporting could certainly be a good deal better here.

We have an internal issue tracking error reporting improvements.  But an issue in this repository relating to reporting of this particular error could be a useful way for people to find out when the problem's fixed, so please feel free to submit one.
