### ISSUE TITLE
Personal Firewall on Mac OS X 10.11 makes build stuck with Alpine Linux 3.3 based container

### ISSUE THREAD

**Issue by ovanes** [docker/for-mac#124]
### Expected behavior

Docker build can download and install all packages required during the Alpine Linux build process.
### Actual behavior

The build hangs after dialog appears if a process is allowed to contact a remote server. Usually it hangs when `curl` is run to download sources.
### Information

Diagnostic ID: 459FCE3D-998C-4790-AC46-4B662F395D4F
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Install Little Snitch for Mac OS X
2. Run `docker build` and try to install these package when Little Snitch is active:

``` Dockerfile
FROM smebberson/alpine-base:2.0.0

# grab gosu for easy step-down from root
ENV GOSU_VERSION 1.7

RUN set -x \
        && apk add --no-cache \
                libgcc \
                libstdc++ \
                openssl \
                curl \ 
                git

RUN set -x \
    && apk add --no-cache --virtual .gosu-deps \
        dpkg \
        gnupg \
    && curl -L -o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
    && curl -L -o /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true \
    && apk del .gosu-deps
```

If Little Snitch asks for permission for the process to connect to a requested server and the permission is given, build process will hang indefinitely.

**Comment by dave-tucker** [comment]
Thanks for the report @ovanes 
I'm unable to reproduce this using the steps provided using Docker for Mac Beta 26 and Little Snitch Version 3.7.

Can you confirm if this is still an issue?

**Comment by ovanes** [comment]
@dave-tucker: I have the latest beta installed and LittleSnitch asked me several times (for different packages) for permission to connect to the internet. It worked just fine after the approval. I had tested it with: 1.12.1-beta26 (build: 12048) and 1.12.1-beta26.1 (build: 12100). With 1.12.1-beta26.1 (build: 12100) I was able to reproduce it once in 20 builds (with/without --no-cache parameter).

**Comment by ijc25** [comment]
@ovanes, thanks you for the additional information. sorry that nobody got back to you at the time.

Are you still able to reproduce this with the latest beta? There have been many improvements to networking stuff between beta26.1 and the latest beta (beta30 at time of writing).

If you can still repro then a new diagnostics upload would be appreciated since we have also improved the information collected a lot since beta26.1.

I've looked through the current logs and don't see anything network related. If you could give a time range when you were able to reproduce right before the new upload then that would help narrow down to the relevant logs.

Have you also reported this issue to the little snitch developers? It seems like their intention is to be completely transparent to the applications (when not denying a request of course) and if this is not holding for docker for mac then the problem here could just as easily be a little snitch issue.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
