### ISSUE TITLE
Docker won't run on mac

### ISSUE THREAD

**Issue by trips2821** [docker/for-mac#1258]
Docker doesn't start.  Here's the diagnostic info:

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/7ACAFE06-FA86-4617-A2E9-4B91BBF95CC1/20170203-143636.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mattjohnson/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mattjohnson/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mattjohnson/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mattjohnson/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mattjohnson/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mattjohnson/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by NumerousHats** [comment]
Just got the same problem after update install. Not sure if this is a true bug, or if the state of the app was somehow left in disarray. At this point, I can't even reset defaults, and I'm even having trouble doing a clean uninstall.

**Comment by NumerousHats** [comment]
There is this: https://github.com/docker/for-mac/issues/1190, but the suggested solution didn't work for me. What is a good way to do a truly clean uninstall? I don't care about preserving old containers...

**Comment by NumerousHats** [comment]
I also tried this: https://github.com/docker/for-mac/issues/899. Still no joy.

**Comment by JMDidon** [comment]
Seems that the 1.13.0 doesn't even launch... You might have to re-install the previous version you had. See #1259

**Comment by ijc25** [comment]
@trips2821 thanks for your report. I see evidence of two separate issues in your diagnostics.

Firstly your `qcow2` backing file appears to have become corrupt. Starting with 1.13.0 we began performing some consistency checks on the `qcow2` file at start of day in an effort to identify corruption closer to the time it occurs rather than letting it fester for an unknown period if time. Unfortunately this means that any historical but latent corruption will be treated as fatal (the trade off is that we should be much better able to diagnose any future corruption). I'm afraid that the solution to this is "Whale menu -> Uninstall and reset -> Reset to factory defaults". Unfortunately this removes containers and images so they will need to be rebuilt :(. Sorry for this.

The second issue I see is:
```
<Error>: com.docker.driver.amd64-linux(783,0x70000bcb6000) malloc: *** error for object 0x4d205b8: incorrect checksum for freed object - object was probably modified after being freed.
	*** set a breakpoint in malloc_error_break to debug
```
which is a subtle memory corruption bug which we've been unable to track down. If you are still able to reproduce this issue having done the factory reset to solve the first issue then I would be very grateful indeed if you could try the debugging described in https://github.com/docker/for-mac/issues/1143#issuecomment-272923920 and report back.

Everyone else (@NumerousHats & perhaps @JMDidon) please file separate issues with your own diagnostics (`Whale Menu` -> `Diagnose and Feedback...` will guide you) so we can investigate your particular circumstances, which may differ from the above -- the symptom "does not start" can have a variety of causes.

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
