### ISSUE TITLE
docker crashed during starting up after upgrade the last version

### ISSUE THREAD

**Issue by zephyrluo** [docker/for-mac#1259]
### Expected behavior
Start up normally.

### Actual behavior
Throw exception during starting.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1.  update the newest docker version through app's update notification. 
 2. reboot machine
 3. docker icon was appeared in system status bar
 4. crashed
 5. Diagnostic log:
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1004)
logs: /tmp/E0628413-0C5F-4F5D-9F83-56ED29A5E513/20170204-133252.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/luozhifan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/luozhifan/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/luozhifan/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/luozhifan/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/luozhifan/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/luozhifan/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by ddunbar** [comment]
Hitting this same issue.

Diagnostic-ID: 052445AB-C722-4F80-B655-63407DB4B05F

**Comment by jesperronn** [comment]
Same here for me 6726ED04-B86B-4AD5-90A7-7C0BD59E8CD2

Any known workarounds?

**Comment by JMDidon** [comment]
I had the same problem. What I ended up doing was restoring the old version of Docker back.

The past versions are not even available on the website... So you have to do it manually. When Docker for Mac updates, it just delete the old app and install the new one. You just have to delete the one you have on the application folder, and put back the previous one from the trash.

**Comment by ijc25** [comment]
@zephyrluo, @ddunbar, @jesperronn  In each case your qcow2 backing file appears to have become corrupt. Starting with 1.13.0 we began performing some consistency checks on the qcow2 file at start of day in an effort to identify corruption closer to the time it occurs rather than letting it fester for an unknown period if time. Unfortunately this means that any historical but latent corruption will be treated as fatal (the trade off is that we should be much better able to diagnose any future corruption). I'm afraid that the solution to this is "Whale menu -> Uninstall and reset -> Reset to factory defaults". Unfortunately this removes containers and images so they will need to be rebuilt :(. Sorry for this.

@JMDidon see my comment to you at the end of https://github.com/docker/for-mac/issues/1258#issuecomment-281063629, without I diagnostic ID we can do very little to diagnose your specific circumstance so please file your own issue if you continue to have problems.
