### ISSUE TITLE
Docker for Mac cannot start: “docker ps failed”

### ISSUE THREAD

**Issue by leonfl** [docker/for-mac#1263]
### Expected behavior
Start as expected.
### Actual behavior
Always on starting, cannot started.
Run Diagnose: show that [ERROR] docker-cli, detail as below
- Docker for Mac: version: 1.13.0 (0c6d765c5)
- macOS: version 10.12.1 (build: 16B2659)
### Information

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.1 (build: 16B2659)
logs: /tmp/55C5EA4D-6164-47D3-AA87-B0636ABC428D/20170206-162500.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
**[ERROR]  docker-cli**
         **docker ps failed**
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start Mac
  2. Start Docker

**Comment by ijc25** [comment]
@leonfl, thanks for your report. Unfortunately 55C5EA4D-6164-47D3-AA87-B0636ABC428D is not found on our servers.

Could you please run Diagnose & Feedback again from the :whale: menu, select Diagnose & Upload, and paste the results of the diagnostic run (including diagnostic ID) back here? This will help us understand what is happening with the Docker application. Thanks!

I see that you are located in China so you may need to activate your VPN in order to upload to our s3 bucket.

**Comment by leonfl** [comment]
@ijc25 , Thanks for your help, last time I just run "DIagnose only".

I have run Diagnose & Feedback again, this is the result(almost same as before):

> Diagnostic ID: 
> 55C5EA4D-6164-47D3-AA87-B0636ABC428D

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.1 (build: 16B2659)
logs: /tmp/55C5EA4D-6164-47D3-AA87-B0636ABC428D/20170222-160923.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
**[ERROR]  docker-cli
         docker ps failed**
[OK]     menubar

---------------
Tell me if anything need.
Thank you

**Comment by ijc25** [comment]
@leonfl thanks, your new diagnostic made it through.

Looking at your logs I see that your `docker.log` ends with several dockerd panics like this one:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x41 pc=0x557e60]

goroutine 1 [running]:
panic(0x1b394c0, 0xc8200100e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/daemon.(*Daemon).Register(0xc8204901a0, 0xc82048e1e0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:91 +0x40
github.com/docker/docker/daemon.(*Daemon).restore(0xc8204901a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:155 +0x1670
github.com/docker/docker/daemon.NewDaemon(0xc820422a80, 0x7f17cc36d1c8, 0xc82014c5a8, 0x7f17cc51f250, 0xc8203fd790, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:605 +0x34aa
main.(*DaemonCli).start(0xc820416f30, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:265 +0x1951
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491
```

I'd advise to first upgrade to the docker 1.13.1 release but if this issue then persists to file a bug against the engine at https://github.com/docker/docker.

I'll close this issue now since it does not appear to be docker/for-mac specific.

**Comment by leonfl** [comment]
@ijc25 , Thanks for your help.

I just upgrade to docker 1.13.1, and the issue still exist and same as before, and diagnostic result are all same as before, the ID also same as before.

You sure it's the docker engine problem? Maybe I need file a new issue for docker engine.

**Comment by ijc25** [comment]
Yes, a dockerd panic is surely a docker engine problem. Please file a new issue against https://github.com/docker/docker.

**Comment by leonfl** [comment]
@ijc25 , Thanks for your help, I'll file a new issue against engine soon.
