### ISSUE TITLE
docker-compose timed out when running up with new container

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1265]
### Expected behavior
docker-compose will restart the process with the new container

### Actual behavior
docker-compose times out and then docker is unresponsive

### Information
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C68)
logs: /tmp/960549A5-E20C-4E41-B51B-FA16000C14C6/20170206-172219.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Not sure what causes it. It just happens every once in a while.

**Comment by daveisfera** [comment]
Froze up a again:
960549A5-E20C-4E41-B51B-FA16000C14C6

**Comment by daveisfera** [comment]
This time couldn't start any new containers or restart already running ones:
960549A5-E20C-4E41-B51B-FA16000C14C6

**Comment by ijc25** [comment]
Hi @daveisfera thanks for your report.

Your logs show the symptoms of an issue (the "forget-not-found" issue) which we have an internal ticket for (and which was also seen in #864, #915 and a few others) resulting in these sorts of log messages:
```
[com.docker.osxfs][24226] <Warning>: forget not found for node 34290
[com.docker.osxfs][24226] <Warning>: forget not found for node 34289
[com.docker.osxfs][24226] <Warning>: forget not found for node 34288
[com.docker.osxfs][24226] <Warning>: forget not found for node 34278
[com.docker.osxfs][24226] <Warning>: forget not found for node 34287
[com.docker.osxfs][24226] <Warning>: forget not found for node 34284
```

Unfortunately this issue is very elusive and we have not been able to reproduce. Any information which you can provide around your workloads and the circumstances under which the issue occurs would be invaluable since we've so far been unable to make any progress on tracking it down without a reproducer.

For completeness I should say that your logs also show symptoms of another issue (the "state-not-recoverable" issue) which is believed to be low impact (and therefore not the cause of the symptoms you are seeing). This one is responsible for this sort of log message:
```
[com.docker.osxfs][2349] <Warning>: dropped event syscall unlink for «some path» (bad lookup path)
[com.docker.osxfs][2349] <Warning>: dropped event syscall unlink for «some path» (bad lookup path)
[com.docker.osxfs][2349] <Error>: transfused: Event unlink «some path» error: State not recoverable
[com.docker.osxfs][2349] <Warning>: dropped event syscall unlink for «some path» (bad lookup path)
[com.docker.osxfs][2349] <Error>: transfused: Event unlink «some path» error: State not recoverable
[com.docker.osxfs][2349] <Warning>: dropped event syscall unlink for «some path» (bad lookup path)
```

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
