### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by shuntera** [docker/for-mac#1266]
### Expected behavior
No error on reboot
### Actual behavior
Docker crash on restart of mac every time
### Information
Diagnostic ID: E933CE15-B547-48E5-8B91-FA6B1B747EC2
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...Reboot MacBook Pro
  2. ...

**Comment by yallop** [comment]
Thanks for the report, @shuntera.

Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either

    uninstall/reinstall or
    rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 and restart the app.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.
