### ISSUE TITLE
Diagnostic failing on logs phase

### ISSUE THREAD

**Issue by nwillc** [docker/for-mac#1268]
### Expected behavior

Diagnostic & Feedback should pass.

### Actual behavior

Diagnostic & Feedback fails on log phase (see below).

#### Output
```
  Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.4 (build: 16E144f)
logs: /tmp/E0BF3F84-9FB3-4BEB-A978-86004C1A8B2D/20170207-203241.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --style syslog --last 4d | grep -i docker > \"/tmp/E0BF3F84-9FB3-4BEB-A978-86004C1A8B2D/20170207-203241/docker-system-os.log\": exit 1")
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

#### Other notes
Manually running the command shown yields very little:

```
/usr/bin/log show --style syslog --last 4d
Skipping info and debug messages, pass --info and/or --debug to include.
Timestamp                       (process)[PID]
```

But syslog is full of docker messages:

```
[~]$ syslog -k Sender Docker | tail -10
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
Feb  7 20:27:52 lipstick Docker[14944] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Feb  7 20:27:56 lipstick Docker[14944] <Notice>: Docker is responding
Feb  7 20:27:56 lipstick Docker[14943] <Notice>: VM started at 2017-02-07 20:27:56 -0500 EST
Feb  7 20:28:37 lipstick Docker[14942] <Notice>: Using protocol TwoThousandU msize 8215
--- last message repeated 1 time ---
Feb  7 20:29:35 lipstick Docker[14942] <Notice>: 127.0.0.1:0: dispatcher shutting down: read: Eof
Feb  7 20:30:44 lipstick Docker[14942] <Notice>: Using protocol TwoThousandU msize 8215
Feb  7 20:31:30 lipstick Docker[14942] <Notice>: 127.0.0.1:0: dispatcher shutting down: read: Eof
Feb  7 20:32:42 lipstick Docker[14942] <Notice>: Using protocol TwoThousandU msize 8215
Feb  7 20:33:27 lipstick Docker[14942] <Notice>: 127.0.0.1:0: dispatcher shutting down: read: Eof
```
But note that first line!  Looks like Apple changed how it's doing logs....

I'm running 10.12.4 Beta (16E144f)

### Steps to reproduce the behavior
Run Diagnostic & Feedback

**Comment by ijc25** [comment]
Thanks for your report @nwillc.

Apple did indeed begin transitioning to a new logging scheme in MacOS 10.12, although both versions remain somewhat functional in this version. At the moment docker for mac is a slightly weird hybrid where the backend still uses the old style logging while the frontend (UI) stuff is redirected to the new scheme (actually, via some magic in the Swift runtime rather than any explicit code on our end).

In existing 10.12.x GA releases this works just fine, but it seems like maybe something has gone awry in 10.12.4 beta.

The fact that you seem to see no logs at all (I'm assuming you didn't manually filter a load of non-Docker logging out of the examples you gave) makes me suspect this is a general Apple/MacOS 10.12.4 beta issue/brokenness rather than something wrong with how Docker 4 Mac is approaching logging.

Please could you try `/usr/bin/log show --style syslog` (i.e. without the `--last 4d` option) and let me know what you see. Could you also try `/usr/bin/log show --style syslog --debug` to get the full logging. For now I'm going to assume this is a 10.12.4 beta issue, but please let me know if those two commands produce any output at all (about Docker or otherwise) -- if they do I will escalate internally to check everything is OK on our end.

Thanks again for your report.

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
