### ISSUE TITLE
Consistent Docker for Mac crash

### ISSUE THREAD

**Issue by sersut** [docker/for-mac#1272]
### Expected behavior

I am running 7 containers, 4 of them with heavy network and CPU load and consistently the docker daemon crashes after some time. I have read a few similar issues, the closest being https://github.com/docker/for-mac/issues/1020, resetted, reinstalled, moved to beta version, but nothing worked.

Looking at the log files I consistently see a DNS refresh or config change event right before the crash but I was not able to root cause the issue to it.

Since my setup is a bit complicated, 2 set of services via 2 docker-compose files, let me know the type of more information needed and I'll provide. Thanks for looking at this.

### Actual behavior

NO crash. 

### Information

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/AE55669E-FF2C-45B6-B906-3B7558BED258/20170208-150229.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
@sersut thank you for your report. I see evidence of a few different failure modes here.

Firstly I see hypervisor crashes like #1170 (triple fault) and #1176 (EPT fault) with #1170 being more prevalent. I'd recommend subscribing to both of those issues for further updates.

Secondly I see the "forget-not-found" issue I talked about in https://github.com/docker/for-mac/issues/1265#issuecomment-281093186. As I say there this issue is very elusive and we have not been able to reproduce. Any information which you can provide around your workloads and the circumstances under which the issue occurs would be invaluable since we've so far been unable to make any progress on tracking it down without a reproducer.

I _think_ it is likely that the DNS updates are unrelated/harmless to any of those.

As it stands we have good repro cases for the hypervisor crashes (although the bad news is we fear it may be a MacOS kernel bug...). But if you can give any clues as to what workloads might be causing the "forget-not-found" in particular we would be very grateful.

**Comment by sersut** [comment]
Potentially this might be related to a memory problem.

When hitting this issue I was running 7 containers, 4 of which were postgresql on a 16 GB machine. We were configuring the [shared_buffers](https://www.postgresql.org/docs/9.6/static/runtime-config-resource.html) setting of postgres to be 25% of the memory seen by the container. But due to the behavior of [ohai](https://github.com/chef/ohai) (our tool to find out the memory of the system) we were seeing the full available memory as 16GB (the total of my laptop) to each container instead of the configured 4GB. So each postgres instance was trying to map 4GB of memory when they come up and failing to do so which was eventually leading to a crash. 

I have not seen this issue after setting 512MB in the postgres configuration (granted I have not been running these test containers as frequently since then) :D Hope this helps...

**Comment by ijc25** [comment]
Thanks for the additional info my feeling is that #1170/#1176/#1170 are all related to the MacOS kernel's handling of swapping of memory used by Hypervisor.framework vms, so heavy memory pressure (especially if you give the VM all of your host memory with no overhead) could well be a factor.

I think this is probably unrelated to the "forget-not-found" issue, although the fact that you are running postgres might be interesting, I shall relay this to our fs devs. Any info about your postgres configuration would be useful, are you using `postgres:latest` or something else? Are you tweaking it from the defaults?

**Comment by sersut** [comment]
Agree on your thinking, hence I removed the DNS updates part from the title 😄 

This is a custom installation of postgres with some other $things that we use for our smoke testing. I think the relevant configuration we do are: 

```
max_connections = 350
shared_buffers = "#{(node['memory']['total'].to_i / 4) / (1024)}MB"
work_mem = 8MB
```

postgres backing store is not on a shared volume but we share bunch of other directories that contains the configuration files for various things.

**Comment by sersut** [comment]
FWIW when we run the same test on ubuntu, we don't get a daemon crash. Instead we are unable to start postgres (service not the container) most of the time.

**Comment by ijc25** [comment]
Thanks, I've passed that info on to the filesystem guys.

**Comment by ijc25** [comment]
We are consolidating the `forget-not-found` issue into ticket https://github.com/docker/for-mac/issues/1265 to track it in a single place please subscribe there for further updates.
