### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by Hugh472** [docker/for-mac#1301]
### Information

  Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/1A5155C1-4271-433D-B76E-93AC4038DB59/20170214-112121.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Kyle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/Kyle/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Kyle/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/Kyle/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/Kyle/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Kyle/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

**Comment by ijc25** [comment]
In hindsight I think I was too quick to put this down to preexisting corruption detected by our new checks, this does appear to be a new one. I have now escalated it internally and have designated https://github.com/docker/for-mac/issues/1315 as the public tracking issue. Please subscribe to #1315 for further updates.

**Comment by Hugh472** [comment]
Ian,

    Thank you for double-checking.  I personally just uninstalled and reinstalled Docker, and everything was fine, but just in case it was an actual bug I wanted to make sure someone knew about it.  Thank you for letting me know.

Best,
Kyle
