### ISSUE TITLE
Software Update Fatal Error: com.docker.osx.hyperkit.linux failed to start. Exit code 1

### ISSUE THREAD

**Issue by melostbr** [docker/for-mac#1306]
### Expected behavior
Install Update Successfully
### Actual behavior
Fatal Error 
### Information
Trying to install following upgrades:
  Docker 1.13.1
  Docker Compose 1.11.1
  Linux kernel 4.9.8

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/63A3E493-242A-4E11-B8CB-C3F6E978E88B/20170215-082415.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/melost/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/melost/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/melost/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/melost/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/melost/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/melost/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Click on "Install update" in Docker Software Update box (15353).
  2. Receive "Fatal Error: com.docker.osx.hyperkit.linux failed to start. Exit code 1"

**Comment by opichon** [comment]
I cannot even run the diagnostic. Docker 1.13.1 is completely broken on my macbook Pro..

**Comment by ijc25** [comment]
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

@opichon if the above doesn't also apply to you then you can also run a diagnostic from a terminal with:
`/Users/ijc/Library/Group\ Containers/group.com.docker/bin/docker-diagnose -u`. After doing that please open an issue with the output from that command and the other information requested in the issue template.
