### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by jmlagace** [docker/for-mac#1307]
### Expected behavior

Docker Starting

### Actual behavior

Docker is not starting (looks like it is stuck in a loop)

### Information

Docker for Mac: version: 1.13.1-beta42 (2ffb2b491)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/5F87F7B6-7A83-4CAF-9CDC-9D03C7E66615/20170215-092409.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start Docker
  2. Wait

**Comment by lewisporter** [comment]
I am also getting this issue. 

`Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/444B5429-D6D6-46A3-B95A-452511C14AE7/20170215-160024.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk
`

ID: 444B5429-D6D6-46A3-B95A-452511C14AE7

**Comment by austinpray** [comment]
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/21F6F5A7-3EB4-4D32-88C2-B45E7BC04CC4/20170215-143612.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/austinpray/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/austinpray/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/austinpray/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

ID: 21F6F5A7-3EB4-4D32-88C2-B45E7BC04CC4

**Comment by ijc25** [comment]
@jmlagace thank you for your report. I can see in your VM console log that for some reason the docker engine has failed to start. Digging into your docker ending logs I see:

```
Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/_[...]_/config.json: open [...]/config.json: no such file or directory
```
I see you were previously running 1.13.0-rc4-beta34.1 and have recently upgraded to 1.13.1-beta42. Unfortunately I believe there were some changes to the plugin infrastructure between 1.12/1.13-rc (where is was experimental) and the final 1.13 release which necessitate removing any plugins you might have installed. To achieve this with docker for mac I'm afraid you will need to perform a factory reset which unfortunately means that containers and images will need to be rebuilt.  I apologise for the inconvenience.

I'm going to close this bug for now on the assumption that the above is a correct diagnosis but if things still do not work after a factory reset then please do reopen with a fresh diagnostic taken from the newly reset system.

If the initial reset works OK but the problem reoccurs after reinstalling your plugins then please ensure they are compatible with Docker 1.13 and let us know what plugins you are using.

@lewisporter in general please file issues of your own rather than adding a "me too" to a potentially unrelated issue (the symptom of "doesn't start" can have many causes). I can't tell from your logs what has gone wrong (other than it is not the same as @jmlagace's issue), your VM console logs show lots of `BUG: soft lockup - CPU#0 stuck for 22s!` but because of this we seem to have not collected any diagnostics from within the VM meaning there is not much to go on. There is also some indication that your qcow image has become corrupted, which may or may not be related to the soft lockup. That being the case all I can suggest is to do a factory reset, which I'm afraid will delete your containers and require them to be rebuilt, sorry. If this issue persists after the factory reset then please open a fresh ticket with a new diagnostic from the reset system describing your particular scenario.

**Comment by jmlagace** [comment]
@ijc25 I did not have any plugins installed. 

The only quirk I have in my environment is that my source code is stored on an SDCard and the volumes are linking to the location of the SDCard. Although I'm pointing this out I have upgraded with that setup before without any issues. 

Closing the issue might be the only resolution since I reinstalled the stable version as I needed to start working and deliver a project rapidly (the only reason I was still on the beta branch is because I installed Docker for Mac early on when the beta branch was the only thing available).

Thanks
