### ISSUE TITLE
Docker.qcow2 moved to external drive that crashed the docker-engine and corrupted the file. 

### ISSUE THREAD

**Issue by n1tr0** [docker/for-mac#1330]
### Expected behavior

The docker engine was supposed to copy over the Docker.qcow2 to the location selected from Advanced settings.

### Actual behavior

Not all of the Docker.qcow2 was copied over and then the docker engine restarted and without creating a link to the file needed.  It was restarted and hung-up in the restart process looking for the Docker.qcow2 in the previous location.

I need my Docker engine to work now and the disk space reclaimed since I was moving 180 Gigs of data and only ended up with 75 Gigs of data when it moved the Docker.qcow2 file.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW, **AGREED!**
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Go the upper right hand corner and click the docker whale, to then bring up the docker menu.
  2. Select the Advanced (gear) menu, then in the advanced menu you can change your location for where the files are stored, files being the Docker.qcow2
  3. Wait and see if it crashes once you select to store the large bundle off to an external drive.

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/3EE01DE3-0367-4823-92F5-5E4CAE9C2FAE/20170223-100403.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/n1tr0/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/n1tr0/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/n1tr0/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/n1tr0/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/n1tr0/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/n1tr0/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by ijc25** [comment]
@n1tr0 I'm very sorry for this. I'm going to escalate this to an internal ticket immediately.

Can you confirm that a) the file in the new/destination location is only partially complete and that b) the file in the old/source location was deleted even though the copy/move failed?

Can you also confirm that there was sufficient space on the target drive? (Clearly the error handling is broken either way, but it would be useful to know if the error was expected and could have been avoided by some pre-move checks)

Was there any error dialog or message before the crash?

Your logs show that docker is using the partial copy on the external drive, it's complaining abut #1315 but clearly in your case the cause is different.

If the file is still present in the old location you may be able to manually move it to the new location. If the file is no longer in the old location then I'm afraid the only course of action I can suggest is to remove the file from the new location, this will unfortunately require your containers and images to be rebuilt.

Sorry once again for this.

**Comment by n1tr0** [comment]
Yes to a, while using the advanced menu to select the new location it seemed to use mv rather then cp and check the integrity of the file before rebooting.  

Yes, to the disk space.  There was plenty of the room on the target drive.  

No, to a display before the docker engine crashed while rebooting.  The only display was after the engine was hung and would not let you alter the docker settings.

Do you suggest removing the Docker.qcow2 on the external drive and restart the docker-engine?  Since its not a complete image I don't see how thats an issue to test out, and looks positive.

Thanks

**Comment by ijc25** [comment]
Thank you for the additional information.

> Do you suggest removing the Docker.qcow2 on the external drive and restart the docker-engine?

Assuming the original/old file is gone then yes, this is your best bet to be able to use Docker again. Sorry. 

If you remove the file rather than doing the factory reset then it should create you a new one at the new location. If you were to factory reset it would also reset the storage location and you'd need to change it back (although at least the file would be small this time).

**Comment by n1tr0** [comment]
My issue is solved but I think there is a greater issue in moving the storage location and how it is handled.  I how this helped to to track this down.

Thanks for the information on getting the docker-engine restarted.  For some additional information the docker-engine started and the storage location was now on the external drive.
