### ISSUE TITLE
Update to Version 17.03.0-ce-mac1 deletes insecure registries

### ISSUE THREAD

**Issue by leenamba** [docker/for-mac#1369]
### Expected behavior
Updating should keep existing insecure registries.

### Actual behavior
Updating deletes existing insecure registries.

### Information
Docker for Mac: version: 17.03.0-ce-mac1 (05a8abd30)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/73BF6C8A-AF5B-425B-A2B4-11193F06B012/20170302-181643.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install docker for mac 1.13
  2. add an insecure registry
  3. upgrade to docker for mac 17.03

**Comment by martinth** [comment]
This might be related: Version 17.03 seems to completely ignore anything that is configured in the `daemon.json`. I had a custom DNS server in there and after the update, it seemed to be ignored.

After adding the configuration thought the UI it worked again. The previous location for this file was `~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker/daemon.json`. 
Was the location changed? I tried searching my disk but I found no other copy. Or was the configuration storage changed and the file is simply no longer used and you _have_ to use the UI?

**Comment by MagnusS** [comment]
Thanks for the reports @leenamba and @martinth. I am also able to reproduce this when upgrading from 1.13.1 to 17.03.0-ce-mac2. I have created an internal ticket to track this issue.

@martinth The `daemon.json` location should be the same as before. The database files are kept in a git repository and `git reset --hard` should show the current version of the files. If you change `daemon.json` manually you have to commit the changes for it to be picked up by the database.

**Comment by MagnusS** [comment]
It looks like this may be caused by a database upgrade in the latest version, but we are still investigating. In the mean time you may be able to recover the original `daemon.json` from the database by locating the last commit before the upgrade:

1. `cd ~/Library/Containers/com.docker.docker/Data/database`
2. `git log --oneline --grep "Upgrade to schema version 10"` should show the sha1 and commit message of the commit that reset `daemon.json`
3. `git show COMMIT~1:com.docker.driver.amd64-linux/etc/docker/daemon.json` (replace `COMMIT` with sha1 from 2). This should show the contents of `daemon.json` as it was before it was cleared.

**Comment by thaJeztah** [comment]
@leenamba this still an issue?

**Comment by leenamba** [comment]
@thaJeztah I upgraded to 17.06 and it didn't seem to be an issue. I have not tested the 1.13 to 17.03 again though. Sorry.

**Comment by thaJeztah** [comment]
Great, thanks!
