### ISSUE TITLE
Docker Mac won't start

### ISSUE THREAD

**Issue by morefromalan** [docker/for-mac#1387]
### Expected behavior
Docker should start

### Actual behavior
Docker just stays in "starting..." state

### Information

Diagnostic-ID:
2966B4F1-83FA-4F15-ADCD-865CA5B0038F

### Steps to reproduce the behavior

1. Try to Start Docker for Mac using the UI

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/2966B4F1-83FA-4F15-ADCD-865CA5B0038F/20170305-211147.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/alanpeters/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/alanpeters/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/alanpeters/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/alanpeters/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/alanpeters/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by idris** [comment]
Seeimg the same thing.  Docker says it's started, but then when I try to do anything (like docker ps), it fails and tries to restart.  Happens on today's update as well (Version 17.03.0-ce-mac2 (15654))

**Comment by morefromalan** [comment]
Docker upgrade didn't help, but an OS Upgrade and then Docker Install got it stable again.  
The other data point is that the problem appeared after a hard system crash with Docker running (crash originated in display driver).

**Comment by MagnusS** [comment]
@morefromalan Thanks for the report. 

From the logs it looks like Docker for Mac crashed several times recently due to bugs in Apple's Hypervisor.framework in OS X 10.10. If you have upgraded to macOS 10.12 (or a newer version of 10.11) these issues should be fixed. 

Your VM disk image was also corrupted (perhaps due to the crash) which prevented Docker for Mac from starting. If you did a fresh install (with uninstall first) the disk image was recreated and these errors should be gone now.

So hopefully, with the OS upgrade, your Docker for Mac should be stable and working again!

@idris Please open a new issue with a diagnostics ID so we can take a look at your logs (Diagnose & Feedback from the menu). It may be a different issue.
