### ISSUE TITLE
Cannot add, remove, add overlapping directory

### ISSUE THREAD

**Issue by atombender** [docker/for-mac#139]
### Expected behavior

Should be able to remove a directory and then add a new directory that overlaps with the removed one.
### Actual behavior

Docker for Mac refuses to do this, complaining there's an overlap.
### Steps to reproduce the behavior
1. Under File Sharing tab, add `/Users/foo` (which overlaps with `/Users`, obviously).
2. Save and restart. App will refuse.
3. Remove `/Users`.
4. Save and restart. App will still refuse, even though there's no overlap anymore.

**Comment by dsheets** [comment]
It is a known issue for combining overlapping export directories (e.g. `/Users/foo` is exported and then, in a single step, it is removed and `/Users` is exported). I cannot reproduce the behavior you describe of increasing the specificity of the export. This case is explicitly handled.

Are you certain you experience the issue when making an export change in this direction?

The work-around for combining exports is to remove, apply, and then add the ancestor and apply.

**Comment by atombender** [comment]
Sorry, I got the steps revered: If `/Users/foo` is exported, then removing it and adding `/Users` in a single step will fail. I have to remove it, save, then add `/Users`, then save.

**Comment by acdha** [comment]
Beyond the scope of fixing this bug, it feels like this would be a good question for the install / first-run process: I was trying to restrict the scope of my sharing from anything in my home directory to be a specific `~/Projects`. It might be nice to prompt the user a bit on the implications of this change since it does appear to open the possibility of a container getting access to e.g. `~/.ssh` and other interesting files.

**Comment by dsheets** [comment]
@acdha that's a great idea and one we've thought about before. It would be great if you could open a new issue with the feature request and we can use to track and discuss it. Thanks for your feedback!
