### ISSUE TITLE
RAM&CPU setting changed automagically

### ISSUE THREAD

**Issue by bicpi** [docker/for-mac#1415]
### Expected behavior

My RAM and CPU settings should stay the same as long as I do not change them manually.

### Actual behavior

My fan started working heavily and I found the Docker settings window look like attached; I'm sure that CPU was set to 2 before and RAM something between 4-5GB.

I was also wondering why I was not able to set the RAM 5GB (button greyed out), now I think I know when checking the preferences: the button is greyed out on the current active setting. So then this might mean that it was still saved somewhere, the 5 GB setting, because I could not set it back to this value from the screenshot scenario.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnostic ID: C86C03C5-8637-4FB7-BB2B-C300768E5E81
  - A reproducible case if this is a bug, Dockerfiles FTW
Couldn't reproduce; did not happen again so far
  - Page URL if this is a docs issue or the name of a man page
n/a

![image](https://cloud.githubusercontent.com/assets/301163/23789872/f5351aaa-057c-11e7-891e-b414dfd30fd6.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by m-lautenbach** [comment]
In our company, that these setting reset with every software update.
Could that be the same issue?

**Comment by bicpi** [comment]
We also noticed once that e.g. the configured insecure registries were reset.

**Comment by m-lautenbach** [comment]
I don't know about these ones, but if it relates to the update is reproducible.
Which helps the dev with fixing it.

**Comment by djs55** [comment]
In the original report's diagnostics I can see the `com.docker.hyperkit` process running with arguments `-m 4864M -c 2` which sounds like it's expected.

Regarding settings changing over an update -- there was a bug in the most recent release which was subsequently hotfixed -- see https://github.com/docker/for-mac/issues/1354 . Furthermore I've created a PR with a more fine-grained configuration upgrade mechanism which should prevent such things happening in future.

*However* the screenshot showing the 1048576.0 GB is clearly wrong -- I'll escalate that to the UI team. My guess is that something went wrong when we switched from coarse-grained GB memory settings to find-grained MB memory settings. Perhaps the UI actually told the hyperkit process to use vast amounts of memory and the fan was caused by excessive swapping.

Thanks again for your report.

**Comment by Keysox** [comment]
I also just came across this same issue myself.

When I changed my settings back to what I had them at previously, the `Apply & Restart` button became in a disabled state. I believe that means it was just a UI issue and Docker was appropriately using the correct amount of CPUs/Memory. If I were to change either slider from there, the button gets enabled again.
