### ISSUE TITLE
Is it possible to set memory / cpu settings for docker for mac in flat files?

### ISSUE THREAD

**Issue by kortina** [docker/for-mac#1434]
### Expected behavior

I came across some files in:
` ls ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/`, namely `memory`, `memoryMiB`, `ncpu`, which look like they might be for locking in settings for memory and cpu usage. 

I expected to be able to change them, restart docker, and have docker use the settings found in these files.

### Actual behavior

Docker uses it's default settings, ignoring values in these files.

This is particularly annoying because when I update to a new version of Docker, my memory gets reset back down to 2GB from 8GB where I normally like it.

**Comment by kortina** [comment]
I played with this a bit more, and it looks like I had to do a few things in order to get Docker to pickup the changes and show them in the preferences gui.

1. `git add` and `commit` the any of the files edited `memory`, `memoryMiB`, `ncpu`
2. restart Docker (I did the following)

`ps aux | grep "/Applications/Docker.app " | awk '{print $2}' | xargs -I {} kill -9 {}; open -a /Applications/Docker.app`

Is there a better / recommended way to restart Docker to get it to pickup config changes than what I did in (2) ? I tried a `kill -HUP` but that did not work.

Is there a way to automatically do this after updating Docker for mac? (This resets to default memory / cpus every time.)

**Comment by djs55** [comment]
Thanks for your report.

There was a bug in a recent update which caused memory and cpu parameters to reset -- this was fixed in a hotfix-- see https://github.com/docker/for-mac/issues/1354 The general upgrade mechanism will be improved in a future release to prevent this happening again. Sorry for any inconvenience caused.

The configuration parameters are stored in the git repo, rather than the checked out copy as you've observed. It should be sufficient to `git add` and `git commit` the new values -- `Docker` is watching the `master` branch and when the values change it should either take the new configuration immediately (e.g. `dns` settings) or reboot the VM (`memoryMiB`, `ncpu`). Note this is an internal interface which changes from time to time.

In cases where an application restart is required, it is safe to `kill -TERM` the running `Docker` and then to run a new instance with `open /Applications/Docker.app`. The first instance will shutdown and release a lock, the second instance will block trying to acquire the lock and then finish starting up.

I hope this answers your questions -- thank you for using Docker for Mac!
