### ISSUE TITLE
741472B1-079E-4AC7-8C05-205D6EBF8D97

### ISSUE THREAD

**Issue by bajulto** [docker/for-mac#1436]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bajulto** [comment]
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.10.5 (build: 14F27)
logs: /tmp/741472B1-079E-4AC7-8C05-205D6EBF8D97/20170316-142057.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by djs55** [comment]
Thanks for your report.

I detected symptom of problem 'aufs-corruption' in 741472B1-079E-4AC7-8C05-205D6EBF8D97/20170316-142057.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The log in moby/var/log/docker.log matches:
```

time="2017-03-16T12:07:51.445340986Z" level=debug msg="Failed to load layer sha256:9fde5ba9cbafe26cc48eb4cd27ae005589ec9ec8d8adfcab527e3ce941ca380e: failed to get diff id for sha256:9fde5ba9cbafe26cc48eb4cd27ae005589ec9ec8d8adfcab527e3ce941ca380e: invalid checksum digest format" 
time="2017-03-16T12:07:51.450042174Z" level=debug msg="Failed to load layer sha256:bcdb57d0c14986ad57bcc6645d5c87005709bf500de3fd913dee6cf5ea6ab4e8: failed to get diff id for sha256:bcdb57d0c14986ad57bcc6645d5c87005709bf500de3fd913dee6cf5ea6ab4e8: invalid checksum digest format" 
time="2017-03-16T12:07:51.463909658Z" level=debug msg="Failed to load mount d627a98cb26a387917b308b84e26620d0ee829fccef07d17e180d7e7cc05636b: invalid mount id value" 
time="2017-03-16T12:07:51.465252886Z" level=debug msg="Max Concurrent Downloads: 3" 
time="2017-03-16T12:07:51.465559300Z" level=debug msg="Max Concurrent Uploads: 5" 
time="2017-03-16T12:07:51.652928424Z" level=debug msg="Cleaning up old mountid : start." 
time="2017-03-16T12:07:51.654413230Z" level=fatal msg="Error starting daemon: layer does not exist" 
time="2017-03-16T13:06:45.016098117Z" level=debug msg="docker group found. gid: 50" 
time="2017-03-16T13:06:45.016777621Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)" 
```
After the reset to factory defaults -- and provided you don't import from toolbox -- Docker will use `overlay2` which should be more stable than `aufs`.

Thanks again for your report. Please open a fresh issue if something like this happens again.
