### ISSUE TITLE
Unexpected EADDRINUSE when binding ports

### ISSUE THREAD

**Issue by acdha** [docker/for-mac#1440]
1. Check out https://github.com/chromium/badssl.com locally
2. Type `make`
3. After building the container, it will attempt to start it and fail with this error:

```
docker run -it -p 80:80 -p 443:443 -p 1000-1024:1000-1024 badssl
docker: Error response from daemon: driver failed programming external connectivity on endpoint trusting_ardinghelli (9fa34dc7084b7bd42e7b884cb091927ba1dff532ed2c0b484778cd6c7070d3ee): Error starting userland proxy: Bind for 0.0.0.0:1023: unexpected error (Failure EADDRINUSE).
```

`lsof -i TCP:1023` shows there is nothing listening on that port.

This was the only thing which has been run on a fresh Docker Mac install of the stable release.

Diagnostic ID: EB38E30F-3A69-4E3E-ABC6-6127E3BB4644

**Comment by djs55** [comment]
Unfortunately it seems to work for me on Version 17.03.1-ce-rc1-mac3 (15841):
```
docker run -it -p 80:80 -p 443:443 -p 1000-1024:1000-1024 badssl
==> /var/log/nginx/access.log <==

==> /var/log/nginx/error.log <==
```
Looking through your log files I can't spot any other use of port 1023. The error does appear to come from the userspace proxy.

Does the error always happen or could it have been a transient failure?

Could you try typing the following commands on the host and let me know what happens:

- to verify that the port really is free on the Mac
```
$ sudo nc -l 0.0.0.0 1023
```
- to check that docker really can't allocate this specific port
```
$ docker run -it -p 1023:80 nginx
```
- to verify the port is free in the VM
```
$ docker run --rm --net=host --pid=host --privileged -it justincormack/debian nsenter -m -t 1 sh
# nc -l -p 1023 0.0.0.0
```
- to verify that proxy can be run in the VM
```
$ docker run --rm --net=host --pid=host --privileged -it justincormack/debian nsenter -m -t 1 sh
# /usr/bin/slirp-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1023 -container-ip 127.0.0.1 -container-port 80 -i
# /usr/bin/slirp-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1023 -container-ip 127.0.0.1 -container-port 80 -i -no-local-ip
```

**Comment by acdha** [comment]
Okay, this is somewhat odd – ports in that range turned out to have been taken by nfsd/rpc.statd/lockd/etc. but I don't use NFS on this system. Is that auto-started by Docker Mac under any circumstances?

**Comment by djs55** [comment]
Docker for Mac does not use NFS. For file sharing we use the FUSE protocol running over a hypervisor socket (`virtio-vsock`). One of the reasons for avoid NFS was to avoid having to configure and manage the ports, host services, exports etc. Also NFS doesn't support the full range of filesystem features we wanted to support like `inotify`.

I know some people have been using NFS for file sharing as it supports an "async" mode which is currently faster than volume sharing in Docker for Mac -- could you have any elements of some other tool like dlite or docker-for-mac-nfs or similar lying around? Or perhaps some other software uses NFS internally?

I'll close this ticket since it sounds like the port was actually legitimately in-use by something else. Let me know if you discover any other problems.

**Comment by acdha** [comment]
I did at one point have dlite installed, so perhaps that was what enabled it. Sorry about the confusion.
