### ISSUE TITLE
Docker won't start after adding configuration parameters via "preferences" as json

### ISSUE THREAD

**Issue by peteblin** [docker/for-mac#1466]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  I added the following to the docker daemon configuration

{
"iptables": false,
"storage-driver": "devicemapper"
}

  2. Apply changes and restart.

Docker will not start.

--Peter

**Comment by lizrice** [comment]
Very similar issue here.  Diagnostic ID AADEFD13-95E6-4848-BD67-D05948CD7FAA

I added "userns-remap":"default" to the json. To be completely honest can't recall what exactly happened next, but things weren't behaving great. Clicked the "reset your daemon settings" link and I hoped I'd be back to normal. But:

```$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine
```

After a reboot I got a slightly different result: 

```$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64
Error response from daemon: dial unix /Users/liz/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

and 

```
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/AADEFD13-95E6-4848-BD67-D05948CD7FAA/20170326-100039.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk
```

**Comment by justincormack** [comment]
@lizrice Hmm, I just tried adding userns-remap and it worked fine, also resetting worked. I am on the dev version, which is closer to the beta channel, but this should not have changed anything. Does quitting the app and restarting help? 

@peteblin adding `"storage-driver": "devicemapper"` is not going to work, we have no devicemapper support, we only support `vfs`, `overlay`, `aufs` and `overlay2` at present.

**Comment by lizrice** [comment]
A regular restart didn't help, but a "reset to factory settings" got me back up and running again.

**Comment by justincormack** [comment]
Thats odd, hopefully someone can work out from the diagnostic what went wrong.

**Comment by avsm** [comment]
@peteblin Thanks for the report! As @justincormack explained, there's no support for 'device-mapper' at the moment in our embedded Linux.  Is there any particular reason you need this support instead of overlay2?

@lizrice I'm looking at your diagnostic tarball and there some suspicious behaviour with truncated logs there. The tarball doesn't actually have anything in the Docker `daemon.json`, and (amusingly but unhelpfully) the diagnostics service is failing to start. I've submitted an internal PR to improve some of the diagnostics logging that should be helpful if this happens again, but there isn't quite enough to diagnose your problem from this report.  I have confirmed that `userns-remap:"default"` works on the beta channel though.  If you see this problem again, we'd appreciate a fresh bug report to help chase down the issue...

**Comment by peteblin** [comment]
Anil

I am installing an image into docker that requires the following
configuration for running on CentOS. I am attempting to get the image to
run on OSX.

docker.conf file located in docker.service.d :

>tee /etc/systemd/system/docker.service.d/docker.conf <<-EOF
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --iptables=false --storage-driver=devicemapper
EOF






docker-create file:

#!/bin/bash
docker create \
--network=host \
--uts=host \
--shm-size=2g \
--ulimit core=-1 \
--ulimit memlock=-1 \
--ulimit nofile=2448:38048 \
--cap-add=IPC_LOCK \
--cap-add=SYS_NICE \
--env 'username_admin_globalaccesslevel=admin' \
--env 'username_admin_password=admin' \
--name=solace solace-app:<version-edition>

I will try using overlay2.

Are there any other parameters I should change that you know won't work on
OSX?

Thanks
--Peter

**Comment by avsm** [comment]
@peteblin unfortunately `--net=host` will not work in Docker for Mac at this time, (see https://github.com/docker/for-mac/issues/155 for the tracking issue).  Ideally that application should expose a well-defined port to connect to rather than exposing the entire Docker bridge to the host -- is this a request you can raise upstream with the Solace-app maker?

**Comment by peteblin** [comment]
--Anil

It sure is!!

Solace has set of well defined ports they use!!

Thanks for the help!1

Best,
--Peter

On Tue, Mar 28, 2017 at 9:48 AM, Anil Madhavapeddy <notifications@github.com

**Comment by avsm** [comment]
Great, glad to hear you have it working now. If you could encourage them to update their documentation to avoid the use of `--net=host`, we would appreciate it :-)

If you run into any further issues with Docker for Mac, please do not hesitate to open up a fresh bug report here.
