### ISSUE TITLE
Trying out vfarcic/docker-flow-proxy

### ISSUE THREAD

**Issue by aleskinen** [docker/for-mac#1471]
### Actual behavior
Artos-MacBook-Pro:docker-flow-proxy ale$ scripts/swarm-cluster.sh
Running pre-create checks...
Error with pre-create check: "404 Not Found"

### Information
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/F2FE3067-D7E4-4785-B551-CC65E42DF3E7/20170327-165431.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Propably comes from this:
for i in 1 2 3; do
    docker-machine create --driver vmwarevsphere --engine-opt experimental=true --vmwarevsphere-vcenter=vcenterappliance --vmwarevsphere-vcenter-port=9443 --vmwarevsphere-username=arto --vmwarevsphere-datastore=Docker1 --vmwarevsphere-network=DMZ2 node-$i
done

I there any logs etc, that reveal what is wrong?

**Comment by avsm** [comment]
I'm looking at the upstream repository where I think the referenced container image come from at https://github.com/vfarcic/docker-flow-proxy.

There are two scripts in that repository in `scripts/`:
- `swarm-cluster.sh`:   TL;DR: do not run `swarm-cluster.sh` on Docker for Mac and just do `docker swarm init` instead.  Longer explanation: this uses Docker Machine to provision virtual machines to simulate a cluster.  It should not be necessary to run this in Docker for Mac, which supports a single host only, but _can_ be run in swarm mode by doing `docker swarm init` instead.  You won't be able to add multiple hosts to it, but you can create services on your Mac to test what they will be like when eventually deployed to a cluster.
- `swarm-services.sh` does the service create commands, and works fine for me on Docker for Mac except for an error involving `docker-machine` that can be safely ignored (since we are running in single-host mode).  Running it resulted in:

```
$ docker service ls
ID            NAME            MODE        REPLICAS  IMAGE
0udl0w0v742s  proxy           replicated  3/3       vfarcic/docker-flow-proxy:latest
wug50d8snmzm  go-demo-db      replicated  1/1       mongo:latest
xtwbji9isfod  go-demo         replicated  3/3       vfarcic/go-demo:latest
zpr47z1qudac  swarm-listener  replicated  1/1       vfarcic/docker-flow-swarm-listener:latest
```

on my laptop.  You will probably need to tweak the script in order to publish ports on the local machine.  Ports advertised on Docker for Mac will end up on `localhost`, so you do not need to reference a separate machine.

> I there any logs etc, that reveal what is wrong?

If you need logs from the Docker daemon, you can run a container that will give you a login shell to the embedded Linux VM.  Do:

```
# docker run --rm --net=host --pid=host --privileged -it justincormack/debian nsenter -m -t 1 sh
<enters the container>
# cd /var/log
# tail docker.log
```

I hope this helps unblock you with trying out docker-flow-proxy on Docker for Mac.  Since there's no bug in Docker for Mac directly, I am closing this issue, but please do feel free to reopen if you need further information.
