### ISSUE TITLE
com.docker.osx.hyperkit failed to start

### ISSUE THREAD

**Issue by jpetazzo** [docker/for-mac#1475]
### Expected behavior

D4M starts.

(This is just after resetting D4M to factory defaults; see #1474)

### Actual behavior

I see an error dialog saying "com.docker.osx.hyperkit failed to start"

### Information

  - Diagnostic ID: E51882D1-961C-499B-96BA-59AFA70EF932

### Steps to reproduce the behavior

  - This is reproducible on my machine (i.e. I get that error each time I start D4M)

**Comment by avsm** [comment]
Thanks for the bug report! I've looked through the logs and there appears to be a migration issue in the database.  The `docker-system.log` reports:

```
Docker[com.docker.driver.amd64-linux][42125] <Critical>: Failed to create transaction for field-level upgrade: p9p.MessageRerror{Ename:"No such file or directory"}
Docker[com.docker.osx.hyperkit.linux][42090] <Notice>: Reap com.docker.driver.amd64-linux (pid 42125): exit status 1
Docker[com.docker.osx.hyperkit.linux][42095] <Error>: Failed to watch the com.docker.driver.amd64-linux/state/ directory in the database: 9p: (Invalid_argument
	  "Irmin_git.read: 47084c951695fb85c0858b3a9bf14f2ce0718572 not found")
Docker[com.docker.osxfs][42128] <Error>: Fatal unexpected failure: Database transaction start failed: (Invalid_argument
	  "Irmin_git.read: 47084c951695fb85c0858b3a9bf14f2ce0718572 not found")
```

I'm investigating where this error came from...

**Comment by avsm** [comment]
@jpetazzo We don't have quite enough information in the diagnostics tarball to track down the issue that caused this.  If you reset to factory defaults again, does it happen? 

We are trying to distinguish between a one-off startup race, and it happening deterministically on every app startup.  The latter would be very odd, since the factory reset erases the internal database entirely.

**Comment by jpetazzo** [comment]
@avsm unfortunately, I can't reset to factory defaults again: when I try to start D4M, after a few seconds, I get the `com.docker.osx.hyperkit.linux failed to start` error box, preventing me from going to the preference panel to do a factory reset.

I tried to be very fast, and go immediately to the preference panel while D4M is still starting; the pref panel shows up, but immediately after, I get the following error panel:

![image](https://cloud.githubusercontent.com/assets/171481/24410116/d7bd9582-1397-11e7-8f7f-1e04c5e3e0c6.png)

```
Error

Failed to retrieve settings values.

failed to get memory setting
```

It seems to be a modal dialog, preventing me from interacting with the preferences panel.

And a few seconds later, the other error comes back:

![image](https://cloud.githubusercontent.com/assets/171481/24410167/fb5a2d5c-1397-11e7-827d-45fd116c24e8.png)

Let me know if you'd like me to try anything else.

**Comment by avsm** [comment]
This definitely sounds like a corrupted database.  Could you:

- Shut down Docker for Mac
- `cd ~/Library/Containers/com.docker.docker/Data`
- `mv database database.old`
- `cd database.old`
- `git log`

This will show us what's in the DataKit database.  If you restart any time after moving the database directory out of the way, D4Mac should construct fresh state and restart from scratch, hopefully without an error.

**Comment by jpetazzo** [comment]
Ayaye!

```
$ git log
fatal: bad object HEAD
```

If it's safe (i.e. if that database doesn't contain secrets) I can attach it here; or otherwise send it to you through another channel.

Meanwhile, moving the database out of the way did indeed allow me to restart D4M. Victory! Thanks!

**Comment by avsm** [comment]
@jpetazzo great! It seems that it's a one-off startup race since your machine recovered. We can hopefully create a CI test that resets/starts in a tight loop to try to recreate the bug.

The database could potentially contain private information -- I'll send you an out-of-band location to upload it to.  Thanks very much for helping track this down, and I'll close this issue for now as there is an active internal issue and this is probably a pretty rare issue.

**Comment by ismith** [comment]
I just had the same problem, same workaround allowed D4M to start.
