### ISSUE TITLE
3428FE91-D565-4202-B3CB-E4948C3B50E9

### ISSUE THREAD

**Issue by rodrigomilfont** [docker/for-mac#1476]
### Expected behavior
Docker start using docker.dmg 
### Actual behavior
Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1
### Information
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/3428FE91-D565-4202-B3CB-E4948C3B50E9/20170327-210545.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rmilfont/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/rmilfont/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmilfont/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rmilfont/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmilfont/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rmilfont/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

**Comment by avsm** [comment]
Thank you for the bug report! I analysed your logs, and detected symptoms of an old block corruption from when you were running Docker 1.13beta.  

Recent Docker for Mac releases check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.  It looks like you upgraded on the 25th March and then immediately had the corruption check trigger.

As a workaround we recommend either uninstalling and reinstalling the application (or a factory reset, if you can get to the whale menu) or stop the application and `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information. For further details, the log in docker-system.log matches:
```
Docker[com.docker.driver.amd64-linux][9072] <Notice>: com.docker.hyperkit: [ERROR] Found two references to cluster 174903: 101.58456 and 46345.42528
Docker[com.docker.driver.amd64-linux][9072] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure "Found two references to cluster 174903: 101.58456 and 46345.42528")
Docker[com.docker.driver.amd64-linux][9072] <Notice>: Mirage-block error: Unknown (Failure "Found two references to cluster 174903: 101.58456 and 46345.42528")
Docker[com.docker.driver.amd64-linux][9072] <Notice>: Could not open mirage-block device: Invalid argument
```

**Comment by rodrigomilfont** [comment]
Tks, the workaround fix this issue.
