### ISSUE TITLE
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### ISSUE THREAD

**Issue by GitHublaohuang** [docker/for-mac#1499]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jeanlaurent** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.  If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
