### ISSUE TITLE
com.docker.hyperkit goes to 400% CPU after unsleeping

### ISSUE THREAD

**Issue by nedbat** [docker/for-mac#1533]
### Expected behavior

1. Look at Activity Monitor. com.docker.hyperkit is using ~1% CPU.
2. Sleep the Mac by closing the lid.
3. Unsleep the Mac by opening the lid.
4. Look at Activity Monitor. com.docker.hyperkit should still be using only ~1% CPU.

### Actual behavior

In step 4, com.docker.hyperkit is using ~400% CPU

### Information

I have configured Docker to use 4 CPUs.  I have no Docker images running (docker ps shows none).

Diagnostic ID: 43187721-B94C-4745-BE76-E743A6850110

I am on OS X 10.10.5

**Comment by dsheets** [comment]
This is a known issue with OS X 10.10. We worked around the issue as best as we could by suspending the hypervisor immediately before sleep and resuming it immediately after sleep but this issue still occurs in some cases. We've reported it to Apple and we no longer see reports of the issue with OS X 10.11.6 or macOS 10.12. The best way to fix this issue is to upgrade your OS to 10.11 or 10.12. We have deprecated 10.10 support for this and similar problems.

Thanks for using Docker for Mac!
