### ISSUE TITLE
Repositories and Swarms not loaded

### ISSUE THREAD

**Issue by bvis** [docker/for-mac#1573]
### Expected behavior
Show the configured swarms in Docker Cloud and the repositories associated to the logged-in user.

### Actual behavior
It does not show anything. Just a "Loading..." sentence.
![image](https://cloud.githubusercontent.com/assets/580682/25479353/d171524e-2b44-11e7-844b-7ad91ebf14cd.png)

### Information

The output when I execute the "Diagnose & Feedback" is:

>>> Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.12 (build: 16A323)
logs: /tmp/5C78DBB7-8788-48C1-9CEB-8DA642C76D82/20170427-130847.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Diagnostic ID: **5C78DBB7-8788-48C1-9CEB-8DA642C76D82**

### Steps to reproduce the behavior
I don't know how to reproduce or fix it, it's just happening from some time ago.
In the first version I tried this feature it worked like a charm.

**Comment by jeanlaurent** [comment]
Hi @bvis sorry you were hit by that.

The fix is going to be shipped in the coming days with the next Docker for Mac version, most probably with 17.05-0-RC2.

As a workaround, :
* Quit Docker for Mac
* Launch the “Keychain Access” app look for a “docker swarm federation” key ( you can search for it in the top right search box), and just delete the key there.
* Restart your Docker for Mac and login again

Let us know how it goes for you.

**Comment by bvis** [comment]
Your workaround works as expected. Thanks.
