### ISSUE TITLE
Docker crashes on startup

### ISSUE THREAD

**Issue by githinho** [docker/for-mac#1651]
Diagnostic ID: 4AEF58CC-A144-45CE-9F0A-47458E7860AA

Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/4AEF58CC-A144-45CE-9F0A-47458E7860AA/20170526-082347.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/-/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/-/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/-/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/-/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/-/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by seetpalsingh** [comment]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 007F5BD4-1DE9-4E5A-927F-C3FD9CADFA99/20190219073654

### Expected behavior

run on startup/login

### Actual behavior
crashes on startup

### Information

  - macOS Version:macOS 10.13.6
  - Mac mini6,2
  - 8gb ram

### Diagnostic logs

```
Docker for Mac: 

```

### Steps to reproduce the behavior


  1. put it on run on startup/login
  2. restart/ re-login to system
