### ISSUE TITLE
Failure "docker ps: timeout after 10.00s"

### ISSUE THREAD

**Issue by sarikasoni12** [docker/for-mac#1654]
Docker for Mac: version: 17.03.0-ce-mac2 (32de84251)
macOS: version 10.10.5 (build: 14F27)
logs: /tmp/61ED7353-6042-453A-8111-9A8338FCF17F/20170529-094441.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by mikebarkas** [comment]
I had the same issue as above. I believe my issue was from leaving containers running while changing `docker-compose.yml` file and closing laptop. Coming back to laptop and `ps` command seems to being non-responsive. I could not restart docker app for mac with similar error as above.

I resolved this by `Docker icon > Preferences > Reset` and then restarted my laptop.

OS X 10.11.6
Docker for Mac: Version 17.03.1-ce-mac12

**Comment by alycda** [comment]
I am still having this issue.

I originally installed docker via `brew` but encountered this issue. I un-installed and re-installed via the download link. The issue still persists even though I have "Reset Factory Defaults" multiple times.

https://github.com/docker/for-mac/issues/2655#issuecomment-370669249
62F58FE7-C42C-4771-96DD-06DC45ACCD29

**Comment by tylerssn** [comment]
@alycda - for me, this was caused by some corruption within docker-machine and resetting docker to factory state did not work.

*Details:*

When I executed `docker-machine ls` I saw a `default` image and a `dinghy` image - both had a state of "Error". `docker-machine rm default dinghy` returned an exit error and they were not removed. 

To resolve this I executed `docker-machine create` (parameters did not matter) on `default` and `dinghy` which removed each because they already existed and were corrupt.

I then, for overkill & because I had already reset docker to the factory defaults, I forcefully purged docker and docker-machine and removed all docker references in `~/.bashrc` as well as `~/.zshrc`.

I reinstalled docker and finally, all is well again.

*Summary*

I forcefully removed all items listed in `docker-machine ls` and removed docker references in my `~/.bashrc` & `~/.zshrc` before reinstalling docker.
