### ISSUE TITLE
Port forwarding doesn't work at all

### ISSUE THREAD

**Issue by lyptt** [docker/for-mac#1675]
### Expected behavior
Web server should be accessible

### Actual behavior
Web server is inaccessible

### Information
Diagnostic ID: E751FE08-0D47-4003-A6FD-0E69B7BFBC7E

Dockerfile: (public_html is just a folder with an index.html file inside it)
```
FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/
RUN apt-get update && apt-get install -y curl
EXPOSE 80
```

### Steps to reproduce the behavior

  1. `docker build -t myimage .`
  2. `docker run --name ds_dev -i -p 80:8080 myimage`
  3. `curl localhost:8080/index.html`
  4. Observe result: `curl: (7) Failed to connect to localhost port 8080: Connection refused`
  5. `docker exec -it ds_dev curl 127.0.0.1:80`
  6. Observe result: `<html></html>`

Notice that the http server works, and is fully functional locally within the container, but port forwarding does not work at all. I've also tried running `curl` against `127.0.0.1`, same result.

I assume I'm missing some flag that fixes everything for me magically. Any ideas?

**Comment by djs55** [comment]
Thanks for the clear repro instructions. I fixed a minor typo in the `Dockerfile` by replacing `public-html` with `public_html`.

Step 2 should be `docker run --name ds_dev -i -p 8080:80 myimage` -- the syntax is

- `-p [host IP:]<host port>:<container port>`

Where `<host port>` is `8080` and `<container port>` is `80`. If the `host IP` is unspecified then it defaults to `0.0.0.0` i.e. all the interfaces on your Mac. You may prefer to use something like `-p 127.0.0.1:8080:80` to bind only to `127.0.0.1`.

I hope this helps! Since I think this was a minor typo, I'll close this ticket. Feel free to open a fresh ticket if you have any other problems.

**Comment by joe-el-khoury** [comment]
This saved me tons of time. Thanks!

**Comment by pranavanmaru** [comment]
https://docs.docker.com/docker-for-mac/networking/#there-is-no-docker0-bridge-on-macos
