### ISSUE TITLE
17.03.1-ce-mac12: After a crash Docker is not opening - Fatal Error

### ISSUE THREAD

**Issue by rmilushev** [docker/for-mac#1685]
### Expected behavior
Open Docker app for Mac OS X 
### Actual behavior
Opens modal window with "Fatal Error" 
```
com.docker.osx.hyperkit.linux failed to start
Exit code 1
```
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/1909365A-0985-4509-A085-A25C88B4ED8B/20170603-231718.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rmilushev/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/rmilushev/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmilushev/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rmilushev/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmilushev/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rmilushev/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```
Diagnostic ID:
1909365A-0985-4509-A085-A25C88B4ED8B
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. With Docker 17.03.1-ce-mac12, while building an image, turn off your mac (crash).
  2. After rebooting, try to open Docker.

**Comment by djs55** [comment]
The diagnostic logs contain the error
```
"Found a reference to cluster 118255 outside the file (max cluster 118254) from cluster 4244.62112"
```
which means the file `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` has become corrupted. Unfortunately the only workaround is to delete this file, restart the app and then rebuild your images and containers -- sorry for the inconvenience.

Regarding improving crash reliability -- we used to use a more strict "flush all data to the drive" behaviour to prevent data loss over Mac crashes, but this resulted in very poor (basically unusable) performance for some workloads (e.g. database transactions). Since the Mac is primarily a development platform we switched the behaviour back to the faster "flush data to OS memory buffers" which is much faster but the cost is that data can be lost if the Mac crashes.
