### ISSUE TITLE
Dowgrade Docker for Mac

### ISSUE THREAD

**Issue by valeriangalliat** [docker/for-mac#1698]
### Expected behavior

Ability to downgrade to an older version when Docker is broken.

### Actual behavior

Can't downgrade.

### Information

I was using 17.05.0-ce to leverage multi stage builds. Recently updated to 17.06.0-ce-rc1.

This release have an issue that is already known and fixed (https://github.com/moby/moby/issues/33493), but not yet released.

Without this fix (or downgrading to an older version) I can't build any image locally (most of my projects use `ONBUILD COPY`. I can't find any way to downgrade to an older version.

I understand this is the Edge channel, but I'm willing to test bleeding edge features and I accept to run into bugs when using those features, so I can report them and help making the release more stable, but I also need to be able to keep working after finding and eventually reporting a bug by downgrading to a working release.

**Comment by zbruhnke** [comment]
in case this helps anyone else I put an older version of the docker edge beta in an S3 bucket here since i had one in trash

This one in particular is reflected in the filename

17.05.0-ce-rc1-mac8-build16582

If it helps you're welcome to it - I'll leave this up for a while

https://s3-us-west-2.amazonaws.com/docker-edge/Docker-edge-17.05.0-ce-rc1-mac8-build16582-git-sha-73d01bb48e.dmg

**Comment by valeriangalliat** [comment]
Yaas! Works like a charm, thank you very much sir.

**Comment by franklinyu** [comment]
See #1120.
