### ISSUE TITLE
Original ip is not passed to containers

### ISSUE THREAD

**Issue by withinboredom** [docker/for-mac#180]
### Expected behavior

See my real ip (or an X-FORWARDED-FOR header): ex: 10.100.2.14
### Actual behavior

Instead I see 172.19.0.1, which is not my host's ip.
### Information

Diagnostic ID: 70CE1D3C-D5A6-4C95-ABA8-17CEF9371D01
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. `HOST: docker run --rm --name nginx-test -p 8080:80 nginx`
2. `HOST: curl localhost:8080`
3.  You'll see an ip in the logs with something like `172.17.0.1`, take note of that.

This is not the ip address of the actual machine that made the call. For debuggers that call back to the originating ip (such as php xdebug) this means docker cannot be used to debug anything. I would expect to see an IP of the original machine (such as a truly remote host).

**Comment by AlexGustafsson** [comment]
Isn't that expected behavior? Since you're not passing any network flag the container is using the default bridge mode. So you're seeing the container's IP address on the docker0 bridged interface.

**Comment by withinboredom** [comment]
No, I should see the remote ip (in linux or docker toolbox) of the connected machine from inside the container, and not the container's gateway ip.

**Comment by withinboredom** [comment]
This is a pretty serious issue as NAT appears to be broken ... kind of a deal breaker.

**Comment by samoht** [comment]
I confirm that I can reproduce the issue. I will discuss the issue further with the team to see what we can do to fix it.

**Comment by samoht** [comment]
I also confirm that we can reproduce the issue on Linux, so the issue is not in Docker for Mac. /cc @thajeztah is it a know issue on Linux?

**Comment by ijc25** [comment]
I had second thoughts about whether I had really reproduced on native Linux.

I had done a `docker run` then a `﻿⁠⁠⁠⁠curl localhost...`﻿⁠⁠⁠⁠ like the ticket says and saw an originating IP of 172.17.0.1, which is the IP of the `﻿⁠⁠⁠⁠docker0﻿⁠⁠⁠⁠` bridge, which thinking about it more is _an_ IP of the originating host (even if one maybe wouldn't think about it as "the" IP of the host).

In the for-mac case the ﻿⁠⁠⁠⁠172.17.0.1﻿⁠⁠⁠⁠ is not going to be an address which the OSX host knows about, which is the crux of the issue here since something which ought to dial back to the mac will end up dailing back to the VM hosting the containers instead.

So I think I was too quick to tell @samoht I was seeing the same issue on native Linux, sorry. Reopening.

I think what would be needed here would be some mechanism to forward ports back out of the VM to the host (i.e. the inverse of what `docker run -p NN:NN` does). ISTR that being discussed in another context somewhere but the specifics are escaping me right now.

**Comment by thaJeztah** [comment]
@samoht @ijc25 I know there's an issue in swarm mode (see https://github.com/docker/docker/issues/25526)

**Comment by PanJ** [comment]
I tried to replicate the issue and found out that the IP address like `172.17.0.1` only appears when the request is originated from the same host as the container.

This behavior is for standalone container. For swarm mode, it is another separate [issue](https://github.com/docker/docker/issues/25526).

**Comment by thaJeztah** [comment]
@PanJ in that case, I suspect it's because of the userland-proxy

**Comment by PanJ** [comment]
@thaJeztah 
I just noticed that this is docker for mac repo. Tried to reproduce again with docker for mac and the problem persists event the client and server is different machine. Both with machine in same network and doing NAT over the internet.

**Comment by samoht** [comment]
Thanks for the report and sorry the delay! I have forwarded the issue to our networking team, we will keep you updated when we start making progress on fixing that issue.

**Comment by djs55** [comment]
I think making this just work in Docker for Mac will be quite involved. We can't add an `X-Forwarded-For` header since this is a TCP proxy, not an HTTP one. I think we would have to teach the userland proxy how to do transparent proxying i.e. to spoof the client IP. From a quick glance at https://www.haproxy.com/blog/howto-transparent-proxying-and-binding-with-haproxy-and-aloha-load-balancer/ I think this involves some or all of:

- `CONFIG_NETFILTER_{,XT_TARGET_}TPROXY` kernel options
- `net.ipv4.ip_nonlocal_bind`
- some new `iptables` rules: would need to be careful here to avoid damaging the main `docker`/`swarm` ones
- some new routing
- update the tunnelling protocol to pass in the client IP and use it inside the VM

As a workaround in the meantime perhaps you could run an explicit HTTP proxy container yourself, and make it add the `X-Forwarded-For` header?

**Comment by withinboredom** [comment]
@djs55 for what it's worth, this also appears to happen with Docker Swarm mode ...

https://github.com/moby/moby/issues/25526

**Comment by mrmachine** [comment]
This makes it impossible to test things like HAproxy load balancing via `source` method which checks the IP address of incoming requests when determining which container to send a connection to on Docker for Mac. All incoming requests will appear to originate from the same IP, the HyperKit VM's IP (not the macOS host IP or other LAN IP).

**Comment by runeimp** [comment]
@samoht Just checking on the status of this. The issue is over a year old and doesn't sound like it's being actively reviewed in the last 9 months. Can we get a status update? Please.

**Comment by tomekit** [comment]
@withinboredom 
I've experienced similar problem when using PHP with XDebug. 
I manually override the: `xdebug.remote_host` from the PHPStorm interpreter options.

**Comment by RWOverdijk** [comment]
👍

**Comment by andrerom** [comment]
Same issue with ports, ssl container in order to do http/2 development would typically not know it's public port is often mapped by docker acting as proxy.

Unsure what we should expect but `X-Forwarded-Port` for instance would make it a bit more standard for http(s) traffic.

**Comment by tbessenreither** [comment]
Same problem with a node service who needs the client IP for authentication.

**Comment by userlerueda** [comment]
Is there a solution for this problem ? Workaround perhaps?

**Comment by andig** [comment]
I have the same problem with a Symfony application behind traefik running on docker at Linux. I was suspecting traefik (or my config) but this issue makes me unsure.

**Comment by kspearrin** [comment]
Same problem here. Always seeing 172.18.0.1 hit our nginx container.

**Comment by kspearrin** [comment]
All networking for this docker instance is handled by `docker-compose`. Is there something we can adjust there to resolve this?

**Comment by arvenil** [comment]
Any workaround for this issue?

**Comment by jabenninghoff** [comment]
I think at this point the most effective workaround would be to use a Linux version of Docker running on a VM on the Mac and not use Docker for Mac ... not exactly a workaround, but another way to solve the problem.

**Comment by tbessenreither** [comment]
Switching the OS will not solve this as it's happening on all plattforms.
It's an issue with dockers networking for services.

**Comment by bestreaction** [comment]
Yes, I tried to all platforms. It doesnt work.

**Comment by yi-huan** [comment]
@arvenil I don't have a solution, I think I should add forwarding at the network, but I don't know what to do.

**Comment by yi-huan** [comment]
I found some previous fixes that don't know how now.
> [traffic coming from gateway IP and X-Forwarded-For](https://groups.google.com/d/msg/docker-user/aHivqowQheg/MBJ6bo2cBoQJ)
> [Correctly express "any address" to iptables.](https://github.com/moby/moby/pull/2633)
> [Forwarding rules](https://github.com/moby/moby/issues/2598#issuecomment-28025678)

**Comment by yi-huan** [comment]
Tested today, using **Centos 7** to get the client IP right.
I only test `docker-compose up`.
< [./docker-compose.yml, ./nginx.vh.default.conf, ./web/index.php](https://github.com/docker/compose/issues/6021#issue-333060073)

**Comment by jabenninghoff** [comment]
I'm not able to test at the moment, but disabling the userland proxy (with `--userland-proxy=false`) is supposed to expose the real IP. This is not possible on Mac or Windows, since both rely on the proxy.

Disabling userland proxy is also [possible on docker-compose](https://botproxy.net/docs/how-to/how-to-disable-userland-proxy-for-docker-compose/).

**Comment by yi-huan** [comment]
@jabenninghoff Thank you, I am a novice,  I thought Windows Docker and Linux is the same, the Docker NIC can be a transparent proxy forwarding to get real IP, now seems to be just agent, no forwarding.

**Comment by vadim-shilov** [comment]
Hi! I've tried to run a container with Node.js app by this doc [nodejs-docker-webapp](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/), but it didn't work on my Mac (macOS High Sierra v10.13.5). There is no connection to http://localhost:[exposed port] when I try to do HTTP request after container starts. :(

**Comment by runeimp** [comment]
@vadim-shilov it is highly unlikely this issue has any effect on your example. This issue is regarding seeing the IP address of an external client from within the Docker container. Not seeing a server within a Docker container from the outside. Be sure to follow the instructions all the way to and through https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#header-test . Also try `http://127.0.0.1:[exposed port]` as you may not have `localhost` setup correctly. If none of that works please check in forums, IRC, Slack, etc. or open another issue. This issue is not for the problem your experiencing.

**Comment by timchenxiaoyu** [comment]
same problem ,  get source ip is docker0 
centos7 docker 1.13.1

**Comment by hamurabiaraujo** [comment]
I had the same problem. I'm now using docker on ubuntu machine and solved with the nginx config to redirect like a proxy. When the nginx redirects to docker machine, we can set a header with the original IP.  

**Schenario:**

- Container listen on :8989 with web server
- Host with nginx listen on :80 and redirecting to container port. On nginx server config, I setted the `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`. This add `X-Forwarded-For ` header with the host original IP and I could get it on my code. [nginx reference](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/#coexistence-with-x-forwarded)

**Comment by dsuckau** [comment]
Still the same problem with macOS High Sierra v10.13.5 and Docker version 18.09.1, build 4c52b90.

Node.js behind nginx in Docker container always gives us 172.18.0.1 as X-Forwarded-For. No matter if the request comes from the host system, that hosts the Docker container or from another system.

On Debian no problem, it always gives us the real client IPs.

**Comment by cncgoko** [comment]
Same issue on Docker for Windows (using linux containers for nginx):
- Windows 10
- Docker 18.09.1

Host networking mode won't help since it's not compatible with Docker for Windows.

**Comment by janorga** [comment]
I have the same issue on Docker for Windows. It seems an issue about Hyper-V routing. However, I can successfully achieve this with Docker Toolbox in Windows. I successfully get the real-client source IP on nginx container.

One issue to take into account is to set the Docker VM in VirtualBox in transparent nat with this command:
`VBoxManage modifyvm <your-vm name> --nataliasmode1 proxyonly`
as it is mentioned in VirtualBox official [forum ](https://forums.virtualbox.org/viewtopic.php?f=7&t=43500)

Maybe you can work with a different solution working with a bridged network interface on Docker for Windows as this [post ](https://forums.docker.com/t/bridge-with-docker-for-windows/30936/5)mentions, but I have not tested this way.

I hope Docker Toolbox solution also works on Mac.

This is the kind of issues because I keep both Docker Toolbox and Docker for Windows installations on my PC.

**Comment by TechCiel** [comment]
Exactly same issue. So surprised this is still not fixed...

**Comment by pat-bateman** [comment]
Had to run my docker containers in Ubuntu-Server with the docker.io package from Ubuntu-Repo universe installed. Et voilà: Originating ip addresses are logged in a simple nginx container.
The docker-ce installation behaves like described above.
What is Ubuntu doing different? (actually I mostly do not like their own ways) I inspected docker networks, iptable rules.. and did not find any differences...

**Comment by sathio** [comment]
will this ever be fixed? I don't want to install linux :)

**Comment by KingRial** [comment]
@sathio unluckily, the same problem is on Linux and Windows.

**Comment by tbessenreither** [comment]
@sathio No, as @KingRial mentioned the problem exists in docker-ce on all operating systems.
The only way to not have it, is to use networking in host-mode and therefore not having docker route the request to your Swarm-Services removing the round robin load ballancing entirely.

**Comment by KingRial** [comment]
@sathio there are also other workarounds, but still no fix up to now.

For example:
- if you need to handle connections based on HTTP/HTTPs protocol you could use HAproxy or nginx to add a reverse-proxy before the docker environment.
The reverse proxy could add "X-Forwarded-For" header to the request with the real IP and, from inside your code, you could check the header instead of the IP connection.
- I am still exploring a solution for pure TCP connections; still no luck on finding a solution for them.

I hope someone will share better workarounds ^^

**Comment by szczepanczykd** [comment]
Hello,

I had some similar issue on Debian 9 ( **apache + php + alpine linux - container ** )
$_SERVER['REMOTE_ADDR'] was returning **only Docker0** interface IP ( **172.17.0.1** ).

I was very surprised because it works a few days ago (the correct IP was returned )

My host firewall is generated from /etc/init.d/firewall.sh  (custom) script, which one flushes all IPTABLES rules and creates them again. I didn't know that Docker creates his own IPTABLES rules.
Now I need to restart firewall, then restart docker service ( to recreate rules )

Please note that I was trying to get a client IP address from the OTHER network interface.
eg. from eth1.15.

**Comment by Gunthervc** [comment]
@szczepanczykd i got Debian 9 bud /etc/init.d/firewall.sh is emty here.

**Comment by szczepanczykd** [comment]
@Gunthervc  /etc/init.d/firewall.sh - this is my custom firewall script.
It flushes all rules, that's why I saw only interface IP instead of hosts. 

This is my working configuration:

```
iptables -L DOCKER -n -v -t nat
Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
  108  6480 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
   43  2604 RETURN     all  --  br-9f4ebfb60ec1 *       0.0.0.0/0            0.0.0.0/0           
   21   980 DNAT       tcp  --  !br-9f4ebfb60ec1 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8090 to:172.18.0.3:80
```
```
iptables -L DOCKER -n -v -t filter
Chain DOCKER (4 references)
 pkts bytes target     prot opt in     out     source               destination         
   21   980 ACCEPT     tcp  --  !br-9f4ebfb60ec1 br-9f4ebfb60ec1  0.0.0.0/0            172.18.0.3           tcp dpt:80
```
See?
Docker is using his own IPTABLES rules.
You have to verify Your network configuration.

**Comment by vincentwinkel** [comment]
Same issue on Docker 18.06.1-ce-mac73 for MacOS X 10.11.6.

**Comment by ukid** [comment]
Same issue

**Comment by vytsci** [comment]
Same on linux. xdebug.remote_connect_back is not working as docker returns wrong ip. It is not possible to get client IP via php-fpm.

**Comment by Cranespud** [comment]
Same issue as @vytsci  but for me it works correctly on linux but not for windows 10 pro.

**Comment by avasuro** [comment]
Same issue, i'm running websockets ("ws" library) on node inside docker container, and when I try to get remote address of connected websocket as described [here (stackoverflow)](https://stackoverflow.com/questions/14822708/how-to-get-client-ip-address-with-websocket-websockets-ws-library-in-node-js/18553850) it returns me 172.28.0.1.
Is there any progress on this issue?

**Comment by rjhdby** [comment]
Same issue on MacOS with UDP. "local client" + "docker server". Server recognise client IP as 172.20.0.1

**Comment by runeimp** [comment]
This issue is well over 2 years old. Don't expect it to ever be fixed with the current architecture Docker uses on macOS. Docker only really cares about Linux and Windows which are the two server architectures that Docker gets used on. I suspect they will happily fix the issue if they every re-architect Docker for Mac with any significant rewrite. But I believe the issue is too buried in the current architecture to be fixed without a serious refactor involved.

**Comment by sathio** [comment]
I agree with @runeimp. for this and other reasons I decided that it's better to just use brew rather than Docker for dev

**Comment by vytsci** [comment]
@sathio well then Docker is useless within production then :D This bug should be added to documentation and workaround should be offered, so no one would waste any time with docker again.

**Comment by yonghaihung** [comment]
> This issue is well over 2 years old. Don't expect it to ever be fixed with the current architecture Docker uses on macOS. Docker only really cares about Linux and Windows which are the two server architectures that Docker gets used on. I suspect they will happily fix the issue if they every re-architect Docker for Mac with any significant rewrite. But I believe the issue is too buried in the current architecture to be fixed without a serious refactor involved.

This issue is everywhere (Linux, Mac, Windows). It seems like a fundamental issue deep within docker. 

https://github.com/moby/moby/issues/15086

**Comment by doublemcz** [comment]
It has been 4 years today now and still no progress :-/

**Comment by a1pilot** [comment]
Seeing this issue with a bitwarden container on Debian 10. Commenting to bump and get updates.

**Comment by melya** [comment]
Same issue. 
Unable to properly configure ubuntu firewall :( 

Any updates ?

**Comment by rpq** [comment]
Just want to add I was having this issue with postgres and it turned out the docker volume where I had postgres's data was causing this. Removing the volume and re-creating the volume solved the issue for me. Hopefully this helps someone.

**Comment by victory7** [comment]
Same issue with docker for Linux 19.03.4 
I can't believe that it's a 4 years old issue !!

**Comment by akytsun** [comment]
i have the same issue(

**Comment by milkice233** [comment]
After struggling for some time I finally find out the solution for my case.

My server is assigned both ipv4 and ipv6 addresses with nginx running in the Docker container, but I forget to turn on the IPv6 support for Docker. 

Thus, when a user accesses the server from a foreign public IPv6 address, Docker userland proxy has no choice but to reconstruct and send the IPv4 packet to the nginx inside the Docker container as if the packet was sent by the Docker gateway. When setting `--userland-proxy=false` flag, the nginx container is not accessible at all when connecting from IPv6 address.

The solution is easy, either by enabling IPv6 support for Docker or disable IPv6 permanently on the host can solve this issue.

**Comment by runeimp** [comment]
@milkice233 interesting solution. Thanks for figuring it out. Seems like something the developers could have figured out over 3 years ago. Or maybe it's a recent change that makes that work? In any case I hope that this is a universal work-around for all Docker platforms. Maybe I'll start playing around with Docker again. Maybe the devs can finally fix the problem knowing about this work-around?

**Comment by milkice233** [comment]
@runeimp I forget to mention that docker is running under Ubuntu 18.04 in my case. I'm not sure whether the bug that original ip not passed to containers is a macOS specific bug or not. I just shared my experience when encoutering this issue under a Linux environment. 😢

**Comment by runeimp** [comment]
@milkice233 Thanks for the clarification that this work-around was on a Linux system specifically. I believe the problem was first noticed on Mac but in any case it seems to be an issue on all platforms with Linux being the most unexpected. At least unexpected by me as Windows and Mac use Virtual Machines instead of containers. Though I believe HyperVisor Containers are used currently on Windows. More testing needs to be done!  😃

**Comment by farazpartoei** [comment]
this configuration worked for me

`    ports:
    - mode: host
      protocol: tcp
      published: 8082
      target: 80`

changing port bind mode to host

how ever you should force your fronted container to run on the specific host in swarm cluster only

i.e.
`    deploy:
      placement:
        constraints: [node.role == manager]`

**Comment by cryptax** [comment]
this works for me:

```
version: "3.2"
services:
   mycontainer:
     build:
       context: .
     ports:
        - "2221:2221"
        - "30000-30009:30000-30009"
     container_name: mycontainer
     network_mode: host
```

Note the addition of `network_mode: host`. I didn't need to use lines such as `ports: - mode: host protocol: tcp published: 8082 target: 80`.
And now my container sees the **original IP address** of incoming sockets.

**Comment by dvcrn** [comment]
As this is the docker for mac repository: https://docs.docker.com/network/network-tutorial-host/

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

**Comment by roenw** [comment]
I'm not sure if this helps, but I am experiencing this issue on CentOS 8 with DockerCE. I experience this when iptables/firewalld is set to masquerade or not masquerade IPs, so may or may not be related.

**Comment by sorgloomer** [comment]
Those solutions above only work on Linux.

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

I wanted to run Tomcat Docker on a Windows host, only to find out that I cannot access the management interface. By default, it is only accessible from localhost as a security measure. So my only option afaik is to reconfigure Tomcat and compromise my apps security.

**Comment by abelmferreira** [comment]
Same here
Docker Desktop 2.2.0.5
Docker Engine 19.03.8

**On Mac OSX 10.14.6**
$ _docker run -it --rm -p 80:80 --name whoami containous/whoami_

**On a remote machine**
$ _curl 192.168.25.87_
Hostname: 07a90be6f0fa
IP: 127.0.0.1
IP: 172.17.0.2
**RemoteAddr: 172.17.0.1:46448**
GET / HTTP/1.1
Host: 192.168.25.87
User-Agent: curl/7.54.0
Accept: */*

Expected to be the ip from remote client on 192.168.25.0 network

**Comment by logopk** [comment]
As a reply to my crosspost to boot2docker I‘ve got the hint to put this Problem/wish on the roadmap at https://github.com/docker/roadmap
Apparently the issue is internally know, but that may get this more publicity...

**Comment by renatoaraujoc** [comment]
So, we're in August, can't we have a solution from docker team? I just want to have the original ip forwarded to containers :/

**Comment by skududufru** [comment]
Same for me. Can we have the original IP forwarded? :grin: :pray:

**Comment by shafzhr** [comment]
> this works for me:
> 
> ```
> version: "3.2"
> services:
>    mycontainer:
>      build:
>        context: .
>      ports:
>         - "2221:2221"
>         - "30000-30009:30000-30009"
>      container_name: mycontainer
>      network_mode: host
> ```
> 
> Note the addition of `network_mode: host`. I didn't need to use lines such as `ports: - mode: host protocol: tcp published: 8082 target: 80`.
> And now my container sees the **original IP address** of incoming sockets.

Thanks. Worked for me.

**Comment by tbessenreither** [comment]
Yeah we know that. But host mode only circumvents the problem.
host mode is not usable in swarm / service environments where mutliple instances need to run on the same machine.

**Comment by correiajoao** [comment]
Same for me...

**Comment by devgnx** [comment]
Yep, same here on Linux aswell

**Comment by knigitz** [comment]
Still an issue in Docker Desktop in Windows 10.  This prevents setting up ACL in web based applications hosted inside a Docker container.  This should be marked critical and have a proper fix.

**Comment by aguedeney** [comment]
This issue has prevented me from using my applications in production.  Is this in the "Roadmap" anywhere?

**Comment by stephen-turner** [comment]
This feature request has now moved to docker/roadmap#157, so I'm going to close this ticket.

**Comment by Trackhe** [comment]
> I'm not sure if this helps, but I am experiencing this issue on CentOS 8 with DockerCE.
> But when I run `sudo firewall-cmd --permanent --zone=trusted --remove-masquerade` I am able to read incoming IPs from within the container. If Mac supports iptables I would look into that.

It helps but the performance is going so bad from 19ms to 2-3seconds

**Comment by sharkymcdongles** [comment]
> > I'm not sure if this helps, but I am experiencing this issue on CentOS 8 with DockerCE.
> > But when I run `sudo firewall-cmd --permanent --zone=trusted --remove-masquerade` I am able to read incoming IPs from within the container. If Mac supports iptables I would look into that.
> 
> It helps but the performance is going so bad from 19ms to 2-3seconds
> On Linux

This worked for me and performance wasn't degraded at all.
