### ISSUE TITLE
Docker stuck in starting mode after the last update/upgrade

### ISSUE THREAD

**Issue by MrMic** [docker/for-mac#1813]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gkalele** [comment]
Same here...Docker is unusable/fails to start every time.

**Comment by jgf20** [comment]
On Friday my docker stopped working and was unable to start, tried updating docker today, but it was still stuck, I had to reset my docker settings to factory defaults for it to work, however not everyone may want or can do this, you will loose your local repositories. I found the reset "solution" in this issue, https://github.com/docker/for-win/issues/482#issuecomment-278993095 it is still open

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.  If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
