### ISSUE TITLE
`docker-machine` inside Docker for Mac should be updated to at least `0.12.1`

### ISSUE THREAD

**Issue by twang2218** [docker/for-mac#1875]
`docker-machine` 0.12.0 has a serious issue:

docker/machine#4156
docker/machine#4166
docker/machine#4189
docker/machine#4197
docker/machine#4198

People cannot use the command to create a docker host. The issue has been fixed in `0.12.1`, and actually, the `0.12.2` has been released for a while. However, the version of `docker-machine` inside Docker for Mac is still `0.12.0`.

Please update the version of `docker-machine` to the latest version. Thanks.

**Comment by brandontamm** [comment]
I am not sure that this issue has been fixed in v0.12.2 - see my most recent tests with v0.12.2: https://github.com/docker/machine/issues/4189

**Comment by dougtoppin** [comment]
I am having exactly the same problem with docker-machine on my mac:

$ docker-machine --version
docker-machine version 0.12.1, build c8b17e8

$ docker-machine create --driver amazonec2 --amazonec2-vpc-id vpc-xxx --amazonec2-zone e aws-test
...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

If I run it manually using what is in ExecStart on the ec2 host like this:

# /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem

I see this:

Error starting daemon: error initializing graphdriver: driver not supported

If I run it again without including aufs it works:

/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem

**Comment by drujensen** [comment]
For those looking for a work-around:
```
brew install docker-machine
brew link --overwrite docker-machine
```

**Comment by twang2218** [comment]
Any updates on this issue? I'm currently using the workaround @drujensen mentioned above, however, Docker for Mac often overwrote the `/usr/local/bin/docker-machine` with the outdated version, which caused many trouble.

Could any one here in the Docker for Mac team update the `docker-machine` to the latest version? Big thanks.

**Comment by drujensen** [comment]
Even though the version has been updated to `v0.12.2 build 0371605` in docker for mac, docker-machine does not properly work and behaves similar to v0.12.0.  

However, the brew version `v0.12.2 build 0371605` is stable.

For example, when performing a `docker-machine ls` using the version with docker for mac, I get Timeout errors.  However, when I replace it using the brew docker-machine, there are no Timeout errors.

```
$docker-machine -v
docker-machine version 0.12.2, build 9371605

$ls -al /usr/local/bin/docker-machine 
lrwxr-xr-x  1 drujensen  staff  77 Sep 13 08:46 /usr/local/bin/docker-machine -> /Users/drujensen/Library/Group Containers/group.com.docker/bin/docker-machine

$docker-machine ls
NAME                     ACTIVE   DRIVER      STATE     URL                        SWARM   DOCKER        ERRORS
catalyst-elk                      amazonec2   Timeout                                                    
catalyst-prod-0.34.2-1            amazonec2   Timeout                                                    
catalyst-prod-0.34.2-2            amazonec2   Timeout                                                    
catalyst-qa-latest-1     -        amazonec2   Running   tcp://52.90.243.114:2376           v17.06.1-ce   
catalyst-sentry                   amazonec2   Timeout                                                    

$brew unlink docker-machine
Unlinking /usr/local/Cellar/docker-machine/0.12.2... 4 symlinks removed

$brew link --overwrite docker-machine
Linking /usr/local/Cellar/docker-machine/0.12.2... 5 symlinks created

$docker-machine -v
docker-machine version 0.12.2, build 9371605

$ls -al /usr/local/bin/docker-machine 
lrwxr-xr-x  1 drujensen  admin  50 Sep 13 08:33 /usr/local/bin/docker-machine -> ../Cellar/docker-machine/0.12.2/bin/docker-machine

$docker-machine ls
NAME                     ACTIVE   DRIVER      STATE     URL                        SWARM   DOCKER        ERRORS
catalyst-elk             -        amazonec2   Running   tcp://52.90.247.179:2376           v17.07.0-ce   
catalyst-prod-0.34.2-1   -        amazonec2   Running   tcp://34.207.77.121:2376           v17.07.0-ce   
catalyst-prod-0.34.2-2   -        amazonec2   Running   tcp://54.234.229.86:2376           v17.07.0-ce   
catalyst-qa-latest-1     -        amazonec2   Running   tcp://52.90.243.114:2376           v17.06.1-ce   
catalyst-sentry          -        amazonec2   Running   tcp://52.87.188.211:2376           v17.07.0-ce   
```

**Comment by twang2218** [comment]
@drujensen Good observation, I thought they should be identical binaries, obviously, it's not the case. 
But, I think it's a different issue, I'm going to close this issue as it's been updated to the 0.12.2 already. Could you open another issue to target the different behavior problem? Thanks.

**Comment by drujensen** [comment]
@twang2218 ok, opened a new issue #2055
