### ISSUE TITLE
D4M ramdomly attempted to restart and fails to launch

### ISSUE THREAD

**Issue by hitthecode** [docker/for-mac#1921]
### Expected behavior
D4M was working and then decided on its own to restart. 

### Actual behavior
Unable to conclude restart. Stuck in restart loop. Have to exit Docker and restart the app.

### Information

Diag ID: 6861C53B-75AD-4CF9-BAA8-AB486192D428

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/6861C53B-75AD-4CF9-BAA8-AB486192D428/20170731-151851.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
1. Use Docker 4 Mac
2. At some arbitrary point have it go crazy.

**Comment by guillaumerose** [comment]
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale` comment.
Stale issues will be closed after an additional 30d of inactivity.

Prevent issues from auto-closing with an `/lifecycle frozen` comment.

If this issue is safe to close now please do so.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle stale
