### ISSUE TITLE
ZSH completion files cannot be used out-of-the-box

### ISSUE THREAD

**Issue by OmeGak** [docker/for-mac#1948]
### Expected behavior

I believe I should be able to simply add the folder containing ZSH completions to my `FPATH` to get them working. That means, instead of them being named `docker.zsh-completion` they should be `_docker` and so on.

### Actual behavior

I need to either rename the completion files (which get replaced on upgrade), copy them (which get out of date), or create symlinks (which, IMHO, is an unnecessary overhead every time I install Docker in a new machine).

### Proposed solution

To prevent breaking compatibility with people that have found a workaround for this I propose this:

```console
$ tree /Applications/Docker.app/Contents/Resources/etc
/Applications/Docker.app/Contents/Resources/etc
├── _docker
├── _docker-compose
├── _docker-machine
├── docker-compose.bash-completion
├── docker-compose.zsh-completion -> _docker-compose
├── docker-machine.bash-completion
├── docker-machine.zsh-completion -> _docker-machine
├── docker.bash-completion
└── docker.zsh-completion -> _docker
```

Thoughts?

**Comment by OmeGak** [comment]
Is there any place I can submit a pull request for this?

**Comment by thaJeztah** [comment]
No this is part of the packaging scripts, and in a closed repository

**Comment by BretFisher** [comment]
Isn't part of the problem here @OmeGak that completion isn't out of the box for a shell like zsh or bash?  

For bash the [Docs step someone through setting up basic bash completion](https://docs.docker.com/docker-for-mac/#install-bash-completion) on macOS. Many Docker users are not that shell savvy and are using Terminal/bash for one of the first times in macOS with Docker. I watch it happen in every workshop I teach :) 

For zsh,  I do once per machine: 
```
ln -s /Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion /usr/local/share/zsh/site-functions/_docker
ln -s /Applications/Docker.app/Contents/Resources/etc/docker-machine.zsh-completion /usr/local/share/zsh/site-functions/_docker-machine
ln -s /Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion /usr/local/share/zsh/site-functions/_docker-compose
```

Would you be willing to [submit a PR for that Docs page](https://github.com/docker/docker.github.io/edit/master/docker-for-mac/index.md) below the bash section on basic zsh completion setup, I tried:

- change your default shell to `/bin/zsh`
- add `autoload -Uz compinit; compinit` to `~/.zshrc`
- run above symlinks
- restart zsh

**Comment by OmeGak** [comment]
Totally right, @BretFisher. As much as I would like an out-of-the-box solution, doing so would make ZSH autocompletion files a special case. I agree updating the docs with instructions to install completion in ZSH as well is probably the way to go about it. I'll be opening a PR tomorrow.

**Comment by thaJeztah** [comment]
Wonder if those symlinks can be setup automatically by Docker for Mac (would probably require a check if no existing file exists there)

@ebriney @gtardif @jeanlaurent wdyt?

**Comment by OmeGak** [comment]
Pinging again @ebriney @gtardif @jeanlaurent.

/remove-lifecycle stale

**Comment by robsonpeixoto** [comment]
```
$ tree /Applications/Docker.app/Contents/Resources/etc
/Applications/Docker.app/Contents/Resources/etc
├── docker-compose.bash-completion
├── docker-compose.zsh-completion
├── docker-machine.bash-completion
├── docker-machine.zsh-completion
├── docker.bash-completion
├── docker.fish-completion
├── docker.zsh-completion
└── zsh
    ├── _docker -> ../docker.zsh-completion
    ├── _docker-compose -> ../docker-compose.zsh-completion
    └── _docker-machine -> ../docker-machine.zsh-completion
```

And the use add `/Applications/Docker.app/Contents/Resources/etc/zsh` to the fpath, like:
```
if [[ -d /Applications/Docker.app/Contents/Resources/etc/zsh ]]; then
  fpath=(/Applications/Docker.app/Contents/Resources/etc/zsh $path)
fi
```

**Comment by MarioRicalde** [comment]
My approach to this was a little bit different. I don't like the idea of using `oh-my-zsh` since they copy and paste it into the repository. Instead, I went with [antibody](https://getantibody.github.io/). I found the individual zsh files on each repo and added those to my `fpath` instead.

Excerpte from [my antibody file](https://github.com/MarioRicalde/artisan/blob/master/zsh/bodies).

```
# docker - Completions
# 
# Usage:
#    docker <tab>
#    docker-compose <tab>
#    docker-machine <tab>
docker/cli path:contrib/completion/zsh kind:fpath
docker/compose path:contrib/completion/zsh kind:fpath
docker/machine path:contrib/completion/zsh kind:fpath
```

I'm not a fan of symlinking from `/Applications` to `homebrew/zsh`, mainly becuase it's a manual thing I'd have to do on every system I use. And using `curl` as proposed in other bits of the documentation is also not ideal, since it's YADTKTO (Yet Another Dependency To Keep Track Of)

Adding a subdirectory and renaming the files as proposed by @robsonpeixoto seems like the best of both worlds, adding to `fpath` is the best way in my opinion.

**Comment by ascarter** [comment]
For what it is worth, I have the following in my `.zshrc` and it seems to work:

```
# Docker
if [[ -d /Applications/Docker.app ]]; then
	for f in docker docker-compose docker-machine; do
		source /Applications/Docker.app/Contents/Resources/etc/${f}.zsh-completion
		compdef _${f} ${f}
		autoload -U _${f}
	done
fi
```

**Comment by ericbn** [comment]
Zsh completion files are meant to be autoloaded by compinit. See the Zsh [Completion System](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files) docs:

> The convention for autoloaded functions used in completion is that they start with an underscore; as already mentioned, the `fpath`/`FPATH` parameter must contain the directory in which they are stored. [...]
>
> When `compinit` is run, it searches all such files accessible via `fpath`/`FPATH` and reads the first line of each of them. This line should contain one of the tags described below. Files whose first line does not start with one of these tags are not considered to be part of the completion system and will not be treated specially.

The `.zsh-completion` is not standard. Not even sure where was it taken from.

The original scripts even have the proper names:
* https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
* https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose
* https://github.com/docker/machine/blob/master/contrib/completion/zsh/_docker-machine

Is there a reason to rename the files to `.zsh-completion` extensions, and to not have them in a separate directory?

**Comment by gmaghera** [comment]
> For what it is worth, I have the following in my `.zshrc` and it seems to work:
> 
> ```
> # Docker
> if [[ -d /Applications/Docker.app ]]; then
> 	for f in docker docker-compose docker-machine; do
> 		source /Applications/Docker.app/Contents/Resources/etc/${f}.zsh-completion
> 		compdef _${f} ${f}
> 		autoload -U _${f}
> 	done
> fi
> ```

This is the only solution that worked for me, and I've tried so many other suggestions...  Thank you!

**Comment by OmeGak** [comment]
I finally found an simpler solution for this:

```shell
brew install docker-completions
```
