### ISSUE TITLE
Cannot start Docker on mac

### ISSUE THREAD

**Issue by orellabac** [docker/for-mac#1972]
### Expected behavior
Docker should start
### Actual behavior
Each time I start docker It just keeps saying that docker is starting.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/0816FD8E-6704-45B7-9CB4-675E89CF4464/20170819-105606.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mauriciorojas/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install Docker for mac from lastest 
  2. Start Docker App

**Comment by biblesyme** [comment]
+1


#Expected behavior

Docker should start

#Actual behavior

Each time I start docker It just keeps saying that docker is starting.

#Information
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/97743DB1-4CC1-40C2-A347-211C1BE5CC31/20170829-152135.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

#Steps to reproduce the behavior

Install Docker for mac from lastest
Start Docker App
