### ISSUE TITLE
Can't complete Docker installation / Docker doesn't start

### ISSUE THREAD

**Issue by adamm-at-mathworks** [docker/for-mac#1975]
### Expected behavior

Docker should install and start

### Actual behavior

Installation fails, Docker won't start

### Information

  Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/3FB062A2-4228-403C-A575-28BBD1A1B99C/20170821-104440.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /home/amoskowi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /home/amoskowi/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /home/amoskowi/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/home/amoskowi/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /home/amoskowi/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /home/amoskowi/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /home/amoskowi/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. Download Docker.dmg
  2. Double-click Docker.dmg
  3. Drag Docker to Applications
  4. Double-click Docker

**Comment by adamm-at-mathworks** [comment]
This appears to be related to SIP (System Integrity Protection). There doesn't appear to be a way to install Docker for mac without disabling SIP.

**Comment by adamm-at-mathworks** [comment]
Looks like this is worse than I thought: I disabled SIP but got the same errors. Just for fun I manually created /usr/bin/local, chmod 0777, tried the install again: same error.

**Comment by djs55** [comment]
@adamm-at-mathworks thanks for your report.

Disabling SIP shouldn't be necessary. Unfortunately the path `/usr/bin/local` is a typo in a log message - it should be `/usr/local/bin`. I've made a PR to fix that in the UI.

The logs have (slightly redacted):
```
com.docker.vmnetd[1057]: File /usr/local/bin/docker is a symlink, unlinking
com.docker.vmnetd[1057]: Client supplied container path /home/<user>/Library/Containers/com.docker.docker/Data
com.docker.vmnetd[1057]: Failed to stat /home/<user>/Library/Containers/com.docker.docker/Data: 0x7fffa7ecc61e
Docker[1026]: [Docker.] Vmnetd: com.docker.vmnetd symlink: server reports failure
Docker[1026]: [Docker.] Terminator: Failed to install symlinks in /usr/bin/local
```
It's actually trying to create a symlink structure that looks as follows:
```
$ ls -l /usr/local/bin/docker
lrwxr-xr-x  1 <user>  staff  63 22 Aug 13:46 /usr/local/bin/docker -> /Users/<user>/Library/Group Containers/group.com.docker/bin/docker
$ ls -l "/Users/<user>/Library/Group Containers/group.com.docker/bin/docker"
lrwxr-xr-x  1 <user>  staff  54 22 Aug 13:46 /Users/<user>/Library/Group Containers/group.com.docker/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
```
Could you check whether the directories
- `~/Library/Group Containers/group.com.docker/`
- `~/Library/Containers/com.docker.docker/Data`
exist? If not, try creating them and restarting.

**Comment by adamm-at-mathworks** [comment]
/usr/local/bin/docker points to the right place although it's /home/<user>/... rather than /Users/<users/...

/home/<user>/Library/Group Containers/group.com.docker/bin/docker also points to the right place.

Is it possible something has /Users hard-coded rather than honoring $HOME?

Something else I noticed: /home/<user>/Library/Containers/com.docker.docker/Data contains the directory "com.docker.driver.amd64-linux. Linux? I'm lookin' right at the box and it's a Mac Mini. :-) Is it possible something else in the installer is going wrong?

**Comment by djs55** [comment]
Thanks for pointing out it's `/home` rather than `/Users` -- is that because you've got an external drive? We've had some problems with the results of `stat` calls before when dealing with non-root filesystems (e.g. [docker/for-mac#1457] which lead me to discover http://apple.stackexchange.com/questions/92226/mac-external-drive-file-rights)

To be completely honest, the way we create these symlinks is not ideal at all. In particular when it goes wrong -- as it has here -- it can be hard to work around. I'll dig a little deeper and see if I can simplify it or figure out a workaround.

The `com.docker.driver.amd64-linux` directory refers to the little Linux helper VM. When you `docker run <foo>` on the Mac it downloads the Linux binaries and runs them transparently in the VM for you. We added `amd64-linux` to the name in case we wanted to support other VM types in future. This may have been a premature generalisation :-)

**Comment by adamm-at-mathworks** [comment]
We run with NFS-mounted home directories, and there's no way around that. These home directories are shared between Mac and Linux systems and I don't know if I have permission to change things like ACLs on them (or if ACLs are even supported).

I might argue that software like Docker for Mac should be installed on a disk that's local to the Mac, and even then maybe not in a user's home directory. Is this something that can be changed or fixed?

**Comment by djs55** [comment]
The symlink problem which is blocking installation should be fixable.

The Linux VM which runs the binaries has a writable disk with a default path of `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`. If this path is in a shared filesystem then I think it should probably be changed via the Whale menu -> Preferences -> Advanced to refer to a local disk (if possible) for 2 reasons:

1. there's quite a lot of "temporary" file I/O: create directory, unpack tar file, remove directory again, which will all be slow over NFS
2. if Docker for Mac was launched on 2 computers at once sharing the same file then the file would be corrupted

It doesn't matter where the `Docker` application itself is installed -- the binaries are read-only and can be kept anywhere. It's really only the `Docker.qcow2` that ought to be stored locally.

**Comment by djs55** [comment]
@adamm-at-mathworks I have an experimental build if you'd like to try it. It's a build from the `master` branch and hasn't been officially released yet (although a similar build will be on the `edge` channel soon).

The URL is: https://download-stage.docker.com/mac/master/18977/Docker.dmg

It reports a version of
```
Version 17.07.0-ce-rc4-mac25 (18977)
Channel: master
95df7d0a3e
```

The build contains
- the fix for the log message
- a workaround for the `stat` failure that *hopefully* will allow the installation to complete

If you get a chance to try it, let me know how it goes. If it still doesn't work, please upload another diagnostic report and I'll take a look at it.

Thanks again for your report!

**Comment by adamm-at-mathworks** [comment]
David, thanks for the updated image but switching to a local home directory seems to have solved the problem. It turns out that "Mac primary" users get local $HOME for exactly this reason.

**Comment by Miladinho** [comment]
Wait this sucks, so there is not fix for this?!?!?!

**Comment by LexBel-co** [comment]
After a year a get fatal Error: cannot install symlinks in /usr/local/bin (stage 4), and nothing here solves the problem

**Comment by djs55** [comment]
@LexBel-co (and anyone else suffering from installation / starting issues): could you reproduce the problem, upload a set of diagnostics (Note if the UI for this doesn't work then run `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload`) and open fresh issues describing what happened and including the diagnostic id? Thanks!

**Comment by LexBel-co** [comment]
@djs55 this is the diagnostic ID: 047BAFAA-11A7-478D-BF0E-35A81D24AEEE/20180815164853

The error occurs with a new installation of Docker for Mac (macOS High Sierra version 10.13.5 (17F77))

**Comment by ncsutmf** [comment]
@djs55 also been having this issue off and on for a while, error comes up when I first login and Docker starts up.  Since the first time I saw this error I have updated both the OS and Docker, but I was still running High Sierra when it started happening.

daignostic ID:  81F4C4DE-D0E1-4D05-9686-8E22CA54846A/20180831134222

Currently running macOS High Sierra version 1.13.6 (17G65) and Docker 18.06.1-ce-mac73 (26764)

I'm usually able to launch Docker after the error pops up without any issues.

**Comment by benjiwheeler** [comment]
Docker installed totally fine on my High Sierra 10.13.5, but since upgrading to 10.13.6, I regularly see this error after Docker runs for 48 hours or so. It's there when I walk in in the morning -- it happens, apparently, during a time when I'm making no changes at all to what's running in Docker, or to the files or directories or permissions in my filesystem. 

(There might be a few keepalives pinging node on one of my Docker instances, but nothing that should be mutating the state of the whole thing significantly.)

![screen shot 2018-09-14 at 9 06 52 am](https://user-images.githubusercontent.com/3431616/45553615-693f4680-b802-11e8-920f-c19dc6e745ab.png)

Diagnostic ID: A9BC3786-3D1E-46B0-981A-76BFD239E8B2/20180914134209

Running Mac High Sierra 10.13.6, Docker Version 18.06.1-ce-mac73 (26764, b0f14f1dac)
