### ISSUE TITLE
Docker Crashing on MacOs

### ISSUE THREAD

**Issue by malviyarahul2001** [docker/for-mac#2041]
### Expected behavior
Not to crash.

### Actual behavior
Crashing everyday.

### Information

Diagnostic ID : 0DCA1DBD-B9D0-40DF-B3CA-DD36BAF22D49
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A361)
logs: /tmp/0DCA1DBD-B9D0-40DF-B3CA-DD36BAF22D49/20170908-095440.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rahul/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rahul/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rahul/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rahul/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

Happens radomly.

**Comment by shaunthomas999** [comment]
Some pointers:

- I had the same issue as described above when I had symbolic links inside `~/.docker/certs.d/' folder. When I removed the symbolic links docker started fine.
- Even without the symbolic link, I had the error once. But when I exited and started docker again, it worked fine.

Docker version info:
- Version:      17.06.2-ce
- API version:  1.30 (minimum version 1.12)
- Git commit:   cec0b72
- Built:        Tue Sep  5 19:59:19 2017
- Experimental: false

**Comment by scranen** [comment]
I'm also seeing crashes since the update to 17.06.2-ce-mac27 (on macOS 10.12.6 build 16G29). In particular it seems to crash consistently when I spin up all my containers at once, but I can sometimes get it to run stable for a while if I spin my containers up one by one with long pauses in between.

I do not have a `~/.docker/certs.d` folder, so that seems unrelated in my case.

**Comment by joshbenner** [comment]
I started seeing this after updating to 17.06.2-ce-mac27 (19124) on macOS 10.12.6.

I encounter this issue while doing seemingly random things on multiple containers simultaneously. Sometimes it's installing packages, sometimes it's writing files. It is most pronounced when testing configuration management against multiple containers at the same time.

**Comment by joshbenner** [comment]
More info: I was running tests of Ansible roles using Docker containers running systemd. This had the effect of systemd inside the container spawning `getty` instances. This seemed to be causing some sort of recursion issue that would lock up the kernel, causing a crash of the docker host.

My issue seems to have been fixed by preventing the `getty` service from starting inside the container.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac, and open a new issue if needed.
