### ISSUE TITLE
Docker 17-09 crashes on High Sierra

### ISSUE THREAD

**Issue by BryanHunt** [docker/for-mac#2084]
Docker 17.09-rc2 and now rc3 seems to crash daily on High Sierra.  The error message first displayed is something about linuxkit exited.  I'll try to get the full error message next time.  I've uploaded several diagnostics.  The latest is `CB73C591-AD61-4C07-869D-D15C466C678D`.

I have no containers running.  My current guess is that it's crashing when my iMac wakes from sleep.

I'm a build behind of the High Sierra GM.  I'm on 17A360a. The App Store is not giving me the option of updating to the GM build for some reason.

**Comment by djs55** [comment]
You could be right about wake from sleep -- this might trigger a bug in the macOS `hypervisor.framework`.

However there's an interesting error in the logs which might be causing a problem:
```
 Failed to commit transaction: p9p.MessageRerror{Ename:"(Failure \"Value: not a valid compressed object\")"}
```
Just in case the configuration database has become corrupt, could you try shutting down the app and then running:
```
mv ~/Library/Containers/com.docker.docker/Data/database ~/Library/Containers/com.docker.docker/Data/database.backup
```
This will reset the memory, CPU settings etc.

**Comment by BryanHunt** [comment]
I was able to update to High Sierra GM today and I also did:

`mv ~/Library/Containers/com.docker.docker/Data/database ~/Library/Containers/com.docker.docker/Data/database.backup`

It crashed again just now (might have been waking from sleep).  The diagnostic id is `CB73C591-AD61-4C07-869D-D15C466C678D`

**Comment by jrreid** [comment]
Seeing a similar error myself (diagnostic id 78E1D36C-6305-4A99-AB6A-1CCF7026AFD8) on the GM.

**Comment by mrfelton** [comment]
Just updated to High Sierra and can't start docker now.

> com.docker.osx.hyperkit.linux failed to start Exit code 1

Diagnostic ID: AE10198A-5735-42DA-A0CF-19643B78C09B

**Comment by qrpike** [comment]
"com.docker.osx.hyperkit.linux failed to start. Exit code 1" Getting this after upgrading to High Sierra

**Comment by michaelstoner** [comment]
@djs55 thanks, that solved it for me, so at least I can recover without having to reinstall and rebuild everything.

**Comment by Blizzke** [comment]
Same issue here ever since I upgraded to high sierra and the mac awakes from sleep. Have been using docker forever and never saw that particular crash before the upgrade.

**Comment by Blizzke** [comment]
So far on my iMac it was after waking up with the "failed to start" message, but after restarting docker it works.
On my macbook it just crashes every couple minutes, even a reset to factory settings hasn't solved anything. This messes with my productivity big time, hopefully the problem can be solved really quickly.

**Comment by djs55** [comment]
Could you try updating to the most recent edge build: `17.09.0-ce-mac31` https://download.docker.com/mac/edge/19478/Docker.dmg -- it's got a fix for a High Sierra "failed to start" issue in it. If you still see bad behaviour, could you upload a fresh set of diagnostics? Thanks!

**Comment by Blizzke** [comment]
Willdo, thanks for the quick reply.

**Comment by Blizzke** [comment]
Installed that version on my MacBook (not at home atm) and that one seems to crash even during a pull ("unexpected EOF"). Diagnostic ID 2A283947-81ED-4B67-9298-A824CE2472F6

**Comment by djs55** [comment]
@Blizzke thanks for the diagnostics. Unfortunately the logs show no obvious reason why the hypervisor process shutdown :( It might be that some logs went missing somewhere. If it happens again, here's a tool which helps get more debug output:

[debug.zip](https://github.com/docker/for-mac/files/1344839/debug.zip)

If you want to try it, first exit Docker from the whale menu (if it hasn't crashed already)

Check the `sha1sum`:
```
$ sha1sum debug.zip
33514d65c6dd1a2740d809d4f3a226bfcbfdfc00  debug.zip
```

Unzip the tool
```
$ unzip debug.zip
Archive:  debug.zip
  inflating: com.docker.shell
```

Finally run it, pointing it at your `Docker.app` to get a prompt. At the prompt type "start" to start all the services with logging to the terminal:
```
$ ./com.docker.shell -bundle /Applications/Docker.app
INFO[0000] Acquired task manager lock
INFO[0000] Maximum number of file descriptors is 10240
INFO[0000] Pidfile com.docker.hyperkit references Pid 5427 but expected path /Applications/Docker.app/Contents/Resources/bin/hyperkit <> actual path '': assuming pid re-use 
stopped 🐳 > start
<logs of debug output will follow>
```
The extra debug output will hopefully capture the root cause of the crash.

**Comment by Blizzke** [comment]
Since I rebooted after installing the edge version it hasn't crashed anymore. It has even survived a 2 hour sleep and still works. I'll check my iMac as soon as possible against that version as well and report back.

**Comment by theneverstill** [comment]
Same issue experienced here (High Sierra), however not when sleeping - it occurs after several hours of running fine (no containers open). I tried @djs55's solution, but that made it crash immediate on start. Restoring the old database at least returned it back to the every-few-hours-crash situation. Fingers crossed for the edge version above.

**Comment by Blizzke** [comment]
On my iMac (where docker was crashing after wakeup) the edge version has just survived about 20 minutes sleep. I'll report once more tomorrow to confirm if a long sleep is ok as well.

**Comment by balboah** [comment]
For me it crashed on start (not because of running while in sleep). 3rd time it showed:
![screen shot 2017-10-03 at 10 29 05](https://user-images.githubusercontent.com/294690/31116311-ebf5496e-a825-11e7-966a-91a1fe5770a4.png)

After "factory reset" it seem to once again be able to start up.

**Comment by wernergillmer** [comment]
Is there any solution yet?

**Comment by BryanHunt** [comment]
@wernergillmer I've been running Version 17.09.0-ce-mac34 (19605) on High Sierra with no crashes.

**Comment by jack-lewin** [comment]
Hi - I'm still having trouble with this, on the latest release for both stable & edge. Tried installing an older version, which didn't work either. Had no issues before upgrading to High Sierra, but I'm now unable to use Docker locally. It would be great to see this fixed in the next release.

@djs55 if it's any help, here's the output I received from the debug tool you provided. Let me know if I can help with any more info!

<details>
<summary>Additional debug output</summary>
<pre>
OSTML0244761:Downloads username$ ./com.docker.shell -bundle /Applications/Docker.app
INFO[0000] Acquired task manager lock                   
INFO[0000] Maximum number of file descriptors is 10240  
stopped 🐳 > start
INFO[0014] Starting tasks                               
INFO[0014] Starting com.docker.db, com.docker.osxfs, vpnkit, com.docker.driver.amd64-linux 
INFO[0014] Start com.docker.db (pid 14154)              
Starting com.docker.db %%VERSION%% ...
2017/12/07 16:20:41 Dialling unix /Users/username/Library/Containers/com.docker.docker/Data/s40
com.docker.db: [INFO] accepted a new connection on fd://3
com.docker.db: [INFO] Using protocol TwoThousand msize 16384
com.docker.osxfs: [INFO] Logging to stdout (stdout:true DEBUG:false)
2017/12/07 16:20:41 Snapshot has changed
2017/12/07 16:20:41 Snapshot has changed
2017/12/07 16:20:41 Snapshot has changed
2017/12/07 16:20:41 Updating default value at com.docker.driver.amd64-linux/schema-version to 1
2017/12/07 16:20:41 Updating default value at com.docker.driver.amd64-linux/mounts to /Users:/Users
/Volumes:/Volumes
/tmp:/tmp
/private:/private
2017/12/07 16:20:41 I don't know how to flush: leaking 125
2017/12/07 16:20:41 I don't know how to flush: leaking 127
2017/12/07 16:20:41 I don't know how to flush: leaking 126
INFO[0014] Start com.docker.osxfs (pid 14155)           
2017/12/07 16:20:41 fatal error reading msg: read unix ->/Users/username/Library/Containers/com.docker.docker/Data/s40: use of closed network connection
2017/12/07 16:20:41 exited read loop
2017/12/07 16:20:41 exited handle loop
INFO[0014] Start vpnkit (pid 14156)                     
SOMAXCONN = 128
INFO[0014] Start com.docker.driver.amd64-linux (pid 14157) 
com.docker.vpnkit: [INFO] Logging to stdout (stdout:true DEBUG:false)
com.docker.vpnkit: [INFO] Setting handler to ignore all SIGPIPE signals
com.docker.vpnkit: [INFO] vpnkit version %VERSION% from %VCS_COMMIT_ID%
com.docker.vpnkit: [INFO] System SOMAXCONN is 128
com.docker.vpnkit: [INFO] Will use a listen backlog of 32
com.docker.vpnkit: [INFO] starting port forwarding server on port_control_url:fd:4 vsock_path:/Users/username/Library/Containers/com.docker.docker/Data/connect
com.docker.vpnkit: [INFO] DNS names  will map to local IP 192.168.65.1
com.docker.vpnkit: [INFO] 2 upstream DNS servers are configured
com.docker.vpnkit: [INFO] attempting to reconnect to database
com.docker.db: [INFO] accepted a new connection on fd://3
com.docker.db: [INFO] Using protocol TwoThousandU msize 8215
com.docker.vpnkit: [INFO] hosts file has bindings for localhost broadcasthost localhost wordpress.local
com.docker.vpnkit: [INFO] Add(2): DNS configuration changed to: use upstream DNS servers nameserver 172.20.220.26#53
order 0
nameserver 172.20.220.25#53
order 0
nameserver 10.5.212.21#53
order 0
com.docker.vpnkit: [INFO] reconnected transport layer
com.docker.vpnkit: [INFO] updating connection limit to 2000
com.docker.vpnkit: [INFO] allowing binds to any IP addresses
com.docker.vpnkit: [INFO] updating resolvers to use upstream DNS servers 
com.docker.vpnkit: [WARNING] No secure random number generator available
com.docker.vpnkit: [INFO] Add(3): DNS configuration changed to: use upstream DNS servers 
com.docker.vpnkit: [INFO] DNS names docker.for.mac.localhost will map to local IP 192.168.65.1
com.docker.vpnkit: [INFO] 0 upstream DNS servers are configured
com.docker.vpnkit: [INFO] updating resolvers to use host resolver
com.docker.vpnkit: [WARNING] No secure random number generator available
com.docker.vpnkit: [INFO] Remove(3): DNS configuration changed to: use upstream DNS servers nameserver 172.20.220.26#53
order 0
nameserver 172.20.220.25#53
order 0
nameserver 10.5.212.21#53
order 0
com.docker.vpnkit: [INFO] Add(3): DNS configuration changed to: use host resolver
com.docker.vpnkit: [INFO] DNS names docker.for.mac.localhost will map to local IP 192.168.65.1
com.docker.vpnkit: [INFO] Will use the host's DNS resolver
com.docker.vpnkit: [INFO] Disabling transparent HTTP redirection
com.docker.vpnkit: [INFO] Creating slirp server peer_ip:192.168.65.2 local_ip:192.168.65.1 domain_search: mtu:1500 port_max_idle_time:300
running 🐳 > INFO[0000] Acquired hypervisor lock                     
2017/12/07 16:20:42 Dialling unix /Users/username/Library/Containers/com.docker.docker/Data/s40
com.docker.db: [INFO] accepted a new connection on fd://3
com.docker.db: [INFO] Using protocol TwoThousand msize 16384
INFO[0000] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
INFO[0000] No need to perform database migration: defaults branch already exists 
2017/12/07 16:20:42 Getting proxy servers
Retrieved proxy settings:
 - http_proxy=<none>
 - https_proxy=<none>
 - no_proxy=<none>
2017/12/07 16:20:42 Snapshot has changed
2017/12/07 16:20:42 Snapshot has changed
2017/12/07 16:20:42 Snapshot has changed
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/schema-version to 1
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/hypervisor to native
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/etc/sysctl.conf to 
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/etc/docker/daemon.json to {}
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/proxy-verbose to false
INFO[0000] On-sleep: no not freeze                      
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/on-sleep to no not freeze
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/filesystem to osxfs
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/network-2 to vpnkit
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/slirp/host
2017/12/07 16:20:42 Setting value in store: []string{"com.docker.driver.amd64-linux", "slirp", "host"}=(*string)(0xc420251240)
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/slirp/docker
2017/12/07 16:20:42 Setting value in store: []string{"com.docker.driver.amd64-linux", "slirp", "docker"}=(*string)(0xc420231680)
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/slirp/highest-ip
2017/12/07 16:20:42 Setting value in store: []string{"com.docker.driver.amd64-linux", "slirp", "highest-ip"}=(*string)(0xc42004c620)
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/expose-docker-socket to false
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/proxy/http
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/proxy/https
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/proxy/exclude
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/native/boot-protocol to direct
INFO[0000] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/native/uefi-boot-disk to /Users/username/UefiBoot.qcow2
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/on-flush to os
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/trim to true
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/compact-after to 262144
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/keep-erased to 262144
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/runtime-asserts to false
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/disk/stats to 
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/slirp/max-connections to 2000
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/slirp/mtu to 1500
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/slirp/resolver to host
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/slirp/enable-http-intercept to false
2017/12/07 16:20:42 Updating default value at com.docker.driver.amd64-linux/slirp/port-max-idle-time to 300
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/slirp/dns
2017/12/07 16:20:42 Removing default value at com.docker.driver.amd64-linux/slirp/domain
INFO[0001] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
INFO[0001] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
2017/12/07 16:20:43 Performing schema upgrade to version 9
2017/12/07 16:20:43 Snapshot has changed
INFO[0002] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
2017/12/07 16:20:44 Removing default value at com.docker.driver.amd64-linux/proxy/mode
INFO[0002] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
2017/12/07 16:20:44 Setting value in store: []string{"com.docker.driver.amd64-linux", "proxy", "mode"}=(*string)(0xc42041b590)
2017/12/07 16:20:44 Snapshot has changed
2017/12/07 16:20:44 Removing default value at com.docker.driver.amd64-linux/proxy-override/http
2017/12/07 16:20:44 Setting value in store: []string{"com.docker.driver.amd64-linux", "proxy-override", "http"}=(*string)(0xc420488b90)
2017/12/07 16:20:44 Removing default value at com.docker.driver.amd64-linux/proxy-override/https
2017/12/07 16:20:44 Setting value in store: []string{"com.docker.driver.amd64-linux", "proxy-override", "https"}=(*string)(0xc420016a00)
2017/12/07 16:20:44 Removing default value at com.docker.driver.amd64-linux/proxy-override/exclude
2017/12/07 16:20:44 Setting value in store: []string{"com.docker.driver.amd64-linux", "proxy-override", "exclude"}=(*string)(0xc4202ba510)
INFO[0002] hypervisor: native                           
INFO[0002] TRIM is enabled; recycling thread will keep 262144 sectors free and will compact after 262144 more sectors are free 
INFO[0002] filesystem: osxfs                            
INFO[0002] network: vpnkit                              
INFO[0003] Docker is not responding: Get http://./info: dial unix /Users/username/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: no such file or directory: waiting 0.5s 
2017/12/07 16:20:45 Snapshot has changed
INFO[0003] Syslog socket is /Users/username/Library/Containers/com.docker.docker/Data/00000002.00000202 
INFO[0003] Logfile is /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/syslog 
INFO[0003] Cannot remove hyperkit pid fileremove /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid: permission denied 
INFO[0003] BootProtocol: direct; UefiBootDisk: /Users/username/UefiBoot.qcow2 
FATA[0003] Error removing /Users/username/Library/Containers/com.docker.docker/Data/00000002.00000202: remove /Users/username/Library/Containers/com.docker.docker/Data/00000002.00000202: permission denied 
INFO[0017] Reap com.docker.driver.amd64-linux (pid 14157): exit status 1 
</pre>
</details>

**Comment by djs55** [comment]
@jack-lewin thanks for the update. I'm interested in these log lines:
```
...
INFO[0003] Cannot remove hyperkit pid fileremove /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid: permission denied 
...
FATA[0003] Error removing /Users/username/Library/Containers/com.docker.docker/Data/00000002.00000202: remove /Users/username/Library/Containers/com.docker.docker/Data/00000002.00000202: permission denied 
INFO[0017] Reap com.docker.driver.amd64-linux (pid 14157): exit status 1 
```
-- in particular the `permission denied` errors in `/Users/username/Library/Containers/com.docker.docker/Data`

Could you take a look in that directory (and the `com.docker.driver.amd64-linux` subdirectory) and see if your user can create and remove files there? Is it mounted on an external volume or NFS share?

**Comment by jack-lewin** [comment]
@djs55 I can create/remove new files/directories in `~/Library/Containers/com.docker.docker/Data` and the `com.docker.driver.amd64-linux` subdirectory (without sudo).

I can't remove the `com.docker.driver.amd64-linux` subdirectory, or either of the items in it, even with sudo (`hypervisor.pid` and `mac.0.tmp`). It's just a normal local directory.

**Comment by djs55** [comment]
That's strange! Try moving the `com.docker.driver.amd64-linux` directory to something like `com.docker.driver.amd64-linux.backup` and restart the app -- it should create a fresh directory.

**Comment by jschalz** [comment]
I was having the error @qrpike mentioned on Sept 27th, solution was uninstalling docker, rebooting, and reinstalling docker (which isn't ideal but worked).

**Comment by jack-lewin** [comment]
I renamed `com.docker.driver.amd64-linux` but got an error about the `~/Library/Containers/com.docker.docker` directory. I renamed that & reinstalled Docker, now it seems to work fine :tada:

Thanks a lot for your help @djs55 - hopefully this is useful for others reading too.
