### ISSUE TITLE
Docker ps not working - high cpu usage for "hyperkit" process

### ISSUE THREAD

**Issue by dennisjansen** [docker/for-mac#2144]
### Actual behavior
Docker ps not working
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. run container microsoft/mssql-server-linux
  2. close mac book - hybernate state
  3. restart mac os - docker hangs

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.  If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
