### ISSUE TITLE
docker login doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by NeilMenne** [docker/for-mac#2211]
### Expected behavior
docker login completes

### Actual behavior
error getting credentials - err: signal: segmentation fault, out: ``

### Information

Diagnostic ID: CBB68278-7E6B-47E8-A48D-D265B0DB1052

### Steps to reproduce the behavior

  1. upgrade to macos high sierra
  2. docker login (I am attempting to setup docker credentials for AWS like `eval "$(aws ecr get-login --region us-east-1| sed -e 's/-e none//g')"`)

**Comment by guillaumerose** [comment]
Does it use custom client certificates (located in ~/.docker/certs.d) ?

**Comment by mowreyw** [comment]
I am seeing the same issue. Login using `eval $(aws ecr get-login)` has been broken since moving to macOS High Sierra. A login command with temporary password is generated, but fails with exit status 1 exit status 1, out: `The user name or passphrase you entered is not correct`

**Comment by FrenchBen** [comment]
The issue here is the lack of update from the AWS CLI, more than likely due to the fact that they run an older version of Docker in their offering.
This has been documented as a deprecated command for a while (`1.11.0`) and removed in `17.06`, see:
https://docs.docker.com/engine/deprecated/#-e-and---email-flags-on-docker-login

There have been a couple of reports of it here:
https://github.com/aws/aws-cli/issues/2753

The solution is to add `--no-include-email` to your eval. 
`eval $(aws ecr get-login --region us-east-1 --no-include-email)

**Comment by NeilMenne** [comment]
@FrenchBen, that fixes it for me. Thanks for finding that information; I spent a bit of time looking for relevant information to no avail.

Feel free to close.

**Comment by mowreyw** [comment]
My issue was something different, as I was already using `--no-include-email`. I found a line in `~/.docker/config.json` that identified `docker-credential-osxkeychain` as the credentials store. Deleting this line allowed me to login using `$(aws ecr get-login --region us-east-2 --no-include-email)` once again.

**Comment by NeilMenne** [comment]
Sounds like we both made it out alive

**Comment by FrenchBen** [comment]
Closing as resolved for both parties

**Comment by jimmytuc** [comment]
It's work! Thanks
