### ISSUE TITLE
Adding a shared path through command line

### ISSUE THREAD

**Issue by haniamr** [docker/for-mac#2214]
### Question
Is there a way to add a shared path in **Docker for Mac** through the command line? (i.e. command or an API)

**Comment by martinm82** [comment]
In 17.09.0 there is a new configuration file called settings.json available. There are already lot of settings in this file but the file sharing part is missing there.
Any idea whether this will be added soon? This would be already a huge improvement for us where we need to provision automatically couple of mac nodes.

**Comment by haniamr** [comment]
@nchazlett any feedback on this? Thanks!

**Comment by carlfischer1** [comment]
The shared folders list displayed in the GUI can also be edited in ~/Library/Group Containers/group.com.docker/settings.json.

If the user has already modified shared folders, the "filesharingDirectories" array will already exist in settings.json, you can just add the path in the json array. If not modified, the array is not present in settings.json, but you can add it with your path in addition to the default ones : 
```
"filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp", 
    "/usr/local/share/dotnet/sdk/NuGetFallbackFolder"
  ]
```
Eventually the app needs restarting so that folders are visible in the VM.

Credit: @gtardif
