### ISSUE TITLE
can I downgrade? I only use the direct connect, and this setting disappear. when I change the proxy setting it will restart every time

### ISSUE THREAD

**Issue by GanLuo96214** [docker/for-mac#2235]
can I downgrade? I only use the direct connect, and this setting disappear. when I change the proxy setting it will restart every time.

**Comment by GanLuo96214** [comment]
I'm using 17.09.0-ce-mac35 (19611).

**Comment by guillaumerose** [comment]
Every time you change the proxy settings, the VM is restarted. We need to do that to propagate new settings. Unfortunately, we don't have plan (yet) for changing that.

**Comment by djs55** [comment]
@GanLuo96214 there is an experimental feature which might help -- it's enabled by:
```
cd ~/Library/Containers/com.docker.docker/Data/database/
git checkout master
mkdir -p com.docker.driver.amd64-linux/slirp/
echo true > com.docker.driver.amd64-linux/slirp/enable-http-intercept
git add com.docker.driver.amd64-linux/slirp/enable-http-intercept 
git commit -s -m 'enable http intercept'
```
and restarting the app. It works by intercepting the outgoing HTTP/HTTPS in a transparent proxy and forwarding it to the system proxy. The advantage is that the VM doesn't need to be rebooted when the upstream proxy changes, since no changes in the VM are needed.

Let me know if this works (or not) for you.

**Comment by GanLuo96214** [comment]
jump to this : https://github.com/docker/for-mac/issues/2230
