### ISSUE TITLE
Timeout connection after near 100 requests to MongoDB

### ISSUE THREAD

**Issue by vlad0337187** [docker/for-mac#2384]
**(in progress, I saved it not to lose information)**

### Expected behavior
Some connections would be finished with "ECONNRESET", some - with success. Just like when running this on host.

### Actual behavior
When I send 1000 requests to MongoDB on host machine at the same time - some of them (57) were finished with error "ECONNRESET", other 947 - finished with success.

When I send even 100 requests from host machine (MongoDB node driver), after some amount of requests, only 649 were finished with success, near 164 were finished with "ECONNRESET", all other were just waiting and after some time it begins to slowly display: 
"connection 960 to mongo:27017 timed out",
and so on for other connections.

After this "timeout" messages started appearing, no one other connection to Mongo didn't finished neither with "ECONNRESET", nor with success.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu: https://pastebin.com/dLTuHv5T
  - A reproducible case if this is a bug, Dockerfiles FTW
      - files:
          - docker-compose.yml: https://pastebin.com/Uf20bxcK
          - .js file, which asks MongoDB: https://pastebin.com/17BgNDqL
  - logs:
      - output of .js script: https://pastebin.com/RDkMtt1p
      - output of Mongo in container: https://pastebin.com/Mkb7rgTd (no errors)
 

### Steps to reproduce the behavior

 - I run MongoDB (zookeeper, kafka, kafka2, kafka3, rest, connect, uitopics, uiconnect are always runned for other purposes).
 - I create some collection in Mongo
 - I add to /etc/hosts such record: "127.0.0.1    mongo" to avoid problems with routing
 - increased amount of available connections for docker in such way: https://github.com/docker/for-mac/issues/1009
 - increased amount of open files system-wide by this way: https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard
 - I launch .js script from host machine
 - Capture the output.

**Comment by YRM64** [comment]
It's critical to comprehend MongoDB Client Timeout Options.  First, "connection timeout is the number of milliseconds the driver will wait before a new connection attempt is aborted".  Mongo driver uses 30s as a default value of the server selection timeout; this time element can be manipulated.  However, Mongo Java and Nodejs driver have a default socket timeout of 0s (essentially no timeout).  Ruby on the otherhand has a 5s socket timeout.  You don't want to manipulate these timeout sessions because the various operations are using that specific timeframe to operate.

Also, keep in mind that the MongoClient timeout options vary depending upon the specific version your system is utilizing.  Variances also exist amongst the different languages of the Mongo drivers.  You must visit https://scalegrid.io/blog/understanding-mongo-client-timeout-options to understand your default timeout choices.

**Comment by deiga** [comment]
@vlad1777d I'm encountering a similar issue but it seems unrelated to Docker For Mac as I have this same symptom also on Linux hosts.

It' super frustrating that mongodb connections suddenly just drop off without any actual issue and then don't come back at all without downing and creating a new container
