### ISSUE TITLE
Slow disk performance with `raw` format on 17.12.0-ce-mac46

### ISSUE THREAD

**Issue by miholeus** [docker/for-mac#2395]
### Expected behavior
It is said that we have new "raw" format that should improve performance. But I have the same poor performance as in `qcow2`.
### Actual behavior
I have APFS on my Mac. I reseted my settings to default on docker. I have `Docker.raw` file. And the speed did not change, it is the same as in `qcow2` format. 
```
root@28718ae8cc37:/app# time dd if=/dev/zero of=file.img bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 14.4795 s, 7.1 MB/s

real    0m14.484s
user    0m0.180s
sys    0m1.700s
```

### Steps to reproduce the behavior

  1. 
```
docker run --rm -it -v `pwd`:`pwd` -w `pwd` alpine /bin/sh
```
  2. In container
```
time dd if=/dev/zero of=file.img bs=1024 count=100000
```
### Information

Docker Community Edition
Version 17.12.0-ce-mac46 (21698)
Channel: stable
0ac7325e4f

**Comment by djs55** [comment]
The raw format should improve the performance of the in-container filesystem, where the data is stored within the `Docker.raw` file. I believe maximum write throughput is increased and the cost in CPU cycles per byte written is decreased.

Unfortunately the shared volume (`-v`) doesn't use `Docker.raw` or `Docker.qcow2`. Instead individual VFS operations are remoted from the VM to the host. I'm currently working on making this faster and hopefully there should be some good performance increases in the next few releases.

Thanks for your report. Since the `Docker.raw` is working as expected I'll close this ticket for now, but hopefully improvements to the volume sharing cases will be available soon. Thanks for your patience in the meantime!

**Comment by miholeus** [comment]
@djs55 thanks for clarification. Will wait for next releases!
