### ISSUE TITLE
Linuxkit has a readonly filesystem

### ISSUE THREAD

**Issue by rabidscorpio** [docker/for-mac#2419]
### Expected behavior
The https://github.com/IFSight/d4m-nfs project sets up nfs in order to share a filesystem with a docker container. Running a script installs nfs and sets up the nfs shares and the performance is much better than any of the current solutions being offered.

### Actual behavior
https://github.com/IFSight/d4m-nfs/issues/55 - linuxkit has a readonly root filesystem so there's no way to install nfs and then enable it.

Why was this change made? And how can NFS be enabled so that those of us who actually care about filesystem performance can use current versions docker for mac with nfs? Thanks!

**Comment by djs55** [comment]
Thanks for your report.

For the past couple of edge releases and now in the stable release, Docker for Mac uses a VM based on [linuxkit](https://github.com/linuxkit/linuxkit). The root filesystem runs `containerd` and all system services (including the `docker` engine itself) are built from docker images and run inside namespaces. The root filesystem contains just enough to bootstrap the rest.

I don't know how the `d4m-nfs` is designed but the root filesystem being read-only is probably not the main problem -- since the `docker` engine runs inside the `docker-ce` container it has its own root filesystem (albeit with some directories shared, see below)

Try logging into the VM: (I recommend this instead of using `screen` on the TTY)
```
$ docker run -it --privileged --pid=host justincormack/nsenter1
```
Then observe the `osxfs` mounts are not in the root filesystem:
```
/ # mount | grep osxfs
/ # 
```
You can list the running `containerd` tasks (containers):
```
/ # ctr t ls
TASK                    PID     STATUS    
kubelet                 1030    RUNNING
ntpd                    1085    RUNNING
vsudd                   1501    RUNNING
host-timesync-daemon    984     RUNNING
diagnose                861     RUNNING
docker-ce               902     RUNNING
trim-after-delete       1197    RUNNING
vpnkit-forwarder        1381    RUNNING
acpid                   826     RUNNING
```
You can get a shell in the `docker-ce` container with:
```
/ # ctr t exec -t -exec-id foo docker-ce sh
/ # mount | grep osxfs
osxfs on /tmp type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
osxfs on /private type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
osxfs on /Volumes type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
osxfs on /Users type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
Note that some directories are writable and shared with the root filesystem, for example `/var`. If you `touch /var/foo` in the `docker-ce` container and then exit you'll see `/var/foo` in the root filesystem:

```
$ docker run -it --privileged --pid=host justincormack/nsenter1
/ # ls /var
cache   empty   local   log     run     tmp
config  lib     lock    opt     spool   vpnkit
/ # ctr t exec -t -exec-id foo docker-ce sh
/ # touch /var/foo
/ # exit
/ # ls /var
cache   empty   lib     lock    opt     spool   vpnkit
config  foo     local   log     run     tmp
/ # exit
$
```

Furthermore you can run an alpine container sharing this writable `/var` with a command like:
```
$ docker run -it  -v /var:/host_var alpine sh
/ # ls /host_var
cache   empty   lib     lock    opt     spool   vpnkit
config  foo     local   log     run     tmp
```

Perhaps the solution is something along the lines of:
- start a privileged container (`docker run --privileged`) sharing `/var` (`-v /var:/host_var`) with the NFS software inside. It's probably worth making a `Dockerfile` for this.
- arrange for the host volumes to be mounted (e.g. under `/host_var/Users`)
- then a `docker run -it -v /var/Users:/home alpine sh` should mount the right directory.
- perhaps inside the `docker-ce` container you could `umount /Users` and something like `mount --bind /var/Users /Users` to replace one type of bind with the other.

Sorry for the disruption this change has caused.

**Comment by if-kenn** [comment]
@djs55 I am one of the main authors of https://github.com/IFSight/d4m-nfs. Thanks for the thoughtful reply.

I have tried to prototype what you are suggesting, but it appears that the Linuxkit VM does not "see" the NFS mount that the privileged container mounts. I have created a video to show you what I am seeing since it is hard to explain. I have [uploaded the mp4](http://ifsight.com/d4m-priv-nfs-test.mp4) so you can download and view it at whatever speed you would like and also included an animated GIF here:

![d4m-priv-nfs-test](https://user-images.githubusercontent.com/5553161/35064934-7a58f09a-fb80-11e7-8b7b-27ce1e9492c3.gif)

```
# script for Mac
ps auxw |grep nfs|grep -v grep
cat /etc/exports
docker ps -a
docker run --name tester --rm -it -v /var:/container_var alpine /bin/sh

# script for tester container 
ls -la /container_var
ls -la /container_var/Users/kenn

# script for Linuxkit host VM
docker run --name nsenter --rm -it --privileged --pid=host justincormack/nsenter1
ctr t ls
ls -la /var/Users/kenn
ls -la /var/Users/kenn

# script for nfsclient container
docker run --name nfsclient --rm -it --privileged -v /var:/host_var alpine /bin/sh
apk add --no-cache nfs-utils
rpcbind -s
mkdir -p /host_var/Users/kenn
ls -la /host_var/Users/kenn
mount -t nfs -o actimeo=2,noacl,noatime,nolock,tcp,async 192.168.65.2:/Users/kenn /host_var/Users/kenn
ls -la /host_var/Users/kenn
```

**Comment by if-kenn** [comment]
@niklasravnsborg can you expound on your confused emoji response? is that with the whole thing or my post?

**Comment by ryansch** [comment]
@if-kenn Have you tried adjusting the bind propagation on the `/var` mount into the nfsclient container?

Docs: https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-bind-propagation

Example: `-v /var:/host_var:shared`

**Comment by ryansch** [comment]
@if-kenn Have you had a chance to review my above comment?  I think it might fix https://github.com/IFSight/d4m-nfs/issues/55

**Comment by myers** [comment]
Given the support for NFS in Docker for Mac 18, maybe this issue is no longer relevant?

**Comment by rivaros** [comment]
I still have problem with the issue:

1. My nfs4-server container needs to export some NFS shares (take a note I am not speaking about NFS support for Mac (that's different) - I just need to share some folders with nfs between some containers).

2. Now a problem - host system on Mac (linuxkit or whatever it is) has no modules nfs & nfsd enabled. I can login with that @justincormack stuff and run
```
modprobe nfs
modprobe nfsd
```

Then things magically start to work. How do I make this change permanent???

Help is needed.

**Comment by djs55** [comment]
@rivaros perhaps try creating a container with `--restart=always` -- I think this will cause the container to be run automatically on system start.

Perhaps something like:
```
docker run --restart=always --privileged --pid=host justincormack/nsenter1 /bin/sh -c "modprobe nfs; modprobe nfsd; while true; do sleep 3600s; done"
```

The `while` loop is to stop the container exiting and restarting in a tight loop.
