### ISSUE TITLE
Docker and Kubernetes fails to start when Kubernetes is enabled

### ISSUE THREAD

**Issue by paulhopkins11** [docker/for-mac#2541]
### Expected behavior
Both docker daemon and kubernetes VMs should start successfully

### Actual behavior
Both show as Starting... but never complete. I now can not disable Kubernetes to get back to just running docker

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 18.02.0-ce-rc1-mac50 (e1912a8c46ae6f60a85d277f7b8d210dc9670b28)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/CDD76C17-B45B-4863-9376-AD258C6ED52D/20180131-101354.tar.gz
failure: com.docker.osxfs is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install latest version
  2. Choose "Enable Kubernetes"

**Comment by pgayvallet** [comment]
As workaround to disable kubernetes without the UI, you can edit `~/Library/Group\ Containers/group.com.docker/settings.json` and set the `kubernetesEnabled` property to false, then quit and relaunch the app.

What I don't understand here is how you got to a state where docker was restarting when enabling k8s (enabling k8s from the options does not restart docker) Did you close/restarted the app during the initial cluster installation ?

**Comment by paulhopkins11** [comment]
Hi, I guess when I enabled k8s it failed to start so I quit docker and restarted it. I have done as suggested and now k8s doesn't try to start but docker now fails to start:
```
Docker for Mac: version: 18.02.0-ce-rc1-mac50 (e1912a8c46ae6f60a85d277f7b8d210dc9670b28)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/CDD76C17-B45B-4863-9376-AD258C6ED52D/20180131-185630.tar.gz
failure: com.docker.osxfs is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by paulhopkins11** [comment]
Ah, a restart sorted that out. Docker is now running. I will try k8s again

**Comment by paulhopkins11** [comment]
It has come up now

**Comment by ospaarmann** [comment]
I have the same issue. It really kills productivity.

MacBook Pro 2017
2,3 GHz Intel Core i5
16 GB RAM
File System: APFS

I tested it with latest Docker stable, 18.03.1-ce

<img width="696" alt="screen shot 2018-07-11 at 13 48 15" src="https://user-images.githubusercontent.com/308086/42574198-52e6bcf4-851e-11e8-8803-508fe08998a7.png">

and Docker edge 19.05.0-ce

<img width="696" alt="screen shot 2018-07-11 at 15 26 06" src="https://user-images.githubusercontent.com/308086/42574501-c67c007a-851e-11e8-9ec6-5536436b2cf8.png">

I started a docker compose with several containers and looked at CPU usage with different configurations and when running tests (Elixir) or just idle:

<img width="920" alt="screen shot 2018-07-11 at 15 24 41" src="https://user-images.githubusercontent.com/308086/42574353-8be11c5c-851e-11e8-8faf-ab1d1b8d752b.png">

**Stable**

- **7 GB RAM, 1 CPUs:** 10-20% idle, 120% running tests
- **7 GB RAM, 2 CPUs:** 20% idle, 150% running tests
- **7 GB RAM, 3 CPUs:** 6-20% idle, 220% running tests

**Edge**

- **5 GB RAM, 1 CPUs:** 5-25% idle, 130% running tests
- **5 GB RAM, 2 CPUs:** 5-25% idle, 140-160% running tests
- **5 GB RAM, 3 CPUs:** 30-120% idle, 200% running tests

**Takeaway:**

Interestingly this issue is present with Edge and Stable. And the CPU setup doesn't really matter (but the factory default of 2 CPUs seems to work best). I also use docker-sync for file syncing.

More interestingly: My colleague is running the exact same setup on an older MacBook with a different file system (HFS). I am running it on APFS. He doesn't have any issues with the latest edge version.
