### ISSUE TITLE
How do you roll-back the mac version?

### ISSUE THREAD

**Issue by vgoklani** [docker/for-mac#2577]
The latest set of pushes have completely broken this thing. My Docker instances all hang after a few days... How do I revert to the version from last month?

**Comment by pgayvallet** [comment]
Rollback will requires you to uninstall your current version then reinstall a previous one. D4M does not handle "rollbacks".

18.01.0-ce-mac48 available here : https://download.docker.com/mac/edge/22004/Docker.dmg ,even if i strongly doubt that's the root cause, no much change on the daemon itself between 18.01 and 18.02
