### ISSUE TITLE
Docker does not fully start on macOS startup - C7186783-CDD0-43DA-8A68-BB9DFC021EA6

### ISSUE THREAD

**Issue by tmanor-redhat** [docker/for-mac#2596]
### Expected behavior
Upon log on to the machine, docker should automatically start fully
### Actual behavior
docker shows as 'Docker is starting'
### Information
Diagnostic ID - C7186783-CDD0-43DA-8A68-BB9DFC021EA6
[ERROR]  docker-cli
         docker ps failed

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

Got a lot of error in the vm logs due to disk being full : 

`sh: write error: No space left on device`

`[33mWARN[0m[0000] failed to load plugin io.containerd.metadata.v1.bolt  [33merror[0m="write /var/lib/containerd/io.containerd.metadata.v1.bolt/meta.db: no space left on device" [33mmodule[0m=containerd`

Can you : 

1/ on the host, make sure there is still space left on the device where the vm disk is.

2/ if it's not an host device space issue, try to increase the vm disk size from the UI ( or if you can't access the UI due to boot failure, edit the `diskSizeMiB` property in the `~/Library/Group\ Containers/group.com.docker/settings.json` and restart docker ?

**Comment by tmanor-redhat** [comment]
Hi,
I was able to reset everything, and Docker appears to be running correctly now.

Thanks!

$ more settings.json 
{
  "proxyHttpMode" : "system",
  "diskPath" : "/Users/..../Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2",
  "diskSizeMiB" : 65536,
  "cpus" : 2,
  "defaultMachineMigrationStatus" : 4,
  "memoryMiB" : 2048,
  "displayedWelcomeWhale" : true,
  "buildNumber" : "21995",
  "filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp"
  ],
  "channelID" : "stable",
  "settingsVersion" : 1,
  "version" : "17.12.0-ce-mac49",
  "displayedWelcomeMessage" : true,
  "dockerAppLaunchPath" : "/Applications/Docker.app",
  "linuxDaemonConfigCreationDate" : "2018-02-15 15:38:19 +0000"
}
