### ISSUE TITLE
Docker for Mac (Edge) is not respecting $DOCKER_CONFIG, or $KUBECONFIG environment variable

### ISSUE THREAD

**Issue by lewiscowper** [docker/for-mac#2635]
### Expected behavior

Docker doesn't write any config files to `~/.docker`, once the `DOCKER_CONFIG` variable has been set (to some path that is not `~/.docker`). Similar situation for `~/.kube` and `KUBECONFIG`.

It'd be awesome to have a setting in Docker for Mac that allowed configuring where configuration files and Volumes etc could be stored.

### Actual behavior

config.json and daemon.json are written to the `~/.docker` directory, instead of the location specified by `DOCKER_CONFIG`

### Information

  - Diagnostic Id 9070B83F-3875-4E21-99A6-C4443476D704

### Steps to reproduce the behavior

  1. Install Docker for Mac (Edge), and set DOCKER_CONFIG environment variable to some path, `~/.docker-example` for example.
  2. Start Docker for Mac
  3. Run `$ ls ~/.docker`
  4. Note the presence of `config.json`, and `daemon.json`

**Comment by pgayvallet** [comment]
Hello,

> set DOCKER_CONFIG environment variable to some path

How are you doing this exactly ?

**Comment by lewiscowper** [comment]
@pgayvallet that's within my shell, I realise that Docker for Mac might not source my shell environment, (in fact it almost definitely won't), however I'd love a way to configure where to store config files for Kubernetes + Docker within Docker For Mac.

**Comment by pgayvallet** [comment]
On windows it's working due to how system properties behave.

On OSX, there is no trivial way to add trully global varenv. There seems to be a way, if you want to try though : https://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks. Please note that this is not officially supported.

**Comment by lewiscowper** [comment]
@pgayvallet is it possible to add a setting within Docker for Mac/Windows to set up where to store configuration files?

**Comment by jasonkarns** [comment]
reopen, please?

**Comment by stefansundin** [comment]
I made a tiny app to help me with this. Instead of launching Docker, I launch Docker-Env, which just runs a shell script before then launching Docker.app. The shell script can set variables (in my case `KUBECONFIG`), or do anything you want it to do.

Get it here: https://github.com/stefansundin/Docker-For-Mac-Env

But it would definitely be a lot more convenient if something was added to the official app!

**Comment by yagi5** [comment]
I found just workaround:

```shell
alias docker="docker --config $HOME/.config/docker/"
```

**Comment by lewiscowper** [comment]
@yagi5 that will change the docker commands that you run from your CLI, but as far as I can tell won't affect where the Mac/Windows App will write config files to.

**Comment by gibfahn** [comment]
I expected calling this from a terminal to work as a workaround, but it doesn't seem to:

```bash
DOCKER_CONFIG=$HOME/.config/docker open -a Docker
```

If I quit Docker for Mac and then run this command it still creates `~/.docker/{config.json,daemon.json}`.

If I `rm -rf ~/.docker && touch ~/.docker` then the dir doesn't created (as there's already a file there), but that's not a great workaround.
