### ISSUE TITLE
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password.

### ISSUE THREAD

**Issue by jfolgado** [docker/for-mac#2640]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gartha1** [comment]
you should fill out the body of the question and not just copy/paste in a template.

but I had a similar problem.. i'm not expert but for me it was that I didn't have internet access. so I connected my wifi, then having done that, I did docker-machine restart.   Another thing to do (since yours said incorrect username/password), is to check your username and password are correct, by trying to log into hub.docker.com so you know your user/pass is correct.

**Comment by cscholze** [comment]
Try logging back in with the CLI via `docker login`

**Comment by StilgarISCA** [comment]
I've run into this issue before too. It happens because the docker client (on macOS at least) allows you to sign in with your email address and password. If you sign out and sign in with your Docker Username and password everything will work. So here's a better description of the issue

**Platform/OS**
Version 17.12.0-ce-mac55(23011)

**Description**
When trying to pull images from the Docker registry `docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password`. This happens if you sign in to Docker using your email address instead of your username.

**Steps to Reproduce**
1. Clean install, or reset preferences for Docker
2. Sign in to Docker GUI using your email address and password
3. In the terminal, pull an image from the Docker registry

**Actual Results**
`docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password`

**Expected Results**
Either of these:
1. The docker client should not allow you to sign in with your email address, only your username
2. If the client allows you to sign in with your email address, it should still work

**Comment by Jiangew** [comment]
docker login from CLI, docker-compose again, then SUCCESS.

**Comment by ztou** [comment]
I had the same issue by login with email, fix it by logout and use the user name other than email to login.

**Comment by rsalazar0000** [comment]
[log.0.txt](https://github.com/docker/for-mac/files/2052241/log.0.txt)
[log.txt](https://github.com/docker/for-mac/files/2052242/log.txt)
[DebugInfo-2018-05-29_14-53-46.txt](https://github.com/docker/for-mac/files/2052243/DebugInfo-2018-05-29_14-53-46.txt)

I have the same issue, but restarting and logging out and logging back in is same issue

**Comment by Akkuma** [comment]
Also note your username is fully lowercase.

**Comment by clucle** [comment]
my solution is not email, but username at login docker hub web

**Comment by chucklor** [comment]
I have the same issue. I restarted docker and restarted my Mac and it's still show the same error when I run: docker run hello-world on my terminal.

**Comment by purecapitalist** [comment]
I have a similar problem. I can log into the websites. I can log into the Docker for Mac application. I CANNOT sign in from CLI.

**Comment by kenorb** [comment]
Same here on Windows 10:
```
>docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
>docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

Workaround:
```
>docker logout
Removing login credentials for https://index.docker.io/v1/
```

**Comment by andy-rust** [comment]
same here on mac

`➜  ~ docker --version
Docker version 18.03.1-ce, build 9ee9f40`

**Comment by rseixas** [comment]
Logged in with username instead of email did the trick.

macOS High Sierra 10.13.5
`docker --version Docker version 18.06.0-ce, build 0ffa825`

**Comment by dbraben** [comment]
1. Run the following code in the CLI to confirm docker is installed:
`docker version`
2. Run the following and use the username you created (not the email) for your docker account as well as the password. If you don't have a docker account go to https://hub.docker.com/:
`docker login`

**Comment by songxiaoxiao** [comment]
I have the same problem, You just need to use your username instead of the mailbox to log in, it's all right.

**Comment by besnikbelegu** [comment]
log out and sign in with the dockerID rather than email and it will work.

**Comment by magaofei** [comment]
```
docker logout
docker login
```
use username not email

**Comment by ankyjk** [comment]
This issue occurs when you are logged into docker account.
I simply Logged out and pulled the docker image 💯 
Worked for mee

**Comment by AllanQ05** [comment]
> 
> 
> ```
> docker logout
> docker login
> ```
> 
> use username not email

it work for me

**Comment by oliverbienert** [comment]
The same here. Windows 10, Docker Engine 18.09.1
Used my username to login, not email, then it worked.

**Comment by nanuklein** [comment]
Had the same issue on Mac OS 10.14.3, docker version 18.09.2  -- a quick command run of "docker login" and entering the actual username instead of the email address helped. Not sure why it allows people to sign in with the email address they used to create their docker profile rather than username.

**Comment by RajendrasinhParmar** [comment]
```
docker logout
```
and then 
```
docker login
```

Using username instead of email resolved the issue. 👍

**Comment by stephaniemdavis** [comment]
The solution that worked for me:

docker logout
docker run hello-world

SUCCESS!

**Comment by SunneyTyagi** [comment]
Yes it works after logging in the docker hub. 
go to https://hub.docker.com/ and login with your credentials, if not have account then register once.
Go to cli/ terminal
$ docker login
$ enter username
$ enter password 
Run the command, it will work.  Success :)

**Comment by fudomunro** [comment]
Was getting:
```
ERROR: Service 'x-y-z' failed to build: Get https://registry-1.docker.io/v2/library/python/manifests/alpine: unauthorized: incorrect username or password
```

and indeed the Windows Docker app had me logged in with my email.

**Comment by sathyaprakash94** [comment]
After done the docker installation, open the cmd or powershell in windows and run the following command

> docker login 
It will ask you username and password of your docker account. After that run the commands provided in the documentation. The Hello-world image pulling from docker hub.

**Comment by Morben** [comment]
thak you~

> I've run into this issue before too. It happens because the docker client (on macOS at least) allows you to sign in with your email address and password. If you sign out and sign in with your Docker Username and password everything will work. So here's a better description of the issue
> 
> **Platform/OS**
> Version 17.12.0-ce-mac55(23011)
> 
> **Description**
> When trying to pull images from the Docker registry `docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password`. This happens if you sign in to Docker using your email address instead of your username.
> 
> **Steps to Reproduce**
> 
> 1. Clean install, or reset preferences for Docker
> 2. Sign in to Docker GUI using your email address and password
> 3. In the terminal, pull an image from the Docker registry
> 
> **Actual Results**
> `docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password`
> 
> **Expected Results**
> Either of these:
> 
> 1. The docker client should not allow you to sign in with your email address, only your username
> 2. If the client allows you to sign in with your email address, it should still work

thak you!

**Comment by nicks9188** [comment]
> Try logging back in with the CLI via `docker login`

Also, use username to login instead of email.

**Comment by mikirex** [comment]
I just had to quit the terminal, signout from the desktop app and signin again through the desktop app. Hope that can help :)

**Comment by amalkapathirage** [comment]
Use the CLI and run "docker login" . Then log in to the docker hub to find the correct user name. When you log in to the docker hub, you will see the username in the right corner. Use it as the user name instead of the email. That will work.

**Comment by MulunehA** [comment]
//use your username instead of email.

Steps:

1. Logout/Signout from  GUI docker

2. Run  below cli  command from PowerShell

   docker login

and, provide you username(not email) and password.

Note: if you don't have docker account you need to signup.

3. Finally, run  below cli command from PowerShell

docker run hello-world

Thanks!

**Comment by CS2Us** [comment]
> Same here on Windows 10:
> 
> ```
> >docker run hello-world
> Unable to find image 'hello-world:latest' locally
> docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password.
> See 'docker run --help'.
> >docker --version
> Docker version 18.03.1-ce, build 9ee9f40
> ```
> 
> The login is correct and works in GUI app. On the other hand, why it needs any login for public repos?
> 
> Workaround:
> 
> ```
> >docker logout
> Removing login credentials for https://index.docker.io/v1/
> ```

It work in my situation when run docker GUI desktop and login by docker GUI desktop.

**Comment by ericjoy1991** [comment]
**Also facing the same issue i guess... help me out to resolve this please.
Description:
When trying to run hello-world….**

/Desktop# sudo docker run hello-world
Unable to find image 'hello-world:latest' locally docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup usrname on 10.200.50.100:53: server misbehaving. See 'docker run --help'.
/Desktop# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 123456
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup er370121 on 10.200.50.100:53: server misbehaving


**Platform/OS**
/.docker# lsb_release -a
No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 16.04.6 LTS Release: 16.04 Codename: xenial
/.docker# docker --version
Docker version 19.03.1, build 74b1e89e8a
/.docker# uname -a
Linux bc-VirtualBox 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


**Steps to Reproduce**

124 sudo apt update
125 apt-get update && apt-get upgrade -y
126 sudo apt-get install \n apt-transport-https \n ca-certificates \n curl \n gnupg-agent \n software-properties-common
127 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
128 sudo apt-key fingerprint 0EBFCD88
129 lsb_release -cs
130 sudo add-apt-repository \n "deb [arch=amd64] https://download.docker.com/linux/ubuntu \n $(lsb_release -cs) \n stable test nightly"
131 docker --version
132 sudo apt-get update
133 sudo apt-get install docker-ce docker-ce-cli containerd.io
134 apt-cache madison docker-ce
137 sudo apt-get install docker-ce=5:19.03.1~3-0~ubuntu-xenial docker-ce-cli=5:19.03.1~3-0~ubuntu-xenial containerd.io

**corporate proxy config details (PROXY with AUTHENTICATION )**
/Desktop# cat /etc/apt/apt.conf
Acquire::http::proxy "http://usrname:paswrod@proxy.example.com:8080/"; Acquire::https::proxy "https://usrname:paswrod@proxy.example.com:8080/"; Acquire::ftp::proxy "ftp://usrname:paswrod@proxy.example.com:8080/"; Acquire::socks::proxy "socks://usrname:paswrod@proxy.example.com:8080/";

/Desktop# cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service] Environment="HTTP_PROXY=http://usrname:paswrod@proxy.example.com:8080/" Environment="HTTPS_PROXY=https://usrname:paswrod@proxy.example.com:8080/ Environment="NO_PROXY="localhost,127.0.0.1,::1"

~/.docker# cat config.json
{ "proxies": { "default":
{
 "httpProxy": "http://usrname:paswrod@proxy.example.com:8080",

 "httpsProxy": "https://usrname:paswrod@proxy.example.com:8080",

 "noProxy": "localhost,127.0.0.0/8,*.local,host.docker.internal"
} } }
once PROXY is configured tries out below steps
sudo systemctl daemon-reload
sudo systemctl restart docker.service




_Already tried the above mentioned things such as using username instead of email…so we can skip that part…_

**Comment by ericjoy1991** [comment]
folks please ignore my issue ...posted by mistake in mac forum..:neutral_face:

**Comment by bruhatta** [comment]
> ```
> docker logout
> docker login
> ```
> 
> use username not email

Thanks .It worked

**Comment by figonzal1** [comment]
If for any reason, you still have the same error after all this, check if your password has special characters ...
Solved Thanks

**Comment by bhmckendrick** [comment]
> > ```
> > # docker logout
> > # docker login
> > ```
> > 
> > 
> > use username not email
> 
> Thanks .It worked

Same - logout and login fixed the 503 issue for me.

**Comment by cpolzer** [comment]
```
# docker logout
# docker login
```
 Worked.

My problem was: I did "docker login registry-1.docker.io" and it said: "login successful".
Why? The error message stated 
```
docker build .
Sending build context to Docker daemon  132.6kB
Step 1/8 : FROM ubuntu:18.04
Get https://registry-1.docker.io/v2/library/ubuntu/manifests/18.04: unauthorized: incorrect username or password

```

**Comment by vmlogsin** [comment]
```Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

> > docker logout
> > docker login
> > ```
> > 
> > 
 This worked for me
