### ISSUE TITLE
Docker hangs on wake-up

### ISSUE THREAD

**Issue by bfad** [docker/for-mac#268]
### Expected behavior
Waking up from sleep I should be able to use docker right away

### Actual behavior
It hangs

### Information

Diagnostic ID: 63D00E22-5B9F-423A-90B8-2E2414EA536A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A286a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/63D00E22-5B9F-423A-90B8-2E2414EA536A/20160813-154138/qemu-img-check.stdout 2> /tmp/63D00E22-5B9F-423A-90B8-2E2414EA536A/20160813-154138/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     driver.amd64-linux

### Steps to reproduce

1. Have docker running just fine
2. Put the computer to sleep (wait an hour jut to make sure really asleep)
3. Wake up the computer and try to use docker

### Information

After a few minutes, it's no longer hanging, but I can't use it. This is what the diagnostics say then:

Diagnostic ID: 63D00E22-5B9F-423A-90B8-2E2414EA536A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/username/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/63D00E22-5B9F-423A-90B8-2E2414EA536A/20160813-154442/qemu-img-check.stdout 2> /tmp/63D00E22-5B9F-423A-90B8-2E2414EA536A/20160813-154442/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/username/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

**Comment by v4tech** [comment]
Hey @bfad - Do you think you have the same issue as https://github.com/docker/for-mac/issues/85 ?

If so, come over and join us...  😞 ⏳

**Comment by bfad** [comment]
@v4tech I don't think it's the same issue. It's not that my docker instances stop running, it's that docker itself hangs / becomes unresponsive. I can't even do a `docker ps`.

**Comment by aripalo** [comment]
Hi all! 

This is sort of a “repost” from my comment in `compose` issue https://github.com/docker/compose/issues/3904 (which actually seems to be _effect_ of `for-mac` hanging) as I do have this exact same issue, but with added weirdness that besides after sleep, `for-mac` hangs also sometimes randomly even without going to sleep.

I've written as detailed report as I could in https://github.com/docker/compose/issues/3904#issuecomment-246327884, but here's the gist of it:

### What happens

Usually after waking up from sleep (_e.g. Macbook lid close & open again_), Docker `for-mac` seems to hang. 

1. If I had running containers, they're unresponsive and even `ctrl`+`c` on terminal won't close them.

2. If I try to then run `docker-compose up` (or any other `docker-compose` command, which is why I originally reported this issue on https://github.com/docker/compose/issues/3904) `compose` will ouput following:
  ```bash
  $ docker-compose up
  Traceback (most recent call last):
    File "<string>", line 3, in <module>
    File "compose/cli/main.py", line 61, in main
    File "compose/cli/main.py", line 113, in perform_command
    File "contextlib.py", line 35, in __exit__
    File "compose/cli/errors.py", line 56, in handle_connection_errors
  TypeError: log_timeout_error() takes exactly 1 argument (0 given)
  docker-compose returned -1
  ```

This issue affects all running containers, not just the one that was open/running before going to sleep.

Even restarting Docker (via Menubar icon) does not help.

### What helps

Only full reboot recovers the issue.

### Debug info

- No custom `$DOCKER_HOST` is set
- `docker-compose ps` hangs
- `docker info` hangs
- Running latest stable `for-mac`:
  ```bash
  $ docker --version
  Docker version 1.12.0, build 8eab29e
  
  $ docker-compose --version
  docker-compose version 1.8.0, build f3628c7
  
  $ docker-machine --version
  docker-machine version 0.8.0, build b85aac1
  ```

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by aripalo** [comment]
Issue closed & merged with https://github.com/docker/for-mac/issues/119 so future discussion should be there. But just in case someone ends up reading this issue:

A temporary “solution” (until an actual fix comes along) is to run `sudo pkill docker` and then restart the Docker for Mac app.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
