### ISSUE TITLE
start idea or android studio,   docker crashed

### ISSUE THREAD

**Issue by wxh2013** [docker/for-mac#2694]
### Expected behavior

start idea or android studio,   docker crashed

![screen shot 2018-03-13 at 3 09 26 pm](https://user-images.githubusercontent.com/7362131/37327274-94781656-26d0-11e8-9f8f-e067931cd2c5.png)

### Information

Docker for Mac: 17.12.0-ce
![screen shot 2018-03-13 at 3 03 49 pm](https://user-images.githubusercontent.com/7362131/37327091-dd44ec84-26cf-11e8-92ab-eb9cffb940dc.png)

android studio: 3.0.1

![screen shot 2018-03-13 at 3 05 39 pm](https://user-images.githubusercontent.com/7362131/37327152-105fea42-26d0-11e8-9198-d047aafe8de9.png)

mac version: 10.13.3

![screen shot 2018-03-13 at 3 06 44 pm](https://user-images.githubusercontent.com/7362131/37327186-2b5914ae-26d0-11e8-9560-1730424b5cdb.png)

![screen shot 2018-03-13 at 3 07 55 pm](https://user-images.githubusercontent.com/7362131/37327218-5b603e70-26d0-11e8-9e03-7f67f22d6b71.png)

### Steps to reproduce the behavior

  1. Start docker daemon
  2. Start android studio or idea
  3.Docker daemon quit and alert "com.docker.supervisor failed to start
Exit code 9"

**Comment by djs55** [comment]
@wxh2013 thanks for your report.

Looking at the logs, I think the diagnostic report was taken before the crash since I can't see log lines pertaining to the crash itself. However I think there was a conflict between the Apple "Hypervisor.framework" (as used by Docker.app) and the kernel modules `HAXM` as used by Android studio.

Could you update the `HAXM` version by following the instructions in this thread: https://github.com/moby/moby/issues/24530#issuecomment-291831250 and let me know if it fixes the problem?

**Comment by wxh2013** [comment]
@djs55 thanks for the reply.
It's doesn't work.   I have lastest HAXM version(6.2.1).    And I not run the android emulator,  just start or close the android studio.     This problem has troubled me for more than half a year.

How about this Diagnostic ID， B984B77D-CD4F-4ED8-82CB-ADA107E132EC
