### ISSUE TITLE
Not Working for MacOS Oracle Virtual Box on Windows 10

### ISSUE THREAD

**Issue by karmakargopi** [docker/for-mac#2704]
Issues without logs and details cannot be exploited, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version...

```
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by karmakargopi** [comment]
Diagnostic ID:A35B2BDA-5B79-4144-925E-6CD8203B0C07

**Comment by djs55** [comment]
Hi,

Docker for Mac requires hardware virtualisation which is not available in Oracle Virtual Box. I believe nested virtualisation is available in VMware fusion.

However note that we don't support or recommend running Docker for Mac in a VM so it may or may not work for you in practice.

Since you are running Windows 10, I recommend you try Docker for Windows.
