### ISSUE TITLE
Docker Failed to start with kubernetes failing

### ISSUE THREAD

**Issue by idurotola** [docker/for-mac#2813]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jprivillaso** [comment]
I am having the same issue. 
2ABD91D4-E8EA-4D20-84FC-255B78822044
Docker won't start, it keeps starting forever after the latest update for macOS

**Comment by YRM64** [comment]
Don't feel bad jprivilloso, for me, Docker keeps starting forever (I mean for an unreasonable length of time ~ hours), and I hadn't been given the opportunity to enable anything, or update anything because it would never finish starting.  I'm using MacOs, version 12.6.3.  In fact, the Docker dialogue box never opened up because it never finished starting.

**Comment by jprivillaso** [comment]
@YRM64 I solved the issue restarting docker to its default state :) That can be done at the preferences
