### ISSUE TITLE
Problem running "Dockerized web server"

### ISSUE THREAD

**Issue by leifdenby** [docker/for-mac#288]
### Expected behavior

Having successfully installed docker and managed to run the hello world test I tried to run the [Dockerized web server](https://docs.docker.com/docker-for-mac/#step-3-explore-the-application-and-run-examples) as in the documentation. However I get an error

### Actual behavior

```
~ » docker run -d -p 80:80 --name webserver nginx 
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
51f5c6a04d83: Extracting [==================================================>] 51.36 MB/51.36 MB
a3ed95caeb02: Download complete
51d229e136d0: Download complete
bcd41daec8cc: Download complete
docker: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-067789940 /var/lib/docker/image/aufs/layerdb/sha256/4dcab49015d47e8f300ec33400a02cebc7b54cadd09c37e49eccbc655279da90: directory not empty.
See 'docker run --help'.
```

### Information

Diagnostic ID: F4CD5B3C-B39D-4DF9-8FDA-B9D6FA2BD768
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install fresh Docker for Mac
2. Run nginx example from documentation `docker run -d -p 80:80 --name webserver nginx`

**Comment by dsheets** [comment]
This could be due to disk image corruption or a kernel bug that has since been fixed in a more recent release (1.12.1 is now available). If you still observe this issue, we'd be very interested in another report. Otherwise, if it is fixed after upgrading or resetting to factory defaults, there is little we can do. We are working to improve both the robustness of the disk image under application/power failure and keeping the included Linux components up-to-date for each release. Thanks for using Docker for Mac!
