### ISSUE TITLE
Docker not running on Mac after install

### ISSUE THREAD

**Issue by mateuslongo** [docker/for-mac#2885]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue
  - macOS Version: High Sierra 10.13.4

### Expected behavior
Installation completed
### Actual behavior
This error appeared: Failed to install symlinks in /usr/local/bin (stage 5)
### Information

```
Diagnostic ID: 7746F600-5EC9-440E-A14C-F717B338BB6D


Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/7746F600-5EC9-440E-A14C-F717B338BB6D/20180507-152943.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mateus/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/mateus/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mateus/Library/Containers/com.docker.docker/Data/vms/0/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/mateus/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/mateus/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started


```

### Steps to reproduce the behavior

  1. Install Docker for mac
  2. Run Docker
  3. Run again and start diagnostics tool.

**Comment by YRM64** [comment]
Mateuslongo,
There are a ton of reasons why Docker won't start after installation.  And, sometimes the reason is something puzzling such as Docker won't finish starting.  I, myself waited hours for Docker to finish starting one day, and I said to myself "we seriously need something new for Mac users." I reinstalled Docker three times, and each time Docker wouldn't finish starting.  But to get to the root of it all, the logs pretty much help identify specific problems.  

What we can do:
1 ) Use our Macs console for log queries 2) Make sure our certificates are set up correctly
3) Docker for Mac won't start up if the Mac user account and the home folder are renamed after we install our application 4) Project directories outside /Users - affects file sharing and volume mounting 
5) incompatible CPUs can be problematic

I used my own situation as an example above, and yet the tutorials indicated that if Docker still fails to start:  make sure to quit Docker before installing a new version.  I not only quit Docker but I dragged it to the trash bin because I didn't have access to the menu.  I never had the Docker daemon running so that wasn't an issue, and couldn't run the uninstall commands from the menu because I had no menu.  I didn't have access to Docker environment variables.  NPM would inconsistently report that I had Docker one day, and the next day I had no Docker.  For the days it reported I had Docker, I never had access to the Docker menu/dialogue access box to orchestrate my configurations.  And, one of the troubleshooting tips I didn't have the opportunity to try before my laptop went on the blink was the ability to run ls of -i tcp:8080.  As I read the blogs and visit Github, some of the same troubleshooting tips that worked for some, didn't work for others.  Sometimes, it appeared to be consistency in terms of what worked, and what didn't work.  But what I came to realize is that we all have a tendency to interpret, manifest, and describe events a little bit differently than one another and often times that's what makes the difference in something working on my Mac vs. something working on yours.  As a consequence, I pay close attention to how folks express their experiences with Docker, and often times find myself sharing in their experiences.  Pleased to know you were able to find resolution.
