### ISSUE TITLE
How to change kernel for "docker-machine"

### ISSUE THREAD

**Issue by peterromfeldhk** [docker/for-mac#2895]
or whats the best way to run docker on OSX but be able to change kernel of the actual VM running docker?

**Comment by YRM64** [comment]
You have to change the kernel configurations, however, I too would like to know why you need to change the kernel for Docker-for-Mac?

**Comment by peterromfeldhk** [comment]
we encountered a issue and suspected its related to a bug in this old kernel that is used.

we ended up running docker(CI runner) on a spare Linux machine instead which allowed a complete different approach to the issue.

**Comment by stephen-turner** [comment]
OK, glad you got it working. I’m going to close this issue now, although I’m not aware of any bugs related to the version of the kernel used: it should be an internal implementation detail as far as the user is concerned.

**Comment by mageekguy** [comment]
Hi!

Firstly, thanks for your good job.
Secondly, upgrading kernel version may be a very good idea, because currently, it's not possible to use `net.ipv4.ip_unprivileged_port_start=0` as a `sysctl` entry because this instruction is available only since kernel version ≥ 4.11.
And this instruction is very useful to bind (for example) apache on a privileged port (aka 80) as a non-root user (see https://github.com/moby/moby/issues/8460).

**Comment by morganchristiansson** [comment]
I'm getting this error trying to run container as non-root user:

```ERROR: for myproject_myservice_1  Cannot start service myservice: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory\"": unknown
```

As you say this is because of old Linux kernel in Docker for Mac.... CAP_NET_BIND doesn't work correctly either so will have to find a different approach to allow privileged port.... Following advice in https://github.com/moby/moby/issues/8460#issuecomment-312459310
