### ISSUE TITLE
docker-for-mac: registry.docker.io: Service Unavailable

### ISSUE THREAD

**Issue by antipetrov** [docker/for-mac#2897]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Expected behavior
  1. docker pull postgres:latest

  2. image is pulled

### Actual behavior

1. docker pull

2. error:
Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=antipetrov&client_id=docker&offline_token=true&service=registry.docker.io: Service Unavailable
  

### Information

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/6C70BC3A-F804-4591-9352-BB61BD51BA93/20180510-220058.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk


```

### Steps to reproduce the behavior

  1. run docker for mac (tried reinstall also)

  2. docker pull postgres:latest

Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=antipetrov&client_id=docker&offline_token=true&service=registry.docker.io: Service Unavailable

**Comment by sylogex** [comment]
Same! OS X, Service Unavailable ! =(

**Comment by amarox** [comment]
Confirm! 10.13.4

**Comment by amarox** [comment]
https://github.com/docker/for-mac/issues/1317#issuecomment-350640901 work for me

**Comment by YRM64** [comment]
Antipetrov,

Sometimes this is deemed a temporary dilemma with Docker because of the Service Unavailable warning.  I would like for you to try a couple of troubleshooting steps to rule out anything other than a temporary problem.  Start with checking all connections; especially network.    Next, check your proxy settings. And, then restart Docker.  

When you check your network connections, I want you to follow this source code:

$ </dev/tcp/registry-1.docker.io/443 && echo Works
$ curl https://registry-1.docker.io/v2/ && echo Works

If none of the above fixes the problem then it's most likely a temporary issue with Docker services.  If anyone else has an update or anything else to add to the above stated instructions, please post here.
Thanks, and happy coding 🤗

**Comment by amarox** [comment]
```bash
$ </dev/tcp/registry-1.docker.io/443 && echo Works
Works
```

```bash
curl https://registry-1.docker.io/v2/ && echo Works
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
Works
```

**Comment by yunardopatra** [comment]
I just experience this,
Restart Docker service help (sometime)

**Comment by ben-toogood** [comment]
This also causes issues with `gcloud` (e.g. `gcloud docker -- push grc.io/my-app/my-img`). 

Restarting docker temporarily solves the issue but the underlying problem is still there. I'm running version  2.0.0.1.
