### ISSUE TITLE
Docker does not start if the home directory is renamed on Mac

### ISSUE THREAD

**Issue by navneetkarnani** [docker/for-mac#2928]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 877CE598-3BA8-438F-81A3-9F93513C0F61

### Expected behavior
After home folder rename, the docker app should start successfully. Containers should be accessed relative to the home folder, not absolute.

### Actual behavior
Renaming the folder breaks Docker startup. It asks to be reset to factory settings.

### Information

  - macOS Version: 10.13.4

To reproduce follow steps in this article: https://support.apple.com/en-us/HT201548

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Rename user and home folder using the article linked above.

**Comment by akimd** [comment]
Hi,

> Containers should be accessed relative to the home folder, not absolute.

You mean "Disk image" here.  I see that your settings.json is using "/Users/navneet/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2", but I have no idea whether it's the new one, or the old one.

You can change this by hand, or via the GUI, item "Disk".  I'm not sure we want to play with `$HOME`, since the path needs not be in HOME.

**Comment by navneetkarnani** [comment]
I changed the settings.json. Thanks

I think that the location of the file should be relative to the home directory, since that is already used for the settings file. Use relative, only if it is under $HOME. Other cases don't need to worry.

**Comment by akimd** [comment]
That makes sense.  I'll do that, thanks!
