### ISSUE TITLE
Docker CLI freezes until I restart Docker For Mac

### ISSUE THREAD

**Issue by ns-cweber** [docker/for-mac#2938]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 08FA8D50-DC37-40CD-B78C-4A2F03D8FB4D

### Expected behavior
The Docker CLI doesn't freeze indefinitely until I restart Docker for Mac.

### Actual behavior
The Docker CLI freezes indefinitely until I restart Docker for Mac

### Information
Not reproducible. Seems to happen. Twice when I was running `docker system prune -f`. Started appearing a few days ago. I think it happened once before I most recently updated.

  - macOS Version: 10.13.3

### Diagnostic logs
```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/08FA8D50-DC37-40CD-B78C-4A2F03D8FB4D/20180523-155432.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior
???

**Comment by YRM64** [comment]
Docker System Prune:

I warned in a previous GitHub posting the dangers of using this command.  In #30623, Albers reiterates my concerns when he calls it "dangerous" because it's too difficult to predict what all will be actually deleted, and it's not visible to the human eye when using docker system prune.  Docker System Prune removes:
* All stopped containers not used by at least one container.
* All volumes.
* All networks not used by by at least one container.
* All dangling images.

However, the only way to see anything else that may have been removed, you have to run docker system df and docker images ls --filter dangling=true.  Albers suggests adding a --dry-run option to the docker System Prune Command.

It's quite difficult providing a diagnosis unless more information becomes available, such as, what all was deleted when ns-cweber ran the Docker System Prune Command.

Notwithstanding, this use case carries many similarities to #1835 (in that case, the freezes happened occasionally, an upgrade was implemented, and there were hangs until restart).  It's similar to #36447 in that it occured occasionally.  I would like to see what the current thread depicts.

To support my contention that this is a difficult use case to diagnosis, we must revisit other use cases, conduct a comparative analysis, while examining console, diagnostic, and other available information.  And in other similar use cases, user(s) found fixes in conducting clean installs, Docker System Prune -a Cleanup, a full system reboot, resetting Docker to factory default settings, implementing an uninstall/reinstall, a full system re-start, and a piñata restart.  Anyone of these, or another could be a solution for ns-cweber.  There are so many possibilities, that only troubleshooting and testing could provide the answer.

And, if you switch from Docker Machine to Docker Beta, you have to unset environment variables.  

Workarounds for common issues include:

1. When Docker-for-Mac fails to start, make sure to quit Docker-for-Mac before installing a new version of the application; otherwise you could get an app in use error when you copy the new app from .dmg to /applications.

2. Give Mac a re-start to discard any vestige of the Daemon running from a previous version.

3. Run uninstall commands from the menu.

4. If the commands you run aren't working appropriately, unset some environment variables to clear out anything left over from a previously installed version.  Unset the DOCKER_HOST environment variable, and any other related variables.

If you start to experience difficulty, you have the opportunity to watch the live flow of Docker-for-Mac through the terminal by running:

$ pred='process matches ".*(ocker|vpnkit).*"
   |  |  (Process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains [c] "Docker") '
   /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"

There's been use cases come through GitHub without diagnostic reports.  As you well know, Github can't provide appropriate assistance without having access to those logs; and access to console logs gives you an added benefit of getting issues addressed quicker; with better success.  The console log query is significant in terms of searching for missing logs, filtering results in different ways, and creating the types of reports you need to address your specific use case.
