### ISSUE TITLE
Kitematic UI keeps freezing on Mac OS

### ISSUE THREAD

**Issue by LorenzoPrinsloo** [docker/for-mac#2993]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86A5C001-EF3B-4A8A-B465-C15F62B66A37

### Expected behavior
UI shouldnt freeze and allow to interaction
### Actual behavior
Unable to interact with kitematic UI even after restarting docker

### Information

  - macOS Version: High Sierra 10.13.3

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/86A5C001-EF3B-4A8A-B465-C15F62B66A37/20180612-165011.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

**Comment by djs55** [comment]
@LorenzoPrinsloo thanks for your report. It sounds like there is a bug in kitematic, rather than Docker itself. Could you create a ticket over on the kitematic issue tracker here: https://github.com/docker/kitematic/ . Feel free to link the new ticket to this old one.

I'll close this ticket for now as I think Docker Desktop is working correctly.
