### ISSUE TITLE
Docker Desktop for Mac Edge freezes

### ISSUE THREAD

**Issue by towen** [docker/for-mac#3020]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 574DBE94-DEAC-4EB6-986A-76EFD96787C0/20180620-104757

### Expected behavior
Docker to run consistently.

### Actual behavior
Docker freezes after about 5 min of activity. 

### Information
  - I have tried restarting Docker and the system multiple times.
  - Behavior started after I increased the Disk Image size and Memory allocation.
  - macOS Version: 10.13.5

### Diagnostic logs
```
Docker for Mac: version: 18.05.0-ce-mac67 (1fa4e2acfc1a52f79623add2390604515d32297e)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/574DBE94-DEAC-4EB6-986A-76EFD96787C0/20180620-104757.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --debug --info --style syslog --last \"1d\" --predicate \"process matches \\\".*(ocker|vpnkit).*\\\" || (process in {\\\"taskgated-helper\\\", \\\"launchservicesd\\\", \\\"kernel\\\"} && eventMessage contains[c] \\\"docker\\\")\" >\"/tmp/574DBE94-DEAC-4EB6-986A-76EFD96787C0/20180620-104757/docker-system-os.log\" 2>&1: exit 65")
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior
  - Restart docker or Start Docker on login.

**Comment by djs55** [comment]
@towen thanks for your report. Unfortunately due to the failure of the `log show` command we're missing most of the host logs. The VM logs look ok though, and seem to suggest that the diagnostics program was able to contact the `docker` daemon successfully. 

Could you describe more what happens -- what do you mean by "Docker freezes"? Do you mean the GUI? Or commands like `docker ps`? If the CLI, could you double-check that you have no `DOCKER_HOST` environment variable set? Sometimes I forget this myself and try to talk to a missing remote cluster.
