### ISSUE TITLE
EDBF8D3B-92CE-4A53-B0B1-EE9D1F2EC7CF/20180803060009

### ISSUE THREAD

**Issue by funthomas** [docker/for-mac#3141]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
after installation new version Docker crash with notifiaction
### Information

  - macOS Version: 10.13.6 (17G65)

### Diagnostic logs

```
Docker for Mac: version 18.06.0-ce-mac70 (26399)

```

### Steps to reproduce the behavior

after installation upgrade 

cannot install symlinks in /usr/local/bin (cannot handshake)

**Comment by ncsutmf** [comment]
I have also been getting the "cannot install symlinks in /usr/local/bin" error off and on for a while.  The error comes up when I first login and Docker starts up. Since the first time I saw this error I have updated both the OS and Docker, but I was still running High Sierra when it started happening.

diagnostic IDs: 
- 81F4C4DE-D0E1-4D05-9686-8E22CA54846A/20180831134222
- 81F4C4DE-D0E1-4D05-9686-8E22CA54846A/20180907134458

Currently running macOS High Sierra version 1.13.6 (17G65) and Docker 18.06.1-ce-mac73 (26764)

I'm usually able to launch Docker after the error pops up without any issues.  It appears all of the symlinks that are supposed to be there are there, so not sure why it is trying to create new ones, especially at run time (running as standard user) instead of at install time (running elevated as part of the installer).  Also not sure why some of the symlinks point to my user home directory when most modern operating systems are multi-user.

it also appears this has been an issue off and on, here are some of the others that look related: #1975, #2942, #2932

**Comment by sprig** [comment]
I'm having a similar issue on OSX Version 10.13.6 (17G65), Docker Version 18.06.1-ce-mac73 (26764) (as above).
Diagnostic ID: F867CCCB-29FF-407B-BBBC-A15F125315D2/20180907215054

On my end, I can semi-reliably reproduce this by locking my screen/letting computer sleep/closing the clamshell and then logging back in a few minutes later.

**Comment by null9beta** [comment]
i can confirm the same issues. actually it just started a while ago, not sure though that there was a docker or osx update in between. (i mean to identify any update on either side to have change something)

for me i cannot even see any relation to something else (like looking screen or similar), it eventually happens any time. Sometimes after 3 days. sometimes after a week. Sometimes just after an hour running docker.

OSX Version 10.13.6 (17G65)
Docker Version 18.06.1-ce-mac73 (26764) (as above).
Diagnostic ID: AF9F1A00-6E78-4854-AFD6-F1C47548FF1B/20180920133155

**Comment by ajmaddaford** [comment]
I also have this issue since the last time I updated Docker. Ignoring the error seems to allow Docker to carry on working as normal.

OSX Version: 10.13.3 (17D47)
Docker Version: 18.06.1-ce-mac73 (26764)
Diganostic ID: 531077BD-8030-4CFF-A3A8-842720CDC7A1/20180921140828

**Comment by funthomas** [comment]
hi, all. last week I made clean install macOS Mojave 10.14, after few times sleep my MB made this error made again. :( Docker automatically shutdown and start again. It is small bug I hope, but is very ugly for user experience. If I can send some other info about my system or what else please give me feedback soon.

**Comment by d1rtym0nk3y** [comment]
Same issue for me too
When i wake the system from sleep and login I will get a "Fatal Error: cannot install symlinks in /usr/local/bin (cannot handshake)" message.  Docker will then exit and restart without further complaint

OS: macOS 10.14 (18A391)
DOCKER: 18.06.1-ce-mac73 (26764)
Diagnostic ID: A9F7EB17-E78F-405B-A7EE-8122DE859678/20181024084248

**Comment by gilzow** [comment]
Ditto on this error message after logging into machine from a lock state.
OS: macOS 10.14
Docker version 18.06.1-ce, build e68fc7a
Diagnostic ID : 12486D6A-FEDE-459C-AE3A-78823C3427B1/20181109135638

**Comment by null9beta** [comment]
actually i have that problem now frequently, reproducable locking the screen e.g. going for lunch, after coming back and logging back into osx, docker is gone with that message.

here is another diagnostics id. 

OSX Version: "10.14.1 (18B75)"
Docker Desktop Version: "2.0.0.0-mac78 (28905)"
Diagnostic ID: "AF9F1A00-6E78-4854-AFD6-F1C47548FF1B/20181120115916"

Is there any information from the repo maintainer about a potential cause of this? Just wondering because we are posting lots of diagnostics ids here, but there is no response from any official side so far. That would be really helpful.

thanks :)

**Comment by mrsanchos** [comment]
Hi everyone. The same for me. After logging into machine from a lock state I have the same error:
"cannot install symlinks in /usr/local/bin (cannot handshake)"

MacOS-version: 10.14 (18A391)
Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
Diagnostic ID: 2E2125C9-5969-4E74-AAEC-9600C33651DF/20181122073208

**Comment by drorata** [comment]
I believe for me this error occurs when switching users on my machine. Here is the diagnostic ID: 758E8A62-A008-4E8A-9222-70C38BEF5F93/20190214142948

**Comment by sbagdadi-gpsw** [comment]
E58FDC99-DBE7-48FF-A12E-2E521BA777A7/20190326223947 -- Diagnostic ID

**Comment by totemcaf** [comment]
After locking and login again a dialog window appear with that message. Without touching the dialog Docker still runs.
