### ISSUE TITLE
Docker hangs after moving disk to external SSD

### ISSUE THREAD

**Issue by dipan66** [docker/for-mac#3152]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 17ED6860-1EEA-4907-B1A4-C7412F5A8D16/20180809100844

### Expected behavior
After using Docker "Move Disk Image" Docker should move the disk image to the external SSD and restart successfully
### Actual behavior
Docker moves the image correctly - but fails to start from there on. 

### Information
  - Is it reproducible?
     Yes. It is reproducable. I have now tried this twice in the space of 3 days. The result has been the same.
  - Is the problem new?
     Cant say. First time I tried this feature
  - Did the problem appear with an update?
     It certainly did appear after the latest update, but that may be coincidental
  - A reproducible case if this is a bug, Dockerfiles FTW.

  - macOS Version: MacOs High Sierra

### Diagnostic logs

```
Docker for Mac: version High Sierra (10.13.6)

```

### Steps to reproduce the behavior

  1. Install Docker on Mac. 
  2. install an external drive.
  3. Use "Move my image"

**Comment by eclaro** [comment]
I am having the exact same issue. Tried many times, after I move the disk Docker simply does not start anymore, and then I need to reset to factory again and again.

**Comment by adib** [comment]
I'm experiencing the same issue.

Docker version 18.09.0, build 4d60db4
macOS Mojave 10.14.1 (18B75)

**Comment by dipan66** [comment]
It works as expected starting from version Version 2.0.0.0-mac78 (28905). I am running it on macOs Mojave. 
Startup takes longer than it used to take on the internal disk (my external disk is a USB-C SSD - it is fast and is nearly as responsive as an internal disk for VirtualBox)
But once booted - Docker works stably.

**Comment by sivolobov** [comment]
Had the same issue.
After I clicked 'Open' button in dialog window where I chose folder on second internal drive (JetDrive SD card). I checked that in this folder appeared `Docker.raw` file with size `23,62G`. It was whole free disk space on that drive. After about 30 minutes Docker responded that disk have not enough space for moving. Then I noticed that in Docker preferences disk image size was set to 64 GB (note that my boot disk drive had about 15GB free space at all before docker setup). I reduced disk size to 16GB and started moving disk again. After about 20-25 minutes it successfully closed dialog window (where I chose new directory) and docker service restarted.
I think that you need to check disk space before Docker Desktop starts moving disk image.

Docker Desktop version: 2.0.0.3
Docker server version: 18.09.2

**Comment by lauer** [comment]
This issue should be reopen. I had the same problem. I could move the Docker.raw to an external SSD USB3 disk, bug after a restart, the docker machine could not be started, but just keep in "starting" mode.

**Comment by sphism** [comment]
Same problem on High Sierra, when i move image to external ssd it just hangs and never seems to finish

**Comment by vityafx** [comment]
The same with me, external SSD with exFAT, docker simply does not start.

**Comment by lauer** [comment]
I have reformatted the disk as APFS and now i had no problems in restarting my MacMini as long as the USB3 Disk stay attached on reboot.

**Comment by safaci2000** [comment]
+1 can you re-open the issue.  I moved my data to an external location and it gets stuck in the 'starting' and never finishing.

**Comment by sphism** [comment]
@safaci2000 I managed to move mine in the end by reducing it's size first to the smallest size, and then moving it to SSD... can't rememeber if I then resized it up but I would imagine you can once it's there.

**Comment by safaci2000** [comment]
Well, I had to do a factory reset.  I installed it on the new external volume and I'm trying to be careful to ensure I 
1. exit docker first
2. unmount volume
3. disconnect from the docking station 

to avoid any issues, but when I tried to start docker up after mounting the drive once more it got stuck in a loop.  

I did get it working eventually but this is less than stable.  I'm not really seeing a pattern yet as to when it gets in that loop.  

Also, is there a way to see the logs of the docker mac app.  Maybe see what it's trying to do as a guideline to what may be failing?

If this was on linux i'd check dmsg, and /var/log/docker or some variation to see what's hanging.  

What's the equivalent for Docker on mac to help troubleshoot.

**Comment by lbalmelli** [comment]
I am having the same issue here after installing an USB mounted SSD on my raspberry pi. I am building a private docker registry and had to use an SSD because of performance issue when using a SD-card and pushing images to the registry. 

After installing ubuntu 18.04 on the SSD and booting the raspberry, the installation of docker.io will fail. See the output below.

Any idea?

> sudo apt install docker.io
[....]
/lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-08-11 05:03:40 UTC; 49ms ago
     Docs: https://docs.docker.com
  ****Process: 1832 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 1832 (code=exited, status=1/FAILURE**)
Processing triggers for ureadahead (0.100.0-21) ...**
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.25) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

**Comment by Startouf** [comment]
Same problem here, docker stays in "Docker desktop is starting" loop on macOs after moving the images to the SD card

I had changed the image size to 32GB previously, and my SD card has ~60GB so it should not have been too much of a problem ?

Docker desktop community 2.1.0.3 build 38240
macOs 10.14.3

**Comment by GerbenRampaart** [comment]
I had this problem too. What solved it for me was doing Preferences -> Reset button -> Reset Disk Image. That removed all images but after that docker ran from the external disk. Kubernetes runs as well. Of course because of the reset, for Kubernetes it had to re-pull the Kubernetes images.

I run Mac OS Catalina and my external is an USB C Samsung T5.

**Comment by greatghoul** [comment]
I  had the same problem, it hangs on starting.

After tried a few time, I solved it by the following steps

1. Goto reset tab
2. Reset the disk Image only

Then docker will start successfully. (But you will lose your data)

![image](https://user-images.githubusercontent.com/208966/72037627-e042fd00-32d9-11ea-9034-bec66879f12b.png)

**Comment by GerbenRampaart** [comment]
@dipan66 can you re-open this? This is issue is very much alive in Catalina v19.03.5

**Comment by anastazya** [comment]
> @dipan66 can you re-open this? This is issue is very much alive in Catalina v19.03.5

Same for me on Mac OSX Mojave. It hangs indefinitely...

**Comment by poyynt** [comment]
Same here in macOS 10.15.3 Catalina

**Comment by thebennies** [comment]
running a fresh install on mojave 10.14.6.
moving image location to my 128gb thumb drive HFS.
continuing my work with files on my thumb drive, then my thumb free space went to 8kb.
quitting my work with files on thumb drive, after an hour or so, my thumb drive ejected automatically.
waiting for another hour, docker still freeze.
checking my thumb drive. no response.
shut everything down, restart my machine. blank screen, no apple logo, just a chime.
restart my machine with no thumb drive. succeed.
checking my thumb drive on other machine (win & nux). corrupted.
