### ISSUE TITLE
Issue with docker for mac

### ISSUE THREAD

**Issue by VBagmut** [docker/for-mac#3162]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ED5720CB-BFB1-432A-9274-9800FB27AFE3/20180816085321

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version 18.06.0-ce, build 0ffa825

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
