### ISSUE TITLE
Docker restarts alone with heavy usage

### ISSUE THREAD

**Issue by aferrandini** [docker/for-mac#321]
### Steps to reproduce
1. I have several containers with different services:

```
nginx
consumer_XXX_1
consumer_XXX_2
consumer_XXX_3
consumer_XXX_4
consumer_XXX_5
consumer_XXX_6
consumer_XXX_7
consumer_XXX_8
php
composer
rabbitmq
mongo
elasticsearch
memcached
```
1. MongoDB has a DB with 4GB of data.
2. When running a heavy query in MongoDB Docker engine is restarted.
### Expected behavior

It shouldn't be restarted.
### Actual behavior

It's restarted.
### Information

```
Diagnostic ID: F9D14306-DFB2-430B-83F3-F7C86BE4A7B2
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dloeckx** [comment]
I have the same issue, running rather heavy image processing in a container.

`Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/A8CA0F0E-F1D1-4CF6-B9AD-D9C3409B67D0/20161013-114545.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux`

**Comment by samoht** [comment]
@aferrandini your logs contains few:

```
VM: 2016-08-17 10:17:49 +0000 UTC kern.info kernel: auplink[24451]: segfault at 7ffee651fa28 ip 000000000043d049 sp 00007ffee651fa30 error 6 in auplink[400000+ca000]
```

Which should be fixed in more recent Beta releases as we upgraded the Linux kernel that we ship. So we advise you to update. Please re-open an issue if you still have some other problems. Thanks!

@dloeckx your issue is rather different. I see few:

```
Oct  9 10:57:48 Dirk-Loeckx Docker[com.docker.driver.amd64-linux][554] <Critical>: 9p: (Sys_error "/Users/dloeckx/Library/Containers/com.docker.docker/Data/database/.git/tmp/cbef53d3af6e69dbeb1f91a1101a04df241f8deb1dd8write: No space left on device")
Failed to write /Users/dloeckx/Library/Containers/com.docker.docker/Data/tasks/com.docker.driver.amd64-linux open /Users/dloeckx/Library/Containers/com.docker.docker/Data/tasks/com.docker.driver.amd64-linux: no space left on device
```

in the logs, which seems to indicate that your disk is full? Can you check if making some space on your disk is fixing your issue?

**Comment by dloeckx** [comment]
@samoht , thank you very much for the feedback. I cleaned up the hard drive, having >27GB of free space, but unfortunately still run into the same issue.

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/08529DC2-8DF4-4E6D-84F2-DB78B4035829/20161026-101015.tar.gz
```

I just had the issue twice in a row, the previous log ID is 08529DC2-8DF4-4E6D-84F2-DB78B4035829

Would be great if you could help!

**Comment by ijc25** [comment]
@dloeckx your latest bugball (08529DC2-8DF4-4E6D-84F2-DB78B4035829) indicates that the docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785. In your specific case may also be related to the previous disk space issues. If you continue to have problems then please open a fresh ticket since your issue is unrelated to the OP's issue.
