### ISSUE TITLE
cpu8700k  Supervisor has failed, shutting down: Sumac  ervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 726)

### ISSUE THREAD

**Issue by 13138678601** [docker/for-mac#3247]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
