### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by dantuswaroop** [docker/for-mac#3486]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by henning** [comment]
There is not a lot of information that could help people understand what your problem is and support them in helping you...

Could you fill in the form provided by the issue create dialog? 

Expected behaviour, what actually happens, etc? 

There's a good tutorial for this: 
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Nothing needs to be 100% perfect - but investing a bit more into the description than "Fatal Error" helps people who provide you software for free to help you and make the software better.
