### ISSUE TITLE
Kubernetes is starting ... indefinitely...

### ISSUE THREAD

**Issue by RoopGuron** [docker/for-mac#3516]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:914CA9B2-DE7D-486D-AEBA-30B8C4113FEF/20190208233346

### Expected behavior
Kubernetes is expected to start after few minutes
### Actual behavior
Kubernetes is starting......Runs indefinitely...for hours...
### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version...2.0.0.2 (30215) Channel: stable 0b030e17ca

```

![image](https://user-images.githubusercontent.com/10160285/52512270-caecbc80-2bb8-11e9-86a3-b9482d54c627.png)
### Steps to reproduce the behavior

 I have uninstalled docker and installed it again...same result ...I have Kubernetes enabled and as the orchestrator...

**Comment by RoopGuron** [comment]
Diagnostic ID: 914CA9B2-DE7D-486D-AEBA-30B8C4113FEF/20190208233346

**Comment by ChrisJ60** [comment]
I have the same issue on macOS 10.14.3. I was using the integrated Kubernetes just fine yesterday. Then I moved the Docker 'file storage' (Disk) to a non-default location (using the Docker GUI) as I needed case sensitivity (so I moved it to a filesystem formatde as case sensitive HFS+) and now Docker starts but Kubernetes is stuck forever in 'starting' state. I don't know if this is due to moving the storage or due to some other issue.

**Comment by shinwing** [comment]
same issue on macOS 10.14.3.
There is no problem with the old version, and it cannot be used after the upgrade.

**Comment by RoopGuron** [comment]
My Issue turned out to be protection piece of software that was modifying the /etc/resolv.conf on my mac.Essentially disrupting the DNS resolution process.
Once I turned off that piece of software, Kubernetes came back up.

**Comment by shinwing** [comment]
Since I can pull the images, so I think it should have nothing to do with dns.
