### ISSUE TITLE
Cannot create images greater than 10GB in size

### ISSUE THREAD

**Issue by scrotty** [docker/for-mac#352]
### Expected behavior

Be able to create images/containers that can grow to greater than 10GB
### Actual behavior

I see no way to achieve this. In the pre-"Docker-for-Mac" days, there were ways to (painfully) set this in VirtualBox. I don't see how this can be done with the current use of Hypervisor.framework.

Direction would be most welcomed!
### Information

Diagnostic ID: 9492A913-F82B-478C-81F5-D2257E44703C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
### Steps to reproduce
1. Create an image that can easily grow to more than 10GB in size.
2. Observe the "No space left on device" errors within the container

**Comment by ijc25** [comment]
Hi @scrotty thanks for your report and sorry for the delay in getting back to you.

This limit is odd because the default size of the backing disk image we create is 64GB, and AFAIK it always has been.

It's possible that the migration from toolbox resulted in a smaller sized disk being imported from there? If so then a factory reset would reset you to the default 64G, at the expense of losing your current images and containers. In fact regardless of how you ended up in this state I would expect a factory reset to return your to a 64G state.

Please could you try updating to the latest stable release (1.12.3) and if resetting does not help then please upload a new diagnostic (we now collect a lot more useful info).

I have noted your usecase on our internal tracking ticket for issues around disk resizing and configurability. The general case of disk image settings/growing/shrinking etc is tracked publicly by #371 (even though it appears to be more about shrinking).

I'll close, please subscribe to #371 but if a factory reset on the latest stable does not result in a larger disk please reopen this issue.
