### ISSUE TITLE
Fix for CVE-2019-5736?

### ISSUE THREAD

**Issue by rvolgers** [docker/for-mac#3521]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

After clicking "check for updates" I expected to see an update that would update the internal Docker engine to 18.09.2, which contains the fix for CVE-2019-5736.

Alternatively, a statement that Docker for Mac is unaffected. I don't think it  uses user namespaces but it could be unaffected if the `runc` binary is somehow immutable.

### Actual behavior

There is no update and the Docker engine version is 18.09.1, and I was unable to find a statement about whether CVE-2019-5736 affects Docker for Mac.

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Docker Desktop (Docker for Mac / Docker for Windows) is not vulnerable for this CVE, due to it using (among others) a read-only filesystem; an updated version of the Docker Engine (and runc) will be included in an upcoming update though.

For other versions of the Docker Engine, I listed the version that are patched in this comment: 
https://github.com/moby/moby/issues/38713#issuecomment-462690126

**Comment by guillaumerose** [comment]
Anew version of Docker Desktop with Docker 18.09.2 has been released yesterday.
