### ISSUE TITLE
Something wrong with time in container

### ISSUE THREAD

**Issue by Jokero** [docker/for-mac#3544]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I use timeouts or time sleep in my program, I expect that the next code will be executed not sooner than defined delay.

### Actual behavior
The next code might be executed sooner than defined delay.

### Information

It's reproducable only in docker on mac. I was not able to reproduce it on hosts (mac os, ubuntu) and in docker on ubuntu. 
Initially I faced the problem during developing nodejs application, so I created an issue in nodejs repository https://github.com/nodejs/node/issues/26155, but actually this is not a problem with nodejs itself, since I managed to reproduce it with python. 

  - macOS version: 10.14.3 (18D109)
  - docker desktop version: 2.0.0.3 (31259)
  - docker machine version: 0.16.1
  - docker engine version: 18.09.2
### Diagnostic logs

```
Docker for Mac: version...

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Steps to reproduce the behavior

1. Create `test.py`

```py
import datetime
import time

date = datetime.datetime.now()
time.sleep(3)
print (datetime.datetime.now() - date)
```

2. Run the script multiple times

```
docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app python:2.7 python test.py
```
3. Ideally in output you should see a value greater than 3 seconds:
```
0:00:03.007609
```
However, after nth attempt you can get the time less than 3 seconds:
```
0:00:02.971139
```
Although I defined that time sleep should take 3 seconds, it was less

**Comment by djs55** [comment]
Hi,

Looking at the python code, I notice the [time.sleep docs](https://docs.python.org/2/library/time.html) say:

> The actual suspension time may be less than that requested because any caught signal will terminate the sleep() following execution of that signal’s catching routine. Also, the suspension time may be longer than requested by an arbitrary amount because of the scheduling of other activity in the system.

which suggests that code needs to be robust to the sleep returning early (or late) in general (even though I don't think any signals were involved in this case)

I think the `datetime` module doesn't deal with monotonic clocks (where monotonic clocks are guaranteed not to go backwards and which are suitable for writing timing loops). I created a new file `test2.py`:

```python
#!/usr/bin/env python3

import time

start = time.monotonic()
time.sleep(3)
print (time.monotonic() - start)
```
and ran it with
```
docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app python:3.3 python test2.py
```

This works more reliably for me. I suspect the issue with the first python program is due to using a mixture of monotonic and non-monotonic clocks.

Unfortunately it's a known issue on macOS with Hypervisor.framework that the wall-clock in the VM drifts relative to the host at about 2ms for every 3s. We work around this by moving the wall-clock forwards every 30s which unfortunately isn't very smooth-- this may be what you're observing. I've written up more about this problem [here](https://engineering.docker.com/2019/02/addressing-time-drift-in-docker-desktop-for-mac/).

So I think Docker Desktop is working as expected, with the caveat that the wall-clock isn't very smooth. Monotonic clocks should be ok though.

**Comment by Jokero** [comment]
Thank you for the detailed answer. I will close the issue
