### ISSUE TITLE
Local folders with file greater than 1.6 GB locks up the volume.

### ISSUE THREAD

**Issue by mpalamara-otg** [docker/for-mac#355]
### Expected behavior

Run mysql schema files in volume attached to a local folder.
### Actual behavior

Volume freezes when mysql table file grows to 1.6 GB.
### Information

I'm using the official mysql image with a volume /var/lib/mysql attached to a local folder.  When I try to restore a database the volume freezes when a table file reaches 1.6 GB.  `ls /var/lib/mysql` locks up and the container will not shutdown.  I have to kill the docker daemon to stop the container. 

Diagnostic ID: 8EB86A87-4F0C-4F84-B3E6-75CE378D9F2A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Pull official mysql container.
2. Set volume /var/lib/mysql to a local folder on the base system.
3. Set MYSQL_ROOT_PASSWORD environment variable.
4. Start container.
5. Restore a mysql db from mysql dump file using the mysql client.  The mysql dump file needs a table file size that is greater than 1.6GB.
6. Monitor db files in local directory.
7. When table file is 1.6GB, in the container, `ls /var/lib/mysql`.  This volume should be locked up.

**Comment by ijc25** [comment]
Hi @mpalamara-otg, thanks for your report and sorry for the delay in getting back to you.

Are you still able to reproduce this issue with the latest stable (1.12.3 at the time of writing)? Your logs show various older issues (probably unrelated to what you have reported) which have been fixed since and there has also been many improvements to the storage subsystem since 1.12.0-a.

After upgrading the nature of the issues in your logs would lead me to recommend a factory reset, note however that this will destroy and existing containers and images.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
