### ISSUE TITLE
Docker for Mac: Kubernetes stuck at "Starting..."

### ISSUE THREAD

**Issue by kramey56** [docker/for-mac#3768]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 7FDEE889-52CF-47A1-B39B-8ACF024A5F83/20190726235201

### Expected behavior
Kubernetes should be ready after a startup period.

### Actual behavior
Docker engine starts up and then Kubernetes says it is starting and never proceeds past that.
### Information

  - macOS Version: 10.14.5

### Diagnostic logs

```
Docker for Mac: Community 2.0.0.3

```

### Steps to reproduce the behavior

  1. Enable Kubernetes
  2. Reset Docker
  3. Wait...

**Comment by chris9871** [comment]
Also experiencing this on the same Docker version on MacOS 10.13.6 (High Sierra).

**Comment by chris9871** [comment]
Also noted: the k8s container versions do not seem to be pinned to the docker version.  After installing 3 older versions of docker, I think this is related to the k8s container versions, not specifically docker.

**Comment by rvesse** [comment]
Also having the same problem:

- Diagnostic ID - 8C4E7831-A5F0-4B0F-B086-73648E96BA86/20190801093006
- Docker Desktop Community 2.1.0.0 (36874)
- OS X 10.14.6 (Mojave)

![Screenshot 2019-08-01 at 10 45 00](https://user-images.githubusercontent.com/2104864/62283453-7d575b00-b449-11e9-8889-345e365f8ac0.png)

I can see inside the Docker VM that it is stuck waiting for a `docker pull` to progress:

```
 ps | grep docker
 1152 root      0:00 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/docker -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
 1179 root      0:00 /usr/local/bin/docker-init /usr/bin/entrypoint.sh
 1379 root      0:00 {start-docker.sh} /bin/sh -x /usr/bin/start-docker.sh
 1383 root      0:00 /usr/sbin/sntpc -v -i 30 gateway.docker.internal
 1400 root      0:14 /usr/local/bin/dockerd -H unix:///var/run/docker.sock --config-file /run/config/docker/daemon.json --swarm-default-advertise-addr=eth0 --userland-proxy-path /usr/bin/vpnkit-expose-port
 1454 root      0:10 containerd --config /var/run/docker/containerd/containerd.toml --log-level debug
 1498 root      0:00 /usr/bin/trim-after-delete -- /sbin/fstrim /var/lib/docker
 2579 root      0:00 docker pull k8s.gcr.io/kube-apiserver:v1.14.3
 4867 root      0:01 containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/75e1dad55d52bf998ef668931203ed896296963f7ca0dd7c037ec8f0f830ae82 -address /var/run/docker/containerd/containerd.sock -containerd-binary /usr/local/bin/containerd -runtime-root /var/run/docker/runtime-runc -debug
 5942 root      0:00 grep docker
```

The `kubelet` is stuck waiting for a configuration file that doesn't yet exist:

```
> tail /var/lib/log/kubelet.log
2019-08-01T09:51:40Z kubelet + '[' -f /etc/kubernetes/kubelet.conf ]
2019-08-01T09:51:40Z kubelet + sleep 1
2019-08-01T09:51:41Z kubelet + '[' -f /etc/kubernetes/kubelet.conf ]
2019-08-01T09:51:41Z kubelet + sleep 1
2019-08-01T09:51:42Z kubelet + '[' -f /etc/kubernetes/kubelet.conf ]
2019-08-01T09:51:42Z kubelet + sleep 1
2019-08-01T09:51:43Z kubelet + '[' -f /etc/kubernetes/kubelet.conf ]
2019-08-01T09:51:43Z kubelet + sleep 1
2019-08-01T09:51:44Z kubelet + '[' -f /etc/kubernetes/kubelet.conf ]
2019-08-01T09:51:44Z kubelet + sleep 1
```

Have tried multiple resets (disk image, Kubernetes, Factory reset etc) with the same result

**Comment by chris9871** [comment]
I was able to recover using a factory reset.

**Comment by moberg** [comment]
I have the same or similar issue. After upgrading to 2.1.0.0 it seems like Kubernetes stops responding after running for a few hours. Restarting Docker leaves it stuck in starting state. The only thing that seems to resolve it is to reset Docker for Mac to factory defaults.

**Comment by rvesse** [comment]
My problem turned out to be networking issues with my Mac, if you have a poor connection then Docker simply cannot pull all the images required in a timely manner and the install eventually times out and fails.  Resolving the networking problems allowed a Kubernetes Reset to successfully reinstall the Kubernetes cluster

**Comment by siddharth1001** [comment]
I am still facing this issue.
Docker for Mac : Version 2.0.0.3 (31259)

**Comment by benweizhu** [comment]
![image](https://user-images.githubusercontent.com/5471228/79627219-190c3100-8169-11ea-9378-4d52a0954d76.png)

Still this issue

**Comment by alexeymarunin** [comment]
You can turn off Kubernetes by editing 
`~/Library/Group Containers/group.com.docker/settings.json`: 
```json
{
 ...
  "kubernetesEnabled": false,
 ...
}
```
and restart Docker Desktop

**Comment by WoodpeckerBaby** [comment]
Still having issues on the latest. This is a clean installation. 

<img width="767" alt="Screen Shot 2020-05-10 at 6 49 58 AM" src="https://user-images.githubusercontent.com/14303318/81486865-83a51e00-928a-11ea-808b-59947e6f9a73.png">
<img width="958" alt="Screen Shot 2020-05-10 at 6 50 07 AM" src="https://user-images.githubusercontent.com/14303318/81486866-856ee180-928a-11ea-8551-59164dfed3d9.png">

**Comment by anandjaisy** [comment]
First, quit the docker

Go to this location and edit the file

~/Library/Group Containers/group.com.docker/settings.json
{
  "kubernetesEnabled": false,
}

Restart the docker again and Enable the Kubernetes

**Comment by mikechen66** [comment]
Hi anandjaisy
I check the configuration in ~/Library/Group Containers/group.com.docker/settings.json,
it actually shows the following result.  

{
"kubernetesEnabled": false,
}

It means that it have already existed after the installation of Docker for Mac. Do you mean changing the "false" to "true"?

**Comment by mikechen66** [comment]
I check the issue and find the quickest way to solve the issue of kubernetes stucking in the waiting. Please see the following solution. 

$ rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
$ rm -rf ~/.kube

It takes about 6 minutes to complete the Kubernetes--Enable Kubernetes. 

Cheers...

**Comment by mikechen66** [comment]
There is a tricky issue during resetting the Docker Size on Mac. Since resetting the dock size in Mac, the following commands has not been effective.

$ rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
$ rm -rf ~/.kube

Kubernetes falls down into the forever waiting loop. I think that it is a big bug of Docker for Mac.
I may install Kubernetes with the command lines. I will go back to the discussion if I successfully install it.

Notes:

Docker for Mac set the whole available size with default. Mac's other(par of the hard drive) in the hard drive is so big. So it is necessary to adjust the docker size in Mac after optimizing the hard drive of Mac.

**Comment by mikechen66** [comment]
I have finally solve the problem with the strict steps as follows. 

**1. Select the items marked with the red color in Troubleshoot**

1). Reset Kubernetes cluster 
2). Clean/Purge data 
3). Reset to factory setting
4). Uninstall Docker for Mac

**2. Remove Docker for Mac from Applications** 

There are two ways. One is to remove Docker for Mac from Applications, and another is to replace the Docker for Mac with the new installation listed in the step 3. 

**3. Reinstall Docker for Mac** 

1). Click Docker.dmg

2). Drag and drop Docker for Mac to Applications 

If the old Docker has not manually removed from Applications. Mac usually reminds a user to replace the old one with a new installed Docker for Mac. 3). Open and Verify Docker for Mac

**4. Remove both pki and kube**

```
$ rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
$ rm -rf ~/.kube
```

**5. Set the items in Preferences**

1). General

Do not set tick for Start Docker Desktop when you log in. It wastes a lot of time while dealing with the Troubleshoot. 

2). Resources --> Advanced --> Swap

It is preferable to set Swap to 0 GB (or zero GB) because Kubernetes sometimes
keep starting while the Swap is set to any number being larger than 0 GB. Kubernetes is designed to use up the DRAM resource according to the Google principle. Swap is regarded as a bad habit in Kubernetes. 

For example. it is unavoidable to be failed while developers try to set up Swap on the Nvidia portable machines including Jetson Xavier, TX2 and Jetson Nano clusters for Kubernetes. The developers have to set the following command to disable the Swap functionality in the above-mentioned Nvidia machines. 

`
$ sudo swapoff -a  
`
(for Nvidia portable machines) 


3). Kubernetes

 Set tick to Enable Kubernetes 

4)Apply & Restart


Conclusion 

It usually take from 6 to 15 minutes to complete the setting depending on the factors including network speed, vpn and machine capabilities. It still has the unforeseeable factors to stop the successful configuration of Kubernetes even though adopting the above-strict steps. Or it functions bad for re-starting sometimes. I am wondering why Docker has not solved the big issue even though it has been existed for more than 2 years.
