### ISSUE TITLE
docker - issue

### ISSUE THREAD

**Issue by Brainfold** [docker/for-mac#389]
### Information

Diagnostic ID: D5EAA897-D5D2-49AF-83F4-8A164DB2CA86
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Not enough information to reproduce. 

Thanks

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during run-time in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
