### ISSUE TITLE
disk check failed

### ISSUE THREAD

**Issue by Napicciuto** [docker/for-mac#401]
### Information

Diagnostic ID: 422F87C3-EB7A-46D2-A42D-B2DECB114D22
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/napicciuto/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/422F87C3-EB7A-46D2-A42D-B2DECB114D22/20160823-003659/qemu-img-check.stdout 2> /tmp/422F87C3-EB7A-46D2-A42D-B2DECB114D22/20160823-003659/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by tan-z-tan** [comment]
I have the same trouble


### Expected behavior
want to change memory setting through preferences.

### Actual behavior
When i open preferenes.
```
Failed to retrieve setting values.
```

![image](https://cloud.githubusercontent.com/assets/2078683/17922250/067142e4-6a19-11e6-9103-cfffed6281c3.png)

### Information
If I remember correctly, i did followings:
- I changed memory setting from 2G to 4G.
- I updated docker_for_mac.
- Then this error started to occur when i opened preferences.

Diagnostic ID: 833E4FE1-EF8C-4D11-8957-65F5FAF70FE6
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/tanji/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/833E4FE1-EF8C-4D11-8957-65F5FAF70FE6/20160824-163429/qemu-img-check.stdout 2> /tmp/833E4FE1-EF8C-4D11-8957-65F5FAF70FE6/20160824-163429/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
@tan-z-tan your issue is the same as #411. Please track it there.

@Napicciuto I'm still looking at your logs but nothing looks obviously wrong (though, clearly something is wrong with the disk image).
