### ISSUE TITLE
Docker-compose overlapping volumes create an empty shadow file on Mac local filesystem

### ISSUE THREAD

**Issue by jtwebman** [docker/for-mac#4012]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1BE8057E-00AE-4F79-887B-E964947C4818/20191031190452

### Expected behavior

I would expect an empty file doesn't get created for a file that is volumed into another volume on the same container.

### Actual behavior

The file gets mapped in but creates an empty file with the same name in the local path for the other volume.

### Information

When you have a docker-compose file that maps a single file into the same folder structure as another volume in the same container Docker for Mac ends up creating an empty file with the same name in the local folder.

See my repo here with steps to reproduce: https://github.com/jtwebman/docker-shadow-file-issue

  - macOS Version: 10.14.6
  - Docker for Mac: 2.1.0.4 (stable)

**Comment by thaJeztah** [comment]
This is because of how mounting works on Linux; in order to mount something, Linux needs a mountpoint; which means that if you're mounting a file at `/foo` inside the container, that linux will create an empty file (if no file exists), and use that as mountpoint for the file you're mounting.

The same goes when mounting a directory (in which case an empty directory would be created if it doesn't exists)

You can either mount the containing directory instead, or create a dummy `local.json` upfront

**Comment by jtwebman** [comment]
Awesome thank you @thaJeztah for getting back to me so fast. I will just create a local.json file and check it into source control. As this was just a demo project I the real project we have lots of files that we don't want mapped into the directory.
