### ISSUE TITLE
$SSH_AUTH_SOCK is not being forwarded to docker

### ISSUE THREAD

**Issue by mariusgrigaitis** [docker/for-mac#410]
### Expected behavior

OSX ssh-agent socket is available (for mount) in containers

```
$ docker run -it -v ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK} -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" --rm alpine:3.4 /bin/sh -c "apk update && apk add dropbear-ssh && ssh -T git@github.com"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.3-7-g2f47d74 [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.2-11-g9b41a63 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 5968 distinct packages available
(1/2) Installing dropbear (2016.74-r0)
(2/2) Installing dropbear-ssh (2016.74-r0)
Executing busybox-1.24.2-r9.trigger
OK: 5 MiB in 13 packages

Host 'github.com' is not in the trusted hosts file.
(ssh-rsa fingerprint md5 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48)
Do you want to continue connecting? (y/n) yes
Hi <githubusername>! You've successfully authenticated, but GitHub does not provide shell access.
```
### Actual behavior

OSX ssh-agent socket is available, but does not work because it's a socket (unable to connect)

```
$ docker run -it -v ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK} -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" --rm alpine:3.4 /bin/sh -c "apk update && apk add dropbear-ssh && ssh -T git@github.com"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.3-7-g2f47d74 [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.2-11-g9b41a63 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 5968 distinct packages available
(1/2) Installing dropbear (2016.74-r0)
(2/2) Installing dropbear-ssh (2016.74-r0)
Executing busybox-1.24.2-r9.trigger
OK: 5 MiB in 13 packages

Host 'github.com' is not in the trusted hosts file.
(ssh-rsa fingerprint md5 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48)
Do you want to continue connecting? (y/n) yes
ssh: Failed to connect to agent

ssh: Connection to git@github.com:22 exited: No auth methods could be used.
```
### Information

https://forums.docker.com/t/can-we-re-use-the-osx-ssh-agent-socket-in-a-container/8152

It would be great if Docker for Mac would forward osx ssh-agent's socket into VM, just like how it does with docker.sock. Generic solution for socket would also help a lot.

**Comment by mariusgrigaitis** [comment]
#483 is related

**Comment by samoht** [comment]
Have you checked https://github.com/avsm/docker-ssh-agent-forward ? It seems to do what you want.

**Comment by mariusgrigaitis** [comment]
Solution that you provided works, but it's not convenient / experimental

* It requires to append additional parameters on every docker run command which complicates stuff like running containers through docker-compose
* It runs separate ssh-agent and shares your local key to that agent. What if your key is encrypted?
* We want to make our scripts / files as much platform-independent as possible and this complicates things

Would be a lot better if docker for mac provided native support for ssh agent forwarding or socket forwarding in general as mentioned in #483

P.S. currently docker.sock is forwarded, it's probably not that hard to achieve same solution for other sockets too.

**Comment by trinitronx** [comment]
I've run into problems trying to support the `ssh-agent` `SSH_AUTH_SOCK` specifically with "Docker for Mac".

The problem appears to be due to [`osxfuse` not supporting socket connections][1] across the OS X Host / Docker Container boundary.

So I can mount in the `ssh-agent` socket, it appears inside the container fine.  However, accessing it via `ssh-add -l` always results in: "`Could not open a connection to your authentication agent.`"

For example, I can find my `SSH_AUTH_SOCK` file on the OSX host (e.g.: `/private/tmp/com.apple.launchd.abCDEfghiJ/Listeners`)
Then, I can run a container using "Docker for Mac" by passing in the volume mount & environment variable arguments like:  `-v /private/tmp/com.apple.launchd.abCDEfghiJ:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent/Listeners`

Inside the container, the socket appears as a socket owned by `root`.  I'm running as `root` in the container & have `rw` access.  However, `ssh-add` cannot communicate over the socket.

```bash
[root@62b57964834a]# env | grep -i ssh
SSH_AUTH_SOCK=/ssh-agent/Listeners
[root@62b57964834a ansible]# env | grep -i ssh
SSH_AUTH_SOCK=/ssh-agent/Listeners
[root@62b57964834a ansible]# ls -l $SSH_AUTH_SOCK
srw-rw-rw- 1 root root 0 Feb  1 17:57 /ssh-agent/Listeners
[root@62b57964834a]# whoami
root
[root@62b57964834a]# ssh-add -l
Could not open a connection to your authentication agent.
```

[1]: https://docs.docker.com/docker-for-mac/osxfs/#file-types

**Comment by samoht** [comment]
@mariusgrigaitis @trinitronx I was maybe not very clear, but yes support for ssh agent forwarder is planned on our roadmap and is indeed very related to #483. I was just pointing out a possible workaround which works today while we implement the feature.

**Comment by MasterRoot24** [comment]
Ugh, I've just been caught out by this limitation of Docker for Mac 😞 I'm surprised to see that this has still not been resolved 👎

**Comment by andytson** [comment]
I'm not surprised at all. It's a complex issue that goes beyond what normal VM environments can support. I'd really like to have this feature, but I'm not going to assume an easy fix solution is possible.

**Comment by evgenysalnikov** [comment]
+

**Comment by isodude** [comment]
The clean way of working around this is to have a docker being responsible for the ssh-agent.
* Start a docker with a volume /agent and entrypoint ssh-agent
* Use docker cp to copy the private key to the container
* ssh-add the key and remove it.
* Use --volume-from instead of mounting the ssh-socket from localhost.

If you do it as a bash function the magic stuff can happen in the shadows.

**Comment by Mange** [comment]
That forces the user to unlock the key in that Docker container, bypassing
all local customization of the agent, password entry, etc.

Den fre 21 apr. 2017 09:46Josef Johansson <notifications@github.com> skrev:

**Comment by isodude** [comment]
True, but the alternative is worse?

Anyway there not that much you can customize in the local ssh-agent, and the same customization is possible to add to the docker ssh-agent that way. A plus is that it is consistent across platforms. You can also have different ssh-agents for different purposes.

**Comment by andytson** [comment]
Presumably a workaround that doesn't lose local customisations would be to:

* Start a docker ssh server container with the necessary volume
* Use --volume-from instead of mounting the ssh-socket from localhost.
* SSH with agent-forwarding to the docker ssh server container

That way you use your local ssh-agent

**Comment by hilt86** [comment]
copying / mounting a private key won't work if you store your ssh key on a hardware token such as yubikey.

**Comment by lox** [comment]
Copying / mounting private keys is not a good idea. If you are going to, @andytson's approach is the best of the bunch.

**Comment by cecemel** [comment]
at @andytson, since your solution seems to have consensus on its viability, would you mind elaborate a little bit on its steps for the less proficient docker users? Thanks!

**Comment by jesselang** [comment]
@cecemel, I've been using https://github.com/uber-common/docker-ssh-agent-forward which seems to implement @andytson's solution. It provides an sshd container that you can forward the Darwin agent do (`ssh -A ...`), and exposes the agent as a socket in a docker volume that the target container can then use. A crude diagram:

```
+--------+        +--------+             +--------+             +-----------+
|        |  SSH   |        | Filesystem  | Volume | Filesystem  | Target    |
| MacOSX | +----> |  sshd  | +---------> |  With  | +---------> | Container |
|        |        |        |             | Socket |             |           |
+--------+        +--------+             +--------+             +-----------+
```

There's also a [solution using pure `netcat`](https://github.com/docker/for-mac/issues/483#issuecomment-344901087), but I couldn't get it to work reliably for whatever reason.

**Comment by qliam** [comment]
If you want you cant mount a volume from ~/.ssh to /root/.ssh (you can replace root with your user)

**Comment by lox** [comment]
> If you want you cant mount a volume from ~/.ssh to /root/.ssh (you can replace root with your user)

Except it exposes all your keys to everything running in the container.

**Comment by danvaida** [comment]
@mariusgrigaitis for the GitHub cloning part, a workaround would be to use a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) instead, till this will be solved. Hope this helps :)

**Comment by glend** [comment]
> Except it exposes all your keys to everything running in the container.

Not a big deal in development environments.

**Comment by joeyhub** [comment]
The example in your original issue works for me on Linux with the exception that in the container I make the agent simply /ssh-agent to avoid anything strange from creating non-existent folders plus to also simplify things.

Your error report lacks some key details. What happens when you try to ls on the key in docker, cat it, echo the variable to make sure it's good, etc. Have you tested that on another hosts, checked mount options, etc? I might be wrong but I assume both docker.sock and the agent file are the same thing aren't they? A special file pointing to a unix socket? If that is indeed the case and it works for docker.sock perhaps Mac has a different security set up for SSH agent sockets. For me on Linux it looks like they are all sockets and there's no immediately obvious reason why one should work and not another beyond permissions on the host. Are you also sure that agent forwarding is working at all on your host? SSH might be working in an outer shell if ssh it taking your private key directly.

There is some good advice here: https://gist.github.com/d11wtq/8699521

In the long run using the default auth sock is a problematic. If you do a normal docker run or docker-compose run it'll be fine to mount it. You have to keep in mind if what you want to do is something you log in, run, wait for it to finish or if it's something you fire and forget. Basically you're going to have a problem with anything unattended or that you want to initiate through an interface other than SSH.

If instead you do something that daemonises containers and then close the session you started them in then your ssh sock will disappear and those containers will no longer be able to connect to SSH using your keys.

Mounting personal keys to a docker container is a particularly extreme risk and almost defeats the entire point. It's like storing your raw meat in the lion cage. Agent forwarding carries its own risks but is a mitigation of the risk introduced by exposing your keys.

In some cases keys wont be on the machine in question. You'll ssh into a docker host using agent forwarding and in this case you really don't want ssh agent to have persistence. Given that it's dependent on your originating connection, then it shouldn't be possible to make it persistent.

These problems aren't simply docker issues but fundamental to the way SSH key security works.

My recommendation is one of the following:

1. Create separate keys for development, builds, deploy, etc rather than having personal keys used. This wont always be perfect but at least you're not at risk of exposing your own personal keys.
2. Avoid the need for having to ssh into things altogether at all in docker. There are any number of approaches to this (is authentication for read access even needed in a secure network for example). Mirroring such that the problem only exists in one place is another approach (one container managers fetching everything that needs credentials).

**Comment by udondan** [comment]
While those in general are good recommendations, they don't fit every use case. People are using Docker for all sorts of things. [Here](https://groupon.github.io/ansible-silo/)'s a good example why a working ssh socket is required. Silo is a wrapper around Ansible which connects though ssh. Also, this problem is not limited to the ssh socket. It's a general problem with usix sockets, see #483. 

I think this issue can be closed, as it already is covered in #483.

**Comment by YRM64** [comment]
At the time Mariusgrigaitis posted, part of the dilemma stemmed from the fact that folks were trying to mount sockets like we mount files.  Stackoverflow (https://stackoverflow.com/questions/47334784/ssh-agent-forwarding-to-docker-alpine-container-from-Mac-Oslo) has a great article on sharing sockets between Mac through the hypervisor.  Many developers have been successful with using docker-ssh-agent-forward, however, it was an experimental process, and it was recommended for those who were attempting to do so, contact anil@recoil.org for immediate assistance.  There's also a README.md available on Github.

There's yet another option to run ssh-agent in your container, and access it through your MacOs.
The solution:  docker-ssh-agent.  How successful that has been for developers, tap me back at this posting and let me know of your experiences, whether they have been positive or negative.

**Comment by tamsky** [comment]
> There's yet another option to run ssh-agent in your container, and access it through your MacOs.

Running `ssh-agent` "in your container" (read: "on a Linux kernel") means
we can no longer use `ssh-add -K` which retrieves the per-ssh-key passphrase
from the OSX Keychain when decrypt/add-ing keys into the agent.

**Comment by mariusgrigaitis** [comment]
I've created another dirty solution to work-around this issue. See https://github.com/mariusgrigaitis/docker-mac-ssh-auth-sock

It's using undocumented features, etc. However it allows original example to work. No need to pass additional arguments, no need to use different manes for SSH_AUTH_SOCK, etc. Works the same as in Linux host ;)

Let me know what you think.

**Comment by ameesme** [comment]
@mariusgrigaitis Solution works perfectly in a run-context. Wish we'd have the ability to temporarily mount volumes in a build-context, which isn't possible.

**Comment by mariusgrigaitis** [comment]
Yes it's different kind of feature, hopefully will be solved by buildkit

**Comment by bryanhuntesl** [comment]
> Yes it's different kind of feature, hopefully will be solved by buildkit

Nope - not solved. Buildkit SSH support only really works on Linux not docker for mac.

**Comment by tedivm** [comment]
Any updates on this? It's pretty difficult to work with Docker on OSX with private repositories because of this issue.

**Comment by griddyphillip** [comment]
We're also experiencing issues making an in-container hot reload with private dependencies because of this issue

**Comment by wkornewald** [comment]
I've just published [ssh-agent-inject](https://github.com/ensody/ssh-agent-inject) which solves this problem by piping the ssh-agent socket into the Docker container. Since I've only tested this on Windows your feedback (via issues and pull requests) would be welcome. Pre-built binaries for macOS, Linux, and Windows can be found in the [Releases](https://github.com/ensody/ssh-agent-inject/releases) section.

**Comment by griddyphillip** [comment]
What is the correct forum to make this issue more visible?

**Comment by bryanhuntesl** [comment]
> What is the correct forum to make this issue more visible?

I honestly don't know - sometimes it feels like docker inc have slightly lost their way.

**Comment by dko-slapdash** [comment]
> The problem appears to be due to osxfuse not supporting socket connections across the OS X Host / Docker Container boundary.
> Socket files and named pipes only transmit between containers and between OS X processes – no transmission across the hypervisor is supported, yet.

@samoht, if ssh-agent socket forwarding doesn't work, why does mounting of /var/run/docker.sock from MacOS into a docker container works fine then? It's also a socket, and its mounting inside the container works!

```
From inside the container:

root@7b049f9511b6 /# ls /var/run/docker.sock
/var/run/docker.sock
root@7b049f9511b6 /# docker run hello-world
Hello from Docker!
```

**Comment by anchorite** [comment]
@dko-slapdash - I'm not sure that I understand your example correctly, but as far as I understand the issue is to share a socket between the macOS fs and the Linux VM running on the macOS. Sharing a socket between the containers or between the Linux fs and any container should work OK.

Please correct me if I'm wrong.

**Comment by dko-slapdash** [comment]
/var/run/docker.sock lives on MacOS host system (!). And is successfully passed inside the container with Linux. So after that I’m successfully running e.g. “docker build” from inside of a container, the same way I run “docker build” from the linux host system - i.e. the socket sharing really works for at least one example socket.

**Comment by sbussetti** [comment]
@dko-slapdash try doing it with an arbitrarily created socket on the host system, and then mount that socket inside the docker container.  Not with a special socket like /var/run/docker.sock that is automatically exposed.  This issue is specific to the macos implementation of how an arbitrary socket mounted into the container via the `-v` arg.   The socket file will be mounted, but socker communication will not be passed.  This issue doesn't exist on dockerd for linux, for example.

**Comment by dko-slapdash** [comment]
So the question is, how exactly does Docker understand that /var/run/docker.sock on MacOS is "special" (is the path just hardcoded somewhere?), and is there a way to make some other socket as "special" as the docker's one.

**Comment by udondan** [comment]
It doesn't matter. d4m is not open source. The docker core team needs to fix this.

My guess though: The docker socket originates from within the VM and is only made available to the host system.

**Comment by dko-slapdash** [comment]
Today Solomon told me that even his work-around for this is to ssh -A into the container, so I doubt the core team will implement it after 3 years of this ticket existence. 

What’s also pity is that even ssh -A like automation is not possible with pure docker-compose (as far as I see, please correct me if I’m wrong). A wrapping bash script is needed (which generates a public key from the current private one it it wasn’t generated yet, then mounts it inside the container’s authorized_keys, then starts docker-compose).

**Comment by guillaumerose** [comment]
With WSL2, we made lot of changes in Docker Desktop backend, it's much easier now to share Unix  Domain Socket.

The following build allows you to use ssh agent inside the virtual machine :tada:
https://download-stage.docker.com/mac/edge/38763/Docker.dmg

```
$ docker run -it -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" --rm alpine:3.4 /bin/sh -c "apk update && apk add dropbear-ssh && ssh -T git@github.com"
Unable to find image 'alpine:3.4' locally
3.4: Pulling from library/alpine
c1e54eec4b57: Pull complete
Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
Status: Downloaded newer image for alpine:3.4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.6-316-g63ea6d0 [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.6-160-g14ad2a3 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 5973 distinct packages available
(1/2) Installing dropbear (2017.75-r0)
(2/2) Installing dropbear-ssh (2017.75-r0)
Executing busybox-1.24.2-r14.trigger
OK: 5 MiB in 13 packages

Host 'github.com' is not in the trusted hosts file.
(ssh-rsa fingerprint md5 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48)
Do you want to continue connecting? (y/n) y
Hi guillaumerose! You've successfully authenticated, but GitHub does not provide shell access.
```

It's not yet portable with a command you can run on Linux but the basics are here. This feature should land in edge channel in few releases.

**Comment by cbrinker** [comment]
I installed the build published by @guillaumerose above, and tried the example. I could not get it to work. I kept seeing: 
```docker$ ssh-add -l
Error connecting to agent: No such file or directory
```
I double checked and the env variable looked correct (matched what was on the mac host), and the socket file looked to exist on the filesystem properly:
```
docker$ env | grep SSH
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.2DhpuutCw3/Listeners
docker$ ls -latr /private/tmp/com.apple.launchd.2DhpuutCw3/Listeners
srw-rw-rw- 1 root root 0 Sep 23 22:16 /private/tmp/com.apple.launchd.2DhpuutCw3/Listeners
```

I did notice there was no `SSH_AGENT_PID` but that is expected because on the host (mac) OS there is no dedicated `ssh-agent` process running. It is using some dynamic mechanism with the keychain to serve as an ssh-agent when required.

I'd love to know how I can make it work!

**Comment by guillaumerose** [comment]
@cbrinker use SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" in your container. Not the value of SSH_AUTH_SOCK on your host.

How it works:
1. A server (vpnkit-bridge) runs on the host waiting for the VM to connect (over vsock)
2. The VM starts. Inside, a service (vpnkit-bridge client) connects to the host side.
3. According to a well-known list of unix socket to forward, both ends listen what they need. 

```
var servicesConfig = Services{
	GuestServices: map[string]ServiceEndpoints{
		"docker": {
			Guest:   "/run/guest-services/docker.sock",
			Mac:     "docker.raw.sock",
			Windows: `\\.\pipe\docker_engine_linux`,
		},
                ...
	},
	HostServices: map[string]ServiceEndpoints{
                ...
		"ssh-auth": {
			Guest: "/run/host-services/ssh-auth.sock",
			Mac:   os.Getenv("SSH_AUTH_SOCK"),
		},
	},
}

```
4. If an external process connects to a unix socket, in reality, it connects to the bridge which multiplex all the traffic to the other end, that connect to the desired unix socket.

**Comment by cbrinker** [comment]
@guillaumerose I see. Yes, with those changes in place, it works quite well. I can't wait to see this land in a future real version! Thank you

**Comment by tamsky** [comment]
> > @mariusgrigaitis
> > Yes it's different kind of feature, hopefully will be solved by buildkit
> @bryanhuntesl
> Nope - not solved. Buildkit SSH support only really works on Linux not docker for mac.

Buildkit SSH support really works on Docker Desktop for Mac

##  On OSX: `docker build` using `buildkit` + `ssh-agent` works

These instructions were tested with:
- Docker Desktop for Mac `v2.1.0.3`
- Engine `19.03.2` (included with docker desktop)

## Assumptions:
- you have a configured/working `ssh-agent`/`SSH_AUTH_SOCK` in the shell where you execute your `docker build` command.

## `buildkit` requires the following configuration :
- `docker` config: ( `~/.docker/config.json` must include `"experimental" : "enabled"` )
- `dockerd` config: ( must contain `"experimental" : true`)
    In Docker for Mac, this is enabled through:
     "Preferences…" Menu > Daemon icon > Basic tab > enable: "☑︎Experimental features"
   ( Changes to the `dockerd` config file require a restart of `dockerd`. )
- When executing the `docker build` command, you must include two flags:
  1. Environment var `DOCKER_BUILDKIT=1`
  2. Add flag `--ssh default`
    (other argument values are possible;
    see `DOCKER_BUILDKIT=1 docker build --help | grep -A1 ssh`)
- `Dockerfile` file content must start with:  (per [these docs](https://docs.docker.com/develop/develop-images/build_enhancements/#overriding-default-frontends) )
```
# syntax=docker/dockerfile:experimental
```

- And Finally, within your `Dockerfile`, `RUN` commands that require `ssh-agent` access must include `--mount=type=ssh`

## Proof

**Comment by PhilipMourdjis** [comment]
@guillaumerose, Could you give more detail how this should work, I'm trying to use docker-compose but not getting anywhere
```
volumes:
      - ?:?
environment:
      - SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
```

**Comment by guillaumerose** [comment]
```
volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
environment:
      - SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
```

should work.

**Comment by metadan** [comment]
We've got round this in a makefile by assigning the value of the sock var to another var e.g.

`
composer-install:
	MSSH_SOCK=$$(echo $$SSH_AUTH_SOCK)
	eval $$(ssh-agent); \
	docker run --rm \
	  --volume $${PWD}/app\:/app \
	  --volume $MSSH_SOCK:/ssh-auth.sock \
	  --env SSH_AUTH_SOCK=/ssh-auth.sock \
	  --workdir=/app \
	  --volume ~/.composer\:/tmp \
	  --volume ~/.ssh\:/root/.ssh \
	  --volume /etc/passwd\:/etc/passwd\:ro \
	  --volume /etc/group\:/etc/group\:ro \
	  --user $$(id -u)\:$$(id -g) \
	  composer install --ignore-platform-reqs
`

**Comment by nopdotcom** [comment]
@guillaumerose If this is sufficiently configurable, it would serve for [forwarding the GPG socket](https://wiki.gnupg.org/AgentForwarding) too, which would be nice. Some companies mandate that trusted PGP keys have to live inside a hardware token like a Yubikey; to do anything with private keys then requires GPG agent forwarding.

**Comment by matttrach** [comment]
@tamsky, 
Thank you for the in depth analysis, am I right in saying this only works if the docker image was written to work with mac desktop? How would you modify a container that you do not control? I am stuck on the fact that you have to include "--mount=type=ssh" on any run commands that need to use your agent. Any RUN commands written for with the assumption of a mounted ssh agent would fail, right?

**Comment by guillaumerose** [comment]
The ssh agent feature is now available in edge channel.

**Comment by j0ju** [comment]
I tested the feature with SSH-Agent, will that feature also support the socket from the DISPLAY environment variable of OSX? Should I create a ticket?

**Comment by mfominov** [comment]
> The ssh agent feature is now available in edge channel.

thx.

what about this error message when running 
```
ssh-add -L
error fetching identities for protocol 1: agent refused operation

**Comment by andytson** [comment]
It works well for me, however I notice only the root user in the container has the right permissions to access it.

I'm not sure what's best then to run as a non-root user. Changing the socket's permissions on the host is problematic, but also putting something in the container to forward the socket to another file with permissions is also leaky abstraction as well.

**Comment by tamsky** [comment]
@matttrach asked:
> How would you modify a container that you do not control?
I'm not sure what you mean here by "container".   Did you perhaps mean 'image"?   You should be able to control your containers and you should be able modify and build images from `Dockerfile`.

> Any RUN commands written with the assumption of a mounted ssh-agent would fail, right?

Yes; prior to buildkit supporting `RUN`-time volume mounts/secrets... "a mounted ssh-agent" was not possible.

Each `Dockerfile` must add support for it, hence the requirement for the top line comment `# syntax=docker/dockerfile:1.0-experimental` in each `Dockerfile`.

**Comment by treyd** [comment]
somewhat of an ignorant question: if this is fixed in 2.1.4.0 in the edge channel, does that mean it is also fixed in 2.1.4.0 in stable?

if not, what (generally) is the roadmap for edge features/fixes to end up in stable?

**Comment by treyd** [comment]
I can confirm the 2.1.4.0 edge version works with the config described in this post (note, because it threw me for a loop - these mounted volumes have to be exactly what is described): https://github.com/docker/for-mac/issues/410#issuecomment-536531657

Will this be the final implementation for this feature?  If so, does this mean this will only work in this fashion on a Mac, and we would have to use a different method for Linux or Windows?

**Comment by jhg03a** [comment]
SSH_AUTH_SOCK support has existed without a problem on Linux for some time.

**Comment by jvcdk** [comment]
I am probably missing something, sorry... but I can get @guillaumerose's example working where he uses alpine:3.4 as base. But I am working on an image based on Debian (Stretch), and here it does not work. 

Do I need to install something specific? I tried to search for vpnkit-bridge but without any luck.

**Comment by treyd** [comment]
@jvcdk on debian you'll need to install openssh-client in the container.  i was able to get this to work while running 2.1.5.0 edge:

```
docker run -it -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" --rm debian:stretch /bin/sh -c "apt-get update && apt-get -y install openssh-client && ssh -T git@github.com"
```

**Comment by jvcdk** [comment]
Thank you, @treyd, for your quick answer.

I have been testing it a bit this morning and found out that it is because I have a USER statement in my docker file – i.e. I am running as non-root in the container. @andytson mentions it above but I found out there is an additional catch: You cannot use {{sudo}} either.

Is there a way around this?

**Comment by ajardin** [comment]
> Thank you, @treyd, for your quick answer.
> 
> I have been testing it a bit this morning and found out that it is because I have a USER statement in my docker file – i.e. I am running as non-root in the container. @andytson mentions it above but I found out there is an additional catch: You cannot use `sudo` either.
> 
> Edit:
> Work-around seem to be `sudo chmod 666 /run/host-services/ssh-auth.sock`
> 
> Thank you for your help :)

I had the same issue, and I fixed it by creating the mount point and changing the permissions within my Dockerfile. Here is the [related commit](https://github.com/ajardin/docker-images/commit/7028b03bfc5d6c98246a5a14fcf422d74baa7786) if it can help you.

**Comment by vcajes** [comment]
Hey guys, can anybody help me out here? I am testing this on docker edge v2.1.6.0.

First, I just create a new agent with a new socket on OSX and give full permissions:

`eval "$(ssh-agent -a ~/.ssh/ssh-auth.sock)"`
`chmod 666 ~/.ssh/ssh-auth.sock`

`docker run -it -v ~/.ssh/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" --rm alpine:3.4 /bin/sh -c "apk update && apk add dropbear-ssh && ssh -T git@gitlab.com"`

However, I am getting the following error: `ssh: Failed to connect to agent`

Then, if I try to use `openssh-client`:

`docker run -it -v ~/.ssh/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" --rm alpine:3.4 /bin/sh -c "apk update && apk add openssh-client && ssh-add -l && ssh -T git@gitlab.com"`

 I get the following error: `Error connecting to agent: Connection refused`

On the host, `ls -lhatr ~/.ssh/ssh-auth.sock` gives me:
`srwxrwxrwx 1 redacted staff 0 Nov 22 11:24 /Users/redacted/.ssh/ssh-auth.sock`

Additionally, I tried with debian as well as, but no luck:

`docker run -it -v ~/.ssh/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" --rm debian:stretch /bin/sh -c "apt-get update && apt-get -y install openssh-client && ssh-add -l && ssh -T git@gitlab.com"`

`Error connecting to agent: Connection refused`

Is there something am I doing wrong? I would really appreciate some help. Thanks! @andytson

**Comment by jvcdk** [comment]
@vcajes : The chmod command should be done within the docker container, not on the host.

**Comment by vcajes** [comment]
@jvcdk I have tested both approaches, with and without the chmod, on the host and/or on the container, still not luck. Getting the same errors as above.

**Comment by treyd** [comment]
@vcajes Your volume parameter needs to be exactly as above, i.e. `-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock`

You're not actually pointing at a socket on your host system, you're pointing at some other special machinery in Docker Desktop for Mac that enables specifically the SSH agent forwarding.

**Comment by LukasVice** [comment]
@vcajes actually you need to use exactly this mount:
`-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock`

**Comment by vcajes** [comment]
@treyd wow, it was just that. Thanks guys. Working now! :)

**Comment by cbrinker** [comment]
You can also extend the technique like this to get access to the docker socket from within a docker container:

```
-e DOCKER_HOST="unix:///run/guest-services/docker.sock"
--volume /run/guest-services/docker.sock:/run/guest-services/docker.sock
```

**Comment by fnkr** [comment]
I've made a solution for my employer which can be installed via Homebrew and runs as a service: [punktDe/docker-mac-ssh-auth-sock](https://github.com/punktDe/docker-mac-ssh-auth-sock). After install `-v $SSH_AUTH_SOCK:/foo` works on macOS like it does on Linux.

**Comment by jhg03a** [comment]
Workarounds hopefully are no longer necessary with edge builds (2.1.4.0+) and will be fixed for good once those get merged back to a stable release.

**Comment by mat007** [comment]
This will indeed be available in the upcoming (next week) Stable 2.2.0.0 release.

**Comment by endemics** [comment]
A little caveat:
I had trouble getting the feature that @guillaumerose implemented to work on one machine while it was working on another.
I found out that it was related to the fact that on the machine that wasn't working I was starting a new ssh-agent in the terminal where I was running the docker command (so I could control the keys added to the keychain for that particular session) and was expecting the value of SSH_AUTH_SOCK set in the shell of that terminal to be picked up.
Exporting the keys globaly and not starting a new ssh-agent ssh-agent worked so I suspect the value of SSH_AUTH_SOCK picked up is the one available in the environment of the Docker Desktop command.

**Comment by Apollorion** [comment]
On 2.2.0.0, Im still getting the result OP got in his example:

```docker run -it -v ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK} -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" --rm alpine:3.4 /bin/sh -c "apk update && apk add dropbear-ssh && ssh -T git@github.com"```

returns:

```Host 'github.com' is not in the trusted hosts file.
(ssh-rsa fingerprint md5 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48)
Do you want to continue connecting? (y/n) y
ssh: Failed to connect to agent

ssh: Connection to git@github.com:22 exited: No auth methods could be used.```

**Comment by endemics** [comment]
Hi, I can also confirm that the newest stable (2.2.0.0) work as intended when using the "magic" mounting path `-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock`.

Thanks so much @guillaumerose, I guess this issue might finally be closed after 4 years 🎉

**Comment by fnkr** [comment]
I'm not so sure this issue is fixed. Title and description explicitly mention `$SSH_AUTH_SOCK` and `-v ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}`. In our team Linux and macOS people both share the same `docker-compose.yaml` files. Unfortunately, this solution won't work in both cases, or at least I don't know how it could work without one part of the team being required modify or override every `docker-compose.yaml`. Maybe we could create another hack, like symlinking `$SSH_AUTH_SOCK` to `/run/host-services/ssh-auth.sock` in the Docker VM, but we we're hoping this issue would provide a solution that works out of the box and make hacks unnecessary.

**Comment by guillaumerose** [comment]
What about using a `. env` file and add `SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock` ?
Let's close this ticket. Please open a new one for improvements.

To conclude this ticket, in your `docker run` command, add this flags to get ssh agent forwarded:
`-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"`
