### ISSUE TITLE
Fail to logging from the Docker desktop app

### ISSUE THREAD

**Issue by ernestogarciatw** [docker/for-mac#4146]
I am using docker for Mac version 2.1.0.5 and when I tried to logging from the visual pop up it show an authentication error. I tried with different accounts  and different mac computers and obtained the same error. 

![image](https://user-images.githubusercontent.com/57636643/71265371-12cd8b80-2314-11ea-822c-c167a43f70fc.png)
![image](https://user-images.githubusercontent.com/57636643/71265511-59bb8100-2314-11ea-8ba2-c5deb7f0bbf4.png)
![image](https://user-images.githubusercontent.com/57636643/71265519-5d4f0800-2314-11ea-88c2-2ced619d7098.png)

**Comment by libra10062619** [comment]
I got the same issue. But I can login Docker Hub by using Chrome.

**Comment by suavesav** [comment]
I'm running into the same issue with 18.06.0-ce-mac70, so I suspect that the issue is not with the specific version of the desktop app but rather with whatever internal service is getting called to serve the login request.

This was working fine until a few weeks ago.

<img width="553" alt="Screen Shot 2020-01-06 at 1 43 21 PM" src="https://user-images.githubusercontent.com/3641655/71851347-33734080-308b-11ea-80a3-96cc8149f942.png">

**Comment by suavesav** [comment]
upgrading to 2.1.0.5 and logging into docker from the command line (`docker login`), logged me in on the desktop app as well
