### ISSUE TITLE
Bad version in the edge channel

### ISSUE THREAD

**Issue by OItsMAK** [docker/for-mac#4233]
The docker version on the edge channel is 2.1.7.0, but v2.2.0 is already out.

(Am I correct to assume that the edge version should be greater than or equal to the stable version?)

**Comment by stephen-turner** [comment]
That is not always guaranteed. We usually do an Edge shortly after the Stable release, but not necessarily immediately. In this case the gap will be longer than usual because we are dealing with bugs on the Windows version of 2.2, which are a higher priority. In fact 2.1.7.0 was the Release Candidate for 2.2, so they're already very close. Thanks for asking.
