### ISSUE TITLE
Settings UI not loading since latest update (2.2.0.0)

### ISSUE THREAD

**Issue by nWidart** [docker/for-mac#4239]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `6ADA9FAE-8A15-4157-9F36-DA6C80E479DF/20200129194539`

### Expected behavior
The settings UI to load

### Actual behavior
The settings UI does not load.

![image](https://user-images.githubusercontent.com/882397/73391302-f724b000-42d7-11ea-8ac0-79ef345cc4c0.png)

### Information

  - macOS Version: `10.14.6 (18G2022)`

### Diagnostic logs

```
Docker for Mac: `2.2.0.0 (42247)`

```

Thank you,

**Comment by axpendix** [comment]
I have the same issue as well.

**Comment by bwsewell** [comment]
Experiencing the same issue on MacOS 10.14.6, Docker for Mac 2.2.0.3

**Comment by nWidart** [comment]
The issue is still there for `2.2.0.3` indeed.

**Comment by zhangyonguu** [comment]
Still in `2.2.0.4`.

I restarted my Docker. Things happened in the following order：
1. Docker successfully started, the status of Docker turned to `running`, and kubernetes was in `stopped` status, the Setting UI was editable in an instant.
2. Then the Kubernetes started to start and the status of kubernetes turned to `strating` , the Setting UI was not editable.
3. The kubernetes continued to be in `starting` status and the Setting UI continued to be not editable.

I guess it is because the local kubernetes cluster failed to start.

**Comment by nWidart** [comment]
Interesting, my docker-kubernetes has never successfully started afaik. Could be related to the settings I suppose.
I could never figure out why it can't start its own kubernetes nodes. Since I use minikube, I haven't really looked into that.

**Comment by Jaggle** [comment]
Docker version 19.03.8, build afacb8b ; MacOS 10.15, same problem here.

**Comment by bwsewell** [comment]
If I'm remembering correctly, the only way I was able to resolve was to completely uninstall docker for mac from my machine. :(

**Comment by zhcppy** [comment]
I found a magical solution, first open the docker preferences settings, and then click the docker icon in the status bar to select restart. At this time, you will be surprised to find that the settings UI is no longer in the loading state, then select kubernetes in this short time, cancel the enable kubernetes option, finally click the application below and restart. docker returned to normal. All this should be caused by kubernetes not starting normally.

Docker version 2.2.0.5 
MacOS High Sieera 10.13.6

**Comment by nWidart** [comment]
@zhcppy Sadly it did not work for me and broke things more, docker doesn't start at all now:

![image](https://user-images.githubusercontent.com/882397/80063659-a7e8c700-8536-11ea-8c97-fc3e65178bbd.png)

**Comment by zhcppy** [comment]
Sorry, I did n’t help you. The reason why my kubernetes failed to start is the connection failure. You can also look at the log information of docker. I think the main reason for this problem is that kubernetes has been starting. The setting UI should return to normal.
<img width="1327" alt="屏幕快照 2020-04-23 16 40 58" src="https://user-images.githubusercontent.com/19264783/80079454-e1dfba80-8582-11ea-816d-fe4d5a786c91.png">

**Comment by ndevenish** [comment]
I had this same issue but seem to have recovered it. Version 2.3.0.3 (45519) on High Sierra (10.13.6). Hopefully some of this information is helpful for working out what the problem is.

Settings did as above. Clicking all the recovery buttons inside the debug tab did nothing ("Uninstall", "Reset to Factory", pressing them did _nothing_ - as in not even a popup for 'uninstall', I believe). Followed the instructions from https://docs.docker.com/docker-for-mac/troubleshoot/, ran:
```
/Applications/Docker.app/Contents/MacOS/Docker --uninstall
```
But got:
![Screen Shot 2020-06-24 at 17 28 01](https://user-images.githubusercontent.com/529963/85595419-be97c100-b640-11ea-917f-d49159b09a21.png)
Clicking "Factory settings" hung the process. Running diagnostics it said "Diagnose succeeded" but clicking "Open" or "Upload" hung the process. Throughout this Console.app was spamming:
![image](https://user-images.githubusercontent.com/529963/85595844-1cc4a400-b641-11ea-80a2-a86ac7a9608f.png)
and the process needed to be manually terminated.

_However_, something along the way seemed to have actually gotten far enough that the application thought that it was uninstalled - relaunching it required my login as though first startup, and then the settings window worked. I've run the uninstall from within the app and then relaunched to make sure that it's completely clean, and things seem to be working so far.

**Comment by huangyiminghappy** [comment]
i have the same situation in the newest docker 2.4.2.0 version,could anyone tell me what to do ?

**Comment by jackirvine97** [comment]
I had this issue when my Mac's storage was very close to full. Freeing up some space (~5GB) fixed the issue. Appreciate this might be a coincidence, however maybe worth trying?
