### ISSUE TITLE
Docker diagnostics hang forever

### ISSUE THREAD

**Issue by sgammon** [docker/for-mac#4319]
Yes, I have tried with the latest version of my channel (Stable or Edge)
Yes, I have _**tried and failed**_ to upload Diagnostics

### Expected behavior
I was filing a bug because of a software flaw in Docker. While doing that, the Github Issue template prompted me to run and upload diagnostics, and/or paste them into the issue. The issue template also casually warns that all issues will be closed if they do not contain diagnostics logs.

It would be eminently reasonable to assume such a process will complete successfully in almost any circumstance.

### Actual behavior
However, instead, the Docker diagnostics just hang forever.

### Information
  - **Is it reproducible?** No idea.
  - **Is the problem new?** Yes, presumably diagnostics worked before, if diagnostics are required to file issues about everything including diagnostics.
  - **Did the problem appear with an update?** Well, unless it was a flaw in the first commit of Docker, yes, it did. This is the same question again
  - **macOS Version:** `10.15.3` (Catalina)

### Diagnostic logs
*Well, this is awkward.*

```
Docker for Mac: 2.2.0.3 (42716)
Engine: 19.03.5
Notary: 0.6.1
Compose: 1.25.4
Kubernetes: v1.15.5
Credential Helper: 0.6.3
```

### Steps to reproduce the behavior
1. Own a mac
2. Keep your Docker for Mac software up to date

(discovered during research for #4318, originally from #4314)

**Comment by stephen-turner** [comment]
Strange, no-one else has reported this. I assume you tried more than once?

By the way, contrary to the claim in all your bug reports today, not all issues appear as a result of updates. Or at least, not as a result of updates of Docker Desktop. There are lots of issues that appear as a result of other changes on the user's computer such as new versions of the OS, other software being installed, networking changes, etc. That's why the question is useful.
