### ISSUE TITLE
Start daemon on macOS system boot

### ISSUE THREAD

**Issue by dachev** [docker/for-mac#4388]
Currently, the daemon is launched on user login which means that docker services are not available until a GUI session is established. This tight UI coupling is counter-intuitive, unnecessary, and limiting.

ref: moby/moby#40239
ref: docker/for-mac#4069

**Comment by dachev** [comment]
@pavelchalyk, @fnxpt, @UniBen, @mhio, @harrv, @sdt, and @samiracho the old issue was closed by the bot. Feel free to upvote again here.

**Comment by dachev** [comment]
@akimd @mikeparker @samoht @ijc @dsheets Is this project alive or just a PR stunt?

**Comment by harrv** [comment]
@dachev If there is a way to upvote an issue, I don't see it. I think the closest is to subscribe to an issue, and you did that for me by mentioning me in the comment. I am keen to see this issue worked on and resolved though. Requiring a login before containers can be started is quite bad for any docker-based service, and is a limitation that only exists on one platform (Mac) as far as I can tell.

**Comment by mikeparker** [comment]
Can you explain why you'd want to use Docker Desktop without logging on? Are you trying to use it to run production systems? Most people use (linux) servers for this. Docker Desktop is a developer tool, not a server tool.

We could make a Docker Desktop for MacOS Server edition, but that's not currently on the roadmap, as the vast majority of people run workloads either on cloud (linux) servers or local (linux) servers. After linux, windows server is 2nd in popularity. Docker Desktop is designed so that you can write your code and test your containers locally on a mac or windows machine then push them to a real server where they will host your functionality in a proper production environment.

We know that many teams begin with running containers off their local development laptop but ultimately this isn't a scalable solution and running containers in the cloud is so cheap and easy these days that we would rather focus on helping developers get ramped up using docker and then streamlining development flows into the cloud and local servers, rather than supporting production systems running from your laptop after you log off.

There are also implementation problems with keeping containers running after logging off, such as: should other users be able to see whats in another users containers? Many people would expect by logging off, their programs are not accessible from other users, so this behaviour would not be necessarily expected by all.

If theres a use case we've missed please let us know.

**Comment by samoht** [comment]
Please just don't tag random people in issues. I don't work at Docker anymore so I can't help you.

**Comment by harrv** [comment]
@mikeparker Thanks for asking. I'll give you my use case, and I'm sure there are a LOT of others. In my case it is home theater and home automation. There are a lot of docker images for such things, and in both of those categories they need to be running all the time in order to be effective.

I have a Mac mini at home. It is quiet enough to run in my bedroom and consumes low power so I am comfortable leaving it running 24/7. I fully recognize that linux is the most common platform to run containers in production. I also know that if I chose to I could run linux on my Mac mini. However, as a home user I also use my Mac for regular end user things, and I prefer the Mac OS for those things. I can't justify the expense of buying and running additional computers or servers at home just to run home automation and home theater containers.

I think a lot of small business owners would feel the same way.

I am comfortable with using plist files in /Library/LaunchDaemons in order to run non-docker services without a login required. I don't need any gui interface to docker. I just wish that the docker daemon could run as a service without any user session like so many other things can.

The multi-user scenario you mentioned is interesting, but in my mind very similar to the difference between LaunchAgents (associated with a particular user session) and LaunchDaemons (runs independently of any user session and is controlled via sudo). I'm talking about the latter here.

I know that Docker Desktop for Mac has a GUI so the user can set preferences, see a dashboard, etc. Could that not be separated from the docker daemon as it is on other platforms? It would give us so much more flexibility.

**Comment by dachev** [comment]
The biggest reason I would like the daemon to run at system boot is that I would like it to mimic production as closely as possible and be able to test container's interaction with host-system resources like mount points, servers, cron jobs, etc. This is a whole class of bugs that is currently impossible to test for.

It's been a while so details are fading but here is a concrete example that I ran into. I had a container running a node.js app that was port-mapping the host system's SQL server. Everything worked great on my Mac but failed miserably when I launched it in production because the node.js code (foolishly) assumed that the DB server will be already running and bailed out if 3306 didn't respond. This is bad design that would have surfaces if Docker Desktop acted more like the real thing.

As a general rule, when emulating an environment it's better to ask why make something different, rather than rationalize which features should be the same. That's because you can't predict all the ways your system is used, so why make it different? Imagine that MySQL, or NginX came as a Desktop Edition on the mac and could only be used after a user has logged in. Why?

I also think that the notion that someone might want to run production containers in macOS, or use Docker for personal automation, is not outlandish at all.

I don't understand the multi-user argument. Is this a problem specific to macOS? How is this different from running the system web server, a database installed with `brew`, or an application server. We are developers and *NIX users, we don't associate the little icon in the tray with the Docker system. That's what's outlandish to most of us.

**Comment by samiracho** [comment]
My use case is simple. I've a jenkins agent running on a mac to compile some apps. Some of them use docker to generate artifacts. I can start the jenkins agent as daemon but not docker. So right now the only way is to have a desktop session running.

**Comment by yvanfrey** [comment]
Very clearly stated @harrv and @dachev. The missed use case is that independent developers, small organizations, run all kinds of services on their Mac hardware. Not laptops, but Mac pros and Mac minis that are professionally run (secure location, high bandwidth internet connection, backed up, redundant) and that's perfectly fine, great business model that avoids having to pay hosting fees and installing apps on another platform, and... customers are happy. Furthermore, all other software I use, can be started at system startup, node web apps, databases, etc., just not dockerized sadly.

**Comment by emlynmac** [comment]
The primary use case for me here is having a full CI stack on a macOS machine - I don't want to have to have a user log in in order to get all my containers running.
I'd love to see this feature implemented.

**Comment by as19git67** [comment]
I vote for it too. Having Mac minis running stuff without need to be logged in.

**Comment by jmorcar** [comment]
Is there any update ? 

Do someone have any example with launchctl daemon? 

Which is the source binary command or commands to start kubernetes and docker cluster? 


With them it's possible to create a daemon plist file like a 

/Library/LaunchDaemons/com.you.docker.plist

**Comment by harrv** [comment]
I'm sad that there has been no response from the Docker team to this request other than to say, essentially, "Why on earth would you want to run a container 24/7, independent of any particular user session/login on a Mac? The Mac is a toy! Use Linux!" And when several of us answered that question with our very valid and specific use cases many months ago, we have heard no reply or follow up that would indicate that the Docker team is interested AT ALL in giving us a Docker engine for MacOS that doesn't require being tethered to a user session with a GUI.

I'm sad to say that, desperate for real Docker, last weekend I replaced the MacOS on my Mac mini with openSUSE Leap. Despite openSUSE being a fine OS, it still feels like I gave in to the man. Good luck to the rest of you who are still trying to run Docker on your Mac. I hope they eventually listen to user feedback and stop pretending like the only purpose for hosting Docker on MacOS would be to give a short demo on a MacBook or to build an image/solution for something that will then be deployed on Linux.

**Comment by eandersons** [comment]
@mikeparker, another use case would be remote development. I am using SSH to access files and SSH tunnelling to access sites that are running on Docker containers on my work Mac. If there is a need to restart Mac or a power outage happens, then Docker based sites cannot be accessed anymore and development is somewhat interrupted unless one attends the Mac to log in or asks someone to do it.

Of course, workarounds can be used (currently I have not tried any of them, but I am looking at the first one):
- connect to office Mac using remote desktop tools or solutions (DWService, UltraVNC or any other VNC, TeamViewer, AnyDesk or others; some of them may work and some not, it depends on if they are launched before user logs in) to log in so Docker Desktop is started;
- run Docker containers on home computer as all the necessary files can be accessed;
  that may need some additional tweaking though.

**Comment by marleyjaffe** [comment]
I'm currently considering rebuilding my whole home lab because of this issue. It's silly that I can't have docker run on boot up. Has anyone gotten farther at solving it than this post? https://stackoverflow.com/questions/42637339/how-to-start-docker-for-mac-daemon-on-boot

**Comment by andreas-berg** [comment]
"Docker Desktop is a developer tool, not a server tool." is really quite a silly statement. Just stumbled across this crazy-old limitation when setting up a docker-composed set of containers to run on an leftover Mac Mini as a server. 
Thumbs-up for fixing this limitation in Docker Desktop but until then a low-tech workaround is enabling [auto-login](https://support.apple.com/en-us/HT201476). Not a very secure solution since this leaves the (headless) MacMini unlocked, but at least the auto-login starts Docker Desktop (if it is setup to start on user login). Maybe a scripted screen-lock after Docker has started.. feels like year 2000 not >2020..

**Comment by yllekz** [comment]
"Docker Desktop is a developer tool, not a server tool." 

I find this statement strange. Docker Desktop is for personal use as well as enterprise. You cannot say "it's a developer tool" when it is objectively not that.

**Comment by robbiemu** [comment]
@marleyjaffe can't you just run docker-machine for your system daemon docker and use docker desktop only for temporary dev environments? I think that is how they are billing this software when they call it "a developer tool, not a server tool"

**Comment by coltoneshaw** [comment]
+1 for this.

**Comment by bristea** [comment]
Did anyone observe that nobody currently working for Docker ever replied to this? With this level of service, I wonder why would anyone ever want to even pay for the "developer tool". It is the same on the other projects.

**Comment by nicks** [comment]
We currently consider this out of scope for Docker Desktop.

To echo Mike's comment above - Over the past few years, we've been trying to focus Docker more on tooling for developing apps. You can read more about this shift in focus here - https://www.docker.com/blog/docker-next-chapter-advancing-developer-workflows-for-modern-apps/ .

We believe that running containers for dev environments and running containers in production often have conflicting requirements (and in this case, I consider "a mac in a closet" a form of "production"). 

I recognize that using a Mac Mini in the closet as a server is a legit use case -- i do this too :grimacing:. But it's not a use case Docker Desktop is focused on supporting right now. 

I think the honest thing to do is to close this ticket.

**Comment by dachev** [comment]
So launch sequencing and dependency management on reboot is not a valid use case for use developers to test? Wow, thanks for the wonderful dev tool.

**Comment by andreas-berg** [comment]
How should we understand this? 
Docker maintains two separate product lines: a toy product "Docker Desktop for X/Y/Z" for developers play around with and a production grade product "Docker Engine"? 
Afaik both lines are mostly the same tech with a few differing quirks, what is the point in messing with two product lines?
Docker Desktop is now available also for Linux, are the same intentional limitations as described here also added to the Linux version? Is Docker inteding to EOL the DockerEngine-product?
I ended up putting Linux&DockerEngine on my "macmini in the closet" since Docker Desktop for Mac simply is not stable enough to be run as "production"-server. 
Kudos though to Docker for making docker-compose so portable, minimal downtime and no glitches when copying volumes & docker-compose.yaml from MacOS -> Linux.
