### ISSUE TITLE
Provide option to disable the "rate Docker desktop" dialog

### ISSUE THREAD

**Issue by unikitty37** [docker/for-mac#4413]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 0AF36CC9-128C-4A2F-BC1A-3C33DA2C9C65/20200401115610

### Expected behavior

Docker for Mac lets me get on with my work, and only interrupts me for critical problems. If it wants marketing feedback, there should be a setting in Preferences to enable this. It should be **off by default**.

Alternatively, disabling "send usage statistics" should also disable these dialogs — but, in that case, "send usage statistics" should also be off by default (necessary for GDPR compliance, in any case, as sending unnecessary data off the user's machine requires explicit, informed, unforced, opt-in consent).

### Actual behavior

Docker for Mac pops up intrusive dialogs asking me whether I would recommend it to my friends. (The answer is "no, not while it puts the desires of Docker's marketing department ahead of the user's needs", BTW — though I expressed this somewhat more forcefully in the rating dialog!)

### Information

  - macOS Version: Mac OS X 10.14.6 (18G3020)

The problem is reproducible, but it presumably requires someone at Docker's end to trigger a survey. This particular instance appeared immediately after an update, but I can't remember if previous occurrences have done this.

Annoying people with these dialogs is counterproductive, as you merely get a load of low scores and angry responses. I can't see how you can get useful data on that basis.

### Diagnostic logs

I'm unable to attach the full output of the diagnostics from "Diagnose & Feedback" in the menu, as when I clicked on it, I got a notification that a file had been unarchived, but I'm unable to find the file that was created. It's **not** in the Downloads folder as I would expect!

```
Docker for Mac: version 2.2.0.4 (43472)

```

### Steps to reproduce the behavior

Keep using Docker for Mac. Eventually, it will decide to nag you. (Only the developers and the marketing department know how to trigger this!)

**Comment by stephen-turner** [comment]
@unikitty37 Let me explain what we are doing with this data, even if we might not end up agreeing in the end.

1. This is nothing to do with the Marketing department: it goes straight to Development. We (developers) read every comment, and it is the major source for what we prioritise on our roadmap. The feedback is incredibly valuable to us.

2. Contrary to your assumption, the feedback is overwhelmingly positive.

3. We do realise that it's too intrusive at the moment (mainly because we've had lots of feedback about this from the dialog!). It dates from the time when Docker Desktop was nothing more than a way of exposing the docker command line in your native Mac/Windows terminal, and we didn't have anywhere else to put it. Now that we have added a UI in the latest version, we plan to move the feedback dialog into our own UI, and also change the wording to make the question less silly.
