### ISSUE TITLE
Ability to find different release versions 

### ISSUE THREAD

**Issue by flxfxp** [docker/for-mac#444]
I'm looking for "Beta 15 Release Notes (2016-06-10 1.11.2-beta15)" as that's what my staging environment runs, and I'd like to keep consistency especially after the whole 1.12.0 drama.

Where can I download this release? Thanks

**Comment by funonly** [comment]
I would like this too since there is an amazing amount of issues and no movement in any of them.
If you found anything can you please share it here?

**Comment by Dominik-K** [comment]
You can download older releases on the beta channel. Unfortunately, you need to know the build number. See Docker [forum question](https://forums.docker.com/t/specific-docker-for-mac-version/16807).

The ones I've found:

* https://download.docker.com/mac/beta/1.12.0.9779/Docker.dmg (from [@cpuguy83](https://github.com/docker/docker/issues/24343#issuecomment-230605770)) 
* https://download.docker.com/mac/beta/1.11.2.9168/Docker.dmg (from [forum](https://forums.docker.com/t/specific-docker-for-mac-version/16807/3)

**Comment by flxfxp** [comment]
Thanks for beta/1.11.2.9168! It works on my PC but on my laptop it seems to fail on "rsa/crypto": verification failed, even though I have a valid beta token : /

Not supporting older versions is kind of unacceptable, what the hell...

**Comment by mchiang0610** [comment]
Thanks. Adding this as a feature request.

**Comment by ijc25** [comment]
Closing as per slack discussion with @mchiang0610

**Comment by lmakarov** [comment]
> Closing as per slack discussion with @mchiang0610
@ijc25, @mchiang0610 do you guys mind elaborating on why this is being closed as a "won't fix"?

**Comment by flxfxp** [comment]
Indeed. It would be great to update the participants and keep this process transparent.

**Comment by arnalyse** [comment]
Same here. If it weren't for the [Caskroom of `homebrew-cask`](https://github.com/caskroom/homebrew-cask/commit/ae4de82e170cb36386141c40f3deb983267627f5), I wouldn't have been able to find the old version.

I appreciate the forward momentum, but I'd really appreciate the access to older versions to downgrade if needed. 😅

**Comment by mkernel** [comment]
Same here. We are suffering from severe performance drops and would love to downgrade to the "latest fast build". Finding that one would help a lot.

**Comment by dsheets** [comment]
@mkernel have you tried the block device flush workaround in <https://github.com/docker/for-mac/issues/668#issuecomment-250406582>?

**Comment by mkernel** [comment]
@dsheets Yes. In those cases where we tried that we're still seeing underperforming containers.
So to do some performance measuring it would be really helpful to have a browseable archive of old docker versions.

**Comment by flxfxp** [comment]
I would still like a satisfying answer to the closure of this issue.

**Comment by friism** [comment]
(parts of response re-used from https://github.com/docker/for-mac/issues/1120#issuecomment-277774579)

@flxfxp we're continuously fixing bugs (including security-related problems), and those fixes are released in new versions of Docker for Mac. We don't support or patch older versions - we only support the latest version on the stable and beta channels respectively.

Because we want users to be running software that's patched and secure, we don't publicly document how to download and install old versions.

If you find incompatibilities between Docker 1.11 and newer versions, please open an issue so that we can address them.

**Comment by matthughes** [comment]
@friism To be frank, this a ridiculous response.  I know of no other open-source software project that behaves this way.  I understand the desire for forward progress but if I upgrade Docker for Mac and my dev environment is hosed due to a regression, my only recourse is to report the bug and wait for it to get fixed or fix myself?

Every package/artifact manager in the world allows you to downgrade -- including to insecure versions.  And please let's not throw around the security boogeyman as a real response; the official Docker yum repo allows me to go to older insecure versions https://yum.dockerproject.org/repo/main/centos/7/Packages/.  Why should Docker for Mac -- something that is for 99% of users, a *development* tool -- be treated different?

I'm not asking that this be baked into the software; just that the URLs for the old versions be discoverable somehow.  This secrecy doesn't even allow for good bug reporting.  Maybe I upgraded three times without noticing the bug get introduced.  If I was a good OS user, I would find which version broke the expected behavior.  But without being able to go to previous versions, I can't even report an accurate bug.

I implore you to reconsider this.

**Comment by rishighan** [comment]
@friism I deploy my app to Elastic Beanstalk and Amazon officially supports Docker version 17.03.1-ce as of August 2017. Are you saying that I have no choice but to switch deployment solutions to something that supports the bleeding edge version of Docker? I think that is not a reasonable approach to what is a real requirement by many developers.

I am not suggesting that you support all old releases, but at least make them available for download, with the caveats clearly documented. I would warrant that most developers are aware of what risks they are exposing themselves to using older versions, but to say that security issues and bugs can be resolved by _not_ making the older releases available for download is a little ridiculous.

**Comment by friism** [comment]
@rishighan Elastic Beanstalk is not a Docker product so I can't really comment on it, but I will note that it seems odd that AWS is trying to build a "supported" product on a version of Docker that's no longer supported.

If you want to use Docker, I recommend getting it straight from us (for example using Docker for AWS) or installing recent Docker versions on your AWS instances from Docker repos. 

If you're interested in Docker versions with longer support lifecycles, Docker Enterprise Edition is a great choice.
