### ISSUE TITLE
What happened to wireguard kernel module?

### ISSUE THREAD

**Issue by thebalaa** [docker/for-mac#4560]
What happened to `# ls /root/lib/modules/4.19.76-linuxkit/extra wireguard.ko` ?

We were hoping to depend on it being there!

**Comment by j0ju** [comment]
This is a similiar issue to #4549, used features have been vanished from the 2.3.0.x series.
Please include this again.

**Comment by thebalaa** [comment]
Thanks @j0ju, for connecting these issues!

**Comment by slushie** [comment]
This is affecting all of my users on `2.3.0.2 (45183)`. There is no kernel module for WireGuard included in the LinuxKit build for Docker Desktop. Initially, I assumed this was a bug for LinuxKit since there have been changes to the way the WG module is pulled into the kernel tree, but now I believe that is unrelated. 

The most frustrating part, for me at least, is that `docker version` reports the _exact same_ version strings for every component across this upgrade. That makes it really difficult to determine which users are affected. However, it's possible to get the build timestamp for the LinuxKit kernel and that can be used to identify affected users. 

```
$ docker run -ti --net=host  alpine uname -a
Linux docker-desktop 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 Linux
```

I'm currently recommending that users downgrade to the previous Docker Desktop release due to this and other issues in the latest release. We're waiting for a response from Docker, Inc. before suggesting that users upgrade.

**Comment by aharonnovo** [comment]
Link another issue for feature that vanished from 2.3.0.x series - openvswitch #4660

**Comment by slushie** [comment]
I've been motivated by the lack of response from Docker, Inc. that I put together [my own solution to build kernel modules for Docker VMs](https://github.com/slushie/docker-module-builder). I'm using it now to build the `wireguard` module for my users. Hopefully it can be useful for you as well!

**Comment by stephen-turner** [comment]
As of Docker Desktop 2.5, we are up to date with upstream LinuxKit.
