### ISSUE TITLE
`docker run` hangs after 2.3.1.0 -> 2.3.2.0

### ISSUE THREAD

**Issue by GrahamCampbell** [docker/for-mac#4723]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 033393C4-DA56-4CE5-A7D9-1AF56515FB65/20200630161802
  - macOS Version: 10.15.5 (19F101)
  - Docker for Mac: 2.3.2.0 (46268)

**Comment by DoDoENT** [comment]
Same happened to me, but it was because it waited for file system synchronization to finish. After waiting almost an hour (I want to bind-mount a folder that is over 40 GB large), it failed with error
```
docker: Error response from daemon: unable to enable two-way sync on /Users/dodo/Work/Microblink/core-utils: list failed: grpc: trying to send message larger than max (59176125 vs. 26214400).
See 'docker run --help'.
```

I am now trying to switch to stable version.

**Comment by GrahamCampbell** [comment]
I unchecked all the directory syncs from the settings (contrary to the docs) and rebooted. Then it seemed to sync automatically, and sent me push notifications for what it was syncing.

**Comment by masterkain** [comment]
using edge I have found that if your folder has large files (mine was a 5GB log) the daemon does not respond in time.
I deleted the file and it started.

However I'm having issues with this new two-way copy functionality:

- file watchers does not work (I use `guard` to run tests)
- although I tried to disable the folders in File sharing they will perform the copy anyway since I have `:cached` in my volume in `docker-compose.yml`

**Comment by GrahamCampbell** [comment]
> I have the same folder appearing twice in Docker File Sharing UI

I am seeing this also.

**Comment by DoDoENT** [comment]
With stable v2.3.0.5 this does not happen.
