### ISSUE TITLE
Error "Your computer was restarted because of a problem" when I put my Macbook to sleep with Docker for Mac running

### ISSUE THREAD

**Issue by thijskaspers** [docker/for-mac#4916]
I was wondering if anyone else has this issue too?

Whenever I have Docker for Mac running and I close the lid of my Macbook Pro 16", I end up seeing "Your computer was restarted because of a problem" when I open my laptop again after a few hours or the next morning.

There isn't a single day this isn't happening for me, unless I manually shutdown Docker for Mac before putting the laptop to sleep.

This has been happening since macOS 10.15.4, and strangely didn't happen anymore in macOS 10.15.5 and the error has now returned after upgrading macOS to 10.15.6.

I'm still unsure if this has something to do with virtualisation of macOS, my settings, or that there is a bug in Docker for Mac that is causing this.

My Docker for Mac version is 2.3.0.4

**Comment by glenpike** [comment]
Anecdata, but I've been having a lot of these errors recently, even after Apple pushed something that's supposed to fix it.
Not sure if it's because I have Docker running or not - I always do - it's intermittent.  I only have 8GB of memory on my machine and Docker uses about 7GB of that, so wondering if there are issues with memory and waking 🤷

**Comment by thijskaspers** [comment]
For me it shouldn't have to do with lack of memory I guess. I have 64GB, and 48GB of that is available for Docker.

**Comment by jdam68** [comment]
I have the same issue as @thijskaspers on two similar machines:
* mbp 16'' 64gb and mbp 16 32gb (early 2020 models)
* docker desktop 3.1.0
* macOS to 10.15.6

If I don't kill docker before going away for longer than 30minutes, the computer dies and I get the "Your computer was restarted because of a problem" message. Killing docker solves the problem but I often forget to do it because I use it everyday.
