### ISSUE TITLE
unable to create context store: $HOME is not defined

### ISSUE THREAD

**Issue by FlorianVeaux** [docker/for-mac#4919]
### Expected behavior

Running docker commands without an `HOME` environment variable set up should work.

### Actual behavior

Running `HOME="" docker run python` now returns `unable to create context store: $HOME is not defined` with the following configuration:

docker-desktop-for-mac: 2.3.0.5 (48029)
Channel: stable
Engine: 19.03.12

The same commands works with the same version of the docker engine but v2.3.0.4 of docker for mac.

### Information
The problem has been reproduced on other macOs machines. This behavior seems to have been introduced with docker for mac 2.3.0.5.

Reproduction steps should be as simple as running `HOME="" docker run <ANY_IMAGE>`
  - macOS Version: 10.15.16

**Comment by gtardif** [comment]
Thanks for the feedback, we re working on a fix for this. 

In the meantime, as a workaround, you can turn off cloud experience and this should allow you to run with HOME="".
(in desktop Preferences > Command line, turn off "enable cloud experience")

**Comment by FlorianVeaux** [comment]
Thanks for the quick answer. The workaround works great for the time being 👍

**Comment by edgarlanting** [comment]
Thanks for the quick follow up @gtardif I went back to one version older to work around this.

**Comment by gtardif** [comment]
For our information, what is the reason for setting HOME="" ? Trying to better understand the use case behind this

**Comment by edgarlanting** [comment]
Hi @gtardif in my case I did not change any env vars on my Mac. My $HOME was set and during spinning up containers this behaviour was caused.

**Comment by WilliamMayor** [comment]
We had this issue too (glad to see there's a workaround).

In our case  we use `.env` files to really explicitly list the environment that will be used to run a script or passed to an image. We keep various `.env` files around in order to test an image in `.env/production` or `.env/testing`. We're trying to keep the environment in develop as "clean" as the one in production so we don't have odd errors when we deploy.

There are lots of scripts that run in these environments. Some run on the host machine, some run inside docker containers, some call docker commands.

We ended up putting `HOME=/Users/xyz` into our `.env` files in order to get the scripts to run. But this means in some cases that we'd run a script inside a docker container that referenced a completely wrong HOME path.

I'm not sure I've explained our use case very well here. Sorry about that :(

**Comment by Panfilwk** [comment]
> For our information, what is the reason for setting HOME="" ? Trying to better understand the use case behind this

As another datapoint, this was happening for us due to some integration with bazel. Bazel clears most environment variables by default in its execution sandbox, including `$HOME`

**Comment by xjbhenry** [comment]
> > For our information, what is the reason for setting HOME="" ? Trying to better understand the use case behind this
> 
> As another datapoint, this was happening for us due to some integration with bazel. Bazel clears most environment variables by default in its execution sandbox, including `$HOME`

having the same issue with bazel as well

**Comment by JoshuaCrestone** [comment]
@Panfilwk - did you have a fix for getting things working with Bazel?

**Comment by mvladev** [comment]
> having the same issue with bazel as well

You can workaround the bazel issue by passing the HOME environment. e.g.

```
bazel build --action_env HOME=${HOME} //...
```
