### ISSUE TITLE
Another container breaks when using gRPC FUSE

### ISSUE THREAD

**Issue by hughsw** [docker/for-mac#4972]
Similar to issues reported in #4964 but I don't know enough to say that this is the same issue.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  CDF6C54F-DD10-459F-9401-2F769C811A8F/20201004195811

### Expected behavior

I expect that latest Docker for Mac with default gRPC FUSE settings will correctly run my containers that use host file sharing.

### Actual behavior

MariaDB (InnoDB engine) fails to work in a container with the DB files mounted via file sharing.   When executing queries it returns errors like `Table 'dockergrpc.roomtypezonemaps' doesn't exist in engine`.

If gRPC FUSE is turned off in the Preferences (so osxfs is used), the container runs without errors.

### Information

- Reproducible (see below)
- New problem with latest Docker for Mac update
- macOS Version: 10.15.6
- MariaDB image: `mariadb:10.4.13`

### Diagnostic logs

```
Docker for Mac: version... 2.4.0.0 (48506) stable

Diagnose succeeded
```

### Steps to reproduce the behavior

The attached tar file has a `Readme.md`, a `./run` script, and a `./mysql` folder of MariaDB database files.  Just run the script and use any SQL client to try to access any data in the `dockergrpc` database.  If you don't have an SQL client ready to 
 hand, run the script and then run this docker command and look for the errors in the output:
```
$ docker exec docker-grpc-fuse-bug  mysql_upgrade -u root -pDockerForever
```

[docker-for-mac-grpc-bug.tar.gz](https://github.com/docker/for-mac/files/5324276/docker-for-mac-grpc-bug.tar.gz)

**Comment by djs55** [comment]
@hughsw thanks very much for the repro -- the `mysql_upgrade` produces these errors for me:
```
Phase 6/7: Checking and upgrading tables
Processing databases
dockergrpc
dockergrpc.bidlinespecificationcommaps
Error    : Table 'dockergrpc.bidlinespecificationcommaps' doesn't exist in engine
status   : Operation failed
dockergrpc.roomtypezonemaps
Error    : Table 'dockergrpc.roomtypezonemaps' doesn't exist in engine
status   : Operation failed
information_schema
performance_schema

Repairing tables
dockergrpc.bidlinespecificationcommaps
Error    : Table 'dockergrpc.bidlinespecificationcommaps' doesn't exist in engine
status   : Operation failed
dockergrpc.roomtypezonemaps
Error    : Table 'dockergrpc.roomtypezonemaps' doesn't exist in engine
status   : Operation failed
Phase 7/7: Running 'FLUSH PRIVILEGES'
OK
```
(this is with the latest 2.4.0.1 snapshot which fixes a number of filesystem issues)
I've had a quick look through the filesystem-level trace and also `strace`'d the `mysqld` process during the upgrade but I've not yet spotted the difference. I'll have to dig deeper.

Thanks again for the repro instructions!

**Comment by djs55** [comment]
Looking at a low-level trace of the failing upgrade I see:
```
2020/10/15 18:24:16 rx 224: LOOKUP i16 ["BidLineSpecificationComMaps.frm"] 32b
2020/10/15 18:24:16 tx 224:     OK, {i17 g18 tE=1s tA=1s {M0100640 SZ=1080 L=1 0:0 B8*4096 i0:57534373 A 1602786158.000000 M 1601734091.000000 C 1602786158.464658}}
...
2020/10/15 18:24:49 rx 2834: LOOKUP i16 ["BidLineSpecificationComMaps.frm"] 32b
2020/10/15 18:24:49 tx 2834:     OK, {i17 g18 tE=1s tA=1s {M0100640 SZ=1080 L=1 999:999 B8*4096 i0:57534373 A 1602786158.000000 M 1601734091.000000 C 1602786256.248817}}
...
2020/10/15 18:24:56 rx 21392: LOOKUP i16 ["BidLineSpecificationComMaps.frm"] 32b
2020/10/15 18:24:56 tx 21392:     OK, {i17 g18 tE=1s tA=1s {M0100640 SZ=1080 L=1 999:999 B8*4096 i0:57534373 A 1602786158.000000 M 1601734091.000000 C 1602786256.248817}}
...
2020/10/15 18:24:56 rx 21504: LOOKUP i16 ["bidlinespecificationcommaps.frm"] 32b
2020/10/15 18:24:56 Found linked inode, but Nlink == 1, ino=57534373, fullPath="bugs/mysql/docker-for-mac-grpc-bug/mysql/dockergrpc/bidlinespecificationcommaps.frm"
2020/10/15 18:24:56 tx 21504:     OK, {i17 g18 tE=1s tA=1s {M0100640 SZ=1080 L=1 999:999 B8*4096 i0:57534373 A 1602786158.000000 M 1601734091.000000 C 1602786256.248817}}
```
-- I'm a bit suspicious about this because the first lookups use file case `BidLineSpecificationComMaps.frm` whereas the last one is all lower-case `bidlinespecificationcommaps.frm`. I'm not 100% sure if this is the root cause of the problem, but the behaviour of gRPC FUSE is subtly different to the previous system `osxfs` with regards to case. The new system is stricter, and tries to reject file accesses which don't use the canonical file case (where canonical is the case the file was created with). The rationale is to ensure that containers work correctly when run in production on Linux, where the filesystems are all case-sensitive and where `BigLineSpecificationComMaps.frm` is a different file than `bidlinespecificationscommaps.frm`.

I'll dig further.

**Comment by djs55** [comment]
@hughsw there is definitely a case-sensitivity issue when switching from `osxfs` to gRPC FUSE; from this stack overflow post: https://stackoverflow.com/a/64146846/6774019

> The `lower_case_table_names` setting tells mysql how to store and compare table names. If the file system the database is stored on is itself not case-sensitive, it will force you to use `lower_case_table_names=2`.
>
> The MacOS filesystem is not case-sensitive. Up until Docker Desktop 2.4, the mysql container apparently didn't know that the underlying filesystem is not case-sensitive and set `lower_case_table_names=0`. However, since upgrading to Docker 2.4, Docker is apparently smarter about how it mounts volumes. So the container realizes its running on a case-insensitive filesystem and forces `lower_case_table_names=2`. The problem is that you cannot change the value of `lower_case_table_names` after initializing the database. And since the data dictionary was initialized with `lower_case_table_names=0`, it will fail to initialize with the server set to `lower_case_table_names=2`.

I suspect dumping the database SQL with `osxfs` and re-importing it with gRPC FUSE and an empty `/var/lib/mysql` would fix the problem.

However there is a more reliable and higher performance potential fix that I'd like to get your opinion on: rather than use files shared from the host for `/var/lib/mysql`, how about using a persistent `docker volume` like this:

```
docker volume create persistent-var-lib-mysql
docker run -v persistent-var-lib-mysql:/var/lib/mysql ... mariadb:10.4.13
```
With a persistent docker volume the files are stored directly in the Linux filesystem inside the helper VM, rather than on the host. The volume is persistent and survives until you manually call `docker volume rm`. It stays around even if the containers are destroyed and re-created.

This means that
- I/O is fast because it doesn't have to be remoted from the VM to the host. Databases expect their backing storage to be fast and local, rather than remote like NFS.
- filesystem behaviour is 100% Linux, rather than being a compromise between Linux and macOS (which Linux containers don't expect)

So this should be faster during development and then more likely to work perfectly in production.


If you want to access the volume contents you can attach it to another container e.g.
```
docker run -v persistent-var-lib-mysql:/var/lib/mysql alpine tar -c -C /var/lib/mysql . | tar -xv
x ./
x ./aria_log.00000001
x ./mysql/
...
```
For a compose example have a look here: https://github.com/docker/awesome-compose/tree/master/nextcloud-redis-mariadb -- you would need an extra `volume:` section:
```
version: '3.7'
services:
  ...
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
```
Let me know what you think of this possible approach. Do you think it could work? There may well be usability issues that I've not thought of -- your feedback is most welcome.

Thanks again for the very interesting bug report!

**Comment by djs55** [comment]
As a further experiment, running a Samba server to expose a named volume might work. I tried:
```
docker run --rm --name samba -p 139:139 -p 445:445  -v persistent-var-lib-mysql:/mount dperson/samba -p -n -s "mysql;/mount
```
and then was able to see the files from a windows machine by opening `\\<IP of Mac>`. Unfortunately I wasn't able to mount them from my Mac but I suspect filesharing isn't working for other reasons (I'm on the Big Sur beta)

**Comment by hughsw** [comment]
@djs55 Thanks for the sleuthing and pointers to the (likely) underlying cause.

Runtime performance isn't an issue for our developers using Mac OS X, and using Docker volumes would obscure desired transparency.  These containers are being run on Mac as part of developer forensic work on the DB files backed-up from a live Linux site by `mariabackup`.  Dumping and rebuilding via an SQL-file round trip might be an option, but our DB is 10+ GB (compressed) and growing, so the dump/restore cycle would be a bit tedious, and, worse, it would inject doubt about the restored DB being a snapshot of the live DB vs the way that `mariabackup` snapshots the actual DB files...

The Samba idea is interesting because we're looking at Samba to solve some other issues too.  Thanks!
 
For now, despite the fortuitous incorrectness, turning off gPRC FUSE and using osxfs is a simple solution.  

Eventually we will have to figure out a solution that doesn't rely on an uncontrolled lucky oversight...
