### ISSUE TITLE
Fatal Error: one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3

### ISSUE THREAD

**Issue by dimitris254** [docker/for-mac#5057]
I downloaded Docket from the docket website and when I tried to install it (on my Mac Pro (late 2013) with macOS 10.13.6 & GC: AMD FirePro D700) I got this message.

I tried all (3) buttons on the dialog window, but every time I run the app, I get the same result.
(BTW: the Diagnose & Feedback, does nothing. Or what it does, it never ends...)

(another issue opened here some 6 months ago (now closed), did not offer any insight on solving the problem)

What can I do to install Docket?

**Comment by oOhyeahh** [comment]
I had the same issue `one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 12227)`






  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: cannot get the diagnostics id because it never finish the diagnose.

### Expected behavior

can run docker desktop.

### Actual behavior

It stops when I try to install helper and throws the error `one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 12227)`

### Information

  - macOS Version: 11.0 Big Sur

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior


 1. Download latest the docker desktop (either stable or edge) version and install the docker
 2. open docker desktop app

**Comment by dmpro** [comment]
Same as @oOhyeahh - MacBook Pro (13-inch, M1, 2020) - Downloaded latest docker. Cannot run docker and diagnostics hangs.

**Comment by be-drum** [comment]
Have the same issue

**Comment by seriklevan** [comment]
Have the same issue

**Comment by p3p3br0** [comment]
After installing Docker Desktop Version for Mac - same issue! 

one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 3247)

MacBook Pro (13-inch, M1, 2020)
MacOS BigSur 11.0.1

**Comment by Antriksh-Jain-mpf** [comment]
I am also facing the same issue.

**Comment by 93lykevin** [comment]
I am also having this issue. 
MacBook Pro (13-inch, M1, 2020)
MacOS BigSur 11.0.0

**Comment by gpetrov** [comment]
Docker is not yet compatible with Apple M1, they are working hard on it to make it happen, see:
https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/

**Comment by MrSsunlight** [comment]
> 我也有这个问题。
> MacBook Pro（13英寸，
> M1,2020 ）MacOS BigSur 11.0.0

me too

**Comment by rkh-hash** [comment]
Same issue 😕 

* MacBook Pro (13-inch, M1, 2020)
* BigSur `11.0.1`

**Comment by appumistri** [comment]
> Same issue 😕
> 
> * MacBook Pro (13-inch, M1, 2020)
> * BigSur `11.0.1`

Me too :|

**Comment by reinmind** [comment]
I run to the same issue when I tried to instlle the docker tech preview on my Macbook Air M1.
Failed to start the daemon process.
Is there anyone got idea to fix it?

**Comment by Dids** [comment]
Why is there still no explanation to this issue or any workarounds or ETAs on a fix?
I thought Docker should've worked fine on Big Sur on Intel hardware?

**Comment by oOhyeahh** [comment]
Looks like this release https://docs.docker.com/docker-for-mac/apple-m1/ to solve my problem.
