### ISSUE TITLE
After upgrading to Docker Desktop 2.5.1.0 (49923) pulling images from a private registry fails

### ISSUE THREAD

**Issue by HarryWeppner** [docker/for-mac#5079]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `18EDBB54-4B49-411C-8EC0-F6679F0DA3A4/20201119231517`

### Expected behavior

The system pulls images from a private registry.

### Actual behavior

```bash
Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: ""
```

### Information

  - macOS Version: 10.15.7

### Diagnostic logs

```
Docker for Mac: 2.5.1.0 (49923) edge
```

### Steps to reproduce the behavior

```
$ docker pull <private-registry>/<repo>:<tag>
Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: ""
```

Note: `<private-registry>/<repo>:<tag>` are obviously placeholders for a valid image. If I downgrade again, the same command works.

**Comment by stephen-turner** [comment]
Thanks for the report, @HarryWeppner. I suspect this bug is in the upstream engine, which we have taken a new pre-release version of in 2.5.1.0. Could you file the ticket in https://github.com/moby/moby instead? Sorry, I would move it if I could, but it's not possible because the engine is not part of the docker org.
