### ISSUE TITLE
qemu: uncaught target signal 6 (Aborted) when running elixir amd64 image on M1

### ISSUE THREAD

**Issue by SteffenDE** [docker/for-mac#5148]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Image runs using qemu.

### Actual behavior

```
> docker run --rm -it hexpm/elixir-amd64:1.11.1-erlang-23.2-ubuntu-focal-20201008 iex
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
sigaltstack: Invalid argument
sigaltstack: Invalid argument
sigaltstack: Invalid argument
qemu: uncaught target signal 6 (Aborted) - core dumped
```

### Information

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Use M1 preview
  2. Run `docker run --rm -it hexpm/elixir-amd64:1.11.1-erlang-23.2-ubuntu-focal-20201008 iex`

Not sure if this is related to docker or a problem that qemu must address. Just leaving this here as this is what I found when building an existing amd64 project. There's also a arm64 image of elixir, so this is not critical for me.

**Comment by SteffenDE** [comment]
Possibly related to #5122

**Comment by stephen-turner** [comment]
This is a qemu bug, which is the upstream component we use for running Intel (amd64) containers on M1 (arm64) chips, and is unfortunately not something we control. In general we recommend running arm64 containers on M1 chips because (even ignoring any crashes) they will always be faster and use less memory.

Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one. Now that M1 is a mainstream platform, we think that most container authors will be keen to do this.

**Comment by SteffenDE** [comment]
There actually are already arm64 images available (since long before M1 was introduced), but it'd still be great to be able to run containers of existing images that are built for x86. Anyways, I'm still glad that running x86 containers works at all, so thank you all for your great work!
