### ISSUE TITLE
High CPU on macOS Cataline

### ISSUE THREAD

**Issue by marvix** [docker/for-mac#5209]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
CPU: 2.3 GHz Dual-Core Intel Core i5
RAM: 16 GB 2133 MHz LPDDR3
OS: Cataline 10.15.7
Docker: 3.0.3 (51017)

![image](https://user-images.githubusercontent.com/3768431/103430554-62f15600-4bd6-11eb-907d-51159f42680f.png)
![image](https://user-images.githubusercontent.com/3768431/103430555-6a186400-4bd6-11eb-9ecb-1f79ea26e48a.png)
![image](https://user-images.githubusercontent.com/3768431/103462608-82ec5b00-4d37-11eb-8788-037d188d5ad8.png)

I thought it CPU issue, so changed the thermal paste and I cleaned the fans, yet the CPU temperature reaches 95C degree with high usage by docker.

Cloud be container issue? or it just docker?

**Comment by marvix** [comment]
I got the problem, the PHP container was running with the latest Alpine version, and sometimes that was eating the CPU.
I changed the OS to ubuntu core and apparently, this solved the issue.

**Comment by mad4dweb** [comment]
HI im having the same CPU boost on OSX Big Sur on the com.docker.hyperkit  it boost more than 120%  constantly

I managed to lower it by deleting all unused FILE SHARING in the docker APP and by Disable all the experimental features

However  when i open nextcloud and start generating the image previews or thumbnails , it boosts up the CPU

im using version 3.0.3 

![Screen Shot 2021-01-04 at 2 47 22 AM](https://user-images.githubusercontent.com/20199989/103512735-4d2e9b80-4e37-11eb-9e86-5a28a8fd73e1.png)

**Comment by Dyostiq** [comment]
Hi, I have the same issue, with very high CPU usage by the hyperkit process.
I didn't manage to fix it by disabling experimental features and file sharing. I've tried multiple times and made a few factory resets and nothing helped. However, I had a GoLand opened in the background with a docker service connected – it turned out disconnecting it from docker reduced the cpu usage from 400% to 4% so it may be the thing. As I've observed when the service in GoLand is on, the CPU usage by the hyperkit is increasing with every restart of the docker app.

**Comment by goosefraba** [comment]
I have the same issue. I have no containers running and still 100% CPU for the com.docker.backend task

**Comment by Apollorion** [comment]
Also seeing 100% CPU utilization but seems to be the hyperkit process for me.

**Comment by tot-ra** [comment]
Similar issue, Catalina, 2019. CPU goes from 100% -> 500% over the course of 2-4 min just because I **connect external monitors to USB-C**. Maybe Its some hardware issue ofc, but maybe its somehow software-related too..
(had to cut-out the middle of the video because github has 10mb limit, but you get the idea..)

https://user-images.githubusercontent.com/445122/104203732-270b8b80-5435-11eb-8aee-d670d1a05981.mov

**Comment by deitch** [comment]
Same here, I just updated to latest today 3.1.0(51484) and am getting killed by it. Literally 0 containers running, went onto the hyperkit VM, no real CPU taken by processes, no real i/o going on, no idea what it is doing.

**Comment by deitch** [comment]
Well, wow. As soon as I disable gRPC Fuse under Experimental, as suggested in some other comment threads, it goes away. Here is hoping it stays that way...

**Comment by kuberlog** [comment]
Literally fried my macbook charger.

**Comment by goosefraba** [comment]
I downgraded to 2.0.5.1 (MacOSX) today and the issue is gone. So it seems one of the 3.x versions contain those errors

**Comment by goosefraba** [comment]
with 3.2.2 it seems to be fixed
