### ISSUE TITLE
USB passthrough on MacOS using new Hypervisor framework

### ISSUE THREAD

**Issue by drozycki** [docker/for-mac#5263]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
MacOS now supports USB passthrough with their new Hypervisor framework. 

### Actual behavior
```
> docker run --device=/dev/cu.usbserial-220 ...
docker: Error response from daemon: error gathering device information while adding custom device "/dev/cu.usbserial-220": no such file or directory.
```
I have verified that the device is there.

### Information
[The FAQ currently says](https://docs.docker.com/docker-for-mac/faqs/#can-i-pass-through-a-usb-device-to-a-container):
> Unfortunately, it is not possible to pass through a USB device (or a serial port) to a container as it requires support at the hypervisor level.

[USB support was last discussed in 2018, when it was closed as won't fix.](https://github.com/docker/for-mac/issues/3110) The Hypervisor framework was not available then.

[Related Apple Developer Reference](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_device-access)

  - macOS Version: 11.1 (Build 20C69) on the 2020 M1 Mini
  - Docker for Mac: The December 2020 release of Docker Desktop for Apple Silicon. The about page says 0.0.0 lol
### Diagnostic logs

```


```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Thanks for the report. The existence of the [entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_device-access) is quite interesting, however I can't find USB-specific APIs in either the [hypervisor.framework docs](https://developer.apple.com/documentation/hypervisor) or the [virtualization.framework docs](https://developer.apple.com/documentation/virtualization/vzvirtualmachineconfiguration).

An implementation via the `hypervisor.framework` would have to be with [hyperkit](https://github.com/moby/hyperkit) and would likely be a significant amount of work: probably a whole PCI USB interface device would have to be emulated and (somehow) individual devices mapped to host devices. I would assume it's not possible or desirable to pass an entire host PCI controller to the VM since the host needs USB devices too.

An implementation via the `virtualization.framework` would be ideal and much easier for us to consume but I don't think it currently exists.

As a feature request, perhaps a better place to discuss this would be on a [docker/roadmap](https://github.com/docker/roadmap) ticket -- feel free to open an issue there. I'll close this one as I don't think there's anything we can do about this in the short term.
