### ISSUE TITLE
Docker M1 Preview sometimes hangs while running netperf 

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#5280]
When running "netperf" to host interactively in Docker M1 Preview, it crashes most of the time.

### Steps to reproduce the behavior

1) Run `netserver -D` on host side
2) Run `docker run --rm -it --add-host=host.docker.internal:host-gateway centos bash`
3) In container, get netperf and install it: `curl https://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/aarch64/media/core/release/netperf-2.7.0-6.mga8.aarch64.rpm --output netperf-2.7.0-6.mga8.aarch64.rpm && rpm -Uvh netperf-2.7.0-6.mga8.aarch64.rpm`
4) In container, run netperf: `netperf -H host.docker.internal`

### Behavior

In some cases, it completes successfully. If that happens, just restart Docker and do the steps again.

In most cases, this result into a "Fatal Error".
The error message varies. It can be one of:

    ERRO[0085] error waiting for container: invalid character 'u' looking for beginning of value 
    ERRO[0074] error waiting for container: invalid character 'u' looking for beginning of value 
    ERRO[0089] error waiting for container: invalid character 'u' looking for beginning of value

**Comment by djs55** [comment]
@BenjaminPoulain thanks for your report and repro instructions. For my benefit I've taken the liberty of creating a simple [Dockerfile](https://github.com/djs55/simple-docker-images/blob/master/netperf/Dockerfile) and pushing an image `djs55/netperf:latest` for testing.

I installed the latest build (we released an update yesterday, it's available here: https://docs.docker.com/docker-for-mac/apple-m1/ ) and tried to reproduce with:

```
dave@m1 netperf % docker run djs55/netperf:latest -H host.docker.internal
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to host.docker.internal () port 0 AF_INET
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

131072  16384  16384    10.00    2062.34   
```
(note we've added the `host.docker.internal` DNS in the recent build so we don't need the `--add-host` anymore)

I used the "Restart" whale menu option between runs and tried it 10 times -- do you think this should be enough? (I did hit a restart failure once which I think was because we're not currently shutting the VM down gracefully via the `requestStop` API so the filesystem can get a bit damaged)

I've not seen the problem yet so it could be that we fixed it in the recent build. However I'm still suspicious. The error message you see printed is what happens if the connection to the VM is broken, which could be for many different reasons. It might be worth checking `~/Library/Containers/com.docker.docker/Data/vms/0/console.log` in case there's something like a kernel crash at the end. I had a strange problem while debugging earlier builds where the connection with the VM got a TCP RST... at least this was my inference from a "Connection reset by peer" error. I noticed that I had left another test VM running in the background which might not have renewed its DHCP lease properly. My guess was the background VM used the IP by mistake, saw the traffic unexpectedly and sent RST for the active connections. The problem seemed to go away when I removed the old test VM. It's a bit circumstantial though.

Anyway, I'll keep an eye out for it. In the meantime, do try the latest build and let me know if it's any better / worse.

Thanks!

**Comment by BenjaminPoulain** [comment]
Thanks for looking into this.

The crash does not reproduce after your latest updates with the steps above.

**But**, if some heavy networking runs for a bit longer, the crashes come back.
For example, this crashes every time: `netperf -H  host.docker.internal -l 360`.

From the device or Linux side, I don't see anything obvious. Logs attached:
[console.log](https://github.com/docker/for-mac/files/6006918/console.log)

**Comment by djs55** [comment]
Sorry for the delay getting back to you. Previously when something failed the various processes were killed and this could result in missing logs from the VM (I believe). I've made a build with a bunch of improvements:

1. the VM console log should be more reliable
2. there is a "crash detector" which monitors the VM console for various patterns and pops up a fatal error via the UI (see below)
3. the kernel is now 5.11.5.
4. previously we weren't shutting down the VM gracefully, so perhaps filesystem corruption was possible. We now trigger a shutdown from inside the VM

For reference, the latest dev build is here: https://desktop-stage.docker.com/mac/stable/arm64/61782/Docker.dmg

I cleaned my log files (`rm -rf ~/Library/Containers/com.docker.docker/Data/log/`) and the VM disk (`rm ~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw`) just in case, booted up this version and ran the netperf workload again. I'm able to reproduce a crash which looks like:

```
[ 1165.471118] list_add corruption. next->prev should be prev (ffff0000e0227c28), but was ffff0000d6d7c218. (next=ffff0000d6d7c218).
[ 1165.471225] ------------[ cut here ]------------
[ 1165.471311] kernel BUG at lib/list_debug.c:23!
[ 1165.471349] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
[ 1165.471411] Modules linked in: grpcfuse(O) xfrm_user xfrm_algo vmw_vsock_virtio_transport vmw_vsock_virtio_transport_common vsock
[ 1165.471459] CPU: 2 PID: 2752 Comm: runc:[2:INIT] Tainted: G        W  O    T 5.11.5-linuxkit #1
[ 1165.471483] pstate: 00401005 (nzcv daif +PAN -UAO -TCO BTYPE=--)
[ 1165.471519] pc : __list_add_valid+0x40/0xb0
[ 1165.471586] lr : __list_add_valid+0x40/0xb0
[ 1165.471601] sp : ffff800012b7bc30
[ 1165.471614] x29: ffff800012b7bc30 x28: ffff0000eee8e0c0 
[ 1165.471647] x27: 0000000000000000 x26: 0000000000000000 
[ 1165.471664] x25: 000000000000000b x24: ffff0000d6da8a08 
[ 1165.471715] x23: 0000000000200000 x22: 0000000000000000 
[ 1165.471748] x21: ffff0000e0227c28 x20: ffff0000d6d7c218 
[ 1165.471774] x19: ffff0000d6d7c218 x18: 0000000000000000 
[ 1165.471801] x17: 0000000000000000 x16: 0000000000000000 
[ 1165.471822] x15: 0000000000000000 x14: 3030306666666628 
[ 1165.471844] x13: 2076657270206562 x12: 20747562202c2938 
[ 1165.471884] x11: 3263373232306530 x10: 3764366430303030 
[ 1165.471913] x9 : ffff8000100e23b4 x8 : ffff800012b7b8c8 
[ 1165.471933] x7 : 0000000000000a20 x6 : 0000000000000001 
[ 1165.471961] x5 : c0000000ffffefff x4 : 0000000000000000 
[ 1165.471978] x3 : ffff00012f7bdaf0 x2 : 6a2bd8ddd5e2fd00 
[ 1165.472016] x1 : 0000000000000000 x0 : 0000000000000075 
[ 1165.472039] Call trace:
[ 1165.472051]  __list_add_valid+0x40/0xb0
[ 1165.472067]  __list_add+0x30/0x58
[ 1165.472132]  inode_sb_list_add+0x3c/0x58
[ 1165.472165]  new_inode+0x38/0x4c
[ 1165.472203]  shmem_get_inode+0x60/0x1bc
[ 1165.472246]  shmem_symlink+0x74/0x230
[ 1165.472303]  vfs_symlink+0x78/0xac
[ 1165.472339]  do_symlinkat+0xd4/0x118
[ 1165.472359]  __arm64_sys_symlinkat+0x2c/0x3c
[ 1165.472377]  do_el0_svc+0x184/0x1d8
[ 1165.472459]  el0_svc+0x20/0x30
[ 1165.472494]  el0_sync_handler+0xc4/0x128
[ 1165.472512]  el0_sync+0x174/0x180
[ 1165.472528] Code: aa1503e1 b0004720 9136ac00 9418ef07 (d4210000) 
[ 1165.472596] ---[ end trace f09e31c28016af87 ]---
[ 1165.472627] Kernel panic - not syncing: Oops - BUG: Fatal exception
[ 1165.472671] SMP: stopping secondary CPUs
[ 1165.472734] Kernel Offset: disabled
[ 1165.472759] CPU features: 0x099d0296,6a008030
[ 1165.472794] Memory Limit: none
[ 1165.472851] Rebooting in 1 seconds..
```

![Screenshot 2564-03-10 at 19 32 50](https://user-images.githubusercontent.com/198586/110686518-6ce79480-81d7-11eb-99f4-34d0c8948ec6.png)

The crash usually involves `new_inode` called from different filesystem sys calls. It's interesting it's always filesystem related even though the `netperf` test is hammering the network. I've seen it on 5.10.11 as well as 5.11.5. I'm not sure what the problem is but I'm still investigating.
