### ISSUE TITLE
docker ps failed / disk check failed

### ISSUE THREAD

**Issue by sarvex** [docker/for-mac#531]
### Expected behavior
Docker App should start normally

### Actual behavior
Docker App starts, but crashes and loads the bug submission dialog. And this dialog is hidden (inactive) because of welcome dialog

### Information

Diagnostic ID: FFB52729-00C4-4057-9823-9375C0A57A46
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/sarvex/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/FFB52729-00C4-4057-9823-9375C0A57A46/20160907-085528/qemu-img-check.stdout 2> /tmp/FFB52729-00C4-4057-9823-9375C0A57A46/20160907-085528/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during startup in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 likely to be fixed on the beta channel within the week.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version.

**Comment by sarvex** [comment]
Both #64 and #202 have different error stacks and thus not pertinent of the current issue. 

Kindly let me know what additional information is required. I hoped that the "Diagnostic Information" will be comprehensive. If it is not comprehensive may the diagnostic tool updated to include all the desired information

**Comment by dsheets** [comment]
They are pertinent to the current issue. You are running the stable release of Docker for Mac on macOS 10.12 Sierra which has known instabilities that have been addressed in the fixes for #64 and #202 which have not yet reached the stable channel (but which are both in just-released Beta 25). The fix for #202 will not reach the stable channel until the release after the imminent release. These instabilities can cause a variety of failures including things like disk corruption which you appear to be experiencing.

We recommend running the Docker for Mac Beta channel on macOS Sierra after uninstalling your current installation. I'm sorry but we cannot investigate issues with our stable releases on a so-far unstable beta version of an operating system.

**Comment by sarvex** [comment]
It is alright to not investigate an unsupported beta operating system. but then the bug should be marked such, so that when support is extended to the operating systems all these bugs can be reverified. 

"Defer the bug" or mark it "Wont Fix" till osx 10.12 is released, but not "missing information" or "duplicate. Marking is duplicate to other irrelevant bugs will at best help ignore the issue; which will prove detrimental to the software stability.

**Comment by dsheets** [comment]
We seem to be misunderstanding each other. We are interested in problems with Docker for Mac on macOS Sierra Beta. The stable channel lags the beta channel by typically 4-6 releases unless there are critical hotfixes that must be applied. Because macOS Sierra is still in Beta and has an unpredictable release schedule with new and exciting bugs, we cannot reasonably find, fix, and QA problems with Docker for Mac stable on macOS Sierra Beta. Instead, we push macOS Sierra Beta fixes to our beta channel which is updated approximately once a week. It is highly likely that the issue you have reported is caused, either directly or indirectly, by the issues in #64 and #202. Because of this, and the fact that the imminent stable release will not contain the fix for #202 (which can manifest in many different ways), we highly recommend that you use the Docker for Mac beta channel while macOS Sierra is in Beta. An upcoming release to the stable channel will synchronize with the beta channel. When macOS Sierra exits Beta (perhaps today!), we will likely do a stable channel release and issue subsequent hotfixes (still lagging 1 week from the beta for QA) for any issues in the stable channel.

I hope this makes sense and helps you understand why we do not support our stable release on macOS Sierra Beta. I have opened issues to update the documentation and make this clear from the app during installation if macOS Sierra release is scheduled two or more weeks from today.

Thanks for your report!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
