### ISSUE TITLE
User Interface problem - Misleading "Upgrade" button in 3.1.0

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5323]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features 
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I expect an "Upgrade" button to be about upgrading the software, not about switching to a new hub.docker.com plan.

### Actual behavior

I was surprised by this "Upgrade" button in Docker Desktop for Mac 3.1.0:

<img width="1249" alt="Settings_and_Docker_for_Mac_release_notes___Docker_Documentation" src="https://user-images.githubusercontent.com/112444/107364853-35cb7980-6a99-11eb-8b9a-c5ee57b9385e.png">

I thought it was another way of notifying us about a docker desktop upgrade. But in reality it's a link to try to get us to use a higher dockerhub plan. 

I guess if it said "Upgrade plan" it would be clear. It's a strange place to be selling plan upgrades though.

### Information
  - macOS Version: Big Sur
  - Docker Desktop Version: 3.1.0

**Comment by stephen-turner** [comment]
Yes, I agree, and I've raised this internally too. I _think_ we consistently use "update" for new versions of the software and "upgrade" for upgrading your plan, but the words are too similar and I would like to make it clearer.

I'm not sure why it's a strange place though. But maybe it's because you see it as "a higher dockerhub plan". The subscriptions no longer apply to Docker Hub only, they are across all our products. In Desktop, you get support, and some additional functionality around image scanning, and we intend to add more premium features later.

**Comment by stephen-turner** [comment]
cc @stlucek @dieucao

**Comment by rfay** [comment]
IMO both "upgrade" and "update" would be very ambiguous here. We don't expect to be hit up for a plan change in the docker desktop UI, but if so, make it "plan upgrade" or something, or "hub plan upgrade".

I didn't know that subscriptions affect docker desktop behavior or features. But of course, the link takes you to hub.docker.com, and it's not at all clear there that there's anything about Docker Desktop.

<img width="741" alt="Docker_Hub" src="https://user-images.githubusercontent.com/112444/107388060-aa5ee200-6ab2-11eb-90b0-e62c7b95d651.png">

Also... I am never logged into the desktop because all my push work is on the command line, where I have to use token because of 2FA.

**Comment by stephen-turner** [comment]
Your comments are valuable, thank you. It should be made clearer on the website too.
