### ISSUE TITLE
Mac M1 Preview 60902 crash on permission denied creating nfs volume

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5325]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

M1 Preview build Docker Desktop build 60902: https://desktop.docker.com/mac/stable/arm64/60902/Docker.dmg

Docker desktop should be able to use NFS mounts, and if NFS is not configured to allow it (permission denied) it should gracefully report this... and not crash.

If Docker gets a failure to mount an nfs volume, it should not crash

### Actual behavior

Crash (followed the permission denied by a bit)

<img width="597" alt="Cursor" src="https://user-images.githubusercontent.com/112444/107393703-535c0b80-6ab8-11eb-8502-e23a11a06417.png">

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks @rfay, we'll have a look.

**Comment by schniper** [comment]
ALso interested in this. I have a working nfs config on n Intel Macbook. The same config dies with "permission denied" on an M1 Mac Mini.
Anyone managed to go around this? It happens on the latest preview build as well (the one with the fixed host.docker.internal).

**Comment by rfay** [comment]
It's not hard to get NFS configured, if that's your goal. See the M1 instructions for ddev, https://github.com/drud/ddev/releases/tag/v1.17.0-alpha5

This issue is about it crashing when misconfigured.

> 6. To get NFS going, there is a difference in networking. You have to find out the eth0 interface inside the container. Find the source IP for NFS by running `docker run -it --rm busybox sh -c 'ping -c1 vm.docker.internal | awk "/PING/ { gsub(/[\(\):]/, \"\"); print \$3 }"'`  That IP range (probably 192.168.64.0) should then be added to your /etc/exports like this:
```
/Users/rfay -alldirs -mapall=501:20 -network=192.168.64.0 -mask 255.255.255.0
```

**Comment by schniper** [comment]
That doesn't work, really. Also, I've read about mapping /System/Volumes/Data/Users... instead of /Users, since Catalina. That still fails.

Here's an example of my config:

/etc/exports:
/System/Volumes/Data/Users/costin/Sites -alldirs -mapall=501:20 -network=192.168.65.0 -mask 255.255.255.0

(my VM IP is in that range)
Also tried with localhost.

In Docker, I have /Users/costin/Sites shared.
At some point I also had /System/Volumes/Data - no joy.

/etc/nfsconf:
nfs.server.mount.require_resv_port = 0

docker-compose:
version: '3.9'
services:
  app:
    build:
      context: ./docker/app-generic
      dockerfile: Dockerfile
    container_name: app
    image: keypoint/app-generic
    networks:
     - dockernet
    ports:
     - "${APP_PORT}:80"
     - "${APP_SSL_PORT}:443"
    volumes:
     - letsencrypt:/etc/letsencrypt:nocopy
volumes:
  letsencrypt:
    driver: local
    driver_opts:
      device: ":/System/Volumes/Data/Users/costin/Sites/docker-dev/docker/letsencrypt"
      o: addr=host.docker.internal,rw,nolock,hard,nointr
      type: nfs

Error:
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting app ... error

ERROR: for app  Cannot start service app: error while mounting volume '/var/lib/docker/volumes/docker-dev_letsencrypt/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/costin/Sites/docker-dev/docker/letsencrypt:/var/lib/docker/volumes/docker-dev_letsencrypt/_data, data: addr=192.168.64.1,nolock,hard,nointr: permission denied

ERROR: for app  Cannot start service app: error while mounting volume '/var/lib/docker/volumes/docker-dev_letsencrypt/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/costin/Sites/docker-dev/docker/letsencrypt:/var/lib/docker/volumes/docker-dev_letsencrypt/_data, data: addr=192.168.64.1,nolock,hard,nointr: permission denied

**Comment by schniper** [comment]
I've went a while ago through the steps of adding nfsd to full disk access and all other similar tips I could find.
Kind of difficult to debug as well, as nothing else is being logged. Or I don't know where to look...

**Comment by schniper** [comment]
$%$#@#% me... The IP range was 192.168.64.0. Although your docker run reported .65, which was consistent with what was set in Docker's preferences.
I eventually saw a couple of messages in Console.

Thank you, @rfay

**Comment by schniper** [comment]
@rfay just one more thing, maybe you ran into this too: I have actually had to make the same compromise on my other computer as well: I have to set -mapall=0:0, otherwise I get all sorts of permission errors from the containers. Any idea how to address this?

And to the very cool Docker team, as this thread threatens to go into nfs only territory: with my containers being able to use nfs again, I keep getting crashes on the last preview build, after about a minute of running. I should say that I am sharing a few containers with up to 10Gb of data, I think.

The errors are different, as it seems the docker daemon goes away and whatever is running at that point crashes.
I have never noticed them on Preview 7.
They may be related to NFS share sizes? Some of the containers (elasticsearch storage) I have never used with NFS before, so maybe I hit a threshold. I'll try to move some back to bind.

Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 502 Server Error for http+docker://localhost/version: Bad Gateway ("b'Bad response from Docker engine'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 502 Server Error for http+docker://localhost/version: Bad Gateway ("b'Bad response from Docker engine'")
[9737] Failed to execute script docker-compose

![image](https://user-images.githubusercontent.com/533628/108001644-a9b7d580-6ff5-11eb-8593-eb1aed8eb5f4.png)

**Comment by rfay** [comment]
Sorry, we've already polluted this issue too much with support. You can find me on Docker slack and I'll be happy to help you. But your issues are with NFS, not with docker.

**Comment by schniper** [comment]
The main part of the issue above seems to be Docker issue, actually, but you are right about NFS. Thanks

**Comment by rfay** [comment]
For anybody stumbling here... NFS works fine. This issue is about crashing when misconfigured.

**Comment by djs55** [comment]
@rfay did the RC 2 fix this particular bug or is it still present? My initial assumption (which could be wrong!) was that this crash was related to the other kernel crash because my only repro of the kernel crash also happened to do lots of network I/O. Earlier builds like 60902 also had a bug where they didn't pick up the kernel crash in the logs properly, making everything extra confusing.

Anyway, let me know if this is still an issue with RC 2 and I'll take a look!

**Comment by schniper** [comment]
I’ll take a look. With a NFS correct configuration, it was crashing at random intervals. Will try to test RC2 in the coming hours.
Thank you!

**Comment by schniper** [comment]
Hi,

I confirm that for the 10 minutes I have tested it, it didn’t crash anymore, with a bunch of large NFS containers mounted.
I did have to comment out my elasticsearch memory locking params, but that is a different issue (it didn’t happen a while back, on Intel, though).

Thank you for all your effort!

**Comment by rfay** [comment]
I am unable to recreate this issue with Docker Desktop 3.3.0 RC2 (62345). With /etc/exports empty and nfsd running and starting up a project that uses NFS. I think we should call it fixed. Thanks so much!
