### ISSUE TITLE
Unable to uninstall/reinstall docker for Mac. (I'm happy to blow it all away and start over!)

### ISSUE THREAD

**Issue by Starblade42** [docker/for-mac#533]
### Expected behavior
I should be able to uninstall and re-install docker and end up with something that works.
### Actual behavior
I continue to get errors when I start the application. I've even deleted the folders created by the application in the respective Library folders (using AppTrap to track the files created and allow me to easily remove them when I put the docker app in the trash)
### Information

Diagnostic ID: CAECB6F5-715F-47FD-A4E8-17BA198F0B8B
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@Starblade42 Thanks for sending this in. We are looking into issues related to macOS Sierra.

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during startup in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 likely to be fixed on the beta channel within the week.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
