### ISSUE TITLE
docker engine not starting

### ISSUE THREAD

**Issue by gaurav46** [docker/for-mac#5369]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C30D2077-11C9-4BE9-BDDD-14432057F73C/20210219143844

### Expected behavior
docker should start
### Actual behavior
docker not starting
### Information

  - macOS Version: big sur
  - Docker Desktop Version: m1 tech preview latest

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by musha68k** [comment]
I'm seeing the same issue here as well, even after going through "reset" escalation steps of:

1. triggering all the "troubleshoot resets"
2. thoroughly cleaning the docker installation with AppCleaner
3. installing again
4. rebooting

It worked well after I installed this latest release, but after macOS crashed this morning (didn't check if related) it has been stuck in this state since. I ran into exactly the same progression and state with the previous release.

These are the "docker" related log lines I'm seeing a lot of here through Console stream (macOS 11.2.1, MacBook Pro M1):

Process `com.docker.backend`:
```
external: GET /features 200 "DockerDesktopGo" ""
```
```
still waiting for connection from VM after 3m20.851169333s (state = &{%!s(int=0)  22b0848f262afb2c319199dd84b3e4596f2603d2ec82f181218267897cee2ea5 tcp+bootstrap+client://gateway.docker.internal:51164/22b0848f262afb2c319199dd84b3e4596f2603d2ec82f181218267897cee2ea5}, err = <nil>)
```


It looks like there is a connection problem with the macOS hypervisor - or QEMU even?

Let me know if you need more data - I can look through history if need be.

**Comment by mateka** [comment]
Did You try to disable the firewall? On my machine, after putting Mac to sleep, Docker cannot start. Turning off the firewall and restarting Docker - helps.

**Comment by musha68k** [comment]
Thanks, deactivating the firewall completely did indeed unlock the latest docker preview for M1 👍 
I had whitelisted the docker app but that didn't work as assumed.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/95477/108607118-70cc8780-738c-11eb-9950-6ea9439abb61.png">
