### ISSUE TITLE
docker can't start..

### ISSUE THREAD

**Issue by baozigit** [docker/for-mac#544]
### Information

Diagnostic ID: 4D1EB3E2-273F-4700-BD1E-F806C2BBFDDC
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during startup in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed on the beta channel yesterday.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
