### ISSUE TITLE
50CC5AFF-0F0D-4BAB-8F27-3A8409B0E416/20210312004304

### ISSUE THREAD

**Issue by gaeros** [docker/for-mac#5449]
- [x
[20210312004304.zip](https://github.com/docker/for-mac/files/6126771/20210312004304.zip)
 ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
