### ISSUE TITLE
docker -v: timeout after 10.00s

### ISSUE THREAD

**Issue by baozigit** [docker/for-mac#545]
### Information

Diagnostic ID: 4D1EB3E2-273F-4700-BD1E-F806C2BBFDDC
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during execution in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed on the beta channel yesterday.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version.
