### ISSUE TITLE
How to map ports so guest can access database running on host?

### ISSUE THREAD

**Issue by pate** [docker/for-mac#548]
### Expected behavior

Configure Docker for Mac so that containers can connect to a service on my host OS X, e.g. Postgres DB running on port 5432.

### Actual behavior

No apparent way to configure Docker so that containers can punch out onto the host:

![image](https://cloud.githubusercontent.com/assets/1011676/18347452/dacf30e8-75c5-11e6-98cd-3850fac7d85b.png)

### Information

I presume there is some virtualization like VirtualBox going on in the background, but I don't see it listed under `VBoxManage list vms`. Is this possible?

 - Docker for Mac Version 1.12.0-a (build: 11213) ad6ab836187e4111082447b7c0a6a74d01929a5c
 - Host OS: OS X 10.11.2

### Steps to reproduce the behavior

  1. Be a noob
  2. Have limited drive space and be unwilling to run Postgres inside yet another container
  3. Try to connect to Postgres DB running on host from inside a docker container.

**Comment by djs55** [comment]
Thanks for the clear report.

The virtualisation technology we use is called [hyperkit](https://github.com/docker/hyperkit) (based on `xhyve` which is based on `bhyve`) runs VMs as individual processes via the Apple "hypervisor.framework" -- have a look for a process called "com.docker.hyperkit" with lots of VM configuration arguments.

To connect to a database running on the host: the container should be able to contact the host either using it's external IP (e.g. the one on your LAN) or by the internal IP `192.168.65.1`. For example (using `ssh` rather than `postgres` because that's all I've got available):

```
djs$ docker run -it alpine sh
/ # apk update && apk add openssh-client
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.3-11-gacf3763 [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.2-11-g9b41a63 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 5970 distinct packages available
(1/1) Installing openssh-client (7.2_p2-r3)
Executing busybox-1.24.2-r9.trigger
OK: 7 MiB in 12 packages

/ # ssh djs@192.168.65.1
The authenticity of host '192.168.65.1 (192.168.65.1)' can't be established.
ECDSA key fingerprint is SHA256:rYBaZNtsUrOOTnwYgwi1W79/3ndLOSZY9qZW1ANymBo.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.65.1' (ECDSA) to the list of known hosts.
Password:
```

Note this magic IP `192.168.65.1` is specific to Docker for Mac and Windows. We'd like to find a nicer way of doing this.

Let me know if that helps! Please re-open the issue if it doesn't work as expected.
