### ISSUE TITLE
docker ps / docker info suddenly timeout and fail

### ISSUE THREAD

**Issue by barbarello** [docker/for-mac#55]
### Information

Diagnostic ID: 9224B1F5-B54A-44AE-BE4C-3C7CBF2A5CC8
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Please provide more information:

- Expected behavior
- Actual behavior
- Steps to reproduce

And anything else which could think of. For intance, what is the output of `docker version`? Did you see any error during the install/upgrade process?

I am closing this issue now but please re-open when you have more information.
