### ISSUE TITLE
com.docker.hyperkit consuming excessive (>100%) CPU continually

### ISSUE THREAD

**Issue by mobilenik** [docker/for-mac#5517]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A3627E9D-037C-4136-A3F4-78368FADA09D/20210329090434

### Expected behavior
If my containers are doing nothing, I expect Docker to consume no additional CPU

### Actual behavior
hyperkit runs over 100% CPU all the time, which means my fan is always on and it drains my battery really fast

### Information
I am on Mac OS Big Sure 11.2.3 and am using Docker desktop 20.10.5

### Steps to reproduce the behavior
Seems to be happening with any image

**Comment by cjheppell** [comment]
I can confirm that the same is also happening for me and all colleagues on my team.

Invoking `docker build` for various Go based images causes the docker hyperkit process to consume all CPUs allocated to the docker daemon which effectively freezes the entire system and renders it completely unusable.

In worst case scenarios, this has put so much pressure on the machine that it stops responding completely and the only way out is holding the power button to force the machine to reboot.

This seems to be worse when building images (buildkit or no buildkit) rather than running containers in my case.
