### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by mwindholtz** [docker/for-mac#5519]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mwindholtz** [comment]
00EA4BE6-FA1F-40A9-8F7C-ED52BFE6F6DE/20210329155052

**Comment by dhinojosa** [comment]
Same here.

**Comment by mstefan21** [comment]
Same problem, but also on version 3.3.0 and also on version 3.1.0. Where can I download 3.2.2?

**Comment by mstefan21** [comment]
F73F30CD-185E-453C-BAEA-208F5C038404/20210331144838

**Comment by minkbear** [comment]
same problem on 3.2.2

**Comment by harrouet** [comment]
Same problem.
Is this as described in issue  #5507 ?

**Comment by cardio-junkie** [comment]
Even with all troubleshooting steps including a complete wipe of all Docker components and restarting the OS, Docker Desktop will not start if I upgrade to any version newer than 3.1.0 👎

**Comment by dhinojosa** [comment]
I got it to work (Maybe). I moved ~/.kube/config to another backup file name and it worked. All my Kubernetes clusters are down right now intentionally although I still had a config file that points to them. I think somehow it is trying to resolve what Kubernetes clusters you have running, and if it points to a cluster that doesn't exist then Docker never starts.

Hope that works for all of you. Let me know. I am interested.

**Comment by harrouet** [comment]
Honestly this is at least the 5+ issue talking about docker not starting, and none of them have gone above the level of a community forum discussion. I regret that Docker does not seem to care. Maybe Docker strongly needs a competitor.

In my case the issue is not related to Kubernetes. Docker just would not start, even when installed from scratch.

**Comment by dhinojosa** [comment]
Agree @harrouet

**Comment by dhinojosa** [comment]
One other thing I forgot to mention is also I uninstalled VirtualBox. If you can stand to part ways with Virtual Box, remove it by running the installer, and click on the remove VirtualBox on the bottom right-hand side of the installer's window. Even after uninstalling, I went into _~/Library_ and searched (`sudo find . -iname 'virtualbox'`) for any virtual box content.  I found a folder _.VirtualBox_ I removed that folder.  That along with moving the Kubernetes config to a backup seemed to have done the trick

**Comment by dresnick-sf** [comment]
The only workaround I've found is to downgrade to 3.1.0 (and I'm grateful to @cardio-junkie for that, I was about to reimage my laptop to see if that would help).

But due to the fact that docker insists on always upgrading (due to this ["feature"](https://github.com/docker/for-mac/issues/5119)), I am now forced to constantly reinstall the older version from scratch. Tips for anyone in this scenario: delete the docker app from the Applications folder and delete `~/.docker` if the app refuses to start without factory reset and then hangs on factory reset.

docker is turning into a real mess.

**Comment by harrouet** [comment]
> One other thing I forgot to mention is also I uninstalled VirtualBox. If you can stand to part ways with Virtual Box, remove it by running the installer, and click on the remove VirtualBox on the bottom right-hand side of the installer's window. Even after uninstalling, I went into _~/Library_ and searched (`sudo find . -iname 'virtualbox'`) for any virtual box content. I found a folder _.VirtualBox_ I removed that folder. That along with moving the Kubernetes config to a backup seemed to have done the trick

Thanks @dhinojosa. I also had a `~/Library/VirtualBox` folder, renamed it to see what happens, but still no luck.

Actually there seem to be a "disk full" issue in `/dev/vda1` in the logs, but nothing in the settings suggests that it should be limited.
