### ISSUE TITLE
Ask automatically for factory reset for docker.

### ISSUE THREAD

**Issue by AsmitNepali** [docker/for-mac#5565]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lujiamingzZ** [comment]
我也遇到了这个问题，请求解决！！！
https://github.com/docker/docker.github.io/issues/12655

**Comment by toph-allen** [comment]
I'm also seeing this. I downgraded from Docker 3.3.0 to 3.2.2, because I was being hit by a bug seemingly related to #5559 (or #5527). But relaunching 3.2.2 on macOS 11.3 Beta (20E5224a) gives me the following message.

<img width="1262" alt="Screen Shot 2021-04-12 at 5 02 14 PM" src="https://user-images.githubusercontent.com/3117884/114462467-147a2d00-9bb1-11eb-9321-258880ee985a.png">
