### ISSUE TITLE
3.3.0 high cpu usage

### ISSUE THREAD

**Issue by kumarunster** [docker/for-mac#5567]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DF430136-020F-4A49-8BD7-B12D769058A8/20210412130752

### Expected behavior

com.docker.hyperkit should not consume much cpu on idle docker containers

### Actual behavior

com.docker.hyperkit consumes too much cpu, as already reported on previous versions of docker for mac.

here are issue numbers for your reference:  #5092, #5044

<img width="1211" alt="Bildschirmfoto 2021-04-12 um 15 40 39" src="https://user-images.githubusercontent.com/2104820/114404046-a1b78480-9ba5-11eb-9d5a-e0b056c2f3da.png">

### Information

  - macOS Version:
  10.15.7 (19H524) Catalina

```
  Modellname:	MacBook Pro
  Modell-Identifizierung:	MacBookPro16,1
  Prozessortyp:	6-Core Intel Core i7
  Prozessorgeschwindigkeit:	2,6 GHz
  Anzahl der Prozessoren:	1
  Gesamtanzahl der Kerne:	6
  L2-Cache (pro Kern):	256 KB
  L3-Cache:	12 MB
  Hyper-Threading Technologie:	Aktiviert
  Speicher:	32 GB
```

  - Docker Desktop Version:

3.3.0 (62916)

**Comment by stephen-turner** [comment]
There are various possible causes of high CPU, but let me tell you the most common and you can see if any of them apply to you:

1. Running Kubernetes. We have made some optimisations to Kubernetes, but there are upstream problems we can't fix.
2. Sharing too many files. Unlike on Linux, where all containers have direct access to the file system, on Mac the files have to be shared into the VM that is running the containers, which is an inherently expensive operation. We have some tips in the documentation (https://docs.docker.com/docker-for-mac/#resources) about ways to reduce the load, including sharing only the files/directories you need to (e.g. do NOT share the whole of your home directory, this will almost inevitably lead to high CPU!) and using named volumes instead of bind mounts for things like databases. For certain write-heavy workloads, switching from grpcfuse to osxfs in the preferences may also help.
3. Using the Docker plugin on JetBrains products. See https://github.com/docker/for-mac/issues/5116#issuecomment-755870142 (and the remainder of that ticket).

**Comment by kumarunster** [comment]
@stephen-turner thanks for the quick response.
in my case:
1. not running kubernetes locally
2. yes, I do have mongodb, postgres and redis mounted to local folders, I'll try to migrate to named volume. The hint with osxfs helped to reduce CPU usage by down by half so far. Thank you.
3. Not using any JetBrains Plugins here.

Will try complete 2.) with named volumes in some time and report again.

**Comment by tomaszputon** [comment]
I can confirm, that this is true -> upgraded from 3.2.2 to 3.3.0 and have same high CPU consumption.

**Comment by hsunatkkday** [comment]
I have the same problem on version 3.3.1.
<img width="758" alt="Screen Shot 2021-04-27 at 12 16 49 PM" src="https://user-images.githubusercontent.com/40378436/116184531-86767880-a752-11eb-873f-92903e786009.png">

**Comment by Schwad** [comment]
I'll see if the above guidance helps but I am definitely getting hit with this out of the blue, while just even using my browser. v 3.3.1

**Comment by skys215** [comment]
Same here using version 3.3.3.

I'm running `mysql` only. The docker will have high cpu usage sometimes even doing nothing.

I will keep eye on it if there's some occasion that triggers the problem.
