### ISSUE TITLE
Very slow fsync() on shared container volume

### ISSUE THREAD

**Issue by osheroff** [docker/for-mac#560]
When re-creating a development database, mysql under docker will call `fsync()` a lot.  these calls are taking between 25 and 30ms each.  The container was booted as:

``````
docker run -v /var/lib/mysql --name MYSQL_DATA_NEW busybox true
docker run --volumes-from MYSQL_DATA_NEW --net docker -d --name mysql --hostname mysql  -p 3306:3306 [private-repo]/mysql bash run.sh```
``````

You can see the slowness under strace:

```
root@ea5b3c31c695:/# strace -p `pgrep -f mysqld` -ff -t -TT 2>&1 | grep fsync
[pid 27356] 04:38:57 fsync(9)           = 0 <0.024066>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.018833>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.024052>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.028534>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.025760>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.022935>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.020960>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.025935>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.023266>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.025116>
[pid 27356] 04:38:57 fsync(9)           = 0 <0.023262>
```
### Information
- Docker for Mac: version: 1.12.1-beta25 (158f2ee)
- OSX 10.11.6 (15G31)
### Steps to reproduce the behavior
1.  Perform lots of "create table" statements with mysql with its data directory shared from another container.  Watch the slowness commence.

Note that tuning and tweaking mysql to do less fsyncs gets some mild speed win, but nowhere near native speeds.

**Comment by libo** [comment]
Yeps.. I can see the same behaviour. Thanks @osheroff for investigating :-)

**Comment by samoht** [comment]
fsync on OSX unfortunately slower than on Linux: see https://github.com/mirage/mirage-block-unix/issues/49 for the initial issue and https://github.com/mirage/mirage-block-unix/pull/52 for the "fix". Since latest beta we allow to turn on an "experimental" mode where fsync is faster but less safe: if your computer crashed in the middle of an fsync, we won't guarantee in that mode that you won't corrupt the qcow2 image ... so use it at your own risk. Closing as a duplicate of https://github.com/docker/for-mac/issues/668#issuecomment-250406582

**Comment by dsheets** [comment]
This looks like it is related to bind mounts rather than block device syncs. I haven't reproduced it yet but I am reopening as the block device issue is not the likely cause.
