### ISSUE TITLE
Docker start Error

### ISSUE THREAD

**Issue by Blenzkim** [docker/for-mac#562]
### Information

Diagnostic ID: 1E0696CC-0737-4629-AA51-9FB7128809A0
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during installation in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg.
