### ISSUE TITLE
During installation

### ISSUE THREAD

**Issue by Glagnar** [docker/for-mac#563]
### Information

Diagnostic ID: 9704BE79-3B46-4DB8-820F-8C4553BD72EF
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/tgilbert/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/9704BE79-3B46-4DB8-820F-8C4553BD72EF/20160909-080339/qemu-img-check.stdout 2> /tmp/9704BE79-3B46-4DB8-820F-8C4553BD72EF/20160909-080339/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/tgilbert/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/tgilbert/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/tgilbert/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/tgilbert/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/tgilbert/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during installation in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg.
