### ISSUE TITLE
Setting "Open Docker Desktop dashboard at startup" not working

### ISSUE THREAD

**Issue by cn007b** [docker/for-mac#5652]
On Mac Big Sur 11.3 regardless of setting "Open Docker Desktop dashboard at startup" from General section dashboard alway appears when launch docker.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker dashboard does not appear when launch docker.

### Actual behavior
Docker dashboard appears when launch docker.

### Information

  - Is it reproducible: yes.
  - Is the problem new: yes.
  - Did the problem appear with an update: apparently after some of them.
  - macOS Version: big sur 11.3.
  - Intel chip or Apple chip: inter.
  - Docker Desktop Version: 3.3.1 (63152).

### Steps to reproduce the behavior
Launch docker on Mac Big Sur 11.3.

**Comment by djs55** [comment]
@cn007b thanks for your report. I was unable to reproduce the problem with the latest version (3.3.2). Could you upgrade and try again? If it doesn't work, could you manually upload diagnostics from the terminal following the instructions here: https://docs.docker.com/docker-for-mac/troubleshoot/#diagnosing-from-the-terminal (Unfortunately there is a bug in the diagnostics upload from the UI which will be fixed in 3.3.3)
