### ISSUE TITLE
Unexpected volume unmount

### ISSUE THREAD

**Issue by mcculleydj** [docker/for-mac#5656]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

^ re: Diagnostics ID, I was able to generate the diagnostics, but it's been trying to upload for about an hour. I don't think it's going to happen, unless it has, and it failed to notify. The timestamp for the report was 20210506014148.

I'm pretty confident you'll be able to repro this without diagnostics. I also suspect that a lot of complaints about volumes "randomly" unmounting or high CPU usage can be attributed to what I am about to describe.

### Expected behavior

  - volume remains mounted even if a directory on the host is removed

### Actual behavior

  - volume unmounts when a directory on the host is removed

### Information

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: 2.6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.3.2 (63878)

### Steps to reproduce the behavior

Describing this in the context of docker-compose and Node, but this would apply to any bind mount and volume combination.

  - take a standard Node.js project and run it using docker-compose
  - bind mount the project
  - created a volume in the compose file and mount it to isolate node_modules in the container from node_modules on the host
 
```
services:
  node:
      ...
      volumes:
          - .:/app
          - exclude:/app/node_modules
 
volumes:
  exclude:    
```
  - after docker-compose up you can safely `npm i` from the host and not share OSX node_modules with a Linux container or pay the performance cost of bind mounting a ton of dependencies
  - connect to the running container
  - now `rm -rf node_modules` from the host
  - observe that the volume has been unmounted
  - if you were to `npm i` from the host again you'd now be bind mounting node_modules (this is where the high CPU usage may happen as FUSE tries to sync 100s of MBs of deps and confuses people who do not understand the volume is no longer mounted)

This pattern of using a volume to _mask_ node_modules was discussed at DockerCon and is a fairly common. If what I've described is not a bug in your view, then is there a method to truly isolate a volume from actions like `rm -rf`  on the host in a set up like this?

Alternatives are:
- individually mounting everything at the top level of the project except the node_modules
- remembering to `rm -rf node_modules/*` if you want to remove node_modules on the host since this will leave the mounted volume in place

**Comment by stephen-turner** [comment]
Thanks for the report, @mcculleydj. Interesting, I hadn't previously seen that hack for hiding a subdirectory from the VM.

However, I'm afraid that while it will stop the subdirectory being visible inside the VM, it won't do what you were hoping in terms of performance. It will prevent changes on the VM's filesystem being synced back to the host, but it won't prevent changes on the host's filesystem being synced to the VM. We did at one point consider a mechanism for including and excluding subdirectories from the cache, but there are lots of corner cases (overlapping directories, symlinks, etc.) and it got very complicated (and buggy!) very quickly.

The volume being unmounted when you rm the subdirectory is a bug, and I've filed an internal ticket. It should continue to stay mounted with the contents of the `exclude` volume. However, even before that step, changes in the subdirectory on the host will be notified to the VM even if they're not visible there.

Oh, and the diagnostics upload will be fixed in 3.3.3.

**Comment by mcculleydj** [comment]
Thanks for the rapid and detailed response! Good to know that rm from host unmounting volume is not expected behavior. Also, good to know that while this hack prevents OSX node_modules from showing up in a Linux container it does not stop Docker from spending the cycles to sync those files even if they don't show up. That explains why the fan will often kick on when the container is running during an `npm i` on the host even with the exclude volume mounted. Noted on the complexity of "bind mount everything but X." and the upload issue. Will the internal ticket become a GitHub issue that I can track? I am interested to see fix if possible, thanks again!

**Comment by stephen-turner** [comment]
Actually, I'll reopen this issue for the part that is a bug.
