### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by elvizlai** [docker/for-mac#567]
### Information

Diagnostic ID: 6C02AD9B-7374-4356-A2F5-E446E032592F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/elvizlai/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/6C02AD9B-7374-4356-A2F5-E446E032592F/20160909-191835/qemu-img-check.stdout 2> /tmp/6C02AD9B-7374-4356-A2F5-E446E032592F/20160909-191835/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during run-time in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.
