### ISSUE TITLE
Docker always meets fetal error after Mac updates to 10.12

### ISSUE THREAD

**Issue by nowsyn** [docker/for-mac#569]
### Information

Diagnostic ID: 6C38C890-9C2C-40A8-A64B-8FFCDB503829
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A285a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during run-time in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.
