### ISSUE TITLE
High CPU usage by docker

### ISSUE THREAD

**Issue by hannahagee** [docker/for-mac#5698]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B88C33F9-3526-4B55-BDB6-745C5EC4A940/20210517130519

### Expected behavior
Docker would not consume up to and over 100% cpu

### Actual behavior
Docker increasingly consumes cpu. If there is any action to Docker desktop UI the cpu increases more.

### Information

  - macOS Version: Catalina 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: v20.10.6

### Steps to reproduce the behavior

  1. Start Docker Desktop

**Comment by stephen-turner** [comment]
Thank you for the report.

There are various possible causes of high CPU, but let me tell you the most common and you can see if any of them apply to you:

Running Kubernetes. We have made some optimisations to Kubernetes, but there are upstream problems we can't fix.
Sharing too many files. Unlike on Linux, where all containers have direct access to the file system, on Mac the files have to be shared into the VM that is running the containers, which is an inherently expensive operation. We have some tips in the documentation (https://docs.docker.com/docker-for-mac/#resources) about ways to reduce the load, including sharing only the files/directories you need to (do not share the whole of your home directory!) and using named volumes instead of bind mounts for things like databases. For certain write-heavy workloads, switching from grpcfuse to osxfs in the preferences may also help.
Using the Docker plugin on JetBrains products. See https://github.com/docker/for-mac/issues/5116#issuecomment-755870142 (and the remainder of that ticket).
Maybe one of these will help you.

**Comment by kevin-lindsay-1** [comment]
I'm having this issue too, seemingly after a new update. I'm trying a few versions to see if that behavior changes between them.

**Comment by karnauskas** [comment]
I noticed high docker cpu usage as well. Running cluster created by `kind` (Kubernetes in Docker) only.

**Comment by cscetbon** [comment]
I have the same issue, disabling GRPC feature fixes it but then my containers get stuck when they try to access the filesystems a second time. It's really annoying ...

**Comment by mvidalgarcia** [comment]
> I noticed high docker cpu usage as well. Running cluster created by `kind` (Kubernetes in Docker) only.

Same here, did you manage to solve it? @kevin-lindsay-1

**Comment by kevin-lindsay-1** [comment]
@mvidalgarcia I switched over from minikube to dd's built-in kube, and then made sure my ventilation on my mac was good.

CPU heat is definitely a factor in the real-world performance of docker; I ventilated better and the issue largely went away.

Hard to say if any OS or docker updates made an impact.

**Comment by karnauskas** [comment]
was this issue resolved?
