### ISSUE TITLE
Cocker Crashing

### ISSUE THREAD

**Issue by deep1kk** [docker/for-mac#573]
### Information

Diagnostic ID: 1121848E-7A59-460C-A7ED-72D4665AF24F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Not enough details. Closing

**Comment by dsheets** [comment]
If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
