### ISSUE TITLE
MacBook Pro m1 - The storage doesn't change with system prune. 

### ISSUE THREAD

**Issue by alexrobl** [docker/for-mac#5747]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: AB7C4038-A35A-435D-B901-CFA43A55529B/20210611235458

### Information

  - macOS Version: Big Sur 11.04
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 20.10.7

### Steps to reproduce the behavior

  1. I installed some images and run containers, I want to delete this images and container.
  2. I run "docker system prune -a"
  3. I can look in the terminal that was okey and the containers, images etc was delete, but I find out that in docker desktop interface the data storage doesn't change. so, this space in the disk doesn't recover.

Could anyone help me?

**Comment by brandon-blb** [comment]
Hi, I have the exact same issue.

### Information

- macOS Version: Big Sur 11.4
- Intel chip or Apple chip: Apple M1
- Docker Version: 20.10.7, build f0df350
- Docker Desktop Version: 3.4.0 (3.4.0.5223)
- Experimental Features: all standard (Nothing extra enabled, changed)

I have the same issue and had to purge all data a few times now and start over due to this issue.
The the image below, you can see that Docker desktop states 26.5 GB is used, but from `docker system df ` you can see I am close to 11 GB.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/10627196/123273933-5a356900-d503-11eb-9cfb-aa168730343b.png">

Also, see the size of the Docker.raw file:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/10627196/123275332-843b5b00-d504-11eb-8158-0525916eddd8.png">

I am not sure if this is a issue just with docker desktop reporting the incorrect value, because if I ssh into the vm, the total disk size is 13.6:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/10627196/123276069-252a1600-d505-11eb-9c16-fc28e1b1ceaa.png">

I do recall having a issue were postgres reported no space left when trying t restore a db, even if there should have been enough space.

Hope this helps with any investigations.
