### ISSUE TITLE
inotify MODIFY events not happening when file is being written in 3.4.0

### ISSUE THREAD

**Issue by kishaningithub** [docker/for-mac#5755]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B0A9A7FC-66B5-4990-844A-28D1DCF2C092/20210615000732

### Expected behavior
inotify MODIFY events should happen for every write in the volume mounted file

### Actual behavior
inotify MODIFY events are happening only when the process writing to the file terminates/the file is closed

### Impact
Log processors(Eg [fluent-bit](https://fluentbit.io/)) are not able to pickup changes to the log files which are volume mounted within the container

### Information

  - macOS Version: macOS BigSur 11.4
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 3.4.0 (3.4.0.5223)

### Steps to reproduce the behavior

- Create a new directory, `cd` into it and place following contents in `writer.go`
```writer.go
func main()  {
	file1, _ := os.OpenFile("./file.txt", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	for i := 0; i < 1000; i++ {
		_, _ = file1.WriteString("content\n")
		fmt.Printf("%d lines written\n", i + 1)
		time.Sleep(1 * time.Second)
	}
}
```
- From the directory, run the following commands in separate tabs
```shell
# Write ./file.txt continuously with 1 second delay between writes
$ go run writer.go

# Monitor inotify events in the mounted volume
$ docker run --rm -it -v "$(pwd):/app" -w /app kishanb/centos-inotify:7 inotifywait -m .

# View no. of lines visible inside container
$ docker run --rm -it -v "$(pwd):/app" -w /app kishanb/centos-inotify:7 wc -l ./file.txt 

# Watch no. of lines visible in host
$ watch wc -l ./file.txt 
```

- If you observe the file being written the changes are actually visible inside the container but the inotify MODIFY event never gets fired till the go process is terminated 

Also note, when file is closed after write MODIFY events are getting fired as expected, the problem is only with continuous write
```
# Open file for append, close and repeat
$ while true; do echo 'content' >> ./file.txt; done
```

#### Screen recording GIF

![inotify_modify](https://user-images.githubusercontent.com/763760/121977284-4bccac00-cda3-11eb-8f2e-76ad0bd939d8.gif)

**Comment by djs55** [comment]
@kishaningithub thanks for the very clear report and repro steps. I see the same phenomenon on my local machine.

Docker Desktop uses the native macOS `fsevents` API to watch the host filesystem for changes. Unfortunately this API only generates a file modification event when the file is closed after a write. The best reference I could find for this behaviour is from [Mac OS X Internals: A Systems Approach, Section 11.8.2](https://books.google.co.uk/books?id=K8vUkpOXhN4C&pg=PA1416&lpg=PA1416&dq=fsevents+modify+when+file+is+closed&source=bl&ots=ONjjSZWpUD&sig=ACfU3U01Q6MhdwXffv9msYqeF1JzIaSimQ&hl=en&sa=X&ved=2ahUKEwj707K7xKvxAhWR8uAKHSq2CUgQ6AEwCXoECAoQAw#v=onepage&q=fsevents%20modify%20when%20file%20is%20closed&f=false)  page 1416 "The Fsevents Mechanism" where it says:

> `FSE_CONTENT_MODIFIED`: A file's content was modified -- specifically, a file that is being closed was written to while it was open.

Unfortunately I don't think there is anything we can do in Docker Desktop to work around this.

For log processing it would be more efficient to store the logs inside a native Linux `docker volume` (e.g. `docker volume create my-logs` and then `docker run -v my-logs:/some/path`. Since the files will be inside a Linux filesystem, the filesystem events will be 100% as expected. The only disadvantage is the logs will not be visible directly on the host; but they can be easily accessed from containers (`docker run -v my-logs:...`) and from the new [Volume UI in Docker Desktop 3.4](https://www.docker.com/blog/volume-management-compose-v2-skipping-updates-and-more-in-docker-desktop-3-4/). Let me know if this would work for you, and if not, please describe your setup in more detail and I'll see if I can think of any other advice.

**Comment by kishaningithub** [comment]
Thanks for the detailed response @djs55 

I followed the above approach via docker compose named volumes and things are very reliable.  

Closing the issue.

**Comment by djs55** [comment]
@kishaningithub thanks for letting me know -- I'm glad everything is working reliably for you!
