### ISSUE TITLE
M1 docker build golang image error (version 3.4.0)

### ISSUE THREAD

**Issue by leezy23** [docker/for-mac#5757]
![image](https://user-images.githubusercontent.com/38031780/122009087-50698280-cdec-11eb-869c-13e5f9bea564.png)

**Comment by leezy23** [comment]
/lib64/ld-linux-x86-64.so.2: No such file or directory

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
