### ISSUE TITLE
Docker is not able to start at mac startup

### ISSUE THREAD

**Issue by hex22a** [docker/for-mac#5768]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 0B8737CE-EBF1-4D5B-91C2-9DC2723EC5B9/20210618120435

### Expected behavior

Docker starts at startup

### Actual behavior

Docker is not able to start

### Information

  - macOS Version: 11.4 (20F71)
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: Version 3.4.0 (3.4.0.5223)

### Steps to reproduce the behavior

  1. start mac

**Comment by kurtjunker** [comment]
Hi,

I had the same Problem since Update Docker Desktop to Version 3.4. After downgrade the Version to 3.3 Docker Desktop is working as expected.

Expected:
- start Docker Desktop with OS

Actual:
- Docker Desktop freezing on Startup
- Hard Kill via Application Manager is necessary

**Information**

- macOS Version: 11.4
- Intel or Apple Chip: Apple Chip
- Docker Desktop Version: 3.4.0

Steps to reproduce the behavior:
- install or update Docker Desktop 3.4.0
- restart Mac

**Comment by BenjaminX** [comment]
3.5 still not working, "Failed to ping backend API".

**Comment by BlakesEyeR1** [comment]
I have made a couple of upgrade attempts and had to revert to 3.3 "Failed to ping backend API".
