### ISSUE TITLE
Docker 3.5.0 failure running docker command in our container. Works on 3.4.0

### ISSUE THREAD

**Issue by ericvn** [docker/for-mac#5787]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 15DA2C3F-D198-493A-BAD4-492E424F3D4C/20210624175324

### Expected behavior

The docker commands run successfully as in the past.

### Actual behavior

Running the `docker` command yields 
```
docker ps
Cannot connect to the Docker daemon at unix:///Users/ericvn/.docker/run/docker.sock. Is the docker daemon running?
```
It seems to not want to use /var/run/docker.sock
If I set DOCKER_HOST or use -H and specify unix:///var/run/docker.sock, the command runs successfully.
```
build-tools:/work$ docker ps
CONTAINER ID   IMAGE                                                         COMMAND                  CREATED         STATUS         PORTS     NAMES
bc7932739e79   gcr.io/istio-testing/build-tools:master-2021-06-16T23-16-54   "/usr/local/bin/dock…"   5 seconds ago   Up 4 seconds             serene_darwin
```

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.0

### Steps to reproduce the behavior

  1. On a Mac with Docker Desktop and make install, clone the https://github.com/istio/istio repo. You will want to export `DOCKER_SOCKET_MOUNT=-v /var/run/docker.sock.raw:/var/run/docker.sock` (to get around the problem I reported in an earlier PR) and run `make shell`. Once you get the prompt, try running `docker ps`. It will hopefully fail with some sort of  `Cannot connect to the Docker daemon` message. If you then export DOCKER_HOST=unix:///var/run/docker.sock and rerun docker ps it will work.

**Comment by Winedays** [comment]
I solved this problem following https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues
using `docker pull --platform linux/amd64 python:3.8.3-alpine3.12`

**Comment by stephen-turner** [comment]
@djs55 PTAL. Thanks.

**Comment by thaJeztah** [comment]
Do you have specific (docker-related) environment variables set in your host environment? This line looks suspicious; https://github.com/istio/istio/blob/bb351241cbabee893357416e34288f0690dae858/common/scripts/run.sh#L55

```
--env-file <(env | grep -v ${ENV_BLOCKLIST}) \
```

From that, it looks like it's copying all of the host's environment variables to the container's environment (with some exclusion list); https://github.com/istio/istio/blob/5aea843a932deb3b363fafeea3f0b1a1bfc4d3ea/common/scripts/setup_env.sh#L89

```
export ENV_BLOCKLIST="${ENV_BLOCKLIST:-^_\|PATH\|SHELL\|EDITOR\|TMUX\|USER\|HOME\|PWD\|TERM\|GO\|rvm\|SSH\|TMPDIR\|CC\|CXX\|MAKEFILE_LIST}"
```


Those environment variables may not match the environment inside the container. e.g., the docker socket is bind-mounted at `/var/run/docker.sock` inside the container; https://github.com/istio/istio/blob/bb351241cbabee893357416e34288f0690dae858/common/scripts/run.sh#L53

```
 ${DOCKER_SOCKET_MOUNT:--v /var/run/docker.sock:/var/run/docker.sock} \
```
 but from your report, it looks like the cli inside the container is trying to connect to  `/Users/ericvn/.docker/run/docker.sock` (which won't be there)

**Comment by ericvn** [comment]
@thaJeztah I had thought of this yesterday as well. In my current working container environment, I see:
```
env | grep DOCKER
DOCKER_SOCKET_MOUNT=-v /var/run/docker.sock.raw:/var/run/docker.sock
DOCKER_GID=
MAKE_DOCKER=./common/scripts/run.sh make --no-print-directory -e -f Makefile.core.mk
DOCKER_HOST=unix:///var/run/docker.sock
```
If I unset `DOCKER_HOST`, I get the Cannot connect message. I can uset all the other `DOCKER` env vars (noting that they are not all Docker specific), the docker ps continues to fail. I did remove the line that passes in the env list as another thought yesterday, and verified again today, and the env list is much smaller but docker ps still fails. In that environment if I set DOCKER_HOST, docker ps works.

I'm not sure if something in the `docker` command changed in how it determines the default docker host. The docs imply it should default to /var/run/docker.sock, which seems to no longer be the case, as explicitly setting it to that makes things work. It seems the new default is replacing `/var`with something pointing to the host's user's .docker directory `/Users/ericvn/.docker`.

**Comment by ericvn** [comment]
One thing I do notice is the endpoint for the desktop-linux context seems to point to the now failing endpoint being used:
```
docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                KUBERNETES ENDPOINT                                           ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                    https://c1.us-east.containers.cloud.ibm.com:30079 (default)   swarm
desktop-linux       moby                                                          unix:///Users/ericvn/.docker/run/docker.sock
```

**Comment by ericvn** [comment]
That's why I did the `env | grep DOCKER` shown in my prior comment. Looking at the page you mention, all the env vars do have DOCKER in them, so that should rule out that issue.

`docker version` inside the container yields:
```
docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Simply starting the dev container using a constant build image:
Docker Desktop for Mac v 3.4.0 - `docker ps` in container works
Docker Desktop for Mac v 3.5.x - `docker ps` in the container fails.
Docker Desktop for Mac v 3.5.x - set DOCKER_HOST to var/run/docker.sock, `docker ps` succeeds.

**Comment by ericvn** [comment]
Also a docker context from inside the container:
```
docker context list
NAME            DESCRIPTION                               DOCKER ENDPOINT                                KUBERNETES ENDPOINT                                           ORCHESTRATOR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                    https://c1.us-east.containers.cloud.ibm.com:30079 (default)   swarm
desktop-linux                                             unix:///Users/ericvn/.docker/run/docker.sock
Warning: DOCKER_HOST environment variable overrides the active context. To use a context, either set the global --context flag, or unset DOCKER_HOST environment variable.
```

**Comment by ericvn** [comment]
I do see the the release notes: `The default docker CLI context is now desktop-linux.`

**Comment by thaJeztah** [comment]
> So seems the default context is not the default *'d context, but maybe something changed so desktop-linux is now the default context.

Oh! Looks like your comment about the context crossed my comment. Hmm.. yes, that looks suspicious, and would explain (if the container shares the `~/.docker` directory).

@djs55 I think you know more about that `desktop-linux` context? (I saw you mention it somewhere, but wasn't aware it also uses a non-standard location for the socket)

**Comment by briceburg** [comment]
We also just got hit by this issue when updating to docker for mac 3.5.0|1 ... and use a tool very similar to istio's that wraps a container w/ the current environment as if it were installed on the system: https://github.com/briceburg/tools/blob/main/bin/exec

it does mount the user's ~/.docker as ~/.docker in the container....

the proposed workaround of setting DOCKER_HOST=/var/run/docker.sock in the container does not seem to work. e.g. 

```
EXEC_IMAGE=docker:20 \
  bin/exec sh -c 'DOCKER_HOST=/var/run/docker.sock docker ps'
  
 > Cannot connect to the Docker daemon at tcp://localhost:2375/var/run/docker.sock. Is the docker daemon running?
```

because this tool is in widespread use I have to recommend our developers stick w/ 3.4 until an appropriate/stable workaround can be found. I am going to experiment w/ some others now...

**Comment by briceburg** [comment]
I've also tried to use the new desktop-linux from within the container by unsetting DOCKER_HOST. I even set world-writble perms on the ~/.docker/run/docker.sock as a shot in the dark...

```
EXEC_IMAGE=docker:20 \
  bin/exec sh -c 'unset DOCKER_HOST; docker ps'

# Cannot connect to the Docker daemon at unix:///Users/brice.burgess/.docker/run/docker.sock. Is the docker daemon running?
```

because this tool is in widespread use I have to recommend our developers stick w/ 3.4 until an appropriate/stable workaround can be found. I am going to experiment w/ some others now...

**Comment by ericvn** [comment]
> Oh! Looks like your comment about the context crossed my comment. Hmm.. yes, that looks suspicious, and would explain (if the container shares the `~/.docker` directory).

Yes, we do share the .docker directory into the container. I would have to verify, but I believe that is done so the `docker` in the container can push images to repos with the creds obtained from the host. I know that the creds can't be obtained in the container (running linux) from the host's (MacOS in this case) keychain.

**Comment by briceburg** [comment]
OK -- I did have success with the workaround. I wasn't understanding it properly.

The trick is to start the DooD container (that has the docker client in it) under the `default` docker context instead of `desktop-linux` *and* to pass this to any child containers.


One way I found to re-produce without custom tooling is via docker-compose. Given the following docker-compose.yml file;

```
---
version: "3.9"
services:
  foo:
    image: docker:20
    command: docker ps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

If we run (from within the directory containing this compose file),

```
docker run -it --rm \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  docker/compose:1.29.2 sh -c '
    docker-compose run foo
  '
```

it works as expected. 

**however** if our DooD container passes through the environment (via tools like bin/exec or the istio run.sh wrapper @ericvn is using that are mounting ~/.docker), we get the `Cannot connect to the Docker daemon` error. e.g.

```
docker run -it --rm \
  -e "DOCKER_CONFIG=$HOME/.docker" \
  -v "$HOME/.docker:$HOME/.docker" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  docker/compose:1.29.2 sh -c '
    docker-compose run foo
  '
```

results in `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))`


**To workaround**, we need to start our container under the `default` docker context instead of `desktop-linux` *and* pass it through.

```
export DOCKER_HOST=$(docker context inspect -f "{{ .Endpoints.docker.Host }}" default)
docker run -it --rm \
  -e "DOCKER_HOST=$DOCKER_HOST" \
  -e "DOCKER_CONFIG=$HOME/.docker" \
  -v "$HOME/.docker:$HOME/.docker" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  docker/compose:1.29.2 sh -c '
    docker-compose run foo
  '
```

@thaJeztah do you think I should modify bin/exec to accommodate or is this something that may see an upstream fix restoring previous behavior? 

thanks!

**Comment by djs55** [comment]
@briceburg @ericvn I've created a developer build of Docker Desktop which switches the user back to the `default` context exactly once on upgrade: https://desktop-stage.docker.com/win/stable/amd64/66318/Docker%20Desktop%20Installer.exe Hopefully this fixes the short-term issue -- let me know if you get a chance to try it!

Thinking about the future: docker CLI contexts are relatively new and maybe not very heavily used yet.  On my local machine I have 6 or 7 contexts configured, representing other machines on my network and in the cloud, accessible over `ssh`. I wonder when developers clone istio/istio and run `make shell` and then `docker ps`, is it desirable to always choose the local engine (so explicitly choosing `default` would make sense) or would it be useful to use the currently configured (perhaps remote) engine? I'm curious to know what you think. Depending which `docker` commands you need to run, using a remote engine might not be feasible currently. For example `-p` will publish a port on the remote engine (not the local machine) and `-v` will bind from the remote engine's host (again not the local machine). Anyway, I'm keen to know what you think!

**Comment by ericvn** [comment]
@djs55 Unfortunately, I am running on a Mac so cannot try the provided installer.

I'm not sure `docker ps` is run all that much in the Istio build container, it's just an easy thing to run in the container that failed. I think `docker build (or maybe buildx)`, `docker push`and `docker exec` might be the most common. I wasn't part of the team that did the build container implementation, just one who helped test it on the Mac. I expect that today, most would probably be using the local engine. I'm now wondering if we could just change the volume binding to match that used by the current context, although a quick test didn't seem to work.

**Comment by ericvn** [comment]
It seems I can remove the workaround (setting DOCKER_HOST) after upgrading to 3.5.2, and I can again run `docker` commands inside the build container.

**Comment by lorenrh** [comment]
We have just released the 3.5.2 version of Docker Desktop, so I'm closing this. 😄

**Comment by djs55** [comment]
@ericvn thanks for your feedback. Hopefully everything works as it did before, and in Docker Desktop we'll avoid automatically switching CLI contexts in future :)

**Comment by briceburg** [comment]
@djs55 I am sorry to have lapsed in response. it's good to hear this was "fixed" (or at least, previous behavior restored) in 3.5.2+ 

I must say the context stuff is *very cool* and reminds me a lot of the docker machine days where there was an enjoyable and simple approach to remotely scheduling containers -- especially services and such. 

For my particular use-case, I was running "contained tooling" (think `git`, `terraform`, `gradle`) and using a tool like [bin/exec](https://github.com/briceburg/tools/blob/main/bin/exec) to pass-through the current user's environment.

I can still modify this tool to use the "default" context workaround discussed here and be able to support for docker/for-mac 3.5.0 and 3.5.1

for these kinds of tools (bin/exec and the istio wrapper), we 99.99% of the time infer running locally and can rely on DOCKER_HOST to set otherwise.

at one point I ported [edit.com](https://github.com/dockerland/dex-dockerfiles-extra/tree/master/dex-images/edit) and [deltree.exe](https://github.com/dockerland/dex-dockerfiles-extra/tree/master/dex-images/deltree) to run "natively" on linux using this kind of an approach... crazy fun.

Thanks,

~ Brice
