### ISSUE TITLE
Please don't opt users into "experimental" features without asking (compose V2)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5800]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics Irrelevant
  - Diagnostics ID:

### Expected behavior

When I upgrade to a new version of Docker Desktop, I should have the same settings that I had before upgrading.

### Actual behavior

Some users are getting the "Use Docker Compose v2" experimental setting enabled for them on upgrade to Docker Desktop 3.5+  without their consent or buy-in. 
<img width="1040" alt="Settings" src="https://user-images.githubusercontent.com/112444/123820529-e35bef80-d8b7-11eb-9094-92fcd0d7ee36.png">

There are a number of features of Docker Compose v2 which break [ddev](https://github.com/drud/ddev) currently. I'm happy to try to sort them out and make sure things work in upcoming versions (already filed several issues in compose-cli and ddev issue queues), but it's not friendly behavior to enable features like this without user opt-in.

Apparently you have some kind of "canary experiment" going on. Please don't do this. Experimental features are experimental and should be enabled by choice of the user. 

### Information

  - macOS Version: All
  - Intel chip or Apple chip: All
  - Docker Desktop Version: 3.5+

### Steps to reproduce the behavior

This isn't under the control of the users. Some users upgrading to docker desktop 3.5+ get the "compose v2" checkbox enabled for them.

Note that this happens on both Windows and macOS.

**Comment by stephen-turner** [comment]
Sorry, Randy, we're not going to change this. But let me give you some context to explain our reasoning.

The lifecycle of a new version of a feature is roughly this:

1. Experimental feature that people can opt into
2. Experimental feature that people are opted into but can opt out of
3. Feature that is no longer experimental but people can still opt out of it
4. Feature that is mandatory: previous version is no longer available

In this case, because compose is such a core feature, we've elected to do step 2 very slowly, i.e., rolling it out to a gradually increasing percentage of users.

I realise it's step 2 you're objecting to. But the alternative is to jump straight from 1 to 3, i.e., turn it on for everyone at the same time, which would cause far more problems if there are issues with it. Unfortunately the opt-in phase in step 1 doesn't give us enough users and enough data to find all the bugs in all the millions of use cases our software is used for: it's the peril of being a platform. So we think it's better to turn it on for a gradually increasing percentage of users, rather than switch everyone's behaviour at once. When we do, we notify the user and give them instructions how to turn it off again.

**Comment by rfay** [comment]
Hi @stephen-turner - The problem was missing step 1! We needed to be at step 1 for a few months. I could have checked everything and both ddev and compose-cli could have matured to where there was no issue. 

Here we have a few people (random I guess) being canaried into the feature without notice, when it's just been introduced.

I don't object to your four steps. I object to skipping step 1. And I object to Step 2 being randomly distributed to users without notice.

**Comment by stephen-turner** [comment]
We didn't skip step 1. We introduced compose v2 (as "docker compose" rather than "docker-compose") on December 10. We advertised it in-app, and we got about 10% of people using it. After six months we realised that we could never complete the transition unless we started moving some "docker-compose" users onto it, which began on June 9 (step 2). We advertised it in a blog post and in the release notes, and individually for each person who we move onto v2.

Of course we're keen to hear of incompatibilities and welcome bug reports at docker/compose-cli

**Comment by rfay** [comment]
I understand your argument about "docker compose", and also that you wanted to get compose-cli out there, and I know how hard that can be to accomplish.

But...
1. You introduced this as an "experimental" feature last week for the first time. 
2. This was the first time that docker-compose changed behavior for all users of Docker Desktop
3. You knew that 90% of users had not use used "docker compose", and you knew that 100% of users of tools like ddev and lando (which wrap docker-compose) had not yet tried it. 
4. You deliberately enabled the feature for some subset of "canary" users without opt-in. This was the part that caused trouble. This is where you skipped your step 1. 

All I'm asking is... Don't enable an experimental feature until it's had some time as an experimental feature.  Even for a few canary users. 

ddev required 3 PRs to become functional with the new docker-compose;  I created another 3 issues in compose-cli. One made the build stage of projects completely nonfunctional on Windows.  To me this isn't "very few bug reports".  (But I should note I got super-responsive support. Not always the answers I wanted, but super, super responsive, thanks @ndeloof!)

**Comment by ndeloof** [comment]
> You introduced this as an "experimental" feature last week for the first time.
yes indeed, as we do for many other features on each and every release

> This was the first time that docker-compose changed behavior for all users of Docker Desktop
Not for **all** users. We use canary testing here to get a limited set of users to opt-it, and still notify them so they can opt-out

> You knew that 90% of users had not use used "docker compose", and you knew that 100% of users of tools like ddev and lando (which wrap docker-compose) had not yet tried it.
Even 10% of users on such a large user base is still significant with thousands usages a day. About tools, we have some internal tests to cover the basic usages, but we obviously can't test everything. 

> You deliberately enabled the feature for some subset of "canary" users without opt-in. This was the part that caused trouble. This is where you skipped your step 1.
Hey, that's how canary testing work! Maybe you didn't noticed, but accessing this page on github you maybe have been opted-in for some new canary feature you didn't know about, without asking for it

**Comment by stephen-turner** [comment]
I think the only additional thing we could have done is to allow people to switch on the docker-compose -> v2 alias for a period of time before starting to force them. We have had it as an experimental feature for six months with excellent participation (10% is really high for something like this). But I accept that it is possible that ddev and lando use cases were still not captured, and we didn't consider that.

Having said that, I'm still a bit dubious whether it would have made much difference. We find that not many people switch on the experimental features unless they are trying to fix some specific problem. I think that we still would have hit a time where we had to move people forcibly and see what breaks.

**Comment by rfay** [comment]
It would have been very easy to delay the canarying for a couple of months while notifying all of us wrapper maintainer (and the rest of the world) that it was going to happen then, that "docker-compose" would start to appear as a completely different animal in a few months. Then I could have made sure that everything worked in advance.

People don't expect newly introduced experimental features to be enabled without warning. 

I continue to get support issues, including this morning about the compose-cli critical failure on Windows, https://github.com/docker/compose-cli/issues/1854, where somebody installed latest docker desktop, was canaried in, and had a fatal experience for their first experience.

Please, if a feature is "experimental", let it be opt-in for everybody for a period of time. Make a clear statement about when it may appear as a canary or as a default. Then announce when those things happen.

**Comment by davisford** [comment]
@stephen-turner just my $.02 -- this is a horrible idea.  i burned half a day trying to figure out why our CI builds were failing.

https://github.com/docker/compose-cli/issues/1867

**Comment by elijahchancey** [comment]
I spent 2 hours trying to figure out why all of my images refused to build after upgrading Docker for Mac. I've got an M1 chip. When compose v2 is enabled, all of my images fail to build with errors like this:

```
=> => transferring context: 76B                                                                                                                                                                      0.0s
 => CANCELED [irl_dev_python internal] load metadata for docker.io/library/python:3.9.4-slim-buster                                                                                                   0.1s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount168530399/Dockerfile: no such file or directory
```

The current implementation of docker compose v2 isn't ready to be a default setting for everyone.

**Comment by stephen-turner** [comment]
@elijahchancey We've been trialling it for over six months. The current step is to turn it on gradually for some users and see what remaining issues there are. If you find an issue, please file a ticket at https://github.com/docker/compose-cli/

**Comment by davisford** [comment]
> @elijahchancey We've been trialling it for over six months. The current step is to turn it on gradually for some users and see what remaining issues there are. If you find an issue, please file a ticket at https://github.com/docker/compose-cli/

I did.  https://github.com/docker/compose-cli/issues/1867

I appreciate the OSS community but I strongly feel this kind of move should be accompanied with a massive user notice (either dialog or CLI warning) to let the user know that they were opted into an experimental feature.  Countless organizations use the docker toolset to build and run their software through CI/CD systems, and having this stuff just randomly break without any kind of warning I feel is the wrong move.

**Comment by stephen-turner** [comment]
We have both a popup and a CLI warning when it's turned on.

**Comment by booleanbetrayal** [comment]
This experimental feature broke a lot of our Docker binstubs for some reason (compose file path location?) in such a way that it caused mass confusion across our team and cost us several hours of debugging. Please do not auto-enable experimental features that do not have full feature parity.

**Comment by booleanbetrayal** [comment]
> popup

There may be a bug in this logic. Our team never saw any notification of Docker Compose V2 being enabled.

**Comment by booleanbetrayal** [comment]
> We have both a popup and a CLI warning when it's turned on.

There may be a bug in this logic. Our team never saw any notification of Docker Compose V2 being enabled.

**Comment by rfay** [comment]
This canarying strategy continues to create havoc for many, many users of tools that wrap docker-compose. [ddev](https://github.com/drud/ddev)'s latest version now detects docker-compose v2 and notifies people and insists on docker-compose v1. I've opened several issues in docker/compose-cli, they've been promptly addressed, but there are too many problems outstanding, and I can't get though a test run with ddev. 

The unintended impact of what you've done is to delay acceptance of docker-compose v2. And I'm sure it was unintended how many people would be annoyed with the  breakage that happened by turning on an experimental setting without their buy-in.

As @booleanbetrayal says, there have been no reports from any of the affected users of a popup or a CLI warning.

**Comment by damienmckenna** [comment]
From an end-user's perspective the problem happened when I updated to 3.5.2. IMHO "canary" users should have been given a popup that the change was going to take place, indicate that enabling it could break things and provide an option in the dialog to _not_ enable it.

**Comment by deviantintegral** [comment]
On macOS, it looks like the warning is in the form of a system notification:

<img width="359" alt="Screen Shot 2021-07-30 at 10 39 34 AM" src="https://user-images.githubusercontent.com/255023/127671226-3ca1b460-8ac9-408b-abd0-d61bb833bf5c.png">

Unfortunately, it's easy for this to get lost the backlog of notifications. It would be better if there was also a text notification when using `docker-compose`, such as "Docker compose v2 beta will become the default on <some date>, <links to instructions on opting in early>".

I'd like to compare this to the experience of using Docker on Linux directly. I've never once had Docker upgrades break things like this, and feel very confident that only upgrades between major versions would introduce intentional breaking changes. It would be a significant issue if all of a sudden `docker-compose` swapped to `docker compose` in a minor release. Continued breakages like this will drive more of our team to using full VMs for Docker, or running Linux as the host OS, or not using Docker at all, reducing the testing opportunities you're looking for in the first place.

**Comment by stephen-turner** [comment]
There are no "intentional breaking changes" between v1 and v2, only bugs that we haven't caught even after six months of testing with 10% of the users. Please report any bugs at https://github.com/docker/compose-cli.

**Comment by colececil** [comment]
I also wasted a bunch of time on this, because I had no idea I was using the Compose V2 beta. I thought I was still using V1. I don't remember seeing any notification that I was being opted in to the beta - if I had, I don't think this would have been an issue for me. But the problem is, I was running into issues with no idea what had changed, until I stumbled onto this in my Docker Desktop settings. I even read through the release notes when upgrading Docker Desktop, and they also don't make it clear that I was going to automatically be using V2.

My team has a custom dev tool we built in Electron, using the [PDMLab/docker-compose](https://github.com/PDMLab/docker-compose) library to run Docker Compose. Here are a few issues I saw when using V2 (while not realizing I was using V2):

- The Docker Compose logs being output in our Electron app no longer had color.
- When using the `buildMany` function of [PDMLab/docker-compose](https://github.com/PDMLab/docker-compose), Docker Compose not only built the services I pass in, but also the services they depend on (with Compose V1, only the services I pass in are built).
- I was getting some really long Go error message sometimes when running containers. I couldn't figure out what the message meant (and I don't remember exactly what it said), but things seemed to still be working even after getting the error message.

**Comment by booleanbetrayal** [comment]
We just had another coworker experience this despite not having any notifications.

**Comment by stephen-turner** [comment]
FYI in this week's release (Desktop 3.6.0) we will include the compose v2 release candidate, at which point all remaining people will be switched to v2 (but can still switch back for the moment). In the following release (or maybe the one after) we will label it the official 2.0. So this is the last chance to report any bugs.

**Comment by rfay** [comment]
DDEV always tries to support and adapt to every new version of Docker, but this one just isn't possible yet. We haven't yet been able to pass our test suite with compose v2, and of course although issue responsiveness has been great, the latest docker-compose has not been bundled into a desktop version to test with. Please don't default-enable v2 in Desktop 3.6.0. I'm all for v2 being successful, and have worked hard to describe and report the many differences of behavior, but haven't been able to test the results of those fixes.  https://github.com/drud/ddev/pull/3083 is the latest of several ddev PRs to adapt to v2, but it's not usable  (or pursue-able) without the new v2 about to be released with desktop.  Per conversations with @mat007 I will also be adding the ability to test with v2 in next alpha, https://github.com/drud/ddev/issues/3152. 

I understand from @mat007 that your announcement here basically means you're going to turn on 100% canary on this, which means that current ddev will refuse to run with it (but tell people what to do). But those who aren't on latest ddev will just have the various remaining problems in compose v2.

Please don't start the 100% canary yet. Save it for a few weeks until compose v2 and ddev can make progress on passing tests and resolving things that need to be done differently.

**Comment by stephen-turner** [comment]
@damienmckenna Docker Desktop doesn't follow semver. Think of Docker Desktop as basically three things (1) lots of upstream Linux components (engine, docker CLI, compose, Kubernetes etc.) that we bundle; (2) VM management and pass-through magic to make containers run on Windows and Mac and appear to be running natively; (3) a GUI on top. Only category (1) include a public supported interface that could cause backwards compatibility problems, and these components have their own versioning schemes. I suppose in principle we could follow semver by changing our major version number whenever any of the upstream components had an API change, but we don't: we'd be bumping the major version pretty frequently if we did that.

**Comment by rfay** [comment]
@stephen-turner I note that one key thing that needs to be done to increase adoption of compose v2 is to make it available for Linux. I would imagine that there are many applications (like ddev) that are used in a cross-platform way and need to have the same tools everywhere. AFAICT there is no officially sanctioned way to install docker-compose (as opposed to `docker compose`) on Linux. So it won't currently get the use it needs. 

I asked about this in https://github.com/docker/compose-cli/issues/2012 but I guess since it hasn't had a response from the team... there must not yet be a way.

**Comment by deviantintegral** [comment]
From https://github.com/docker/compose-cli/issues/2012:

> Yes, that's a separate tool and can co-exist (for now).

Can both versions of compose exist at the same time in Docker for Mac as well? That would both allow for broader V2 testing, while giving tools and projects time to upgrade (even if they have to use a different path or something to get to the compose 1 binary).

**Comment by stephen-turner** [comment]
> 
> Can both versions of compose exist at the same time in Docker for Mac as well? That would both allow for broader V2 testing, while giving tools and projects time to upgrade (even if they have to use a different path or something to get to the compose 1 binary).

Yes, and that has been the situation since December (eight months ago), which is how we got 10% adoption even before starting to switch people over to it.

**Comment by deviantintegral** [comment]
Today a team member discovered that PHPStorm doesn't support docker-compose v2 fully yet. In particular, it can't parse the path mappings from volume sections. The upstream issue is at https://youtrack.jetbrains.com/issue/WI-61205 and I imagine this applies to all of the JetBrains IDEs.

**Comment by rfay** [comment]
Just a note that ddev v1.18.0-rc3+ (near release of v1.18.0) is now fully compatible with current docker-compose v1 and v2, including PhpStorm weirdnesses.

**Comment by rfay** [comment]
I was wrong about PhpStorm weirdness and ddev, sorry. ddev itself is working with both versions of docker-compose, but PhpStorm is not there yet, as @deviantintegral pointed out, https://youtrack.jetbrains.com/issue/WI-61205

**Comment by rfay** [comment]
Closing this, but I appreciate you being gentle next time there's an "experimental" feature. Please figure out how to get more miles on it before you start canarying people in. Perhaps you could have a "canary me" checkbox :)
