### ISSUE TITLE
 qemu-system-aarch64 Occupy 2.56 GB arm

### ISSUE THREAD

**Issue by shutter-cp** [docker/for-mac#5828]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/37921589/124689352-f3547e80-df0a-11eb-9934-0e9bbfc77dfd.png">

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
