### ISSUE TITLE
Fatal Error - Failed to ping backend API

### ISSUE THREAD

**Issue by Sunhat** [docker/for-mac#5839]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behaviour
It doesn't crash

### Actual behaviour
It crashes

### Information
When running Docker for Mac and the battery dies.
Upon booting again, Docker produces a window that cannot be closed (beach ball): Fatal Error, Failed to ping backend API.
Cannot exit
Must go to terminal to force kill the process

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: ??? Currently broken, can't open - Latest afaik

### Steps to reproduce the behaviour
1. Run docker containers
2. Let battery die
3. Charge & turn device back on
4. Watch Docker get permanently stuck

**Comment by StefanScherer** [comment]
Could you please retrieve and upload the diagnostics from the command line and then copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
Maybe only the settings.json is corrupt, but the logs could tell us more.

**Comment by zolthan** [comment]
I have the same problem with MacOS 11.4 on Intel. I'm using Docker desktop 3.5.2.

The problem is, that this error is thrown on machine startup. The window presenting the error doesn't respond to anything, so it can neither be closed by "Exit" nor can a diagnostic be retrieved, because once you click on any button, docker hangs up and could only be restarted by killing the docker processes.

After having killed anything, docker starts up normally.

**Comment by nstCactus** [comment]
I have the same issue. 
@StefanScherer I ran a diagnostic, here is the ID: 32E07848-3EDE-48B2-BF63-A61D5D69BA2D/20210719063324.

**Comment by RwwL** [comment]
I'm having the same problem as @zolthan, except I'm still on 3.4. because the 3.5.2 upgrade seems to have not run or completed after I confirmed that I wanted to upgrade. Looks like after a restart I also can force-quit and then get it to launch, at least.

Maybe worth mentioning: a week ago I followed [these instructions](https://github.com/docker/for-mac/issues/5754#issuecomment-862177142), tweaking my settings because my containers had disappeared following the 3.4 upgrade, and that had worked fine as far as I could tell.

Diagnostics ID: B464FE06-0ED5-4C29-A0D6-E5DA441CEA94/20210719133415

**Comment by mdgww** [comment]
@StefanScherer - same issue, diagnostic id is 9DEAD23A-1B83-41DF-A215-BF166A678AF0/20210729155425

**Comment by zolthan** [comment]
In the meantime it appears every morning and my morning routine is the cli command `pkill -f 'Docker.app'`.

Any news on this Bug?

**Comment by zolthan** [comment]
Problem seems to be solved with Docker Desktop 3.6.0. I've been starting it twice now and no backend API ping failure.

Can anyone confirm it?

**Comment by hezll** [comment]
Same issue come back with current 4.3.1  4.3.2.
I think external drive may cause this issue although now I have removed it. 
Before I upgrade to 4.3.2, there is no issue.
Btw, I use m1max cpu.

**Comment by hezll** [comment]
cd ~/Library/Group\ Containers/group.com.docker
rm -rf settings.json

Solved!
