### ISSUE TITLE
916DF661-486D-460E-92E0-BAD7893E318E/20210715064237

### ISSUE THREAD

**Issue by ezequiel-parra-ekon-es** [docker/for-mac#5845]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ezequiel-parra-ekon-es** [comment]
ID 916DF661-486D-460E-92E0-BAD7893E318E/20210715064237
MacOS 11.4
Today I started the Mac as always and I get the error

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
