### ISSUE TITLE
Docker SSH connection issue  - MAC M1

### ISSUE THREAD

**Issue by nvshivakumar** [docker/for-mac#5893]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker SSH connection should not be refused

### Actual behavior
I am using latest docker environment in my MAC system. (M!)
I use to connect SSH using php strom (docker with my enviroment)
After some time, docker gets hanged and won't give any responses.
docker -ps won't show any active docker images.
I found below error in "docker dashboard"
Error response from daemon: dial unix docker.raw.sock: connect: connection refused
I am using 6 cpus , 8GB Memory 2GB Swap and My disk image size was 59.6 out of this 26.4 got used)
This issue I am facing since long time.
### Information

  - macOS Version:  11.4 
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version:  3.5.2 

### Steps to reproduce the behavior

Configure docker using 
I am using 6 cpus , 8GB Memory 2GB Swap and My disk image size was 59.6 out of this 26.4 got used)
Note: I am using  docker as follows

Magento 2.4.4 code (docker image)
Mysql 8.0 docker image
Latest elastic search image
Varnish image (Not using right now due to incompatible)

  1. ...
  2. ...

**Comment by jamshid** [comment]
Just curious what do you mean by SSH connection? Do you mean you're setting `DOCKER_HOST=ssh://mymac.local` so that you can use your Docker for Mac remotely? 

I think increasing MaxSessions this on the remote mac helped me in that scenario. The default macOS sshd config limits concurrent connections. Remember you need to redo this each time macOS is updated.
```
echo 'MaxSessions 1000' | sudo tee -a /etc/ssh/sshd_config && sudo launchctl stop com.openssh.sshd
```

I still have problems sometimes where I have to restart Docker for Mac or shut down some containers for builds to work.
I've also tried this but not sure it helps.
```
sudo launchctl limit maxfiles 1024 unlimited
```
