### ISSUE TITLE
com.docker.hyperkit 100% cpu usage is back again

### ISSUE THREAD

**Issue by ddzobov** [docker/for-mac#5894]
#5287 

<img width="960" alt="Снимок экрана 2021-08-03 в 11 44 37" src="https://user-images.githubusercontent.com/9539529/127986089-eda493b3-fe50-4210-8cf0-ddb939fb8f3b.png">
<img width="763" alt="Снимок экрана 2021-08-03 в 11 44 57" src="https://user-images.githubusercontent.com/9539529/127986145-dfcff6c2-3801-4cc9-a8f0-d11b150ac37e.png">

**Comment by StefanScherer** [comment]
Thanks for the heads up. But only this screenshot does not help us understand your current environment. We make improvements from time to time on this topic, but it seems in your particular situation it still uses the CPU a lot.
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
