### ISSUE TITLE
Disable auto update feature

### ISSUE THREAD

**Issue by bentcoder** [docker/for-mac#5907]
Hi,

Is there a way to disable auto update option? All it takes a checkbox in the _Preferences_ to either enable it or disable it. Leave it to people to decide please.

Thanks

1. It should be up to the user to check for updates rather than being dictated with those counterproductive popups.
2. After installing the suggested updates, the exclamation mark is still there to tell you to "Update and Restart" again which is not user friendly and time consuming. You have to keep restarting the device. Not productive at all when you are busy and down't want to keep restarting the device.
3. Just because of some other apps like Chrome, GitHub, Postman etc. follows this path, Docker Desktop doesn't have to feel like it is the best practise or what ever. I would say some other apps don't follow this path so why won't you use them an example.

**Comment by dermoumi** [comment]
From: https://github.com/docker/roadmap/issues/183#issuecomment-818910160

> Pro and Team customers can select "Skip this Update" to ignore all future notifications about a specific update.
Team customers can turn off all checking for updates ever.

**Comment by stephen-turner** [comment]
That comment is out of date. Everyone now has the option to skip any release.

**Comment by bentcoder** [comment]
@stephen-turner 

> That comment is out of date.

It doesn't matter because that comment doesn't solve/answer my issue anyway.

> Everyone now has the option to skip any release.

You either didn't understand the issue or just dismissing it as you have done [here](https://github.com/docker/for-mac/issues/5119).

**Comment by stephen-turner** [comment]
TBH I'm not completely sure if I understand the issue. You said you wanted to turn off "auto update" but that's not a feature we have. We had it briefly, but quickly reverted it because it was unpopular. My comment you just quoted was from that brief period and is not applicable to the current version.

In summary:
If you're asking not to be auto-updated: we removed that already. If you're still seeing it, you need to update to the latest version and you won't see it again.
If you're asking never to be notified about available updates: sorry, we're not going to change that; we believe it's important to notify users when they are out of date. You have the choice whether to apply the update, be reminded again tomorrow, or not be reminded again until there's a newer version.
