### ISSUE TITLE
vmstatevent invalid json: on macOS Sierra

### ISSUE THREAD

**Issue by bureque** [docker/for-mac#591]
### Information

Diagnostic ID: 9777E0DB-4F3A-45A0-952B-F99448543924
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Run docker for mac on system start up I  get the window with message `vmstatevent invalid json:`. The only option then is to press `Exit` and close docker

Next time I run it, it works, but after some time it happens again -

**Comment by dsheets** [comment]
This is issue #64 that was fixed in the beta channel several weeks ago.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
