### ISSUE TITLE
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.

### ISSUE THREAD

**Issue by ctow123** [docker/for-mac#5932]
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.

the problem persists 
docker desktop UI is still using hardware acceleration and blurry lines make it unusable 
_Originally posted by @ulyssessouza in https://github.com/docker/for-mac/issues/5121#issuecomment-896990428_

**Comment by AgingOrange** [comment]
Is v3 still available for download somewhere? V4 crashes regularly and the report windows keeps giving me the spinning beach ball, so I can't report.

**Comment by StefanScherer** [comment]
@AgingOrange older releases have download links in our release notes. We recommend to use the latest version and give feedback rather than sticking to an older version.
You can create diagnostics from the command line, see following the steps at https://docs.docker.com/docker-for-mac/troubleshoot for details.
