### ISSUE TITLE
mem_limit and memswap_limit not having any effect

### ISSUE THREAD

**Issue by LouAdrien** [docker/for-mac#5958]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: C4680285-E25D-479D-A2EA-349717C6D8FC/20210909151904

### Expected behavior
The following options in docker-compose [docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources) specify the two following options, which should properly set container mem and swap limits

mem_limit: 4g
memswap_limit: 8g

### Actual behavior
Using docker stats from outside shows the limit were not respected
<img width="992" alt="Screenshot 2021-09-09 at 16 54 50" src="https://user-images.githubusercontent.com/4233878/132714605-415fec44-7705-4e7b-8fec-cd1a48de6fdd.png">
Using "free" from inside the container shows the following
<img width="631" alt="Screenshot 2021-09-09 at 16 54 19" src="https://user-images.githubusercontent.com/4233878/132714652-04cf3bbc-78b2-4a98-ab7c-97a4bb90aac7.png">

Using both tool, the memory and swap limit seem to NOT be affected by the setting

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?  -> Yes
  - Is the problem new? -> Don't think so
  - A reproducible case if this is a bug, Dockerfiles FTW. --> Attaching a sample docker-compose ( .txt to be supported by github)
[sample-docker-compose.txt](https://github.com/docker/for-mac/files/7137806/sample-docker-compose.txt)

  - macOS Version: 10.15.2
  - Intel chip or Apple chip:  intel
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

  1. use joined dockerfile
  2. docker-compose up

**Comment by thaJeztah** [comment]
Does it work if you set lower limits? If I see it correctly, it looks like your Desktop install is configured to have 2G of memory (lower than the limit you applied)

**Comment by LouAdrien** [comment]
yes you were right, my docker desktop had overall resources limits, thanks!

-> What I was looking for was a way to set resources allocation for the services (i.e a minimum of resources for a specific conainer), not just setting a max limit. Would you have a recommendation of how to do this (without switching to docker swarm if possible)?

**Comment by thaJeztah** [comment]
No, afaik, there's no option to _reserve_ memory / cpu. Even when using swarm services, I don't think the _limits_ are taken into account.

Swarm services _do_ have the `deploy.resources.reservations` options for cpu and memory. Those options are for the swarm scheduler; resources are not reserved "physically", but only an indication for the swarm scheduler. For example, swarm will only schedule at maximum 2 instances of a service that reserve 1GB of memory on a 2GB node. Limits only configure cgroups for the container so that the kernel limits the maximum amount of memory/cpu that they're allowed to consume.

I'm not sure if `docker compose` / `docker-compose` currently takes `deploy.resources.reservations` into account (as it does not have a global overview of all services / stacks deployed on a node).
