### ISSUE TITLE
Container group name swallows numbers in folder (docker-compose)

### ISSUE THREAD

**Issue by norbertspiess** [docker/for-mac#5974]
- [x] I have tried with the latest version of Docker Desktop
- [ ] I have tried disabling enabled experimental features
- [ ] I have uploaded Diagnostics

### Expected behavior
I have a project within a folder called _3ap-platform_, containing a docker-compose.yml. When running `docker-compose up` I expect my containers to be grouped within a container group called _3ap-platform_, same as the folder name. This works flawlessly with Docker Desktop for Mac 3.5.2.
I haven't tested with 3.6.

### Actual behavior
With Docker Desktop 4.0.0 and 4.0.1, the _3_ in the name is swallowed and I end up with _ap-platform_. Hence, new volumes need to be set up. This happens with other folders, named the same way, as well.

![image](https://user-images.githubusercontent.com/29440287/133738786-1025b794-da05-43c8-93b9-3545f57f608b.png)

### Information
  - macOS Version: Big Sur (11.6)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.0.x

### Steps to reproduce the behavior
  1. Install Docker Desktop 4 or 4.0.1
  2. Create docker-compose.yml within a folder, starting with a number. E.g. "3ap-platform".
  2. Run _docker-compose up_ in that folder
  3. Observe naming schema for containers and container group within Docker Dashboard.

**Comment by ndeloof** [comment]
compose V1 allows first character to be a digit (https://github.com/docker/compose/blob/c81046aac0ce1360f1bab64368f9a318c593d82a/compose/cli/command.py#L197-L198) 
compose V2 doesn't (https://github.com/compose-spec/compose-go/blob/master/cli/options.go#L335) since @ulyssessouza [added this extra constraint](https://github.com/compose-spec/compose-go/pull/169).
