### ISSUE TITLE
docker ps error

### ISSUE THREAD

**Issue by coolbeast** [docker/for-mac#60]
### Information

Diagnostic ID: F4B4206B-C5A1-4531-AD92-9CBE7E3DCDBF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Unfortunately the diagnostic uploads from the stable branch are missing some key pieces of information which are needed to figure out why `docker ps` doesn't work (specifically: process lists and output from `docker ps` running inside the VM rather than only the host). Could you try to reproduce with a beta version and open a fresh issue?
