### ISSUE TITLE
Option to hide menubar icon

### ISSUE THREAD

**Issue by jrcii** [docker/for-mac#6023]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Checkbox appears in configuration settings allowing me to reduce clutter in my menubar by removing the Docker icon which I never need

### Actual behavior
The menubar icon is permanently there cluttering my menubar and distracting me

### Information
  - macOS Version: Mojave
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Latest

### Steps to reproduce the behavior
1. Run Docker Desktop

**Comment by waded** [comment]
@joe0BAB Since issue specifies Mac OS, I think "menu bar" can be taken to mean Mac OS menu bar, https://support.apple.com/guide/mac-help/menu-bar-mchlp1446/. It's pretty common for people to ask for a configuration option to turn any icon in this area off. That's what I came looking for.

![image](https://user-images.githubusercontent.com/1535656/140615172-55a2e638-fdcc-4432-9cdd-8e1f22e61e59.png)

**Comment by waded** [comment]
@joe0BAB I'll look to open an issue in [docker/roadmap](https://github.com/docker/roadmap/).

**Comment by joe0BAB** [comment]
Awesome, thank you for sharing your thoughts! We will look into it and see what we can do! I am closing this ticket here in favour of further discussion on the roadmap ticket.
