### ISSUE TITLE
Upgrade to 4.1.1: images disappear from dashboard, daemon fails to start

### ISSUE THREAD

**Issue by Nuru** [docker/for-mac#6026]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7DDDF979-417F-442C-B930-719FC131249A/20211102175512

### Expected behavior

After upgrade to 4.1.1, Docker images would remain visible on Dashboard, Docker would launch successfully after quitting.

### Actual behavior

- After upgrade, Docker Dashboard showed no images and zero disk space used,
```
Images on disk  0 images  Total size: 0 Bytes
```
although Resources -> Advanced showed 
```
Disk image size: 128 GB (117.4 GB used)
```
and images were still available from the command line:
```
$ docker image ls | wc
     140     979   17876
```
- After upgrade and quit, docker failed to launch:

```
2021-11-02T17:43:25Z dockerd time="2021-11-02T17:43:25.514714598Z" level=error 
msg="Handler for GET /system/df returned error: error getting build cache usage: failed to get usage for a7l0jtp813hepnf15q0qeomoc: lstat /var/lib/docker/overlay2/6wrh0rvbn06s0dax1c2uije11/merged/6wrh0rvbn06s0dax1c2uije11/diff: too many levels of symbolic links"
```

- After failed launch, Docker launched successfully, but with same issue about missing images

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1

**Comment by skieffer** [comment]
Same issue.

Images tab in Dashboard says:

    Images on disk  0 images  Total size: 0 Bytes

while

    $ docker images | wc -l
     196


* macOS 10.14.6

* Docker Desktop 4.4.2

**Comment by skieffer** [comment]
...and now they're back.

I had just upgraded Docker Desktop when the problem first arose. It's now several hours later, and all the images are once again listed under the Images tab in Dashboard.

Could it really just be that it takes _time_ to scan all the images? I have 34.17 GB of them in total.

If that's the case, then I would urge to show at least a spinner, and better yet a progress bar, while the images are being scanned (or whatever is happening). Otherwise the user just thinks it's broken.
