### ISSUE TITLE
Sign in does not work with rosetta

### ISSUE THREAD

**Issue by daweth** [docker/for-mac#6067]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: latest
  - Intel chip or Apple chip: M1 Max
  - Docker Desktop Version: 

### Steps to reproduce the behavior
Just click "sign in" on the app

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/desktop/mac/troubleshoot?
