### ISSUE TITLE
Use buildctl on local with Docker for Desktop

### ISSUE THREAD

**Issue by remidebette** [docker/for-mac#6149]
To be able to run (and debug) Buildkit's `buildctl` command on local, the various guides out there recommend to install the backend as a container:

```bash
docker run --rm --privileged -d --name buildkit moby/buildkit

export BUILDKIT_HOST=docker-container://buildkit

buildctl build --frontend=dockerfile.v0 --progress plain  --output  ...
```

This has the major drawback to create a new cache that is distinct from the one of **Docker for Desktop**, and then requires to rerun the builds, be cautious about the disk usage etc.
And that even though we can actually run buildkit commands with **Docker for Desktop** through `docker buildx`

Is there any way to make **Docker for Desktop** a Buildkit Host?

**Comment by jedevc** [comment]
Hi @remidebette, I don't think that what you're describing is a supported scenario.

Is there a particular reason you're wanting to use buildctl instead of buildx? buildctl is more designed as a development tool and for experimental scenarios, while buildx is more general-purpose and is more user-friendly.

If you *really* want to do this, with docker/buildx#23 closed, you could always spin up your own buildkit container, create a remote builder for buildx, and attach directly with buildctl. But wherever possible, you should try and use buildx if you can. If there's something that you're using buildctl for that buildx can't do, do feel free to open a separate issue on the buildx repo :tada:

**Comment by jedevc** [comment]
Hopefully the remote driver should make it into the next release, when that comes out - Docker Desktop should ship the released buildx, very soon after it's released.

**Comment by developer-guy** [comment]
yeah, thanks @jedevc, you rock 🤘, also, thanks to @dentrax, who helped a lot to me while working on the “env” driver for Buildx 🙏
