### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by xzt684** [docker/for-mac#6169]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 958772B5-1115-4FDE-9D15-ECA3CD78C9EF/20220212234650

### Information

  - macOS Version: monterey 12.2.1
  - Intel chip or Apple chip: mac mini m1
  - Docker Desktop Version: 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
