### ISSUE TITLE
unable to run docker

### ISSUE THREAD

**Issue by Milehi24** [docker/for-mac#6170]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sergey-fedosimov** [comment]
I have the same issue. Updating from 4.4.2 to 4.5.0
macOS Catalina 10.15.7 (19H1713)
Had to roll back to 4.4.2, thankfully, no one container had not been affected.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
