### ISSUE TITLE
qq

### ISSUE THREAD

**Issue by SVusal** [docker/for-mac#6203]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SVusal** [comment]
> * [x]  Я пробовал с последней версией Docker Desktop
> * [x]  Я пробовал отключить включенные экспериментальные функции
> * [x]  Я загрузил Диагностика
> * Идентификатор диагностики:
> 
> ### Ожидаемое поведение
> ### Фактическое поведение
> ### Информация
> * Версия для macOS:
> * Чип Intel или чип Apple:
> * Настольная версия Docker:
> 
> ### Выход `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
> ### Действия по воспроизведению поведения
> 1. ...
> 2. ...

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
