### ISSUE TITLE
Docker port-forwarding doesn't work

### ISSUE THREAD

**Issue by bud32** [docker/for-mac#6205]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - Diagnostics ID:

### Expected behavior

I can access localhost:5000

### Actual behavior

I can't access localhost:5000

I run my concainter with `docker run -p 5000:5000 -dit ...` and the ubuntu-based container starts with the server, but it doesn't work on mac. On linux, I can just do `--network=host` but on mac, the server is inaccessible. `docker port $container_id` doesn't show anything either.

**Comment by laurazard** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
