### ISSUE TITLE
Docker Desktop encounters a fatal error after changing the user directory name

### ISSUE THREAD

**Issue by bar-amir** [docker/for-mac#6223]
I've changed my directory name on my Mac, now Docker Desktop crashes or doesn't open at all. The error message is this:
<img width="710" alt="Screen Shot 2022-03-09 at 12 31 09" src="https://user-images.githubusercontent.com/28039736/157426824-bbcaab36-bc52-4ae8-961f-d2a72a27e46f.png">
It shows the previous directory name, "baram", which is now something else.

- Trying to reset to factory defaults doesn't work - neither from the CLI nor the UI (when it manages to load). Trying to reset from the UI crashes it
- Trying to uninstall Docker doesn't work - neither from the CLI nor the UI. Trying to uninstall from the UI turns the app window to blank
- Deleting Docker from the Applications folder and reinstalling doesn't work - I assume it doesn't perform a clean uninstallation?
- Diagnostics ID: `6F90C0FE-860A-446D-957E-D06FF20D37D1/20220309104150`

**Comment by MCF241** [comment]
Hi,

Got the same issue on Mac M1 OSX Monterey 12.2.1 and Docker Desktop 4.5.0.
Try the same as bar-amir and no success.

The issue was solved by editing :

- /Users/${USER}/Library/Group Containers/group.com.docker/settings.json

At beginning of the file around line 10 you must have :

- "dataFolder": "/Users/**baram**/Library/Containers/com.docker.docker/Data/vms/0/data",

Change **baram** by the correct home directory name :
_(Replace ${USER} by your home directory or choosen **data-root** directory_

- "dataFolder": "/Users/**${USER}**/Library/Containers/com.docker.docker/Data/vms/0/data",

Got it 👍 

**NOTA** :
I have lost a lot of time trying to solve the issue and I came with the following deduction or idea; changing the home directory following Apple procedure is ok but didn't change the "Authority-Certificate" that stay with the old user name.

In my case, my account was created with my full family name (23 caractères) and I rename my home directory with the short name (8 characters).

But the certificate stays with the long name. I cannot be sure of that as I didn't find a way to confirm this.

**Comment by synditrix** [comment]
this worked for me, thanks so much!
