### ISSUE TITLE
Unable to uncheck automatically start at log in

### ISSUE THREAD

**Issue by magic890** [docker/for-mac#626]
### Expected behavior

Deactivate Docker from automatic startup

### Actual behavior

Crash

### Information

Diagnostic ID: DE533E19-F8FF-41DC-9105-0D3A5DBAB049
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Top menu Docker icon
2. Preferences
3. Uncheck `Automatically start Docker when you log in`

**Comment by dsheets** [comment]
This is a known issue with macOS Sierra Beta/GM and Docker for Mac 1.12.0-a. This issue is resolved on the beta channel and the fix will reach the stable channel in the next few days. Please see https://docs.docker.com/docker-for-mac/ to learn about and download the beta and ensure that you have uninstalled the stable release prior to installing the beta.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
