### ISSUE TITLE
Docker is failing to start in Mac (Big Sur v11.4)

### ISSUE THREAD

**Issue by veereshcb** [docker/for-mac#6271]
Hi Team,

Docker is failing to start in Mac (Big Sur version 11.4) after upgrade.

Till 11.3 Docker Desktop working fine and it recently stopped after version upgrade.

I have tried clean uninstall and re-install, installing recent version, installing via Homebrew and  even tried with Rancher Desktop. For all I'm getting  below error  where as server is giving error.

Can some one please help on below issue.

```
Logs:

$ docker version
Client:
 Version:      20.10.9
 API version:    1.41
 Go version:    go1.16.8
 Git commit:    c2ea9vd
 Built:       Thu Nov 18 21:15:43 2021
 OS/Arch:      darwin/amd64
 Context:      default
 Experimental:   true
Error response from daemon: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>openresty</center>
</body>
</html>
$
```

- [*] I have tried with the latest version of Docker Desktop
- [*] I have tried disabling enabled experimental features (No because there is nothing to disable)
- [*] I have uploaded logs

**Comment by StefanScherer** [comment]
Docker 20.10.9 seems quite old. The current Docker Desktop 4.7.0 has 20.10.14. 🤔 
Do you have eg. an environment variable DOCKER_HOST set? I haven't seen that plain HTTP error message in the default setting, because by default Docker Desktop uses a Unix socket and not HTTP. So please check that no DOCKER_HOST variable is set.
