### ISSUE TITLE
Docker Desktop doesn't display correctly the icon while running on MacOS dock

### ISSUE THREAD

**Issue by rafae2k** [docker/for-mac#6282]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BC3F711F-FCAE-4451-AEEF-71570DCFF274/20220415134611

### Expected behavior

Docker for Desktop should display the correct icon in it's correct size.

### Actual behavior

Docker for Desktop seems to have a bug on my mac M1 that makes sometimes it's icon not appear (but keeps appearing that white dot on dock) what informs that it's running.

<img width="1440" alt="Screen Shot 2022-04-15 at 10 55 59" src="https://user-images.githubusercontent.com/53544360/163579619-6ea3a514-7ace-4773-8b43-f47143159b09.png">

### Information

  - macOS Version: Monterey 12.3
  - Intel chip or Apple chip: Apple Chip M1
  - Docker Desktop Version:  4.7.0 (77141)

**Comment by trungutt** [comment]
Hi thanks for your report. Could you please try out these builds to see if the problem still persists? (though it seems that this problem happens randomly)

Mac M1: https://desktop-stage.docker.com/mac/main/arm64/77786/Docker.dmg
Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/77786/Docker.dmg

I gave a build for Mac Intel because it could possibly happen on Mac Intel

**Comment by rafae2k** [comment]
> Hi thanks for your report. Could you please try out these builds to see if the problem still persists? (though it seems that this problem happens randomly)
> 
> Mac M1: https://desktop-stage.docker.com/mac/main/arm64/77786/Docker.dmg Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/77786/Docker.dmg
> 
> I gave a build for Mac Intel because it could possibly happen on Mac Intel

1 week testing and so far so good! Closing this issue! 😁👌
