### ISSUE TITLE
Install Docker Desktop silently on Mac

### ISSUE THREAD

**Issue by arthurgallaghersr** [docker/for-mac#6302]
We are attempting to deploy/install Docker Desktop on MacBook Pro (MacOS). 

We are getting two different pop-up messages...

The first pop-up that appears is "Docker is an app downloaded from the Internet. Are you sure you want to open it?"

The second pop-up that appears is "Docker Desktop needs privileged access."

We need assistance with the terminal commands/switches/scripting that will suppress these pop-up messages so that we can silently deploy this application.

**Comment by thaJeztah** [comment]
Do the instruction in [Install from the command line](https://docs.docker.com/desktop/mac/install/#install-from-the-command-line) help?

**Comment by firien** [comment]
It would be nice to be able to install without admin password. Is this solely to access ports <1024?
If so, it would be nice to allow install without admin password - and prompt to install this helper only if a user attempts to map a <1024 port.

**Comment by thaJeztah** [comment]
@firien I think that's being worked on; see https://github.com/docker/roadmap/issues/383

**Comment by JtMotoX** [comment]
I am also running into this issue each time there is an update.  I perform `brew upgrade; brew upgrade --cask --greedy;` which updates docker to the latest version but when I run `open /Applications/Docker.app` after the update is finished, it will not launch because of these 2 pop-ups.  I have to then RDP into the machines and manually go through these pop-ups.  This gets very annoying every time we have to perform updates on these machines.

It would be better if the brew update process asked for the admin password during installation (similar to how the Powershell update via brew works).
