### ISSUE TITLE
Activation of Docker account unsuccessful while installation was able to complete

### ISSUE THREAD

**Issue by weina2018** [docker/for-mac#6303]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
