### ISSUE TITLE
Apple Silicon Docker Desktop updates to Intel version

### ISSUE THREAD

**Issue by m-ivanov** [docker/for-mac#6316]
### Expected behavior
  installing an update  from Docker Desktop on a Apple Silicon  Mac updates to new Apple Silicon version
### Actual behavior
 update install an intel version that does not work , so i need to download the .dmg again from the website
 
 This in not the first time it happens.
 I don't have the the version of the old install but it was a stable version

**Comment by mat007** [comment]
Hi, and thanks for reporting.
A few users are experiencing the same issue, see https://github.com/docker/for-mac/issues/6268#issuecomment-1122550522 and my reply https://github.com/docker/for-mac/issues/6268#issuecomment-1123662986

Could you try to open the UI and go to the Docker Desktop system menu, then select About
![image](https://user-images.githubusercontent.com/2386884/168809111-27cdf319-b122-44db-b2a1-9c8184cd8945.png)

It’s using the same code as the update to find out the architecture (amd64 or arm64), and opens the About window for that architecture.
So if it opens the popup successfully for you, it means the bug is not in that bit of code. If it fails, then we know where to look!

Thanks!

**Comment by m-ivanov** [comment]
I don't know how useful it can be since this is the screenshot of the last version i downloaded manually. During the weekend maybe i will try to find in my backups the prev. docker version tat was installed and caused this extremely annoying issue

![Schermata 2022-05-17 alle 14 24 10](https://user-images.githubusercontent.com/8850170/168810609-418779cd-0ea7-476e-8312-c092c2036349.png)

I reported the issue because this is not the first time it happens

**Comment by m-ivanov** [comment]
this is the Diagnostic ID: 80494043-EEC4-4367-8962-78BBE3016507/20220517124150

**Comment by mat007** [comment]
From the logs it seems the architecture is correct…
What made you think the update was for Intel instead of Arm, by the way?

**Comment by m-ivanov** [comment]
I thought it was Intel because after the update the icon was like one in https://github.com/docker/for-mac/issues/6268#issuecomment-1122550522 and do nothing when clicked that as far i know indicate that the app has bad arch, maybe is something else.

I hope i can find the exact old version i had before to reproduce it

**Comment by m-ivanov** [comment]
i will close the the issue since , if you checked the logs , the title is misleading. Hope 4.8.x il resolving the issue i had in past. Thanks for quick feedback
