### ISSUE TITLE
Gluster support

### ISSUE THREAD

**Issue by daniego** [docker/for-mac#6321]
Hi,
is there any way to get the gluster client installed inside the hypervisor?

**Comment by nicks** [comment]
I'm not familiar with Gluster in particular. But I think we usually encourage people to implement storage systems as volume plugins to the docker engine, rather than modifying the OS. See: https://docs.docker.com/engine/extend/plugins_volume/

Looks like someone has already written a Gluster plugin: https://github.com/mikebarkmin/docker-volume-glusterfs

does that solve your problem?
