### ISSUE TITLE
Dektop can't auto update

### ISSUE THREAD

**Issue by carlmnssn** [docker/for-mac#6373]
Docker dektop is stuck on downloading update, only way to update is download new version and install manually. This is on 4.9.0, but have experienced on earlier versions as well.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/21332259/175236234-95ee90d4-b0c1-465d-8574-0a41980d1231.png">

**Comment by sophos-rickc** [comment]
I've been experiencing this issues since ~4.7. The background download of an update _*never*_ completes. The _*only*_ way to install an update is to manually download and install. Even then, I have to install multiple times. The first install (or two) always seems to cause Docker Desktop to fail to start. Occasionally, I have to completely uninstall Docker and reinstall.

**Comment by xl09253571xl** [comment]
I manually downloaded 4.10.1 from the official website. After installation, I opened the prompt that the application was damaged, so I can only restore to the old version
