### ISSUE TITLE
docker-id

### ISSUE THREAD

**Issue by sarayut999** [docker/for-mac#638]
### Information

Diagnostic ID: 915EE495-B30A-4F01-9E75-450C3F6DC377
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Unfortunately macOS 10.12 triggers some bugs in the current stable version of Docker for Mac. These bugs have all beed fixed in the beta version and are undergoing final testing before being released on the Docker for Mac stable channel. If you would like to test the beta version, it's available from

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

I'll let you know when the stable update is ready -- it won't be long now.
