### ISSUE TITLE
Error Out When CTRL+C docker-compose 

### ISSUE THREAD

**Issue by soleo** [docker/for-mac#640]
### Expected behavior
Just exit the app
### Actual behavior
Error Appear

### Information

Diagnostic ID: CAFE134C-0504-4A44-AB23-58DEDF9B1499
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/xinjiang/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/CAFE134C-0504-4A44-AB23-58DEDF9B1499/20160915-155025/qemu-img-check.stdout 2> /tmp/CAFE134C-0504-4A44-AB23-58DEDF9B1499/20160915-155025/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Unfortunately macOS 10.12 triggers some bugs in the current stable version of Docker for Mac. These bugs have all beed fixed in the beta version and are undergoing final testing before being released on the Docker for Mac stable channel. If you would like to test the beta version, it's available from

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

I'll let you know when the stable update is ready -- it won't be long now.
