### ISSUE TITLE
Docker crashing at startup

### ISSUE THREAD

**Issue by thunderbird** [docker/for-mac#641]
### Information

Diagnostic ID: 34424673-1036-4464-84D3-A3AC343A39C4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/ian/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Unfortunately macOS 10.12 triggers some bugs in the current stable version of Docker for Mac. These bugs have all beed fixed in the beta version and are undergoing final testing before being released on the Docker for Mac stable channel. If you would like to test the beta version, it's available from

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

I'll let you know when the stable update is ready -- it won't be long now.

**Comment by thunderbird** [comment]
I've got the beta working. Took a lot of cleaning to get it to that point. The uninstaller on both beta and stable versions is horrendous. I'll look forward to the stable version.

**Comment by dave-tucker** [comment]
Stable has now been released:
- Release notes: https://download.docker.com/mac/stable/1.12.1.12133/NOTES
- Download: https://download.docker.com/mac/stable/Docker.dmg
