### ISSUE TITLE
reproducible error on m1 mac

### ISSUE THREAD

**Issue by Wealing** [docker/for-mac#6414]
This is my docker file which fails when building on an m1 mac. On different platforms it works fine 

```
FROM python:3.10 AS base
RUN pip install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc
RUN PIPENV_VENV_IN_PROJECT=1 
RUN pipenv install cobra
```
The last command produces the error. FYI, This happens for python images 3.9 and 3.8 as well.

Any help would be appreciated, thank you.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
