### ISSUE TITLE
[Nginx] curl Failed to connect to host

### ISSUE THREAD

**Issue by rogeriofonseca** [docker/for-mac#645]
### Expected behavior
```
 curl -IL http://172.17.0.2:8080
HTTP/1.1 200 OK
```
### Actual behavior
```
curl -IL http://172.17.0.2:8080
_curl: (7) Failed to connect to 172.17.0.2 port 8080: Operation timed out_

```
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior

  1. Create file "Dockerfile"
```
FROM ubuntu
MAINTAINER Rogerio Fonseca <rogerio.fonseca@gmail.com>
RUN apt-get update
RUN apt-get install -y nginx
ADD exemplo /etc/nginx/sites-enabled/default
EXPOSE 8080
```
  2. Create file "exemplo"

```
server {
	listen 8080 default_server;
	server_name localhost;

	root /usr/share/nginx/html;
	index index.html index.htm;
}
```

3. Run command: **$ sudo docker build -t nginx .**

4. Run command: **$ sudo docker run -d nginx /usr/sbin/nginx -g "daemon off;"**

5. Run command: docker inspect 16b970e7fc71 | grep IPAddress
Return: "IPAddress": "172.17.0.2",

6. curl -IL http://172.17.0.2:8080

**The same steps were run on Linux and  works.**

**Comment by djs55** [comment]
On Linux this works because you have access to the docker internals -- the NAT, backend container networks etc. However on the Mac (and Windows and possibly other environments) the containers are run in an isolated VM so you have to explicitly tell docker which ports to expose using a command like:
```
$ docker run -p 8080:8080 -d nginx /usr/sbin/nginx -g "daemon off;"
60ae437bcb0e5e3a738aec48cfa3ea3a8d377067020fb4255b683ef55bf9f019
```
and then
```
$ curl localhost:8080
<!DOCTYPE html>
<html>
...
```

BTW on the Mac you don't need to run `sudo docker` -- running `docker` by itself is fine. The VM containing the Linux `docker` engine runs as a regular non-root user.

I hope this helps!
