### ISSUE TITLE
"com.docker.dev-envs" flagged as malicious by Virus Total

### ISSUE THREAD

**Issue by chennequin** [docker/for-mac#6490]
One component of docker desktop for mac is flagged as malicious by Virus Total

https://www.virustotal.com/gui/file/7627350c9798c64c4284bc2664d24c938f99b957be0e4efff90b706a3db06f2f/detection

**Comment by nicks** [comment]
Thanks for reporting. This is one of the sad facts of life when shipping client software -- occasionally, one of the anti-virus programs flags your software as malicious. :disappointed: 

Your best bet is to complain to the supplier of the anti virus you're using. Going to close this and mark it as unfortunate, because there's not really much we can do on our end.
