### ISSUE TITLE
docker build --build-arg http_proxy not work!!!

### ISSUE THREAD

**Issue by kobeng** [docker/for-mac#6513]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/3805839/194886173-da729746-a903-44a7-9bcf-445ade1a90ae.png">
docker build -f Dockerfile-release --build-arg http_proxy=http://127.0.0.1:7890 --build-arg https_proxy=http://127.0.0.1:7890 .

error 
#7 0.161 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: could not connect to server (check repositories file)

macOS Version: 12.6
Apple M1 Max
Docker Desktop Version: 4.12

**Comment by nicks** [comment]
thanks for reporting! I think this is expected behavior.

Here's our docs on how to set an HTTP proxy from settings or from env variables.
https://docs.docker.com/network/proxy/

The `--build-arg` you're using is something else. It passes arguments to the Dockerfile.
https://docs.docker.com/engine/reference/builder/#arg
There ARE dockerfiles that will turn --build-arg into an HTTP_PROXY env, but I'm not sure I would trust it to work on arbitrary dockerfiles.
