### ISSUE TITLE
Cannot connect to the Docker Damon via /var/run/docker. sock

### ISSUE THREAD

**Issue by lucidlips** [docker/for-mac#6536]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior
Docker works for my use case like the last version did.

### Actual behavior
This version does not work.

### The Issue
After a clean install of Docker at version v4.13.0, executing `skaffold dev` results in a fatal error at the cache check stage:
`Error checking cache.
getting imageID for ghcr.io/digittl/console: latest: Cannot connect to the Docker daemon at unix:///var/run/docker. sock. Is the docker daemon running?`

### Cause
Skaffold v1.39.2 relies on a unix socket located at `/var/run/docker.sock` in order to connect with the Docker daemon. Previous versions of Docker Desktop for mac would create a sym link in that location (tested with v4.12.0) that would point to the actual location of the docker.sock. I found a fresh install of Docker v.4.13.0 did not automatically create this sym link so Skaffold is never able to find the daemon. A user upgrading to v4.13.0 from a previous version will retain the `/var/run/docker.sock` symlink and not be affected, clean installs will be affected.

  - macOS Version: 13.0
  - Intel chip or Apple chip: apple chip
  - Docker Desktop Version: 4.13.0

**Comment by nicks** [comment]
Thanks for the report! We're trying to make Docker Desktop more userspace-friendly (e.g., fewer root privileges). As part of that, we're migrating the sockets to user-owned directories rather than root-owned directories (like /var/run). Desktop 4.13 no longer installs a socket under /var/run.

For now you can work around this by creating the symlink manually:

```
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

We're talking internally about a better way to roll this out. For now, I'm going to duplicate this against https://github.com/docker/for-mac/issues/6529 to centralize the discussion.
