### ISSUE TITLE
/run/host-services/ssh-auth.sock doesn't work

### ISSUE THREAD

**Issue by rdeusser** [docker/for-mac#6541]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I have no idea because however Docker handles `/run/host-services/ssh-auth.sock` doesn't seem to be documented anywhere. The most I've been able to find is [this](https://docs.docker.com/desktop/networking/#ssh-agent-forwarding) which doesn't explain anything.

### Actual behavior
I get this error message:
```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/host-services/ssh-auth.sock.
```

### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: Apple (M1)
  - Docker Desktop Version: v4.13.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

1. Run this minimal script which reproduces the error I get:
```sh
#!/usr/bin/env bash

docker build -t yolo:42 - <<EOF
FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssh-client

USER root
EOF

docker run \
       --rm \
       --interactive \
       --tty \
       --user="root" \
       --network="host" \
       --name="yolo" \
       --workdir $(pwd) \
       --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
       --mount "type=bind,source=$HOME/.ssh/known_hosts,target=/root/.ssh/known_hosts" \
       --mount "type=bind,src=/run/host-services/ssh-auth.sock,target=/run/host-services/ssh-auth.sock" \
       -e "SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock" \
       "yolo:42" bash -c "ssh-add -L"
```

**Comment by rdeusser** [comment]
Okay I figured out that opening Docker from the terminal works: `open -a Docker`. Still, that's kind of obscure. Can we get this documented better somewhere?

**Comment by nicks** [comment]
`open -a Docker` means "open the Docker Desktop app"

If this failed before, but worked after you opened the app, that tells me that you didn't have Docker Desktop running before.

If you didn't have Docker Desktop running before, that tells me that your Docker CLI was probably talking to something else (e.g., a remote docker context, or an app masquerading as Docker). This would explain why /run/host-services/ssh-auth.sock didn't work, because that's a DD-specific thing.

Does that sound plausible?

**Comment by rdeusser** [comment]
I confirmed Docker for Desktop was running while this happened. Furthermore, if I quit the app and reopen via the icon in /Applications it doesn't work. It only works when I open it via terminal.

**Comment by git-rz** [comment]
docker-desktop seems to start it's own ssh-agent process in the case where there is none otherwise available (the normal case, where it may be started with the computer, or through finder..)

However, I am unable to locate that ssh-agent's socket anywhere. Is seems to not be under $TMPDIR, nor ~/.docker, nor /var/run..

We really need documentation around this feature. How do we communicate with the ssh-agent started automatically by docker-desktop?

I agree with @rdeusser, starting ssh-agent in a terminal, and then docker-desktop from the same terminal is a really obscure workflow.

**Comment by jeanpralo** [comment]
I am using 1password for ssh agent and starting docker from terminal using open -a Docker vs starting from Spotlight does the trick. There should be a way of configuring which socket we want to bind /run/host-services/ssh-auth.sock to in the config. How does this magic work anyway ? Is it defaulting to default SSH_AUTH_SOCK env or something ?

**Comment by lochmueller** [comment]
I confirmed this problem in our DEV envs. Restart Docker via CLI solved this, but it is not very cool to spread this information across multiple teams :-/
