### ISSUE TITLE
just installed latest update, got a fatal error, here's the diagnostics from it:

### ISSUE THREAD

**Issue by whiterosetechnologies** [docker/for-mac#658]
[20160916-113236.tar.gz](https://github.com/docker/for-mac/files/477384/20160916-113236.tar.gz)
### Expected behavior
docker functions 
### Actual behavior
fatal error
### Information
auto-diagnosis was seen running. the attached tar.gz file was produced by the docker-initiated auto-diagnosis.
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
847FF8D0-DAB1-42E6-94B3-354289F4D5D7

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior
N/A
  1. ...
  2. ...

**Comment by dsheets** [comment]
Hello!

It looks like you are running the Docker for Mac application from the Trash:

```
Docker[com.docker.helper][335] <Notice>: bundle path: /Users/tonyturner/.Trash/Docker (7528).app/Contents/Library/LoginItems/DockerHelper.app
```

In order for Docker for Mac to function correctly (due to Apple's codesigning restrictions), you need to install it into an Applications directory like `/Applications` or `~/Applications`.

If you still experience this issue after running the application from an Application directory, please re-open this issue.

Thanks for using Docker for Mac!
