### ISSUE TITLE
Feature Request: "Start/Stop Docker" Toggle 

### ISSUE THREAD

**Issue by FuriouslyCurious** [docker/for-mac#665]
Docker for Mac daemon has two options for "Quit Docker" and "Restart Docker".

When I need to free up some memory, it will be super to have "Stop/Start Docker" toggle button too. There is no code in the repo, but if you share relevant code I am happy to submit a pull request for it.

**Comment by ebriney** [comment]
@FuriouslyCurious : 
This is a design decision to avoid confusing users, If the whale is in the tray you could use Docker, if not, Docker will not work.
You must quit the app to stop vm and free resources and launch the app when you want to use Docker.
Pin the app in the Dock or use Spotlight, is it not doing the job?

**Comment by asarkar** [comment]
I opened a similar issue #[1045](https://github.com/docker/for-mac/issues/1045) that was closed with reference to this one. Like I said in it, clearly I'm not the only one looking for this feature. I understand the original design decision but the best design provides features that the users want, not what you think they don't want. The users are smarter than you may consider them to be. "We won't provide a feature because it may confuse users" - how do you know? Has anyone reported being confused?
Can we reopen this ticket and bring it up for discussion?
