### ISSUE TITLE
Docker-Desktop adds `~/.docker/bin/` to my `$PATH` without telling me

### ISSUE THREAD

**Issue by JannikArndt** [docker/for-mac#6664]
After updating to Docker Desktop 4.15.0, it added

``` 
source /Users/<username>/.docker/init-bash.sh || true # Added by Docker Desktop
```

to my `.zshrc`. It also created `.config/fish/config.fish`, `.bash_profile` and `.bashrc` with the same line.

The `bin` folder is currently empty, which makes this even more suspicious.

I consider this bad behavior. Apps are not supposed to change my `$PATH` without _at least_ telling me or mentioning it in the [Release Notes](https://docs.docker.com/desktop/release-notes/#4150).

**Comment by jaminthorns** [comment]
I just encountered this and have the same opinion. Changing my shell initialization scripts automatically is pretty terrible behavior.

Since all Docker Desktop is doing is ensuring that some binaries are on the `PATH`, what it should be doing instead is symlinking those binaries to `/usr/local/bin`, and that operation should be explicitly initiated by the user.

**Comment by goerge** [comment]
@christophermclellan Could you please explain why Docker is adding it's own `bin` folder to the path although it's empty?

**Comment by gimbo** [comment]
@christophermclellan wrote:

> We're looking to address these issues asap.

Any progress on this?

**Comment by gimbo** [comment]
LGTM.

I just shut down v4.16, removed the lines it had added from `~/.zshrc`/`~/.profile`, installed v4.18, and started it — and it didn't add them back in. I see that in Settings/Advanced it had auto-selected "User" configuration for the CLI tools, presumably because it detected they were already in `~/.docker/bin`. So I just need to set up `PATH` in my way, and all is good.

Many thanks! 🙏

**Comment by christophermclellan** [comment]
Thanks for confirming @gimbo. I'll close this issue until further notice.
