### ISSUE TITLE
Cannot connect to the Docker deamon after the lattest version of docker Apple M1 Chip

### ISSUE THREAD

**Issue by DaviYokogawa** [docker/for-mac#6683]
- [x] I have tried the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - 23A8AA84-A0C3-4516-BFF4-E96A3D79636A/20230115100405

### Expected behavior
I expected to be able to start and run a container
### Actual behavior
I can't start the container because the terminal is giving an error in the docker daemon "docker: Cannot connect to the Docker daemon at unix:"
### Information

  - macOS Version: Ventura 13.1
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: Docker Desktop 4.16.1

### Steps to reproduce the behavior

download the latest version of docker, or update to the latest;
docker run -d -p 80:80 docker/getting-started
after this: docker: Cannot connect to the Docker daemon at unix:...

Thanks for your support.

**Comment by ackerthehacker2** [comment]
When you installed docker desktop, did you give your password for the oascript?  It sounds like Docker can write to the socket file ..

I would do a clean uninstall and try to reinstall.  First time you start up, it will prompt you for the administrator passord for oascript:

rm -rf ~/Library/Group\ Containers/group.com.docker
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/.docker
rm -rf ~/Library/Application\ Support/com.docker.docker
rm -rf  ~/Library/Application\ Support/Docker\ Desktop

**Comment by djs55** [comment]
@DaviYokogawa thanks for the report and the diagnostics. Looking at the logs I suspect @ackerthehacker2 is correct -- the Docker engine has started up and is responding, so the issue is probably that the path to the socket file doesn't exist.

Could you also try
```
ls -l /var/run/docker.sock
```
and
```
docker context ls
```
If you don't want to use root access to install the `/var/run/docker.sock` symlink you can decline the `osascript` popup and then use the `desktop-linux` context. On my machine I have:

```
 % docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                               KUBERNETES ENDPOINT                ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                   https://127.0.0.1:6443 (default)   swarm
desktop-linux *     moby                                                          unix:///Users/djs55/.docker/run/docker.sock                                      
% docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
This works fine, but beware that other tools might expect `/var/run/docker.sock` to exist. In that case it's best to re-enable the symlink.

If you've declined it and want to re-enable it, at the moment it's necessary to edit `~/Library/Group\ Containers/group.com.docker/settings.json` and set
```
  "authDeclinedInstallSettings": false,
```
Hopefully this will become a first class thing in the settings UI at some point.

**Comment by DaviYokogawa** [comment]
Thank you guys, your tips helped me a lot, now I can use docker again! 🤩
