### ISSUE TITLE
issue with docker in mackbook air m1 

### ISSUE THREAD

**Issue by pulloxz** [docker/for-mac#6836]
I have an issue , docker says that the engine stopped .. I have m1 macbook air with 8gb ram 
nothing really works and when I try to go to troubleshoot to do anything no button actually work,
the setting is always loading I even tried to reinstall the docker and I have the latest version .
<img width="1320" alt="Screen Shot 2023-05-12 at 12 59 44 PM" src="https://github.com/docker/for-mac/assets/91639370/d7b1fef8-dd81-400f-95aa-3e8624e11e19">
<img width="1440" alt="Screen Shot 2023-05-12 at 1 03 51 PM" src="https://github.com/docker/for-mac/assets/91639370/1418001d-481a-4b61-a852-e860465b766d">
<img width="1440" alt="Screen Shot 2023-05-12 at 1 04 10 PM" src="https://github.com/docker/for-mac/assets/91639370/443da4a1-b94f-4028-9402-50fd67545aa7">

**Comment by AndreSilva1993** [comment]
We’re closing this issue because it doesn’t contain enough information for us to investigate the problem. If you’d like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/desktop/troubleshoot/overview/?
