### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by oviis** [docker/for-mac#71]
### Information

Diagnostic ID: F4466F9B-150B-4082-A6F5-6BA8FA0F085B
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Although `qemu-img` thinks the .qcow2 is intact, it looks like there was a write error which stopped docker from responding (probably the daemon ended up in disk sleep because the block device writes were blocking)
```
 Mirage-block error: Unknown write: End_of_file
 at file .../Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 offset 9857728512 with buffer of length 1536
```
There have been a number of important bug fixes in the beta branch which I hope will fix this. If you are able, please update to beta (25 or later) and open a fresh issue if this recurs.

**Comment by djs55** [comment]
It looks like there are too many hyperkit processes running:
```
$ grep "hyperkit -A -m" ps-ax.log   | wc -l
       3
```
For reference on my local machine there is only one of these processes. This specific bug was fixed in stable and it could cause .qcow2 corruption, which could cause write errors.
