### ISSUE TITLE
docker login command line password misbehaviour

### ISSUE THREAD

**Issue by kishaningithub** [docker/for-mac#712]
Im a new user to docker hub (my user id: kishanb)

```
docker login -u kishanb -p <<My password here>>
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: kishanb
Password: 
Login Succeeded
```

Im sure im entering the correct password.. Tried this several times
as well. 

### Information
  - Diagnostic ID: AA29E5F0-DC99-41D9-B944-0648349F074B

**Comment by dsheets** [comment]
If your password contains characters interpreted by your shell (in particular `$` but there are others), executing a command with your password in it may fail due to shell interpretation. I recommend putting your password between single quotes (`'`) to disable shell interpretation in Bourne (`sh`) and similar shells (`bash`, `ash`). Does that work?

**Comment by kishaningithub** [comment]
Thanks a lot! Special characters caused the mess for me..
