### ISSUE TITLE
Docker not responding after OS X Sierra sleep mode

### ISSUE THREAD

**Issue by ewilansky** [docker/for-mac#726]
### Expected behavior

Following OS X sleep, Docker commands and docker containers respond. 
### Actual behavior

Docker commands, such as Docker ps hang. In addition, attempting to reach any services running in containers fails. 
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu: 
  Diagnostic ID: 4D7F2A13-B944-4D05-A5C5-710DA2467E74 (uploaded)
- A reproducible case if this is a bug, Dockerfiles FTW
  This was reported and closed on an earlier version of Docker. I am currently running the latest beta release for OS X: Docker 1.12.2-rc1-beta27
- Page URL if this is a docs issue or the name of a man page: I saw this issue previously closed.
### Steps to reproduce the behavior
1. Update to v10.13 of OS X Sierra: 
2. Verify or update to Docker 1.12.2-rc1-beta27
3. Run at least one container
4. Allow OS X to sleep. I'm not sure if sleep length has anything to do with this. Typically, the machine sleeps for 8 to 12 hours and then I wake it up and this is when I've seen this behavior.
5. Open a terminal and type docker ps
6. Docker will not return a result
7. Attempt to access a service running in a container, the service will be unresponsive

I was able to recover from this in two ways:
1. Restarting OS X
2. Adjusting the resource configuration of Docker (i.e, # of CPUs), then clicking Apply & Restart

Simply restarting Docker did not resolve the issue.

**Comment by mattiasa** [comment]
This frequently, but not always,  occurs for me as well on OS X Sierra. As with @ewilansky a simple restart of Docker does not help, but if I quit docker via the taskbar icon menu and then verify that all docker processes exit before I restart docker then I'm able to get it back to a working state.

**Comment by ijc25** [comment]
I think this is #933. See https://github.com/docker/for-mac/issues/933#issuecomment-260311428 for more info. In order to switch to the new default you will either need to follow the instructions in that comment or perform a factory reset. I'm unsure with which beta the fix was added so I would encourage you to update to the latest (beta30 at the time of writing).

If you continue to see issues after having disabled the ACPI crash workaround as described please reopen with a new diagnostic from the latest version.

Thanks for your report and sorry for the delay in getting back to you.
