### ISSUE TITLE
docker fails to start after fresh install on 10.12 (hackintosh)

### ISSUE THREAD

**Issue by alepee** [docker/for-mac#731]
### Expected behavior

Docker daemon should start

### Actual behavior

Docker fails, even after reboot and factory reset

### Information

*output from diagnostic tool*:
```logs
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/B2640775-345E-453B-A3A5-99E5D8D186CA/20161002-141726.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/alepee/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

logs: https://cl.ly/3c0L3q3v313F

### Steps to reproduce the behavior

  1. installed docker on a fully setup hackintosh
  2. started docker for mac

**Comment by justincormack** [comment]
Sorry, this is not a supported environment.

**Comment by alepee** [comment]
Solved!
`VT-d` and `VT-x` (Intel Virtualization Technology) must be enabled in BIOS for docker to start a virtual env. Docker Mac is said to be native, but it reality it rely on mac os virtualization capabilities.

**Comment by step21** [comment]
@alepee Don't most guides say that for hackintosh to work, virtualization should be disabled? Or is that only for setup?

**Comment by alepee** [comment]
yes they do, but it may be a legacy. It turns out virtualization works pretty well with my setup and I'm not alone https://www.reddit.com/r/hackintosh/comments/2xqe83/virtualization_on_a_hackintosh/

**Comment by ruoguluo** [comment]
Thanks alepee, I encountered this problem last night. I should go check the BIOS setting and see how it works.

**Comment by alepee** [comment]
@ruoguluo did it solved your problem finally ?

**Comment by ruoguluo** [comment]
@alepee  The problem is solved 👍  Thank you for sharing the solution of enabling Vt-x in BIOS !

**Comment by maksimf** [comment]
A little note: I have hackintosh as well and if I enable both `Intel virtualization technology` and `VT-d` in BIOS my system fails to load, but if I enable only `Intel virtualization technology`, then it's fine, both Hackintosh and Docker work.

**Comment by Tzeejay** [comment]
So the solution for this turns out to be a mix of what @alepee and @maksimf said (for macOS 10.12.6):

`Intel Virtualization Technology` needs to be enabled as well as `VT-d`.

I did not run into the issue that @maksimf described in that I wasn't able to boot into macOS with `VT-d` and `Intel Virtualization Technology` enabled. They're both enabled for me now and boot went as expected, if not I would recommend trying disabling `VT-d` and seeing where that get's you.

**Comment by lauripiisang** [comment]
Can confirm, works for me -- I don't have `VT-d`, but upon re-enabling `Intel Virtualization Technology` which AFAIK is a long word for `VT-x`, docker started fine.

**Comment by ixtli** [comment]
Works for me! It seems like the suggestion to disable VT on hackintoshes is legacy. I also think that it's a bit silly to say it's "not a supported platform." The total hardware configurations you can run OS X on is a very small subset of the total configurations you can run Windows on. As well, Docker explicitly says that you need VT-* turned on, which turns out to be the problem here.
