### ISSUE TITLE
Docker service ls reporting wrong number of running services.

### ISSUE THREAD

**Issue by ingshtrom** [docker/for-mac#745]
### Expected behavior

I would expect all services to have tasks running, but actually running.
### Actual behavior

`docker service ls` shows a list of all of my services running, but `docker ps` shows nothing.
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
  Diagnostic ID: 83AE2F2E-BEB1-49FE-94F1-BBB4D38392C0
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior
1. Start a swarm and add a few services to it. 
2. Restart the machine and see if they are still shown as up upon logging in.

<img width="774" alt="screen shot 2016-10-05 at 11 36 02 am" src="https://cloud.githubusercontent.com/assets/571756/19120135/ef9baf30-8aef-11e6-88d2-122ec2a1d4fd.png">

**Comment by ijc25** [comment]
Hi @ingshtrom, thanks for your report and sorry for the delay in someone getting back to you.

I am assuming that you are running a single node swarm consisting of just your mac, since taking part in a multi node swarm is something which is still work-in-progress for docker for mac. (Sadly I can't tell for sure from the diagnostics, something which we'll address in a future version).

Given that assumption what you report does seem odd to me too, unfortunately this behaviour is part of the [Docker engine](https://github.com/docker/docker) (or perhaps [swarmkit](https://github.com/docker/swarmkit)) and not something we docker/for-mac developers are very familiar with.

If you are still able to reproduce with the latest stable (1.12.3 at time of writing) then I would encourage you to open a ticket on the docker/docker issue tracker.

I'm sorry that it took so long for someone to direct you to the right place.

**Comment by ingshtrom** [comment]
No Problem! Thank you for taking a look!

You are correct, it is just my mac--single node swarm. 

For documentation purposes, I should say that I worked around this by having Docker only start manually. I think by default (or I set it a while back) the Docker daemon will start when the mac starts. For whatever reason, when I turn that off and start Docker manually when I need to use it, my problems go away. It could be a timing issue with the startup of the mac, but either way, that fixed my issue and doesn't cause me any extra headache--and frees up 2GB of RAM :P
