### ISSUE TITLE
Cannot run docker command on the latest Mac OS

### ISSUE THREAD

**Issue by scnypl** [docker/for-mac#763]
### Expected behavior
docker info: get the correct response

### Actual behavior
$ docker info
Error response from daemon: Bad response from Docker engine

### Information
Diagnostic ID: 518FA72C-1E41-4AF5-BE41-AEE788EB17D6

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/518FA72C-1E41-4AF5-BE41-AEE788EB17D6/20161008-004805.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by scnypl** [comment]
[20161008-004805.tar.gz](https://github.com/docker/for-mac/files/516685/20161008-004805.tar.gz)

This is the diagnostic log.

**Comment by JanBednarik** [comment]
Have you tried reset Docker to factory defaults? I had similar issue and factory reset helped.

**Comment by samoht** [comment]
Your logs contain some suspicious:

```
 BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
```

But I am not sure it is related. Your docker.log contains a lot of `TRANSIENT_FAILURE` errors from containerd, and a graphdriver error which doesn't look very good:

```
time="2016-10-07T16:45:18.390915739Z" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
time="2016-10-07T16:45:19.876126399Z" level=error msg="Graph migration failed: \"invalid character '\\\\x00' looking for beginning of value\". Your old graph data was found to be too inconsistent for upgrading to content-addressable storage. Some of the old data was probably not upgraded. We recommend starting over with a clean storage directory if possible."
```

This is probably yet another AUFS corruption error. I you are fine with loosing all your containers, reseting to default factory will probably restore Docker to a good state.

**Comment by brooksph** [comment]
# Expected behavior 
docker info : info 

# Actual Behavior
Error response from daemon: Bad response from Docker engine

$docker info 
Error response from daemon: Bad response from Docker engine

# Information 
Diagnostic ID: 007B7251-3C71-47E2-827A-D4C2C19879C0

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/007B7251-3C71-47E2-827A-D4C2C19879C0/20161011-142526.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Restore to factory settings and reinstall did not help

**Comment by samoht** [comment]
@brooksph: your issue seems different (the installer didn't complete the installation fully), could you please open a new issue so we can track this separately? Thanks!

**Comment by brooksph** [comment]
@samoht Done. Thank you and see #791

**Comment by samoht** [comment]
@brooksph Thank you

@scnypl your issue seems indeed due to an AUFS corruption issue. We plan to switch to overlayFS 2 when it becomes stable enough to avoid this kind of corruption. To fix your issue, I am afraid that you will have to reset to factory defaults.

**Comment by scnypl** [comment]
JanBednarik,

Thank you very much! It works.
