### ISSUE TITLE
If /etc/resolv.conf is updated by VPN client on host machine - docker doesn't see the change

### ISSUE THREAD

**Issue by favoretti** [docker/for-mac#796]
### Expected behavior

While trying to connect to private registry, when DNS servers are updated by a VPN client Docker should use those to do the resolving.
### Actual behavior

In fact, it doesn't. I have to manually log in to moby and add VPN DNS servers as first ones.
### Steps to reproduce the behavior
1. Start docker
2. Start VPN
3. Try to log in to a private repository that's resolvable through VPN-assigned DNS
4. See it fail miserably :)

**Comment by samoht** [comment]
Which version of Docker for Mac are you using? We have improved support for DNS/VPN in latest releases.

If you happen to run a recent version of Docker for Mac but still have that issue, it would be helpful for us if you could upload the logs to our diagnostic server and give us your diagnostic ID so that we can investigate. Thanks!

**Comment by favoretti** [comment]
@samoht Hey, thanks for getting back so quickly. I'm on the latest beta. I'll get home tonight and record a diagnostic session. From what I can see - I can reproduce it every time.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
