### ISSUE TITLE
Different behaviour in docker for mac & docker (linux) when building image with ADD & permission issues

### ISSUE THREAD

**Issue by gtardif** [docker/for-mac#824]
With the following Dockerfile : 

> FROM ubuntu:16.04
> RUN useradd -ms /bin/bash newuser
> USER newuser
> WORKDIR /home/newuser
> 
> ADD test.sh /home/newuser
> RUN chmod +x test.sh

Building this on linux gives : 

> Step 6 : RUN chmod +x test.sh
>  ---> Running in af84e2f646e6
> chmod: changing permissions of 'test.sh': Operation not permitted

since ADD creates the file as root and not 'newuser' ; the following RUN command executes as 'newuser'

With Docker for Mac, strangely the "RUN chmod +x test.sh" executes without any problem. 
The test.sh file in the container is owned by root at the end.

This was tested with docker 1.12.2 on Debian 8.2, 
Docker for mac version 1.12.2-beta28 (12906) Channel: Beta 71c4a001c2
(MacOS 10.10.5)

**Comment by justincormack** [comment]
Hi, this is not actually a Docker for Mac specific issue - the same happens on a Linux system with Ubuntu 16.04, I think related to changes in the 4.4 kernel with respect to capabilities. 

Looks like some changes were merged into 1.12.2 that probably should not have been, as this is an unexpected change for a minor revision.

Basically on kernels since 4.3 non root users can be granted capabilities, so the ability to `chown` files is not being removed when we switch user. As you can switch user anyway it is not really a privilege change, but it is unexpected.

Let me look into how this got released.

**Comment by justincormack** [comment]
This will be fixed in docker 1.12.3

**Comment by justincormack** [comment]
This was fixed, please update to latest beta (beta 29.x)

**Comment by gtardif** [comment]
Thanks, works fine !
