### ISSUE TITLE
Docker ps failed

### ISSUE THREAD

**Issue by KimMatt** [docker/for-mac#84]
### Information

Diagnostic ID: 6FF12D1F-549A-40FF-98F2-B326805121CE
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Shut down computer
2. Hold power button prematurely
3. Turn computer back on.

**Comment by djs55** [comment]
The last thing on the VM console was:
```
 * Mounting local filesystems ... [ ok ]
 * Setting system clock using the hardware clock [UTC] ... [ ok ]
 * Configuring host block device ...^@^@
```
It looks like there's something wrong with the block device. There was a bug in the block device `flush` handling which has been fixed in recent betas (and which will be fixed in the next stable update) -- this might have caused data loss when the power was turned off abruptly.

This may be a cascade failure but the report also shows more than 1 hypervisor process accessing the block device: (this is #71)
```
$ grep "hyperkit -A" ps-ax.log  | wc -l
       2
```
There was a second bug which has also been fixed in recent betas (and which will be fixed in the next stable update) which can cause multiple hypervisor processes to access the qcow2 file, causing further corruption of the block device.

I recommend upgrading to a recent beta (e.g. beta 25) which has all these (and more fixes). Unfortunately the filesystem on the .qcow2 is corrupt and you'll need to use "Whale menu -> Preferences -> Uninstall/Reset -> Reset to factory defaults" to generate a fresh file. Containers and images will unfortunately have to be rebuilt. There will be a stable release soon, but we're still working on stabilising it under OS 10.12 (Sierra).

Please do upgrade to beta 25 and open fresh issues for any problems you encounter. Thank you for the report and I apologise for the inconvenience caused.
