### ISSUE TITLE
SERIOUS BUG: routinely corrupts / hangs after coming out of sleep, needs reset loss of Containers + Images

### ISSUE THREAD

**Issue by HariSekhon** [docker/for-mac#855]
### Expected behavior
1. sleep mac
2. wake mac
3. run docker commands
### Actual behavior

Docker gets stuck starting back up if you left it running when Mac goes in to sleep mode. This happens daily on all 3 of my Macs, 2 laptops and a desktop that Docker gets stuck and never becomes available again.

This has basically become unusable as it requres a factory reset losing all the containers and images and happens so regularly as to render Docker for Mac practically useless, I spend all my time re-downloading images from DockerHub.

There are lots of tickets raised for this recurring issue:
#813
#819
#820
#835
### Information

See #819 and #820 
### Steps to reproduce the behavior
1. sleep mac
2. unsleep mac
3. run docker commands and see they no longer work

Might need to sleep / unsleep a few times to reproduce.

**Comment by samoht** [comment]
Are you using `10.10.5` on all of your laptops?

Some of the problem that you linked comes from an issue with the aufs drivers that we ship in Docker for Mac. In the last Beta, we have switched to `overlay2` as the default storage driver, which should fix these. Did you try running the latest Beta?

**Comment by HariSekhon** [comment]
I think they're on different versions but yes the laptop I'm writing on now is 10.01.5.

One of the first things I did was upgrade to Docker Beta on one of them to see if that made any difference but the issue still recurred, unless that new Beta change to overlay2 happened within the last few days in which case I need to upgrade again to test it.

**Comment by samoht** [comment]
It would be useful to have a diagnostic ID on which of the machine where this is failing, as the issue is probably related to 1/ the OSX version that you are running (there are some OSX kernel bugs in 10.10 related to sleep mode that we can unfortunately do nothing about) and 2/ your Docker for Mac version (there are various causes). We switched to `overlay2` in Beta29 that we released a few days ago.

**Comment by HariSekhon** [comment]
I put the diagnostic in #820, I'll try upgrading to Beta again at some point soon and see if the issue subsides.

**Comment by HariSekhon** [comment]
I'm actually a bit hesitant to upgrade my Macs now as I saw there were some issues with the Mac Sierra version...

**Comment by HariSekhon** [comment]
This occurred on my desktop last night which is currently 10.10.4

**Comment by HariSekhon** [comment]
I've upgraded both to Beta and will keep an eye on this.

**Comment by HariSekhon** [comment]
This has just happened again on my 10.10.4 desktop even after upgrading to the latest Beta yesterday:
```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.10.4 (build: 14E46)
logs: /tmp/A8248812-C53F-46A2-B4B0-55F23050107E/20161028-195302.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by HariSekhon** [comment]
Looks like the Beta version doesn't have the fix in it.

**Comment by HariSekhon** [comment]
This issue is so severe and frequent that I've had to abandon docker for mac and go back to docker machine for reliability reasons.

**Comment by J-Fricke** [comment]
I'm running OSX 10.10.5 and Docker 1.12.3-beta30.1 and seeing basically the same issue with resuming from sleep and my containers are no longer running and I need to start them back up again. It's generally not a huge issue in my dev environment.

Though just today I had a database process running which hung because of this issue and I now have to wait another 30min for it to process again.

I'm also hesitant to upgrade to Sierra due to this computer being an older one and also after reading some of the Sierra bugs Docker still has.

**Comment by samoht** [comment]
Starting with Docker for Mac stable release 1.13 (upcoming), and concurrent Beta releases, we will no longer address issues specific to OS X Yosemite 10.10. In future releases, Docker for Mac could stop working on OS X Yosemite 10.10 due to the deprecated status of this OS X version. We recommend upgrading to the latest version of macOS.

(see https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install)

I am going to close that issue, but please open a new ticket if you see similar problems on 10.11 or 10.12. Thanks!
