### ISSUE TITLE
Time Machine exclusions

### ISSUE THREAD

**Issue by grav** [docker/for-mac#873]
More of a suggestion:

It would be nice, if the TM exclusion that you can make in Docker for Mac would actually be applied to the Time Machine preferences, meaning:

- it would be visible in the Time Machine options
- it would persist, even if you reset Docker for Mac to factory defaults

**Comment by dsheets** [comment]
Thanks for the suggestion! We'll look at this when a number of other storage improvements are coming online.

**Comment by chris-crone** [comment]
Thanks for the feedback @grav! In an upcoming release, we will be excluding the VM from backups by default with the option to include it.

There are two ways to exclude files/folders from backups: by absolute path and by actual object. From what I can tell, only exclusions by absolute path are shown in the Time Machine preferences. You can [see all excluded items using the terminal](http://apple.stackexchange.com/a/25833).

As the VM can be moved in Docker for Mac, we will be excluding it as an object instead of by absolute path so you will unfortunately not be able to see it in the Time Machine preferences.

I think that would be counter-intuitive to not reset *all* settings on a factory reset.

Feel free to reopen this if you feel this solution doesn't meet your needs.
