### ISSUE TITLE
Hyperkit non-insignificant amount of CPU while idle

### ISSUE THREAD

**Issue by cpuguy83** [docker/for-mac#887]
### Expected behavior
Hyperkit should use very little/no CPU while idle

### Actual behavior
After idling for about 30mins, hyperkit is sitting at 4.5% CPU usage.
When first looked at it (a minute or two after touching it) it was between 6%-12%

### Information
Diagnositc ID: F9467209-AD82-445C-88DC-A760AED26E30
As you can see, the upload failed.
```
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior
Idle with docker running
Using ~~OSX~~ macOS 10.1.2
Docker itself is configured with 8 CPU's and 8GB of RAM.

**Comment by tuwannu** [comment]
I'm facing similar issue here, com.docker.hyperkit spends ~2% constantly.

About every 30 seconds or so, the process would go up to ~40-50% CPU Utilization for 2-3 seconds, then drops back to ~2%.

Similarly at the same time that com.docker.hyperkit peaks up during idle, com.docker.osxfs would go up to 20-30% then drops back to 0%.

Diagnostic ID: EA1866A0-AA9F-4463-AC3E-409311271528
OS: macOS 10.12.1
Docker set to 1 CPU and 1GB memory.

    Docker for Mac: version: 1.12.3 (583d1b8)
    OS X: version 10.12.1 (build: 16B2657)
    logs: /tmp/EA1866A0-AA9F-4463-AC3E-409311271528/20161117-014326.tar.gz
    [OK]     vmnetd
    [OK]     dns
    [OK]     driver.amd64-linux
    [OK]     virtualization VT-X
    [OK]     app
    [OK]     moby
    [OK]     system
    [OK]     moby-syslog
    [OK]     db
    [OK]     env
    [OK]     virtualization kern.hv_support
    [OK]     slirp
    [OK]     osxfs
    [OK]     moby-console
    [OK]     logs
    [OK]     docker-cli
    [OK]     menubar
    [OK]     disk
    Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

My data upload also failed. So here is a copy on my dropbox: https://www.dropbox.com/s/8cetqd5uohe9vdx/20161117-014326.tar.gz?dl=0

**Comment by ijc25** [comment]
Thanks for the reports. I assume that "hyperkit" means specifically `com.docker.hyperkit` and not the `com.docker.osx.hyperkit.linux` supervisory process. Given that a 2% background CPU usage when idle is a bit unexpected.

On my 10.11 system I see more like 0.3-0.4% from `com.docker.hyperkit` when idling (the VM will never be 100% idle, so some low level of CPU usage is to be expected). I only have 4CPUs and 8GB RAM though (can't have more CPUs since the host is limited).

Would it be possible for you to use `instruments` (I think it comes along with Xcode? Or is maybe independent in the app store) to gather some traces of what the process is actually doing? The `Time Profiler` widget is probably the most useful, remember to constrain it to just the `com.docker.hyperkit` process (tip: the process selector helpfully shows me several `com.docker (PID)` entries corresponding to various `com.docker.*` processes, I have to use `ps` to determine which is the hyperkit one)

It would definitely also be worth running `top` from within a privileged container (via something like `docker run -it --privileged --pid=host debian nsenter -t 1 -m -n sh`) to check for unexpected activity (either from any containers you are running or from system processes). If you are seeing system process activity that would be good to know about.

@tuwannu your spikes sound consistent with their being actual periodic activity in a container, like a cronjob or some sort of slow polling loop.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
