### ISSUE TITLE
Docker fails to start on Mac (El Capitan)

### ISSUE THREAD

**Issue by snoopdave** [docker/for-mac#899]
### Expected behavior

docker ps works

### Actual behavior

docker ps returns this:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

(env | grep DOCKER says I have no DOCKER settings in my environment)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/510992A6-24DB-40AC-9DB2-06480029ED3E/20161105-101443.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/ApigeeCorporation/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ApigeeCorporation/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/ApigeeCorporation/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

1. Run the Docker.app
2. Enter password
3. See error dialog appear
4. Try docker ps and see error message

**Comment by djs55** [comment]
Thanks for your report. The logs have
```
<Critical>: Communication with networking components failed.
```
The UI failed to communicate with the networking helper process-- it sometimes happens that the Apple API leaves the helper process half-installed. FWIW we're hoping to make the helper process a soft dependency, since it's only needed for a small number of operations.

In the meantime, try the following steps:
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac

Hopefully this will (re-)install the networking helper process properly. Please re-open this issue if your problem persists.

May be related to docker/for-mac#61
