### ISSUE TITLE
B1823159-0C46-4D44-9E1C-6FB3B2B3E973

### ISSUE THREAD

**Issue by muchtajidun** [docker/for-mac#901]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
The logs show a migration from beta 29.3 to stable 1.12.1:
```
<Notice>: migrator: successfully updated from version 1.12.3-beta29.3 to 1.12.1
```
The `docker` daemon is not running inside the VM since it failed to load the containers and images. Note the default graph driver in 1.12.1 stable is `aufs` but the default driver in 1.12.3-beta29.3 is `overlay2`. Neither `overlay2` nor `aufs` seem to be mounted in the VM. I suspect the disk actually has `overlay2` and the stable version cannot read it.

When switching versions, especially from beta (which is under development) to a stable version, it's necessary to select:

:whale: menu -> Uninstall/Reset -> Reset to factory defaults

Note this will delete existing images and containers.

I hope this helps!
