### ISSUE TITLE
Docker Fails to Launch (OS X 10.11.6)

### ISSUE THREAD

**Issue by lycovian** [docker/for-mac#914]
### Expected behavior
Docker will start.

### Actual behavior
Docker never starts or if it does actually indicate that it is started the menu-bar icon and the Docker menu indicate that the daemon is restarting.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/94028958-C2B1-4E12-8678-BB0B1AD0383C/20161108-083303.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. attempt to start docker

**Comment by ijc25** [comment]
Detected symptom of problem 'aufs-corruption' in 94028958-C2B1-4E12-8678-BB0B1AD0383C/20161108-083303.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20
