### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by ramon** [docker/for-mac#915]
### Expected behavior

Working docker

### Actual behavior

Docker not working

### Information
  
[20161108-134645.tar.gz](https://github.com/docker/for-mac/files/578783/20161108-134645.tar.gz)
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.10.5 (build: 14F1509)
logs: /tmp/B5CA040E-7343-405B-BCB5-5F1010298ACB/20161108-134645.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by lukebergts** [comment]
I have the same issue. If i click restart while the docker animation is going and says docker starting it will get to "docker started" but docker ps -a doesn't work because it didn't actually work.

Diagnostic ID - 
493978B4-86A8-4D52-95A8-2F7CF86A67FC

**Comment by ijc25** [comment]
@ramon your logs show symptoms of the same issue as https://github.com/docker/for-mac/issues/864. I've added your case to the internal ticket. Please subscribe to #864 for updates.

@lukebergts your issue is not the same:
Detected symptom of problem 'unsupported-sierra' in 493978B4-86A8-4D52-95A8-2F7CF86A67FC/20161110-140654.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561

**Comment by rogaha** [comment]
@ramon can you please try with the newer `beta` version? It looks like it worked from @lukebergts
