### ISSUE TITLE
docker-compose pull from Docker Trusted Registry fails

### ISSUE THREAD

**Issue by MukulAmbulgekar** [docker/for-mac#916]
**Expected behavior**
Pull image from DTR successfully.

**Actual behavior**
ERROR: Error while pulling image: Get http://<DTR>/v1/repositories/images: dial tcp 172.18.131.117:80: getsockopt: no route to host

**Information**
We are using DTR to store our private images. We are using self signed certificates to access DTR and adding DTR to insecure registries as well. 

When we do fresh docker install or factory reset, we are able to login DTR and pull images using 'docker login & docker pull'. But when we use 'docker-compose' to pull image it throws error getsockopt: no route to host. After we use docker-compose we are not able to login or pull images from DTR with 'docker pull' anymore, it throws above error.

**Steps to reproduce the behavior**

1. Factory reset, docker login and docker pull works. 
2. docker-compose pull fails with no route to host error.
3. Now, docker pull fails as well. (We have to do factory reset to make it work again)

Docker version - Docker version 1.12.1, build 6f9534c
Docker Compose Version - docker-compose version 1.8.1, build 878cff1

EDIT - further investigation led us to confirm that issue is not with docker-compose, it's with new docker network. Once I create test_network, I am not able to login DTR. Same is happening when new default network is created with docker-compose.

 ```
docker network create --driver bridge test_network
```
```
docker network inspect test_network
[
    {
        "Name": "test_network",
        "Id": "2ae3f2edccdef4bf12c07072c2e32fcd313ab98f5829053c491f0c9154f38373",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by ijc25** [comment]
Your test network is `172.18.0.0/16`, which covers `172.18.131.117` which is the IP address of your DTR.

You need to ensure that your docker networks (or any other virtual network) do not overlap with your real infrastructure. I believe this can be done with the `--subnet` option.

**Comment by maciejkra** [comment]
Well the problem occurs only on OS X it doest not happen on Linux.
I have the same problem, new instances lunched by compose, create the network which overlaps with the address of my registry and in result I am not able to download it ;(

**Comment by MukulAmbulgekar** [comment]
+1 @maciejkra, docker networks overlap only on Mac. 
On Linux same compose file works perfectly.

**Comment by ijc25** [comment]
Thanks @maciejkra for the extra context. I had thought this was just a minor usability wrinkle (which I had already escalated internally and forgot to mention) but the interaction with `compose` is a more interesting case. I've added that case to the internal ticket and will reopen.

I think it is likely also the case that even on Linux you can end up overlapping with networks which are routed via your gateway device (e.g. have no explicit route on the host, so engine isn't aware of them). I'm told that it is possible to configure this in your `compose.yml` (with the downside of hardcoding subnets there) and that the preferred solution from the docker engine side is to use "overlay networks". That is probably a topic for the docker/docker support channels though.

**Comment by twang2218** [comment]
I ran into the same issue. The company network ip range is `172.19.0.0/16`, and one of the internal Docker Registry is located in that network. During the `docker-compose up -d`, the docker engine complaints `dial tcp 172.19.1.15:5000: getsockopt: no route to host`, so boot up failed.

After look into the issue, I found one of the user-defined network was created and allocated the ip range `172.19.0.0/16` automatically, so if I run `ip route | grep 172.19` in the Moby host, I can see there is a routing table point all the traffic for `172.19.0.0/16` to the user-defined bridge network.

```bash
$ docker run -it --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
/ # ip route | grep 172.19
172.19.0.0/16 dev br-fb51ae2a56ab  src 172.19.0.1
/ # ip link | grep fb5
27: br-fb51ae2a56ab: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
```

I think this is the reason why it's said `no route to host`.

I have checked `libnetwork` code to have better understanding of how IPAM works, and is there anyway to let docker engine skip those network, and I found all the `libnetwork` works which try to avoid conflict of the host network will fail for Docker for Mac.

Let's look into the code.

First, the network pool is defined at [libnetwork/utils.go: initBroadPredefinedNetworks()](https://github.com/docker/libnetwork/blob/d2141cd80d77b0446480eac1511942f9ce020fc8/ipamutils/utils.go#L28), which are `172.17-31.x.x/16, 192.168.x.x/20`.

Then, for each time a network address range is requested, [libnetwork/utils_linux.go: FindAvailableNetwork()](https://github.com/docker/libnetwork/blob/f4338b6f1085ccfe5972e655cca8a1d15d73439d/netutils/utils_linux.go#L110) will be called to find an available network address range.

```golang
// FindAvailableNetwork returns a network from the passed list which does not
// overlap with existing interfaces in the system
func FindAvailableNetwork(list []*net.IPNet) (*net.IPNet, error) {
	// We don't check for an error here, because we don't really care if we
	// can't read /etc/resolv.conf. So instead we skip the append if resolvConf
	// is nil. It either doesn't exist, or we can't read it for some reason.
	var nameservers []string
	if rc, err := resolvconf.Get(); err == nil {
		nameservers = resolvconf.GetNameserversAsCIDR(rc.Content)
	}
	for _, nw := range list {
		if err := CheckNameserverOverlaps(nameservers, nw); err == nil {
			if err := CheckRouteOverlaps(nw); err == nil {
				return nw, nil
			}
		}
	}
	return nil, fmt.Errorf("no available network")
}
```

As we can see, `libnetwork` try to avoid host network conflict by 2 ways, name server address and routing table.

* If any name server listed in `/etc/resolv.conf` belongs to the next available network from the network pool, then the network will be skipped.
* If any network entry available in the Docker host routing table entry overlaps the next available network, the network will be skipped as well.

Some people have same overlap issue on Linux, tried to [modified `/etc/resolv.conf`](https://github.com/docker/docker/issues/21776#issuecomment-230377605) to workaround the problem, however, this will fail on Docker for Mac, as the `nameserver` entry in `/etc/resolv.conf` in the moby linux came from DHCP, which is just the gateway of the linux host. And `libnetwork` doesn't check `dockerd --dns` or `dns` entry in `daemon.json`, so there is no way we can use such workaround under Docker for Mac.

On Linux, there is another workaround is by adding routing table entry for such network range to the default gateway. However, it's not possible on Docker for Mac either. Routing entry added on Mac is not only temporary, but also not reflected in the Moby Linux's routing table. So, Docker engine has no way to know there is actually overlapping on the host's network.

Currently, we have to use `--subnet`, or similar way in `docker-compose.yml`, to hard code the network address range, every time. We have to be very careful not using `docker network create` without `--subnet` at ANY time, and for each `docker-compose.yml` we write, even something for temporary testing, we have to allocate the IP range manually and we have to memorise such IP range allocated all the time, otherwise, there will be a `no route to host` errors. It's really annoy for corporate network.

Related Issues:

* https://github.com/docker/for-win/issues/341
* https://github.com/docker/libnetwork/issues/1272
* https://github.com/docker/libnetwork/pull/1591
* https://github.com/docker/docker/issues/21776#issuecomment-206133109
* https://github.com/docker/docker/issues/25645
* https://github.com/docker/docker/pull/29376

**Comment by twang2218** [comment]
@MukulAmbulgekar I think the title might need an update, as it's actually not about Docker Trust Registry, it's about the predefined network address range allocation problem.
