### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by ab9-er** [docker/for-mac#920]
### Expected behavior
Docker to start

### Actual behavior
Docker not starting and the whale animation continues to infinity

### Information

Diagnostic ID: EDE9672C-4EB2-43F2-91D6-29F2C35AA6D1
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Start Docker

**Comment by Bluesmile82** [comment]
I have the same problem. It happened suddenly when I was using PyCharm

**Comment by ab9-er** [comment]
This issue has forced me to return to `docker-machine`, something that I am not enjoying at the moment.

**Comment by ijc25** [comment]
Detected symptom of problem 'unsupported-sierra' in EDE9672C-4EB2-43F2-91D6-29F2C35AA6D1/20161109-160717.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561

@ab9-er from your logs it looks like you may recently have downgraded from 1.12.1 to 1.12.0-a for some reason, 1.12.0-a does not work on osx sierra. If the downgrade was deliberate due to e.g. an issue you were having with 1.12.1 then note that we have subsequently released a new stable release: 1.12.3.

Please upgrade to 1.12.3 and if you are still having problems open a fresh issue with details and a new bug ball gathered using the up to date stable version (since we improve the collection of diagnostics as well in newer releases).

@Bluesmile82 we have no way of telling if you have the same issue or just similar symptoms (the latter is more likely IME). Please open a ticket of your own and be sure to include a diagnostic bugball upload and a description of your particular circumstances.
