### ISSUE TITLE
1.12.3-beta30 slow network due to udp i/o timeouts?

### ISSUE THREAD

**Issue by johanneswuerbach** [docker/for-mac#944]
### Expected behavior

`terraform plan` should work

### Actual behavior

`terraform plan` shows a lot of i/o errors like `caused by: Post https://iam.amazonaws.com/: dial tcp: lookup iam.amazonaws.com on 192.168.65.1:53: read udp 172.17.0.2:48966->192.168.65.1:53: i/o timeout` when trying to talk to aws.

Running the same on a colleagues macbook (same network) with beta 27 works like a charm.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/EFA1EC6A-AC0B-4F5B-8676-A29A00B04545/20161114-191709.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW

```
FROM hashicorp/terraform:full

RUN go get github.com/jianyuan/terraform-provider-sentry

WORKDIR /app
```

Sadly I can't share the actual terraform code :-(

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
Hi @johanneswuerbach. Thanks for your report. I suspect DNS issues here since this is an area which saw a lot of work in beta30 to improve  support VPN and other split DNS configurations but which involves introspecting various things from OSX which aren't necessarily clearly exposed which sadly is likely to take us a little while to shake down in various configurations.

Please bear with us while we try and figure out if this is one of the already known issues with beta30 or something new. In the meantime you might like to try switching to the stable branch.

**Comment by ijc25** [comment]
This turns out to be a known issue, unfortunately our DNS proxy/cache will sometimes returns answers with the query bit set. A surprising amount of software actually tolerates this but some does not (Go's builtin resolver being a common one which apparently does not).

A fix is in the works and will either be released in beta31 or perhaps in a beta30.1 hotfix (depending on how the timing works out). In the meantime as I say you should be able to use the stable releases. Thanks again for your report.

**Comment by johanneswuerbach** [comment]
Looks like `1.12.3-beta30.1 (13946)` solved it for me, thanks and keep up the great work 👏
