### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by ab9-er** [docker/for-mac#951]
### Expected behavior
The docker engine starts

### Actual behavior
Docker does not start and the whale animation continues

### Information

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12 (build: 16A323)
logs: /tmp/EDE9672C-4EB2-43F2-91D6-29F2C35AA6D1/20161115-111324.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

Launch the docker app on OSX

**Comment by ab9-er** [comment]
Apparently, the beta version works well for me on Sierra.

**Comment by ijc25** [comment]
You previous issue running an old version on Sierra (#920) appears to have left you with filesystem and/or aufs corruption, likely due to the crashes. In any case you have switched between branches and should perform a factory reset, doing this will resolve the issue you are seeing and bring you back into a supported configuration.
