### ISSUE TITLE
Docker ps hangs after OSX Sierra Upgrade

### ISSUE THREAD

**Issue by cmgraver** [docker/for-mac#972]
I've read similar issues to this involving Sierra BETA, but this is no longer Beta. I've tried removing and re-installing the latest version of Docker.

### Expected behavior
docker ps works

### Actual behavior
docker ps gives no response

### Information

  Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.1 (build: 16B2657)
logs: /tmp/340EC9FC-A3AC-4AFD-8146-B23B27B1D796/20161120-103740.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by rogaha** [comment]
--------------------------------------------------------------------------------
Detected symptom of problem 'aufs-corruption' in 340EC9FC-A3AC-4AFD-8146-B23B27B1D796/20161120-103740.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

**Comment by rogaha** [comment]
@cmgraver can you please try the `reset to factory` approach and let us know how it goes?

**Comment by cmgraver** [comment]
"Preferences -> Uninstall/Reset -> Reset to factory defaults" resolved my problem. Thanks so much for your help.
