### ISSUE TITLE
HTTP Proxy settings from preferences are injected as environment variables in containers

### ISSUE THREAD

**Issue by lukevella** [docker/for-mac#981]
### Expected behavior
I am behind a corporate proxy so I configured the preferences with an HTTP Proxy so that I can pull images from Docker Hub when building my containers, but don't expect the same settings to be injected into the containers as environment variables.

### Actual behavior
The images are pulled successfully through the proxy however, the same HTTP Proxy settings are being injected in to the containers as environment variables. This causes some issues since I am using docker-compose to link two containers and they are attempting to communicate with each other through the proxy (which fails). I tried to exclude the hostnames of the linked containers via the preferences, hoping that they will be injected as $NO_PROXY but this doesn't happen.

### Steps to reproduce the behavior

  1. Configure the preferences with an HTTP/S Proxy and Exclude values.
HTTP_PROXY: `http://proxy.co.corp:8080` 
Exclude:`localhost,co.corp`
  2. docker run -it ubuntu bash
  3. echo $HTTP_PROXY
output: `http://proxy.co.corp:8080`
  3. echo $NO_PROXY
output: empty

**Comment by ebriney** [comment]
`docker run -e HTTP_PROXY= -it ubuntu bash` will do the job, no?

**Comment by lukevella** [comment]
@ebriney That might be a workaround but it doesn't solve the issue. 

I'm hoping that setting the HTTP Proxy settings in the app preferences will have the same effect as setting the environment variables for the docker daemon in systemd. See: https://docs.docker.com/engine/admin/systemd/#/http-proxy

When doing the above the HTTP Proxy environment variables do not get injected into containers. It should be the same on macOS. These settings are only for enabling a connection to Docker registries through a proxy.

**Comment by jamshid** [comment]
Strongly agree, this behavior where a proxy I happen to be using for web browsing on my mac automatically and without my choice gets injected into all containers seems a bit nuts. 

This feature is too clever, causes more confusion than it's worth. Let users enter the proxy in the Docker Preferences tab, anyway there's no guarantee you'd want to use the same proxy the Mac is otherwise using.

And a really bad bug is that Docker for Mac doesn't "reset" this after "unchecking" "Web Proxy (HTTP)" in Settings => Network => Proxies tab. The old value is still in the Docker Preferences, grayed out. I have to actually delete the ip and port from the Mac settings, even though those fields are being ignored by the Mac.

**Comment by djs55** [comment]
Thanks for the report. I've escalated this to the Docker for Mac and Windows networking team. We hope to work on our support for HTTP proxies over the next few releases -- I'll let you know how we get on.

**Comment by djs55** [comment]
@lukevella the latest master builds of Docker for Mac have experimental support for transparent HTTP(S) proxying. If this special mode is enabled then no environment variables are rewritten. If you'd like to try it, I've written some instructions: https://github.com/moby/vpnkit/blob/master/docs/transparent-http-proxy.md

Feedback is very welcome!

**Comment by ascatox** [comment]
The problem has become extremely urgent, without the `no_proxy` radio option in Proxies Tab. I hope the option will be introduced again.

**Comment by uk0** [comment]
look  https://uk0.github.io/2018/04/16/docker-macos-proxy-https-http/

**Comment by unlikezy** [comment]
@djs55 I think this issue may be resolved better.

Let me explain the problem I encounter first:
1. I am using docker behind a corporate proxy
2. I use docker to maintain and iterate our development environment.
3. To pull images from dockerhub, of course, I need to set docker daemon proxy, as this:
![image](https://user-images.githubusercontent.com/3445204/60853616-6731f280-a22f-11e9-975e-8f3ca5d412f0.png)
4. I need to access Internet within the environment, so I also set the proxy inside container, as this:
![image](https://user-images.githubusercontent.com/3445204/60853813-4f0ea300-a230-11e9-9d19-51dd50162140.png)
5.  And I need connect to company local git through https/ssh, which shouldn't be accessed with proxy setting. As you can see in the pictures above, I set "git.local.com" to no_proxy both in docker daemon proxy setting and in container env.
6. Now I encounter the problem:  
     I can not access git.local.com now, since VPN passthrough strategy pass all our container's flow into docker daemon proxy.  
     I have to unset docker daemon proxy to "system proxy", in order to use container proxy completely, if I want to access git.local.com;
     And I have to set docker daemon proxy to "manual proxy", in order to download images from dockerhub.
    And switching this setting require restarting docker daemon, so I have to close all my container when I am developing. This make my life much harder.

I think the key problem is that the proxy to pull images and the proxy for container shouldn't be mixed. They are completely for different purpose.

**Comment by Gladskih** [comment]
Funny that I have reverse problem with Docker for Windows: proxy configuration from docker settings does not injected into containers.

**Comment by hamza15** [comment]
Was this issue ever resolved? I have a problem similar to the original issue. My Jenkins server has proxy setting for both docker engine and docker containers. I need a proxy to build containers and install container binaries (apt-get, npm install etc) but I do not require proxy settings injected into containers after install.

The docker engine proxy settings are added via:
/etc/systemd/system/docker.service.d/http-proxy.conf

The docker container proxy settings are added via:
~/.docker/config.json

My jenkins job will build containers locally and deploy to my development environment but the proxy settings are injected into the containers. This prevents communication between containers since they try to speak to each other via proxy.
